### ISSUE TITLE
How to keep the version when changing tracked files?

### ISSUE THREAD

**Issue by njzjz** [pypa/setuptools-scm#1006]
I have read #717 and #812, but neither provides a solution.

I need to release several packages with different package names. [PEP 621](https://peps.python.org/pep-0621/) requires a static `name` (see [discussion](https://discuss.python.org/t/dynamic-project-names-and-pep-621/21359)), so I have to update `pyproject.toml`, which is tracked by `git`. However, after `pyproject.toml` is changed in the CI, the version is bumped, making it impossible to upload to PyPI.

```
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
         '2.2.9.dev0+gb875ea8f.d20240123' is an invalid value for Version.      
         Error: Can't use PEP 440 local versions. See                           
         https://packaging.python.org/specifications/core-metadata for more     
         information.      
```

In the above situation, I tagged `v2.2.8`, the GitHub Actions updated `name` in `pyproject.toml`, and then `setuptools-scm` gave the version `2.2.9.dev0+gb875ea8f.d20240123`. PyPI rejected the package with this version. I'd like to know if there is a way to get the version `2.2.8` even when a tracked file is changed. Thanks!

**Comment by RonnyPfannschmidt** [comment]
that use-case not supported by normal means and will never be directly supported
you can abuse the `SETUPTOOLS_SCM_PRETEND_VERSION_FOR_mypkg` env var to get things working

**Comment by njzjz** [comment]
> you can abuse the `SETUPTOOLS_SCM_PRETEND_VERSION_FOR_mypkg` env var to get things working

Thanks! The workaround works for me.

In the GitHub Action, I get the version and set `SETUPTOOLS_SCM_PRETEND_VERSION_FOR_mypkg` before any file is changed.
```
      - run: |
          python -m pip install setuptools_scm
          python -c "from setuptools_scm import get_version;print('SETUPTOOLS_SCM_PRETEND_VERSION_FOR_DEEPMD-KIT-CU11='+get_version())" >> $GITHUB_ENV
```

**Comment by CatChenal** [comment]
> In the GitHub Action, I get the version and set `SETUPTOOLS_SCM_PRETEND_VERSION_FOR_mypkg` before any file is changed.
> 
> ```
>       - run: |
>           python -m pip install setuptools_scm
>           python -c "from setuptools_scm import get_version;print('SETUPTOOLS_SCM_PRETEND_VERSION_FOR_DEEPMD-KIT-CU11='+get_version())" >> $GITHUB_ENV
> ```

@njzjz Would you please provide a link to the GH action you amended?
Also, I don't quite understand what "before any file is changed" means: why does it matter?
I am debating getting rid of `setuptools_scm`: it will depends if I can fix the same problem I have!
Thank you.

**Comment by njzjz** [comment]
> > In the GitHub Action, I get the version and set `SETUPTOOLS_SCM_PRETEND_VERSION_FOR_mypkg` before any file is changed.
> > ```
> >       - run: |
> >           python -m pip install setuptools_scm
> >           python -c "from setuptools_scm import get_version;print('SETUPTOOLS_SCM_PRETEND_VERSION_FOR_DEEPMD-KIT-CU11='+get_version())" >> $GITHUB_ENV
> > ```
> 
> @njzjz Would you please provide a link to the GH action you amended? Also, I don't quite understand what "before any file is changed" means: why does it matter? I am debating getting rid of `setuptools_scm`: it will depends if I can fix the same problem I have! Thank you.

@CatChenal You can check https://github.com/deepmodeling/deepmd-kit/pull/3172. The version will be bumped if any of the git-tracked files is changed.

**Comment by CatChenal** [comment]
Thanks Jinzhe! That's a great project!
Unless I'm mistaken, your pyproject.toml is telling me you are no longer using `setuptools_scm`.
I think I'll try your dynamic versioning scheme.
All the best to you.

**Comment by njzjz** [comment]
I use setuptools_scm through [scikit-build-core](https://scikit-build-core.readthedocs.io/en/latest/configuration.html#dynamic-metadata).

**Comment by CatChenal** [comment]
Thank you, I missed that.

Best regards,

Cat Chenal, Ph.D.
