### ISSUE TITLE
Why is get_version at runtime deprecated?

### ISSUE THREAD

**Issue by maxnoe** [pypa/setuptools-scm#1008]
This is very useful for editable installs, where having correct version information would require running `pip install -e .` again after each commit over and over.

See e.g. the setup astropy (and a few other packages that copied it from astroopy) are using to ensure that `get_version` is only called during local development:

https://github.com/astropy/astropy/blob/main/astropy/version.py

https://github.com/astropy/astropy/blob/main/astropy/_dev/scm_version.py

The `astropy._dev` package is not bundled in sdists or wheels.

**Comment by RonnyPfannschmidt** [comment]
Most usages of the function are incomplete

The plan is to provide a better version of version files after introducing a setuptools sub command for creating them


Time is a limiting factor
