### ISSUE TITLE
SETUPTOOLS_SCM_PRETEND_VERSION doesn't write_to

### ISSUE THREAD

**Issue by anarcat** [pypa/setuptools-scm#101]
if SETUPTOOLS_SCM_PRETEND_VERSION is specified, setuptools_scm doesn't `write_to`.

this is because of the last few lines of `__init__.py`:

``` python
    if version:
        if isinstance(version, string_types):
            return version
        version = format_version(
            version,
            version_scheme=version_scheme,
            local_scheme=local_scheme)
        dump_version(
            root=root,
            version=version,
            write_to=write_to,
            template=write_to_template)
        return version
```

it seems to me dump_version() should be ran anyways, no?

**Comment by RonnyPfannschmidt** [comment]
this was to avoid some issues with archives,

i think it no longer holds true, i'd welcome a fix else i'll try to fix it until the weekend

**Comment by anarcat** [comment]
i'm on it.

**Comment by anarcat** [comment]
see #102.
