### ISSUE TITLE
get_version(): normalize=False incompatible with several version schemes

### ISSUE THREAD

**Issue by christian-herber-nxp** [pypa/setuptools-scm#1018]
running anything that calls this function with 
-release-branch-semver
-python-simplified-semver

an error is thrown:

e.g. `ValueError: <ScmVersion v2.0.0 dist=0 node=g17520db dirty=True branch=branch-name> can't be parsed as numeric version`

**Comment by RonnyPfannschmidt** [comment]
the issue is with the simplified parsing in guess_next_simple_semver

fortunately these days the version class is available and allows better parsing
