### ISSUE TITLE
Documented `.git_archival.txt` is not reproducible

### ISSUE THREAD

**Issue by LecrisUT** [pypa/setuptools-scm#1030]
Specifically:
```
ref-names: $Format:%D$
```
Produces different git archive after a commit is added
```diff
< ref-names: HEAD -> master, tag: 1.30
---
> ref-names: tag: 1.30
```

This is rather disastrous for packagers expecting this to be stable.

Either `ref-names` should be eliminated, or the `$Format:%D$` could be altered to eliminate any `HEAD` references

**Comment by RonnyPfannschmidt** [comment]
Duplicate of #418

**Comment by RonnyPfannschmidt** [comment]
Closing as duplicate of #806
