### ISSUE TITLE
Incorrect documentation regarding docker cache

### ISSUE THREAD

**Issue by dp-alvarez** [pypa/setuptools-scm#1031]
In this [documentation](https://setuptools-scm.readthedocs.io/en/latest/usage/) in the "Docker/Podman" section, it mentions how including the .git dir trashes the docker cache and it suggests a workaround.
Unfortunately it does not work because `pip install` for local paths are not cached, as per [pip's documentation](https://pip.pypa.io/en/stable/topics/caching/#locally-built-wheels).

I failed to find a way to forcibly enable the cache for local paths. We could ask for a `--force-cache` flag to be included in pip to make this work, I don't know if there is another way to do it.

**Comment by RonnyPfannschmidt** [comment]
The dependencies will be cached 

The local path itself is fine to not cache 

I fail to see the actual problem

**Comment by dp-alvarez** [comment]
Oh that is right, the dependencies will get cached.
I'm using Pixi to handle environment/dependency management so that gets cached at another layer, I was trying to cache the local wheel.
The use case is to avoid unnecessarily rebuilding the wheel if the .git directory changed but not any other files. Not too critical of a cache in most cases, but nice to have.

I'm closing this since it isn't that common of a use case, appreciate the clarification.
