### ISSUE TITLE
Don't use tag from repo for version

### ISSUE THREAD

**Issue by DaddyWesker** [pypa/setuptools-scm#1035]
Hello.

Is it possible to not use version tag from repo, but instead ask setuptools_scm to use custom version (handcrafted) but apply other additions (+commit hash etc)? I've tried for several days but haven't got any possible way to do this.

Reason for this question is the problem I'm facing when fork'ing another project. If I'm cloning main project (not my fork) setuptools_scm makes normal version like `0.1.8.dev50+g07021cb` though when I'm cloning my fork of this project and trying to see what sort of version setuptools_scm will give me I'm getting `0.1.dev2451+g11b3f0e.d20240419`. As I understand it is related to how setuptools_scm is getting the version - using version tags. But in the fork there are no tags. So I'm getting this weird stuff. So the idea was to use custom version '0.1.8' for example and ask setuptools_scm to just add other stuff except version. But I wasn't been able to do this. Anything I'm trying to add in the setup.py following your documentation is just being ignored by setuptools_scm. Or maybe I'm doing something wrong, which is possible.

I've also seen that there are some sort of variable `SETUPTOOLS_SCM_PRETEND_VERSION` which, by looking at the description, could be the thing I need, but how to change it properly using setup.py or pyproject.toml?

Anyway, thanks in advance for the answer.

**Comment by RonnyPfannschmidt** [comment]
@DaddyWesker did you update your own fork and your local repo with the tags? - unfortunately tags dont pass along automatically and need some manual action

**Comment by RonnyPfannschmidt** [comment]
a easy fix is to just fetch the tags from the upstream and pushing them to your fork as well

**Comment by DaddyWesker** [comment]
No, I haven't updated tags. But is there another fix? Since project could be forked by many others and I don't want to ask them to make some manipulations, but instead I want to ask setuptools_scm to use handcrafted version and add commit hash to it. Is it possible at all?

**Comment by RonnyPfannschmidt** [comment]
It's still not clear what you are asking for

I'm currently inclined to reject the idea

**Comment by DaddyWesker** [comment]
Okay... currently scm gets version from tag and adds some dev...hash stuff to it, right? Is there a way to prevent scm from getting version from git tags and use my own version instead? I know I can just put version='0.1.8' for example and it will be 0.1.8 and that is all. But I want scm to add '+dev...hash' to the version I've put instead of the version it finds from tags. I'm not asking something like "please add this", I'm interested if there is already such possibility?

**Comment by RonnyPfannschmidt** [comment]
There's no built-in mechanism 

The fallbacks are for when the scm is missing

**Comment by DaddyWesker** [comment]
Okay. And `SETUPTOOLS_SCM_PRETEND_VERSION` overrides version entirely? So if i set this variable then version will be like I set the variable without any additions?

**Comment by RonnyPfannschmidt** [comment]
yup

a complete hack to do it would be to have a version scheme that returns a constant and a local scheme that always returns the node

its strongly recommended against
i also strongly recommend against your intended scheme as based on my personal prior experience thats going to be a pain to understand

perhaps one of the calver schemes could be of help

**Comment by DaddyWesker** [comment]
Anywhere i can find a working example of version scheme usage? I've tried to use it like in documentation, but dynamic=['version'] just overrides any schemes. Probably I'm doing something wrong.

what is calver schemes?

**Comment by RonnyPfannschmidt** [comment]
in order to avoid the X-Y problem i'd like to know for what reason/use-case you want this very specific version scheme that is explicitly not compatible with pypi or most commonly understood versioning practices

**Comment by webknjaz** [comment]
FWIW this was solved in attrs by showing the contributors the exact Git commands to run: https://github.com/python-attrs/attrs/blob/main/.github/CONTRIBUTING.md#local-development-environment

**Comment by DaddyWesker** [comment]
@RonnyPfannschmidt

Well, as i stated at the beginning of the issue, in the project I've been working on we want to not ask contributors to update tags. Moreover, it is possible to contributors to have their own tags which can be different from tags from main repo. So we want to exclude tags from version entirely, only add commit hash info to the handcrafted version. Currently project is using setuptools_scm for dynamic versioning and thus why I thought it is possible to somehow bypass usage of tags using setuptools_scm which is probably my bad if it isn't possible. Anyway, If you can explain that hack you mentioned it will be great.

**Comment by DaddyWesker** [comment]
> FWIW this was solved in attrs by showing the contributors the exact Git commands to run: https://github.com/python-attrs/attrs/blob/main/.github/CONTRIBUTING.md#local-development-environment

Yes, thank you. I guess it is exactly what Ronny meant but in case of our project we are trying to avoid of asking contributors to download tags from main repo.

**Comment by RonnyPfannschmidt** [comment]
Closing this as out of scope 
The reasonable expectation is for  basic projects maintenance to happen

**Comment by vsbogd** [comment]
The question in this issue is not about changing versioning scheme. It is about a fallback version. `setuptools_scm` has the `fallback_version` config property which used as far as I understand when executing `git` fails. What we need is a fallback version for the case when there are no tags in a repo.

It could be solved by asking fork owners to sync tags in forks. But on the other hand:
- we need fallback version for the cases of running Python code without installing it first anyway
- releases are not done from forks except testing purposes (in last case it is assumed the person who does test should understand how versioning works) thus syncing tags in forks is superfluous
- requiring doing something manually by instruction usually means people will miss this step and raise issues with questions how to get a proper version

I have looked at the source code of `setuptools_scm` and I see two ways to implement the fallback on a client side:
- providing local versioning scheme
- overriding `parse` function

The question is whether there is a more straightforward way to set a fallback version for this case?

**Comment by RonnyPfannschmidt** [comment]
a possible acceptable solution would be to use the fallback version instead of 0.1 for when no tags are there as long as its accompanied with a big warning

**Comment by DaddyWesker** [comment]
Okay, for those who are interested as I was here is the solution:

```
def get_version(rel_path):
    new_ver = None
    with open(rel_path) as f:  lines = f.read().splitlines()
    for line in lines:
        if line.startswith('__version__'):
            delim = '"' if '"' in line else "'"
            new_ver = line.split(delim)[1].split("+")[0]
    if new_ver is None:
        raise RuntimeError("Unable to find version string.")
    return new_ver

def myscheme(version):
    return get_version("pkg/_version.py")
   
setup(
    ...
    use_scm_version={'root': '..',
                                   'version_scheme': myscheme},
 )
```

pyproject.toml
```
dynamic = [
    "version",
]
```

**Comment by RonnyPfannschmidt** [comment]
PSA the provided code is incorrect on multiple levels 

It would've been better to just set the value directly 

Instead a version scheme that completely sidesteps the tool is used 

Please don't pull this tool into that mess
