### ISSUE TITLE
UserWarning: tag 'v.xxx' no version found

### ISSUE THREAD

**Issue by uliw** [pypa/setuptools-scm#1042]
if I run  `python -m pip install --exists-action=w --no-cache-dir -r docs/requiremthents.txt` locally, all is fine. However, if it runs remotely to build the sphinx documentation at readthedocs.io, it fails when setuptlools_scm tries to get the version information

```
× Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [73 lines of output]
      /tmp/pip-build-env-p9a9kfr7/overlay/lib/python3.11/site-packages/setuptools_scm/version.py:95: UserWarning: tag 'v.0.12.0.8' no version found
        warnings.warn(f"tag {tag!r} no version found")
```
the strange part is that locally
```
python -m setuptools_scm 
0.12.0.25
```
correctly reports 0.12.0.25, whereas the above error message points to 'v.0.12.0.8' .  It's probably related to #804, but I am bit dumbfounded here

**Comment by RonnyPfannschmidt** [comment]
As far as I know,the dot directly after the v is invalid and not allowed

**Comment by RonnyPfannschmidt** [comment]
I suspect the repo with the error has only the incorrect tag,whereas your local repo has better matching tags available

**Comment by uliw** [comment]
indeed. Deleting the offending tag with 
```
git push -d origin v.0.12.0.8
```
solved the problem.
