### ISSUE TITLE
Python version limit

### ISSUE THREAD

**Issue by detrin** [pypa/setuptools-scm#1048]
Hey, I come here after trying to install `ujson==3.1.0` with `python3.7.3` and I can not upgrade those packages. The build setup in `ujson` is without maximal version of `setuptools_scm` which normally makes sense because the package version resolver should test if the python version is compatible. In this package however there is an issue probably no one thought of.

https://github.com/pypa/setuptools_scm/blob/main/pyproject.toml#L7 here you specify only the upper limit on python version. However after 3-5 years if someone will try to install another python package release from 2024 that uses `setuptools_scm` he/she can possibly run into issues. 

I suggest adding also lower boundary for packages for which this package can be installed and fully functional. The issue I had during installation are type hints. Your config supports also `python3.7.3`, but type hints are only from version `python3.8+`.

```
 > [ 7/14] RUN pip install --trusted-host pypi.python.org ujson==3.1.0:                                                                                                                                         
0.249 Collecting ujson==3.1.0                                                                                                                                                                                   
0.646   Downloading https://files.pythonhosted.org/packages/43/23/c2362e88248c169a3ff3e2cbe2d6d6ba5345260658476479b6e8703d4274/ujson-3.1.0.tar.gz (7.1MB)                                                       
3.078     Complete output from command python setup.py egg_info:                                                                                                                                                
3.078     Traceback (most recent call last):
3.078       File "<string>", line 1, in <module>
3.078       File "/tmp/pip-build-_c88o3dq/ujson/setup.py", line 87, in <module>
3.078         classifiers=[x for x in CLASSIFIERS.split("\n") if x],
3.078       File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
3.078         return distutils.core.setup(**attrs)
3.078       File "/usr/local/lib/python3.7/distutils/core.py", line 108, in setup
3.078         _setup_distribution = dist = klass(attrs)
3.078       File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line 444, in __init__
3.078         k: v for k, v in attrs.items()
3.078       File "/usr/local/lib/python3.7/distutils/dist.py", line 292, in __init__
3.078         self.finalize_options()
3.078       File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line 732, in finalize_options
3.078         ep.load()(self, ep.name, value)
3.078       File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2434, in load
3.078         return self.resolve()
3.078       File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
3.078         module = __import__(self.module_name, fromlist=['__name__'], level=0)
3.078       File "/tmp/pip-build-_c88o3dq/ujson/.eggs/setuptools_scm-8.1.0-py3.7.egg/setuptools_scm/__init__.py", line 8, in <module>
3.078         from ._config import DEFAULT_LOCAL_SCHEME
3.078       File "/tmp/pip-build-_c88o3dq/ujson/.eggs/setuptools_scm-8.1.0-py3.7.egg/setuptools_scm/_config.py", line 13, in <module>
3.078         from typing import Protocol
3.078     ImportError: cannot import name 'Protocol' from 'typing' (/usr/local/lib/python3.7/typing.py)
```

**Comment by RonnyPfannschmidt** [comment]
Requires-python is set to 3.8 for the version you are running

**Comment by detrin** [comment]
> Requires-python is set to 3.8 for the version you are running

Maybe I am wrong and the issue lies outside this repository. Here is `ujson==3.1.0` setup.py that I think is causing the issue
https://github.com/ultrajson/ultrajson/blob/5dea5ef3dce50d0dbe96595c1e9c79a95675f126/setup.py#L85
they didn't specify the version range used there. Usually for that there is no need, when you rely on the dependency. 

I am resolving the dependencies in Docker container, this should be the minimum needed to reproduce the error
```
ARG PYTHON_VERSION=3.7.3
FROM python:$PYTHON_VERSION

RUN pip install pip==9.0.1
# RUN pip install --trusted-host pypi.python.org setuptools_scm==7.1.0
RUN pip install --trusted-host pypi.python.org ujson==3.1.0
```
When I don't install `setuptools_scm` within the docker container it automatically tries to use `v8.1.0`. When I try to install the version `8.1.0` in Docker container it doesn't let me to due to the version limitation you pointed out and I missed.

```
ARG PYTHON_VERSION=3.7.3
FROM python:$PYTHON_VERSION

RUN pip install pip==9.0.1
RUN pip install --trusted-host pypi.python.org setuptools_scm==8.1.0
```

```
 > [ 7/15] RUN pip install --trusted-host pypi.python.org setuptools_scm==8.1.0:                                                                                                                                
0.218 Collecting setuptools_scm==8.1.0                                                                                                                                                                          
0.910   Could not find a version that satisfies the requirement setuptools_scm==8.1.0 (from versions: 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.4.1, 1.5.0, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.6.0, 1.7.0, 1.8.0, 1.9.0, 1.10.0, 1.10.1, 1.11.0, 1.11.1, 1.13.0, 1.13.1, 1.14.0rc1, 1.14.0, 1.15.0rc1, 1.15.0, 1.15.1rc1, 1.15.4, 1.15.5, 1.15.6, 1.15.7, 1.16.0, 1.16.1, 1.16.2, 1.17.0, 2.0.0, 2.1.0, 3.0.0, 3.0.1, 3.0.2, 3.0.4, 3.0.5, 3.0.6, 3.1.0, 3.2.0, 3.3.1, 3.3.2, 3.3.3, 3.4.0, 3.4.1, 3.4.2, 3.4.3, 3.5.0, 4.0.0, 4.1.0, 4.1.1, 4.1.2, 5.0.0, 5.0.1, 5.0.2, 6.0.0, 6.0.1, 6.1.0.dev0, 6.1.0, 6.1.1, 6.2.0, 6.3.0, 6.3.1, 6.3.2, 6.4.0, 6.4.1, 6.4.2, 7.0.0, 7.0.1, 7.0.2, 7.0.3, 7.0.4, 7.0.5, 7.1.0)
0.911 No matching distribution found for setuptools_scm==8.1.0
0.918 You are using pip version 9.0.1, however version 24.0 is available.
0.918 You should consider upgrading via the 'pip install --upgrade pip' command.
```
Seems like when I use old pip inside Docker container and we have `setup_requires=["setuptools_scm"]` in setup.py it doesn't check for the versions? I have never seen such behaviour.

**Comment by detrin** [comment]
When I work with `pip==10.0.0` inside the Dockerfile it seems that the issue disappears and I no longer need to specify the version of this repository. So, I think it was a bug in pip v9 and it is solved now.

**Comment by RonnyPfannschmidt** [comment]
Please note that the pip version you used was abhorrently outdated and is pretty much completely broken on numerous recently released packages

**Comment by detrin** [comment]
> Please note that the pip version you used was abhorrently outdated and is pretty much completely broken on numerous recently released packages

Indeed, it is very unfortunate, but I have to stick to this version of pip.
