### ISSUE TITLE
Can not get "no distance and clean" version

### ISSUE THREAD

**Issue by LuisBL** [pypa/setuptools-scm#105]
I try to release a new version: 5.0,
So I tag:

```
git tag -a -m 'test tag' 5.0
```

git describe is:

```
$ git describe --long
5.0-0-g0386a2c
$
```

I'm expecting as explain in : [setuptools_scm](https://github.com/pypa/setuptools_scm)
to get:
`no distance and clean:
    {tag}`
but I get:

```
distance and clean:
    {next_version}.dev{distance}+n{revision hash}
```

As you can see::

```
$ python setup.py install
...
$ ls dist/
Ble-5.1.dev0+ng0386a2c.d20161006-py2.7.egg
$ 
```

Same with a x.y.z version:

```
$ git tag -a -m 'test' 5.0.0
$ python setup.py install
...
$ ls dist/
dist/Ble-5.0.1.dev0+ng0386a2c.d20161006-py2.7.egg
$
```

 I'm using setuptools_scm_git_archive so I report this too.

**Comment by RonnyPfannschmidt** [comment]
`git describe --dirty --tags --long` please

_edit_

the output indicates your workdir is dirty

**Comment by LuisBL** [comment]
yes

```
$ git describe --dirty --tags --long
5.0.0-0-g0386a2c-dirty
```

**Comment by RonnyPfannschmidt** [comment]
then this is not a bug, but the state of your workdir
