### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by jaraco** [pypa/setuptools-scm#1050]
I'm at PyCon sprints and there are some users eagerly awaiting the release of the fix for #1038.

Can we cut a new release? What is the process? I looked at the last release (48b1cb547a407b986f674740eae4f54503a141e3), but it's not obvious to me how that's done. Presumably something like `scriv collect`, but I notice that doesn't indicate any versions to tag.

Please cut a release and let me know if I can help.

**Comment by bilderbuchi** [comment]
Isn't the fix https://github.com/pypa/setuptools_scm/pull/1039/commits/49a89c9181f92c9e436b7b45a6388a536acac026 contained in 8.1.0 already (as per the decoration on the commit message)?

**Comment by RonnyPfannschmidt** [comment]
The fix was already released 

I just haven't sorted the change log as I'm very short on time and people needed the release 

If there's a problem on older python versions,we might need a backport

**Comment by bpkroth** [comment]
I think it's not available in the `main` conda repos yet:
https://anaconda.org/main/setuptools_scm
Only conda-forge:
https://anaconda.org/conda-forge/setuptools_scm
Though not sure what you guys can do about that.

**Comment by RonnyPfannschmidt** [comment]
please report a issue against that downstream - its not managed by us

**Comment by jaraco** [comment]
Thanks all. Sorry for the noise. I missed the tag detail.

**Comment by RonnyPfannschmidt** [comment]
It's entirely my fault the official change log is not up2date

Thanks for reaching out so we could pinpoint the missing downstream update
