### ISSUE TITLE
Rename the project to setuptools-scm

### ISSUE THREAD

**Issue by jaraco** [pypa/setuptools-scm#1067]
As I pointed out in [this message](https://github.com/pypa/setuptools_scm/commit/1e224324604f910d20ef625e18a29b254305417f#r145320262), it seems that this project is unclear on what its name is. Historically, the name has been `setuptools_scm`, but with the 8.0 release and the move to pyproject.toml, the project renamed to `setuptools-scm`, but kept the name `setuptools_scm` in other places.

Incidentally, the project also seems to have had `setuptools-scm` as the indicated name (pre-normalized) in the wheels for versions prior to 8.0 as well. It'd be interesting to know why that is.

I'm not particularly interested in what the name of the project is, but I am interested in being consistent about it and avoiding being capriciously inconsistent just because the normalization allows it.

**Comment by RonnyPfannschmidt** [comment]
lets migrate names to the normalized name for consistency for all paces where its not a import name or entry-point name

**Comment by jaraco** [comment]
> lets migrate names to the normalized name for consistency for all paces where its not a import name or entry-point name

I'll leave `[tool.setuptools_scm]` alone for now, too. We can maybe take advantage of the name mismatch to utilize `[tool.setuptools-scm]` for a different purpose (as a section heading without implying behavior).
