### ISSUE TITLE
error setuptools-scm unable to detect version

### ISSUE THREAD

**Issue by sibylles** [pypa/setuptools-scm#1074]
Dear community

I know that there is a related closed topic. I re-open theh topic because there is an additional issue in my special IT environemnt.
https://github.com/pypa/setuptools-scm/issues/278
[script.docx](https://github.com/user-attachments/files/17186539/script.docx)

I am working on a dedicated virtual machine.
Windows 10 Enerprise.

**The code**

1.	Clone NCCS InVEST respository
Alternatively, you can download and unzip the [repository](https://github.com/mlacayoemery/NCCS-InVEST/archive/refs/heads/main.zip) manually into NCCS/NCCS-InVEST.

2.	Setup development environment
conda config --set ssl_verify false
conda create -n env-invest -c conda-forge "python=3.11"
conda activate env-invest
python --version
python -m pip --version
conda install -c conda-forge git gdal "numpy<2" abseil-cpp
gdalinfo --version
python -m pip install --upgrade pip setuptools wheel
cd NCCS-InVEST_main
pip install -r requirements-dev.txt
pip install .
invest list
invest run --help

**error**
**(env-invest) C:\Users\f80809100\NCCS-InVEST_main>pip install .**
Processing c:\users\f80809100\nccs-invest_main
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [52 lines of output]

LookupError: setuptools-scm was unable to detect version for C:\Users\f80809100\NCCS-InVEST_main.

      Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

      For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.g
[script.docx](https://github.com/user-attachments/files/17186530/script.docx)
it#egg=proj
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

(env-invest) C:\Users\f80809100\NCCS-InVEST_main>invest run --help
Der Befehl "invest" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

(env-invest) C:\Users\f80809100\NCCS-InVEST_main>git tag
fatal: not a git repository (or any of the parent directories): .git

(env-invest) C:\Users\f80809100\NCCS-InVEST_main>git status
fatal: not a git repository (or any of the parent directories): .git

(env-invest) C:\Users\f80809100\NCCS-InVEST_main>git tag
fatal: not a git repository (or any of the parent directories): .git

(env-invest) C:\Users\f80809100\NCCS-InVEST_main>SETUPTOOLS_SCM_DEBUG=1 setup.py --version
Der Befehl "SETUPTOOLS_SCM_DEBUG" ist entweder falsch geschrieben oder

**Comment by RonnyPfannschmidt** [comment]
it seems like windows shells need a different way to set the environment variables

using a downloaded zip file as demonstrated is not supported as those do not have the scm metadata 
please use a full git clone

as per the error messages from git - the .git folder is missing for you, please use a actual got clone

as workaround you can set the SETUPTOOLS_SCM_PRETEND_VERSION environment variable, but you need to ensure its value is sensible for your project

**Comment by sibylles** [comment]
Dear RonnyPfannschmidt
Many thanks. Actually I am a new python/conda user, so I have some follow-up questions.

- what do you mean by "please use a actual got (git) clone? I have installed git.
-What do you mean by set "SETUPTOOL_SCM_PRETEND_Version?

I got the following error
Der Befehl "SETUPTOOLS_SCM_PRETEND_VERSION" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

Kind regaards
Sibylle

**Comment by sibylles** [comment]
(base) C:\Users\f80809100\NCCS>git --version
git version 2.46.1.windows.1

**Comment by RonnyPfannschmidt** [comment]
a git clone is a code checkout made with `git clone`
as far as i can tell you unpacked a zop file, that is not supported

**Comment by sibylles** [comment]
Dear @RonnyPfannschmidt 

I used now
git config --global http.sslbackend schannel
In doing so, I was able to directly downlad the script via https.

(base) C:\Users\f80809100\NCCS>git config --global http.sslbackend schannel
(base) C:\Users\f80809100\NCCS>git clone https://github.com/mlacayoemery/NCCS-InVEST.git
Cloning into 'NCCS-InVEST'...
remote: Enumerating objects: 520, done.
remote: Counting objects: 100% (191/191), done.
remote: Compressing objects: 100% (105/105), done.
remote: Total 520 (delta 94), reused 149 (delta 65), pack-reused 329 (from 1)
Receiving objects: 100% (520/520), 53.03 MiB | 11.97 MiB/s, done.
Resolving deltas: 100% (102/102), done.

**However, I got now a new error at
conda install -c conda-forge git gdal "numpy<2" abseil-cpp**
--> I am wondering if I need to change a simple code, because this error did not appear before when loading the script via repository.

Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(950): An error occurred while installing package 'conda-forge::vc14_runtime-14.40.33810-ha82c5b3_21'.
Rolling back transaction: done
[Errno 13] Permission denied: 'C:\\Users\\f80809100\\AppData\\Local\\miniconda3\\envs\\env-invest\\msvcp140.dll'
()

Kind regards
Sibylle

**Comment by RonnyPfannschmidt** [comment]
the error relates to conda and permission errors on windows, im not familiar with any of that
i recommend reaching out to the conda community for a solution

im closing this issue as solved, as the setuptools-scm part seems to be resolved
