### ISSUE TITLE
Include `__all__` in autogenerated `version_file `

### ISSUE THREAD

**Issue by jamesbraza** [pypa/setuptools-scm#1075]
With an autogenerated `version_file ` from `setuptools_scm==8.1.0`, it does not include an `__all__`.

Thus, my IDE imported `TYPE_CHECKING` from the `version.py` instead of from `typing`.

Can we include an `__all__` in the autogenerated `version.py` file so code inspection won't try to import `TYPE_CHECKING`

**Comment by RonnyPfannschmidt** [comment]
absolutely, i'll take a little while before i can get to it

**Comment by jamesbraza** [comment]
I went ahead and did it since it's such an quick change. Thanks for accepting the request
