### ISSUE TITLE
error: Microsoft Visual C++ 14.0 or greater is required

### ISSUE THREAD

**Issue by sibylles** [pypa/setuptools-scm#1078]
Dear community

I am using a dedicated virtual machine and windows 10.

I started now with  step 2, as the script is now installed and skipped sslback

However I got a new error at, even I have installed Visual basic.
pip install .
uilding wheels for collected packages: natcap.invest
Building wheel for natcap.invest (pyproject.toml) … error
error: subprocess-exited-with-error

× Building wheel for natcap.invest (pyproject.toml) did not run successfully.
│ exit code: 1
╰─> [102 lines of output]

building ‘natcap.invest.delineateit.delineateit_core’ extension
error: Microsoft Visual C++ 14.0 or greater is required. Get it with “Microsoft C++ Build Tools”: [Microsoft C++ Build Tools - Visual Studio](https://visualstudio.microsoft.com/visual-cpp-build-tools/)
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for natcap.invest
Failed to build natcap.invest
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (natcap.invest)

**The planned script**

1. Clone NCCS InVEST respository
mkdir NCCS
cd NCCS
git config --global http.sslbackend schannel
git clone https://github.com/mlacayoemery/NCCS-InVEST.git
cd NCCS-InVEST

2. Setup development environment

conda config --set ssl_verify false
conda create -n env-invest -c conda-forge “python=3.11”
conda activate env-invest
python --version
python -m pip --version
conda install -c conda-forge git gdal “numpy<2” abseil-cpp
gdalinfo --version
python -m pip install --upgrade pip setuptools wheel
cd NCCS-InVEST_main
pip install -r requirements-dev.txt
pip install .

![image](https://github.com/user-attachments/assets/68cb6614-822f-478a-9387-997664203ba1)

Kind regards
Sibylle

**Comment by RonnyPfannschmidt** [comment]
the failed project is named `natcap.invest` please report in the right project
setuptools_scm is not using any compiled libraries itself

i am unfamiliar with building c extensions on windows
as far as i can tell the error message links a howto, so please follow it
