### ISSUE TITLE
Custom local_scheme not used when building

### ISSUE THREAD

**Issue by andy-maier** [pypa/setuptools-scm#1084]
When specifying a local_scheme in pyproject.toml using entrypoints, it is used correctly in `python -m setuptools_scm` but not used in the generated version file, and not used in the file names of the distribution archives when building them.

The `pyroject.toml` file has these relevant sections:
```
[build-system]
requires = [
    "setuptools>=70.0.0",
    "setuptools-scm[toml]>=8.1.0",
    "wheel>=0.41.3"
]
build-backend = "setuptools.build_meta"

. . .

[tool.setuptools_scm]
version_file = "myproject/_version_scm.py"
version_scheme = "no-guess-dev"
local_scheme = "myproject._local_scheme:main"
```

The `myproject/_local_scheme.py` file has this content:
```
from setuptools_scm.version import ScmVersion

def main(version: ScmVersion) -> str:
    return version.format_choice("", "+dirty")
```

Here is the difference between the `python -m setuptools_scm` output and the version in the (freshly) generated `_version_scm.py` file: 

```
Commit state   Latest tag                  python -m setuptools_scm   _version_scm.py
------------------------------------------------------------------------------------------------
Clean          1.23.0 on latest commit     1.23.0                     1.23.0+unknown
Dirty          1.23.0 on latest commit     1.23.0.post1.dev0+dirty    1.23.0.post1.dev0+unknown
Clean          1.22.2 on 13 commits back   1.22.2.post1.dev13         1.22.2.post1.dev13+unknown
Dirty          1.22.2 on 13 commits back   1.22.2.post1.dev13+dirty   1.22.2.post1.dev13+unknown
```

**Comment by andy-maier** [comment]
After some more investigation, it turns out that the result depends on whether "build" is run in an isolated environment or not:

* The above results were for an isolated environment (default of "build").
* When running "build" in a non-isolated environment (i.e. specify its `--no-isolation` option), the generated _version_scm.py file shows the same version that `python -m setuptools_scm` shows.

So my circumvention for now is to run "build" in a non-isolated environment. That's more transparent anyway.

**Comment by RonnyPfannschmidt** [comment]
whats the logging output when `SETUPTOOLS_SCM_DEBUG=1" in the environment

there should be a error when the version scheme is not found - if that error gets accidentally hidden we are missing a bug

**Comment by slayoo** [comment]
Confirming, we get exactly the same symptoms (`setuptools-scm==8.1.0 setuptools==75.3.0`).
The `--no-isolation` options indeed helps, but what is actually needed before is to install the package.

Running with `SETUPTOOLS_SCM_DEBUG=1` before installation we get:
```
...
DEBUG setuptools_scm.entrypoints EntryPoint(name='.git', value='setuptools_scm.git:parse', group='setuptools_scm.parse_scm') found <ScmVersion 2.90 dist=7 node=gfcede85b dirty=True branch=HEAD>
DEBUG setuptools_scm.version scm version <ScmVersion 2.90 dist=7 node=gfcede85b dirty=True branch=HEAD>
DEBUG setuptools_scm.version config Configuration(relative_to='pyproject.toml', root='.', version_scheme='post-release', local_scheme='PySDM.impl.scm_version:scheme', tag_regex=re.compile('^(?:[\\w-]+-)?(?P<version>[vV]?\\d+(?:\\.\\d+){0,2}[^\\+]*)(?:\\+.*)?$'), parentdir_prefix_version=None, fallback_version=None, fallback_root='.', write_to=None, write_to_template=None, version_file=None, version_file_template=None, parse=None, git_describe_command=None, dist_name='PySDM', version_cls=<class 'packaging.version.Version'>, search_parent_directories=False, parent=PosixPath('/home/user/devel/PySDM'))
DEBUG setuptools_scm.entrypoints ep found: post-release
DEBUG setuptools_scm.version version 2.90.post7
DEBUG setuptools_scm.version local_version +unknown
running egg_info
...
```

ad after installation:

```
DEBUG setuptools_scm.entrypoints EntryPoint(name='.git', value='setuptools_scm.git:parse', group='setuptools_scm.parse_scm') found <ScmVersion 2.90 dist=7 node=gfcede85b dirty=True branch=HEAD>
DEBUG setuptools_scm.version scm version <ScmVersion 2.90 dist=7 node=gfcede85b dirty=True branch=HEAD>
DEBUG setuptools_scm.version config Configuration(relative_to='pyproject.toml', root='.', version_scheme='post-release', local_scheme='PySDM.impl.scm_version:scheme', tag_regex=re.compile('^(?:[\\w-]+-)?(?P<version>[vV]?\\d+(?:\\.\\d+){0,2}[^\\+]*)(?:\\+.*)?$'), parentdir_prefix_version=None, fallback_version=None, fallback_root='.', write_to=None, write_to_template=None, version_file=None, version_file_template=None, parse=None, git_describe_command=None, dist_name='PySDM', version_cls=<class 'packaging.version.Version'>, search_parent_directories=False, parent=PosixPath('/home/user/devel/PySDM'))
DEBUG setuptools_scm.entrypoints ep found: post-release
DEBUG setuptools_scm.version version 2.90.post7
DEBUG setuptools_scm.version local_version 
running egg_info
...
```

The `pyproject.toml` includes:
```
[tool.setuptools_scm]
local_scheme = "PySDM.impl.scm_version:scheme"
version_scheme = "post-release"
```

The `scm_version.py` file:
```
def scheme(_):
    """ removes git hash from version string to avoid failures on upload to PyPI """
    return ""
```

This used to work with a `setup.py` back with setuptools==69.1.0 and setuptools-scm==7.1.0

HTH, looking forward to a fix or workaround, thanks

**Comment by RonnyPfannschmidt** [comment]
the canonical way to pass in local code on setuptools is with `setup.py`

the Scheme you posted is the equivalent of the builtin "no-local-version" scheme and i suggest just using that

i came to the conclusion that kex porblem here isthe pythonpath - and the package to be built is not commonly part of the pythonpath of the build tool (intentionally)

as the initial scheme is the equivalent of the dirty-tag scheme -  i recommend just using the builtin schemes and not messing with the default

i intend to enable a option to auto-drop the local tag on the default branch to enable test-pypi uploads and pypi uploads

**Comment by slayoo** [comment]
Thanks for quick reply!
We had it in `setup.py`, but after upgrading `setuptools_scm` it started to be ignored.
Using "no-local-version" works great! Thanks!

**Comment by RonnyPfannschmidt** [comment]
Closing this as environment issue 

Build isolation doesn't add . To pythonpath 

The outlined schemes are already builtin

`setup.py` should be used for passing code to setuptools
