### ISSUE TITLE
add a way to specify python-tag

### ISSUE THREAD

**Issue by kalfa** [pypa/setuptools-scm#1086]
It seems there is no way to specify a non-default python-tag using `pyproject.toml`

The current way is to create a `setup.cfg` file 

```
[bdist_wheel]
python-tag = py39
```

and then passing it to setuoptools-scm
```
DIST_EXTRA_CONFIG="/tmp/build_opts_${CI_CONCURRENT_ID}.cfg" python -m build  .
```

but this defeat the existence of pyproject, which should be the primary way to configure the build.

I suggest to add

```toml
[tool.setuptools_scm]
python-tag = value
```

with the same behaviour of the setup.cfg above.

**Comment by RonnyPfannschmidt** [comment]
Wrong project 

Did you mean to report to setuptools 

There's a tool.setuptools subkey to pass options

**Comment by kalfa** [comment]
Yes, it's actually build.

I spent long some time to understand how to configure the version format with setuptools scm , and it stuck in my head 😂
