### ISSUE TITLE
How to allow including files via symbolic links?

### ISSUE THREAD

**Issue by mgeier** [pypa/setuptools-scm#1092]
I have a directory within my package which contains many symbolic links (which are checked into Git): https://github.com/mgeier/insipid-sphinx-theme/tree/master/src/insipid_sphinx_theme/insipid/icons.

The links point into a Git submodule (which I made sure to check out).

I would like to include all of them (i.e. the files, not the actual symbolic links) into my sdist and wheel, but currently this doesn't happen. The directory (`insipid_sphinx_theme.insipid.icons`) seems to be automatically discovered, but no files from it are added to the sdist/wheel:

```
...
* Getting build dependencies for sdist...
No `packages` or `py_modules` configuration, performing automatic discovery.
`src-layout` detected -- analysing ./src
discovered packages -- ['insipid_sphinx_theme', 'insipid_sphinx_theme.insipid', 'insipid_sphinx_theme.insipid.static', 'insipid_sphinx_theme.insipid.icons']
...
```

How can I tell `setuptools-scm` to add those files?

**Comment by RonnyPfannschmidt** [comment]
This is unsupported 

Use setuptools manifests to deal with that

**Comment by mgeier** [comment]
Thanks for the quick clarification!

It works as expected when I add the symbolic links to `MANIFEST.in`.
