### ISSUE TITLE
PyPI trove classifieds do not match what is in setup.py

### ISSUE THREAD

**Issue by cclauss** [pypa/setuptools-scm#112]
https://github.com/pypa/setuptools_scm/blob/master/setup.py#L110-L113

Tools that use PyPI data can not automatically determine if setuptools_scm is Python3 compatible.

**Comment by RonnyPfannschmidt** [comment]
So what should I put there?

**Comment by RonnyPfannschmidt** [comment]
Feel free to just open a PR with better values :)

**Comment by cclauss** [comment]
In fact, the problem is not what is in this repo.  Instead, the PyPI record at https://pypi.python.org/pypi/setuptools_scm is missing the trove classifiers that are in setup.py.  Compare the text at the very bottom of that page with the previous version https://pypi.python.org/pypi/setuptools_scm/1.13.0 where the trove classifiers were correct.

**Comment by RonnyPfannschmidt** [comment]
it seems that the release process needs an updated script

**Comment by RonnyPfannschmidt** [comment]
will be testing a new upload procedure for 1.15.0

**Comment by RonnyPfannschmidt** [comment]
fixed in https://pypi.python.org/pypi/setuptools_scm/1.15.0 - but may come up again

**Comment by cclauss** [comment]
Thanks.  The setuptools_scm project is in the top 200 most downloaded PyPI packages and its status is back to green on https://python3wos.mybluemix.net/
