### ISSUE TITLE
Q: How to use setuptools_scm in setup.py in nested directory?

### ISSUE THREAD

**Issue by reece** [pypa/setuptools-scm#131]
Brief: I'd like to use setuptools_scm in a setup.py within a sudirectory of the repo. I'm aware of the `version = get_version(root='..', relative_to=__file__)` instructions, but this won't work unless setuptools_scm in manually installed first because it's evaluated before the `setup_requires` packages are installed. Is there a way to get the `use_scm_version=True` ease-of-use within a subdirectory?

Longer story/use case: I have a project that consists of protobuf message definitions and the derived language-specific models. I'd like them all in the same repo and released with a single tag for consistency. The structure is like this:

```
vmc-models
├── Makefile
├── proto
│   ├── types.proto
│   └── vmc.proto
├── c++
│    ├── ...
├── go
│   ├── ...
├── java
│   ├── ...
└── python
    ├── setup.py
    └── vmc
        ├── __init__.py
        └── models
            ├── __init__.py
            ├── types_pb2.py
            └── vmc_pb2.py
```

The top-level Makefile creates `types_pb2.py` and `vmc_pb2.py` from `types.proto` and `vmc.proto`.

So, with this setup, I'd like to be able to build a package and upload it to pypi. Yes, I could manually install setuptools_scm first, but this use case seems so close to what's already supported that it seems worth generalizing existing capabilities.

**Comment by reece** [comment]
Here's the best I've come up with so far:

```
class SCMVersion(object):
    def __str__(self):
        import setuptools_scm
        return setuptools_scm.get_version(root='..', relative_to=__file__)

    def __add__(self, other):
        return str(self) + other


setup(
    version = SCMVersion(),

```

The intent is to defer importing setuptools_scm and to provide the necessary dunder methods (for develop mode installation, at least).

The problem with this is that setuptools says this:

> /home/reece/projects/vmc-models/python/venv/lib/python3.5/site-packages/setuptools/dist.py:340: UserWarning: The version specified (<\_\_main\_\_.SCMVersion object at 0x7f66fd5eba58>) is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
>   "details." % self.metadata.version
>

**Comment by RonnyPfannschmidt** [comment]
@reece keyword arguments for get_version can be passed as dict to use_scm_version

**Comment by RonnyPfannschmidt** [comment]
@reece i created #132 as a followup to enhance the documentation, please provide some feedback if this answers your question or if you need more/an example

**Comment by reece** [comment]
Yep, answers the question. Submitted PR #133 to add docs. Closing this question. Thanks Ronny!

**Comment by why-not-try-calmer** [comment]
Thanks for addressing this use case; is there a way to do exactly that (i.e. declare the parent directory as the parent of `.git`) using _only_ `pyproject.toml`?

**Comment by RonnyPfannschmidt** [comment]
@why-not-try-calmer

```toml
# typed on mobile, use caution 
[tool.setuptools_scm]
root = ".."
```
