### ISSUE TITLE
Equivalent to VersionInfo.version_tuple()?

### ISSUE THREAD

**Issue by nicoddemus** [pypa/setuptools-scm#135]
Hi,

I'm trying to update `mock` to use `setuptools_scm` to solve testing-cabal/mock#385. Here's the relevant code in [`mock/mock.py`](https://github.com/testing-cabal/mock/blob/master/mock/mock.py#L71):

```python
from pbr.version import VersionInfo

_v = VersionInfo('mock').semantic_version()
__version__ = _v.release_string()
version_info = _v.version_tuple()
```

Replacing `__version__` is simple enough, but how about the `version_info` tuple? Is there something in `setuptools_scm` which provides the same functionality? 

Here's what `version_info` looks like for `mock-2.0.0`:

```
>>> import mock
>>> mock.__version__
'2.0.0'
>>> mock.version_info
(2, 0, 0, 'final', 0)
```

**Comment by nicoddemus** [comment]
Just found a related issue: pypa/setuptools_scm#36.

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus please note that if its already using pbr and its runtime metadata services (and likely its tooling for many related things, there is no point to push it to setuptools_scm on its own, as it handles only a subset of all that pbr does

(bascially pbr is a bug ball of features that breaks things for me ^^)

**Comment by RonnyPfannschmidt** [comment]
but in any case, what you request is a run-time service a install requirement would provide
additionally the proper content of a version tuple is undefined

**Comment by nicoddemus** [comment]
> please note that if its already using pbr and its runtime metadata services

You mean `mock`? It only seems to import `pbr`  in [this line](https://github.com/testing-cabal/mock/blob/master/mock/mock.py#L69) to get the version:

```python
from pbr.version import VersionInfo

_v = VersionInfo('mock').semantic_version()
__version__ = _v.release_string()
version_info = _v.version_tuple()
```

There's no other import for `pbr` anywhere on the code.

**Comment by nicoddemus** [comment]
Currently `setuptools_scm` generates a file like this:

```python
# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
version = '2.0.1.dev1+ngb7a77db.d20161129'
```

I would like to propose to generate *in addition* something like:

```python
version_info = (2, 0, 1, 'dev1', 'ngb7a77db.d20161129')
```

It seems like it could be useful and backward compatible. What do you think?

**Comment by jaraco** [comment]
It feels a bit messy to me to have setuptools_scm be generating a version file, but even more hacky for the version file to be generating multiple representations of a given version. If multiple version formats are necessary, mock should provide or require the tools necessary to perform those translations.

Reading the parent ticket, I see that the issue is that the cx_freeze model of packaging is not properly including the package metadata. I'll address that issue in the parent ticket.

**Comment by nicoddemus** [comment]
Thanks for joining in the discussion @jaraco, continuing on the parent ticket.

**Comment by RonnyPfannschmidt** [comment]
@jaraco there is a small reason to do generate the file - utility libraries may want to avoid the cost incurred by initializing pkg_ressources, but i dont see any other good reasons

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt that's one of the points I made in the [parent ticket](https://github.com/testing-cabal/mock/issues/385#issuecomment-263659556).
