### ISSUE TITLE
Using Cython causes issues deploying to PyPI with Travis CI

### ISSUE THREAD

**Issue by ksindi** [pypa/setuptools-scm#139]
I have a Cython file that generates a .c file when calling `tox`, which calls `build_ext --inplace`. The generated .c file corrupts my version. So instead of "jwalk-0.2.18" I get "jwalk-0.2.19.dev0+ng8c0908d.d20170101", which means I get a 400 Client Error when trying to deploy to PyPI with Travis.

What's the best practice to deal with this? My current solution is to just bypass building the c file using the build_ext module as per http://cython.readthedocs.io/en/latest/src/reference/compilation.html#distributing-cython-modules and adding the relevant *.c files to .gitignore.

**Comment by jaraco** [comment]
In my opinion, if the C file is generated, it shouldn't be tracked in source control, as it's not the source but an artifact. If you do that, then building it should add it to your sdist and binary distributions.

Alternately, you may be able to add it to your .ignore file and depending on your SCM, it may continue to track the file but ignore changes to it unless you explicitly invoke commits on it.

I haven't delved deeply into your situation, but I hope these suggestions help.

**Comment by RonnyPfannschmidt** [comment]
with recent versions, you might get by by setting the `SETUPTOOLS_SCM_PRETEND_VERSION` environment variable, but please verify if that fits your use-case

**Comment by ksindi** [comment]
Great suggestions. I think adding it to the .ignore but including it in MANIFEST.in makes sense.
