### ISSUE TITLE
python setup.py test fail from `gitlab-ci.yml`

### ISSUE THREAD

**Issue by LuisBL** [pypa/setuptools-scm#141]
From bash I can do a `python setup.py test`:

    $ python setup.py test
    running test
    running egg_info
    writing proj1.egg-info/PKG-INFO
    writing top-level names to proj1.egg-info/top_level.txt
    writing dependency_links to proj1.egg-info/dependency_links.txt
    reading manifest template 'MANIFEST.in'
    writing manifest file 'proj1.egg-info/SOURCES.txt'
    running build_ext
    test_clean_data (tests.lib_test.TestUtils) ... ok
    ----------------------------------------------------------------------
    Ran 1 test in 0.188s
    OK
    $

But from a gitlab `gitlab-ci.yml`:

    image: python:2
    cache:
      paths:
      - /cache
    mytest:
      script:
      - apt-get update -qy; apt-get install -y python-dev python-pip unzip
      - pip wheel -r requirements.txt --wheel-dir=/cache
      - pip wheel pandas --wheel-dir=/cache
      # To check that .git is on the gitlab runner
      - ls -al .git
      # install and bdist_wheel work but with 0.0.0 version
      - python setup.py install
      - python setup.py bdist_wheel
      # this fail
      - python setup.py test

I get this error::
 
    Running with gitlab-ci-multi-runner 1.8.1 (a2efdd4)
    Using Docker executor with image python:2 ...
    Using locally found image version with exactly the same ID
    Pulling docker image python:2
    ...
    $ ls -al .git
    total 44
    drwxrwxrwx   5 root root 4096 Jan  7 00:56 .
    drwxrwxrwx   8 root root 4096 Jan  7 00:56 ..
    -rw-rw-rw-   1 root root  195 Jan  7 00:56 FETCH_HEAD
    -rw-rw-rw-   1 root root   41 Jan  7 00:56 HEAD
    -rw-rw-rw-   1 root root   41 Jan  7 00:56 ORIG_HEAD
    -rw-rw-rw-   1 root root  339 Jan  7 00:56 config
    -rw-rw-rw-   1 root root 1423 Jan  7 00:56 index
    drwxrwxrwx   3 root root 4096 Jan  6 07:33 logs
    drwxrwxrwx 120 root root 4096 Jan  7 00:56 objects
    -rw-rw-rw-   1 root root  107 Jan  6 07:33 packed-refs
    drwxrwxrwx   5 root root 4096 Jan  6 07:33 refs
    $ python setup.py install
    ...
    $ python setup.py bdist_wheel
    /usr/local/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'use_scm_version' warnings.warn(msg)
    running bdist_wheel
    running build
    running build_py
    running egg_info
    writing proj1.egg-info/PKG-INFO
    writing top-level names to proj1.egg-info/top_level.txt
    writing dependency_links to proj1.egg-info/dependency_links.txt
    reading manifest file 'proj1.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*.py[cod]' found anywhere in distribution
    warning: no previously-included files matching '__pycache__' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    writing manifest file 'proj1.egg-info/SOURCES.txt'
    running build_scripts
    installing to build/bdist.linux-x86_64/wheel
    running install
    running install_lib
    creating build/bdist.linux-x86_64/wheel
    creating build/bdist.linux-x86_64/wheel/tests
    copying build/lib/tests/lib_test.py -> build/bdist.linux-x86_64/wheel/tests
    copying build/lib/tests/__init__.py -> build/bdist.linux-x86_64/wheel/tests
    creating build/bdist.linux-x86_64/wheel/proj1
    creating build/bdist.linux-x86_64/wheel/proj1/data
    copying build/lib/proj1/data/data.csv.gz -> build/bdist.linux-x86_64/wheel/proj1/data
    copying build/lib/proj1/lib.py -> build/bdist.linux-x86_64/wheel/proj1
    copying build/lib/proj1/logger.py -> build/bdist.linux-x86_64/wheel/proj1
    copying build/lib/proj1/__init__.py -> build/bdist.linux-x86_64/wheel/proj1
    running install_egg_info
    Copying proj1.egg-info to build/bdist.linux-x86_64/wheel/proj1-0.0.0-py2.7.egg-info
    running install_scripts
    creating build/bdist.linux-x86_64/wheel/proj1-0.0.0.data
    creating build/bdist.linux-x86_64/wheel/proj1-0.0.0.data/scripts
    copying build/scripts-2.7/proj1-run -> build/bdist.linux-x86_64/wheel/proj1-0.0.0.data/scripts
    changing mode of build/bdist.linux-x86_64/wheel/proj1-0.0.0.data/scripts/proj1-run to 755
    creating build/bdist.linux-x86_64/wheel/proj1-0.0.0.dist-info/WHEEL

    $ python setup.py test
    /usr/local/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'use_scm_version' warnings.warn(msg)
    running test
    running egg_info
    writing proj1.egg-info/PKG-INFO
    writing top-level names to proj1.egg-info/top_level.txt
    writing dependency_links to proj1.egg-info/dependency_links.txt
    reading manifest file 'proj1.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*.py[cod]' found anywhere in distribution
    warning: no previously-included files matching '__pycache__' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution writing manifest file 'proj1.egg-info/SOURCES.txt' running build_ext
    error: [Errno 2] No such file or directory: '/builds/2017/proj1/proj1/version.txt'
    ERROR: Build failed: exit code 1

The `setup.py` file is:

    $ cat ../proj1/setup.py 
    from setuptools import find_packages
    from setuptools import setup

    setup(name='proj1',
      use_scm_version={'write_to': 'proj1/version.txt'},
      description="Proj1",
      packages=find_packages(),
      test_suite = 'tests',
      # include_package_data: to install data from MANIFEST.in
      include_package_data=True,
      scripts=['scripts/proj1-run'],
      zip_safe=False)

The wonderful `setuptools_scm` is installed from requirements:

    $ cat ../proj1/requirements.txt 
    setuptools>=26 
    wheel>=0.29
    setuptools_scm

**Comment by untitaker** [comment]
You cannot use `requirements.txt`, you need to use `setup_requires` as specified in the README

**Comment by LuisBL** [comment]
silly me, it's works thank you
