### ISSUE TITLE
better document the supported SCMs

### ISSUE THREAD

**Issue by cdeil** [pypa/setuptools-scm#142]
Currently the short description of this package at https://github.com/pypa/setuptools_scm#setuptools_scm reads like this:

> setuptools_scm handles managing your python package versions in scm metadata instead of declaring them as the version argument or in a scm managed file.
> It also handles file finders for the supported scm's.

What are the currently supported SCMs?
I think it's hg and git from looking at the code.
Maybe mention this in the README?

If you confirm that it's git and hg, I could add that info to the README? How about right after that sentence talking about supported SCMs?

**Comment by RonnyPfannschmidt** [comment]
currently its only git and hg

there should probably also be a section on making plugins for others scm's via plugins/entry-points/custom functions, unfortunately my time is currently rather limited
