### ISSUE TITLE
Support SemVer pre-release versions (like 2.0.0-beta)

### ISSUE THREAD

**Issue by ralokt** [pypa/setuptools-scm#144]
Currently, any attempt to use such a version will cause infinite sadness.

This is because of the current implementation of `tag_to_version`:

```
def tag_to_version(tag):
    trace('tag', tag)
    # lstrip the v because of py2/py3 differences in setuptools
    # also required for old versions of setuptools
    version = tag.rsplit('-', 1)[-1].lstrip('v')
    if parse_version is None:
        return version
    version = parse_version(version)
    trace('version', repr(version))
    if isinstance(version, SetuptoolsVersion):
        return version
```

ie, `"2.0.0-beta"` is truncated to `"beta"`.

I understand that this is there in order to support tags like `internal_spam-v1.2.3`, and that what I'm asking for is directly at odds with that.

However, SemVer does mandate using Hyphens for pre-release versions:
> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version.

(from [http://semver.org/#spec-item-9](http://semver.org/#spec-item-9) )

Perhaps this could be adressed in the course of the planned switch to SemVer?

**Comment by RonnyPfannschmidt** [comment]
@ralokt pep44 differs a bit from semver with those regards, and currently i'm inclined to prefer mapping the rules of smever to pep440 as opposed to following a foreign version format for python tools

python versions already capture alpha/beta and a series of other cases

that being said, i wouldn't mind a proposed mechanism that does this correctly, but i do fear "correct" wil lbe far more tricky than anticipated right now

**Comment by ralokt** [comment]
I gave it a try! Let me know what you think, I'm open to suggestions (and implementing them). Possibly we'd even want to be a bit less strict? I'm not considering pep440 in my solution at the moment (but that should currently be covered anyway).

**Comment by RonnyPfannschmidt** [comment]
im closing this one, feel free to reopen when you find time to follow up
