### ISSUE TITLE
mention versioneer in the docs

### ISSUE THREAD

**Issue by jaraco** [pypa/setuptools-scm#15]
suggestion by @flub  suggestion to help making it searchable

---
- Bitbucket: https://bitbucket.org/pypa/setuptools_scm/issue/15
- Originally reported by: Ronny Pfannschmidt
- Originally created at: 2015-02-18T11:28:30.165

**Comment by cdeil** [comment]
I just found `setuptools_scm` for the first time and was wandering how it's the same or different from https://github.com/warner/python-versioneer .

+1 to adding at least a mention of https://github.com/warner/python-versioneer in the docs, or even better a few sentences how this package is different. That would be helpful to the many users of https://github.com/warner/python-versioneer to evaluate this "blessed" new package.
