### ISSUE TITLE
Using tags other than version number

### ISSUE THREAD

**Issue by tathagata** [pypa/setuptools-scm#173]
I am trying to use setuptools_scm with a git repository that uses tags for marking versions as well as   milestone releases. For example

`git log --no-walk --tags --decorate --simplify-by-decoration --oneline`

    0c9c618e (tag: MILESTONE_0.1.2, blah blah) Great success  
    11118060 (tag: 1.1.25, lorem impsum) HotFix: Put out fire
    1f1fbe5f (tag: 1.1.24, lorem ispum) bug fix
    048da873 (tag: MILESTONE_0.1.1, blahs blahs) Grand success

So  MILESTONE_0.1.2 and MILESTONE_0.1.1 can not be parsed. I am able to get around if I tag like

     MILESTONE_0.1.2-1.1.25 

but semantically it would not make sense and would break the convention that has been set with downstream.

I was not able to figure this out from the readme, if it is possible to somehow tell this setuptools_scm, that would be great.

**Comment by RonnyPfannschmidt** [comment]
currently the only way is a custom parse function, which is not documented because it is not yet completely implemented/correct

**Comment by kryskool** [comment]
Hi @tathagata 

You can write a version scheme like [this project](https://github.com/apenwarr/sshuttle/blob/master/setup.py)

In your **setup.py** add:

```
...
def version_scheme(version):
    from setuptools_scm.version import guess_next_dev_version
    version = guess_next_dev_version(version)
    return version.lstrip("MILESTONE_")

setup(
    name="mylib",
    use_scm_version={
        'write_to': "mylib/version.py",
        'version_scheme': version_scheme,
},
...
)
```

It works like

```
version = 'MILESTONE_0.1.2'
print(version.lstrip('MILESTONE_'))
0.1.2
```

Regards,

**Comment by tathagata** [comment]
@kryskool thanks for your answer. Unfortunately I ended up not using setuptools_scm - instead shell-ing out to run git commands and added some helper functions that would be good enough for our release process.
