### ISSUE TITLE
Unable to parse a semver version

### ISSUE THREAD

**Issue by KOLANICH** [pypa/setuptools-scm#183]
More precisely, it fails on the git tag "v0.0.1-alpha"

**Comment by RonnyPfannschmidt** [comment]
setuptools_scm handles python version numbers, which are not semver numbers, the parsers fail on the tags, since python does those tags differently

**Comment by Kentzo** [comment]
@KOLANICH See PEP 440 for the exact format.

I do think that setuptools_scm can be extended (e.g. via a plugin) to support semver.

**Comment by RonnyPfannschmidt** [comment]
currently its not possible as we use the python version parsing tooling in the internals
