### ISSUE TITLE
support git's export-ignore

### ISSUE THREAD

**Issue by anntzer** [pypa/setuptools-scm#185]
`git archive` reads the `export-ignore` gitattribute (https://git-scm.com/docs/gitattributes#_creating_an_archive) which allows marking some files as NOT packaged into the archive.  It would be nice if setuptools_scm did the same for the sdist.

Typical use cases would be to remove CI scripts.

Unfortunately AFAICT there is no way to ask git for the files it would archive short of actually running git archive and examining the resulting tarball.  OTOH it appears that such a step is much faster than the sdist build itself, so perhaps that remains an acceptable approach?

**Comment by jaraco** [comment]
I like this idea of restricting the files added by the file finder, though as mentioned, the interface is ugly. I'd feel better if the system processed the export-ignore directly or better if there were an API presenting the files to ignore.

@anntzer: Would you be willing to put together a PR for the feature?

**Comment by anntzer** [comment]
I'll leave it on my todo list, but it's not going to be very high in the priority queue.
Parsing gitattributes ourselves is a bit tricky as they can live in many places, including system-wide, possibly somewhere specified by the local and global gitconfig.  See https://git-scm.com/docs/gitattributes, e.g.
> Attributes that should affect all repositories for a single user should be placed in a file specified by the core.attributesFile configuration option (see git-config[1]). Its default value is $XDG_CONFIG_HOME/git/attributes. If $XDG_CONFIG_HOME is either not set or empty, $HOME/.config/git/attributes is used instead. Attributes for all users on a system should be placed in the $(prefix)/etc/gitattributes file.

(and I think if we do claim to support gitattributes we should do it correctly, not some subset of it).

Alternatively this can go e.g. to a field in setup.cfg (but I still think reusing git's already existing mechanism is better for setuptools_scm -- for the same reason that it uses git ls-files instead of MANIFEST.in).
