### ISSUE TITLE
write_to should also obey relative_to

### ISSUE THREAD

**Issue by anntzer** [pypa/setuptools-scm#188]
Say you have e.g.
```
repo/.git
repo/java/whatever
repo/python
repo/python/setup.py
repo/python/src/yourmagicpackage
```
ie. a typical case where you do need to specify root and relative_to.
In this case it seems preferable for write_to to also obey relative_to, i.e. you (I)'d like to write `relative_to=__file__, root="..", write_to="src/yourmagicpackage/_version.py"` rather than `..., write_to="python/src/yourmagicpackage/_version.py"`.

Obviously this would be a backcompat break, but I think the proposed behavior is more sensible?

**Comment by RonnyPfannschmidt** [comment]
this is an oversight, i need to take a look at correctly fixing it

**Comment by anntzer** [comment]
I now have a case that suggests that the requested behavior is actually needed.

When a package uses both `root=".."` (for example) and `write_to`, installation from a sdist fails; a minimal example is
```
#!/bin/sh
git init testrepo && cd testrepo
mkdir subdir && cd subdir

mkdir pypkg
touch pypkg/__init__.py
cat <<EOF >setup.py
from setuptools import setup, find_packages
setup(
    name="pypkg",
    packages=find_packages(),
    use_scm_version=lambda: {
        "root": "..",
        "relative_to": __file__,
        "write_to": "subdir/pypkg/version.py",
    },
    setup_requires=["setuptools_scm"],
)
EOF

git add . && git commit -m 'A commit.'
git tag v0.0

# Building a wheel works (and one can check that version.py is correctly written).
python setup.py bdist_wheel
rm -rf dist

python setup.py sdist --formats=zip && cd dist
pip install pypkg-0.0.zip
```

The relevant parts of the traceback:
```
Processing ./pypkg-0.0.zip
  Created temporary directory: /tmp/pip-req-build-fify1eow
  Running setup.py (path:/tmp/pip-req-build-fify1eow/setup.py) egg_info for package from file:///tmp/testrepo/subdir/dist/pypkg-0.0.zip
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-fify1eow/setup.py", line 10, in <module>
        setup_requires=["setuptools_scm"],
      File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3.6/site-packages/setuptools/dist.py", line 370, in __init__
        k: v for k, v in attrs.items()
      File "/usr/lib/python3.6/distutils/dist.py", line 281, in __init__
        self.finalize_options()
      File "/usr/lib/python3.6/site-packages/setuptools/dist.py", line 529, in finalize_options
        ep.load()(self, ep.name, value)
      File "/usr/lib/python3.6/site-packages/setuptools_scm/integration.py", line 22, in version_keyword
        dist.metadata.version = get_version(**value)
      File "/usr/lib/python3.6/site-packages/setuptools_scm/__init__.py", line 130, in get_version
        template=write_to_template)
      File "/usr/lib/python3.6/site-packages/setuptools_scm/__init__.py", line 58, in dump_version
        with open(target, 'w') as fp:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-fify1eow/subdir/pypkg/version.py'
Cleaning up...
  Removing source in /tmp/pip-req-build-fify1eow
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-fify1eow/
```
Note the attempt to write to `/tmp/pip-req-build-fify1eow/subdir/pypkg/version.py`, when that probably should instead be `/tmp/pip-req-build-fify1eow/pypkg/version.py` (because `subdir` doesn't exist anymore in the sdist).

Initially, I thought that the issue was that `root` was not taken into account when computing the target of `write_to` when installing from a sdist, but that doesn't actually help because again, once you're in the sdist, `../subdir/pypkg/version.py` doesn't exist either (what you'd "actually" want is `subdir/../pypkg/version.py`, and that's ignoring symlink subtleties).

**Comment by anntzer** [comment]
Looks like the following patch fixes the issue:
```
diff --git a/src/setuptools_scm/__init__.py b/src/setuptools_scm/__init__.py
index b256289..f1c7021 100644
--- a/src/setuptools_scm/__init__.py
+++ b/src/setuptools_scm/__init__.py
@@ -37,11 +37,11 @@ def _version_from_entrypoint(root, entrypoint):
             return version
 
 
-def dump_version(root, version, write_to, template=None):
+def dump_version(setup_py_dir, version, write_to, template=None):
     assert isinstance(version, string_types)
     if not write_to:
         return
-    target = os.path.normpath(os.path.join(root, write_to))
+    target = os.path.normpath(os.path.join(setup_py_dir, write_to))
     ext = os.path.splitext(target)[1]
     template = template or TEMPLATES.get(ext)
 
@@ -108,7 +108,10 @@ def get_version(
     root of the repository by supplying ``__file__``.
     """
     if relative_to:
-        root = os.path.join(os.path.dirname(relative_to), root)
+        setup_py_dir = os.path.dirname(relative_to)
+        root = os.path.join(setup_py_dir, root)
+    else:
+        setup_py_dir = root
     root = os.path.abspath(root)
     trace("root", repr(root))
 
@@ -119,7 +122,7 @@ def get_version(
             parsed_version, version_scheme=version_scheme, local_scheme=local_scheme
         )
         dump_version(
-            root=root,
+            setup_py_dir=setup_py_dir,
             version=version_string,
             write_to=write_to,
             template=write_to_template,
```

However I think this also suggests a number of additional changes, that could be helpful in making things less complex.

1) `relative_to` should default to `__file__`, because I honestly can't imagine any other reasonable value for it (but am happy to hear if I'm wrong) (note that the above patch indeed assumes that `relative_to` *is* the path to setup.py);
2) `root` should be renamed to (e.g.) `scm_root`, because it doesn't (or rather, won't anymore) apply to `write_to`, despite what the name may seem to imply.

**Comment by RonnyPfannschmidt** [comment]
@anntzer a pr with a test would be appreciated the additional changes you discovered are indeed required, a followup issue and later solution seems the most feasible for right now

as for defaults - `relative_to` should probably be the distribution root in the setuptools case and the callers `__file__` in the just `get_version` case

**Comment by anntzer** [comment]
Can the distribution root ever *not* be the directory containing `setup.py`?  In the case of `get_version`, do you want to support directly calling it from outside of a `setup()` call?

**Comment by RonnyPfannschmidt** [comment]
get_version is the outside of setup.py thing, i hope setuptools_scm will soonish-ly be able to work without setuptools to support other packaging utilities

additionally there are setups where setup.py is not in the root
(its certainly not endorsed, but people do what they need to)

**Comment by anntzer** [comment]
Given the possibilities that you raise, I would rather let you pick up whatever parts of the patch I posted above to commit your own fix, because it is genuinely difficult for me to envision all the possible cases.  (For example, again, the patch above does assume that `relative_to` *is* the path to `setup.py` -- it's not clear to me how things should behave otherwise.)

**Comment by jasondamour** [comment]
@RonnyPfannschmidt Since other tickets related to this have been getting closed (since 2017!), what is the current workaround to using `write_to` in a subdirectory?

**Comment by RonnyPfannschmidt** [comment]
Use a path relative to the scm root or opt in to the broken recursive parents findings 

A fixed version with paths relative to the project it's half complete in my worktee and Will hopefully merge soon
