### ISSUE TITLE
PEP440 local-version

### ISSUE THREAD

**Issue by FlorianWilhelm** [pypa/setuptools-scm#189]
I got a question regarding this line:
https://github.com/pypa/setuptools_scm/blob/529b5de893c920fa32b0a42f807ebc9ac8f78aa7/setuptools_scm/git.py#L95

Might it be that according to an updated [PEP440](https://www.python.org/dev/peps/pep-0440/#local-version-identifiers) the local-version is allowed to now even start with a digit? I know it was not always like that and therefore it was necessary to prepend a letter.

**Comment by RonnyPfannschmidt** [comment]
the g is simply put in there to ensure the versioning scheme is consistent, as git is a error prone data source with different styles of data

**Comment by RonnyPfannschmidt** [comment]
oh, and as an extra trick, this also indicates the version control system, git gets a g, hg gets a h

**Comment by FlorianWilhelm** [comment]
Okay, thanks for explaining. But in general it should also work without the `g` even in the case when the sha1 starts with a digit.

**Comment by RonnyPfannschmidt** [comment]
indeed, but personally i suggest to have it for consistence

**Comment by FlorianWilhelm** [comment]
Ok, thanks for the fast reply.
