### ISSUE TITLE
Plans for a new release?

### ISSUE THREAD

**Issue by woodyza** [pypa/setuptools-scm#191]
Hi!

I just spent some quality time fighting with what turned out to be the windows 8.3 filename format issue fixed by #174 - any chance that's scheduled to be rolled into a new release yet?

**Comment by RonnyPfannschmidt** [comment]
thanks for the note, it went under the bus for personal reasons, i#ll try today

**Comment by woodyza** [comment]
awesome, thanks very much 👍

**Comment by RonnyPfannschmidt** [comment]
did a few since then
