### ISSUE TITLE
Handle pristine repo with no existing tags

### ISSUE THREAD

**Issue by mortenlj** [pypa/setuptools-scm#192]
I'm in the process of creating a new library from scratch, and I'm copying parts of `setup.py` from an existing project, because I'm going to use the same tooling.

One problem is that until I create my first tag, `setuptools_scm` will fail hard because it can't detect a version to use. The result is that I have to comment out the `use_scm_version` line until after I have created the first tag, which seems silly.

Would it be possible to issue a warning and setting the version to 0.0.0.dev or something like that instead?

**Comment by mortenlj** [comment]
My bad, I just realized I hadn't even run `git init` in the directory. After running `git init` it will correctly function. Closing this.

**Comment by RonnyPfannschmidt** [comment]
thanks for the followup, better handling of no repo might help users as its indeed easyly possible to miss aux work when you are neck deep in a actual problem
