### ISSUE TITLE
setuptools_scm silently reports garbage version string if git fails to read tag

### ISSUE THREAD

**Issue by sjlongland** [pypa/setuptools-scm#193]
I needed a Debian package of `setuptools_scm` recently, so decided to set up our CI server to track the `master` branch (I'd prefer to use a stable branch, but I can't seem to find one) and build a new release.

Trouble is, it builds a package with version 0.1… This then gives me grief due to the fact that the version number doesn't actually reflect the true version number of the package, and dependant builds using the package, ignore it thinking it's too old.

The end result is the fundamental issue behind https://github.com/pypa/setuptools/issues/1233 which breaks packages like `stdeb`.

The problem can be illustrated with `git describe`:
```
root@bneprdci0:/srv/bamboo/working/163841/EXTPY-SSCM-JOB1/src# ls
appveyor.yml   deb_dist     dist     README.rst  setup.py        setuptools_scm-0.1.dev1+g2521712.tar.gz  testing
CHANGELOG.rst  default.nix  LICENSE  setup.cfg   setuptools_scm  setuptools_scm.egg-info                  tox.ini
root@bneprdci0:/srv/bamboo/working/163841/EXTPY-SSCM-JOB1/src# git describe
fatal: No annotated tags can describe '2521712ff13183a6bca7147a03ddd630795f3dd4'.
However, there were unannotated tags: try --tags.
root@bneprdci0:/srv/bamboo/working/163841/EXTPY-SSCM-JOB1/src# git describe --tags
v1.15.6-13-g2521712
```

It would seem none of the tags in the repository are annotated, and so `git describe` fails to find an appropriate tag.  This has a knock-on effect, with `setuptools_scm` failing to detect its own version string.

**Comment by sjlongland** [comment]
This problem it appears is further exacerbated by the way Atlassian Bamboo checks out git repositories and our use of Docker to build Debian packages.

When the checked-out repository is mounted within a container, the repository references Bamboo's repository cache.  That cache is then outside the container when `setuptools_scm` does its thing.  `setuptools_scm` *silently* fails, and returns a garbage version number instead.  It'd be nice for `setuptools_scm` to report a warning when this happens, so that people like myself have a better chance of diagnosing the issue.

Otherwise, we're left guessing… and that means wasted hours trying different fixes and digging through code we've never had to look at before to get at the root cause.

`setuptools_scm` looks like a fantastic tool, hadn't heard of it before yesterday, and I'm tempted to consider it in some of the packages we develop, but behaviour like the above makes it difficult to be relied upon.

**Comment by RonnyPfannschmidt** [comment]
is there anything we can do to correctly notice that bamboo is breaking the world?

**Comment by sjlongland** [comment]
I'd probably start by checking for errors reported by `git`… I haven't traced through the code fully but this module figures out the tag by making calls to the `git` binary, correct?

If so, there should be an exit status being returned, as well as some diagnostic information.  This will not parse as a tag.  Raising a warning would suffice.  At least then we have something to go on when things go pear shaped as they did here.

**Comment by RonnyPfannschmidt** [comment]
i will invesitgate if there is a way to ask git if the repo is fine
in order to support bamboo until then, you can take a look at setting the `SETUPTOOLS_SCM_PRETEND_VERSION` env variable to something sensible

**Comment by sjlongland** [comment]
Ahh okay, wasn't aware of that feature, I shall investigate.

**Comment by RonnyPfannschmidt** [comment]
it came to my attention that `git status -s` fill fail fatally for worktrees that are mounted in a unfortunate way

**Comment by RonnyPfannschmidt** [comment]
i noted that if .git is not a directory, it contains worktree metadata, im pondering whether thats a more correct way to fix up things

**Comment by automaticgiant** [comment]
is this a good issue to double up on for cases where someone wants to use a git worktree? in such a case,
```
f45c89bd73ab:dms-bwaf-v2 krm158$ cat .git
gitdir: /Users/automaticgiant/dms-bwaf.git/worktrees/dms-bwaf-v2
```
and running under [drone](drone.io) yields `[build:L20:0s] LookupError: setuptools-scm was unable to detect version for '/drone/src'.`

and using `SETUPTOOLS_SCM_PRETEND_VERSION` doesn't help:
```
[build:L7:0s] fatal: Not a git repository: /Users/krm158/src/github.kdc.capitalone.com/automaticgiant/dms-bwaf.git/worktrees/dms-bwaf-v2
[build:L8:0s] File Finder Failed for .git = setuptools_scm.git:list_files_in_archive
```

**Comment by RonnyPfannschmidt** [comment]
closing this as solved as both git workdirs and non-anotated tags are supported
