### ISSUE TITLE
Add the parse_fallback key to the use_scm_version dict

### ISSUE THREAD

**Issue by Kentzo** [pypa/setuptools-scm#194]
So one could specify a custom fallback rather than a full implementation of parse.

**Comment by Kentzo** [comment]
Additionally, I think both `parse` and `parse_fallback` should accept a dict as value. Where keys and values are same as for `setuptools_scm.parse_scm` and `setuptools_scm.parse_scm_fallback`.

This way authors could extend the behavior without creating a separate package.

**Comment by RonnyPfannschmidt** [comment]
with recent refactorings this is obsolete

fallbacks always happen
fallbacks don't get configured intentionally for now
