### ISSUE TITLE
Allow to specify a glob or regex as an entry_point name

### ISSUE THREAD

**Issue by Kentzo** [pypa/setuptools-scm#195]
So plugins could reference other files than at the root directory.

**Comment by Kentzo** [comment]
[My plugin](https://github.com/GreatFruitOmsk/setuptools_scm_about) provides a fallback for cases when there is no SCM metadata, but `__version__` is nevertheless available via a file. Since that file is usually inside user's package which can have an arbitrary name I cannot provide an entry_point in my plugin.

My current workaround is to use '.' as an entry point.

**Comment by RonnyPfannschmidt** [comment]
if someone implements it in a reasonable manner i#ll merge it, i wont work on it myself

**Comment by RonnyPfannschmidt** [comment]
closing this one as wont implement
i would recommend using pyproject.toml as fallback "anchor" similar to the fallback_version builtin fallback
