### ISSUE TITLE
How to specify the order of plugins?

### ISSUE THREAD

**Issue by Kentzo** [pypa/setuptools-scm#196]
Assuming I have multiple setuptools_scm plugins, how can I guarantee an order of their entry_point enumeration?

According to the pkg_resources doc:

> Entry points are yielded from the active distributions in the order that the distributions appear in the working set. (For the global working_set, this should be the same as the order that they are listed in sys.path.) Note that within the entry points advertised by an individual distribution, there is no particular ordering.

How do I define an order of setuptools_scm plugins in working set in modern (>30) versions of setuptools?

**Comment by RonnyPfannschmidt** [comment]
ther is no mechanism to define a custom order, the setuptools order is followed

**Comment by Kentzo** [comment]
By any chance do you know how setuptools defines the order?

**Comment by RonnyPfannschmidt** [comment]
nope

**Comment by jaraco** [comment]
I don't think there's any prescribed order. The order is probably an artifact of how the packages are discovered, which may itself be a platform-specific factor like the order in which files/directories are returned from the file system.

**Comment by Kentzo** [comment]
@jaraco Perhaps the order should be taken from the setup_requires list?

**Comment by jaraco** [comment]
It’s much more complicated than than. Entry points are a general purpose inversion of control tool. They can be defined by any package, even those installed by other package managers such as pip (or manually). They need not be defined in setup_requires.

Moreover, a package may present multiple entry points for the same entry point, such as pytest does with its plugins.

So you could imagine a situation where some packages were previously installed into the environment, other ones are indicated in setup_requires, and the resulting set is completely different.

I think in practice, it’s not going to be possible for setuptools to specify the order of entry points.

What may be worth consideration, however, is for a given entry point, such as a setuptools_scm plug-in, the spec for each entry point could allow for or require some type of priority such that the plugin engine could sort them.

That’s what the keyring project does to order the back ends indicated by entry points.
