### ISSUE TITLE
Pass the value of use_scm_version to custom parse functions

### ISSUE THREAD

**Issue by Kentzo** [pypa/setuptools-scm#197]
It should be possible for plugin developers to introduce new keywords into that dictionary to allow plugin configuration similar to setuptools_scm.

**Comment by Kentzo** [comment]
Perhaps all customizable callables should receive a config.

**Comment by Kentzo** [comment]
In particular, in [my plugin](https://github.com/GreatFruitOmsk/setuptools_scm_about) I'd like to give user a choice to specify a path to a file.

**Comment by RonnyPfannschmidt** [comment]
closing this as  we now have a config object
