### ISSUE TITLE
setuptools_scm explicit silent fallback

### ISSUE THREAD

**Issue by gaborbernat** [pypa/setuptools-scm#198]
Now  if in ``setup.py``  we turn on setuptools_scm and there's no SCM repository an exception is raised that no SCM repository, is it possible to fallback to a value instead of raising this error and still build the package? e.g. ``0.0.0-dev`` ?

**Comment by Kentzo** [comment]
Take a look at https://github.com/GreatFruitOmsk/setuptools_scm_about

Best Regards
Ilya Kulakov

**Comment by RonnyPfannschmidt** [comment]
@gaborbernat the env var `SETUPTOOLS_SCM_PRETEND_VERSION` is the canonical way to make it use a given value instead of trying to find a scm

**Comment by gaborbernat** [comment]
I see, however that overwrites the look for SCM. I wan't fallback to this value if no SCM. The about is what I want.

**Comment by RonnyPfannschmidt** [comment]
@gaborbernat in what cases does this happen to be required, i'd like to know more about the use-case before blindly enabling something

**Comment by gaborbernat** [comment]
the use case is the following:
- let there be a plugin-able library that uses the mechanism at https://packaging.python.org/guides/creating-and-discovering-plugins/
- now you want to write  a plugin for it,  you create a virtualenv, a ``setup.py`` for the plugin and to test it/develop it you use ``pip install -e .``
- in order to mock something together locally (maybe you just want to try something out) with static version in ``setup.py`` no git repository is needed; with ``setuptools_scm`` current version before ``pip install -e .`` you're forced the init an SCM repository (otherwise you're install will fail with an error) - at this point ``setuptools_scm`` forces you a step which you may forget, blowing up with an error. If you determine the plugin viable you'll create the git repository later on, at which point comes handy to have ``setuptools_scm`` manage versioning. The reason the plugins ``setup.py`` contains the use setuptools flag, is because it's generated by a scaffold generator (e.g. cookiecutter).

**Comment by RonnyPfannschmidt** [comment]
hmm, i'd like to point out that a cookiecutter plugin that makes something that requires scm but doesn't ensure/init the scm repo as well is broken and should be fixed instead - in particular if the init step is as cheap as a git init / reminidng the user to do a git init

in addition you can just comment/mask the use_scm_version line and it just stops caring
setuptools_scm itself in normal use is already a opt-in - and actually needs to be able to fail to **prevent** incorrect and broken metadata, my current understanding of your request is basically wanting to get back at broken/bad metadata because surrounding tooling is broken/incomplete

so im currently opposed

**Comment by gaborbernat** [comment]
I see your point, but from my side I want setuptools_scm opt in (e.g. graciously fallback), instead of forced in (e.g. the user might not have git installed locally - so the git init is not necessarily cheap). Either way the about plugin allows this, so no problems.

**Comment by RonnyPfannschmidt** [comment]
i dont consider the issue resolved then,
can you point to the cookiecutter template please as well, i'd like to arrive at a solution that ensures that solving the initial use issue nicely wont introduce incorrect/bad metadata at downstream users

**Comment by gaborbernat** [comment]
I cannot release the code, is not open source :-) but I've explained the use case.

**Comment by RonnyPfannschmidt** [comment]
@gaborbernat i see, in that case im not sure i can provide a well fitting solution in a timely manner

**Comment by gaborbernat** [comment]
hence why I said we can close this for now 👍 thanks for the effort!

**Comment by anntzer** [comment]
Any chance this issue can be reopened?  My use case is the following: I would like to move Matplotlib from versioneer to setuptools_scm, but a precondition on that is the ability to install from github's tarballs (discussion at https://github.com/matplotlib/matplotlib/issues/7962#issuecomment-353630093) which contain no metadata.
Even if you don't want to make this the default (versioneer uses 0+unknown, which seems as good as anything), you could let the users set something like `$SETUPTOOLS_SCM_FALLBACK_VERSION`.

**Comment by RonnyPfannschmidt** [comment]
@anntzer i like the idea, as we now have a config system that passes configuration trough i would like to propose a option to support that use case as a opt-in i propopse using the version `0+unknown.scm_missing`

for bonus points from users one could ask pip for the available versions and pick an increment

**Comment by anntzer** [comment]
Actually that wasn't too bad to implement, see #308.

**Comment by max-sixty** [comment]
A similar case we're seeing is with some CI tools (for example the new Google Cloud Build Github plugin) - the package are copied over, but not the `.git` path. I think this would solve that case too

**Comment by matthijskooijman** [comment]
With #327 merged, I think this issue can be closed? There is now a `fallback_version` config variable that can be set which is used if all other detections fail? It doesn't seem to be documented yet, though.

**Comment by RonnyPfannschmidt** [comment]
thanks, good catch, i didn't manage to finish my backlog on the weekend
