### ISSUE TITLE
document the MANIFEST.in-replacing capabilities of setuptools_scm

### ISSUE THREAD

**Issue by ThomasWaldmann** [pypa/setuptools-scm#199]
Dealing with MANIFEST.in and the package data include/exclude stuff in setup.py usually is a pain.
Either stuff is missing or you include crap accidentally.

setuptools_scm seems to handle this elegantly, but the README and docs focus on its version handling capabilities and don't tell much about the manifest/package-data related functionality.

After noticing that (more or less accidentally, iirc by some other docs mentioning that setuptools_scm can do that based on what's added to git) I did that PR: https://github.com/borgbackup/borg/pull/3355/commits/feb428b4e012686d42cf0240663660757dcf231a

There was also a little discussion about it there: https://github.com/borgbackup/borg/pull/3355

I didn't notice a problem with that yet.

The only thing to remember is to exclude unwanted files via MANIFEST.in.

**Comment by RonnyPfannschmidt** [comment]
@ThomasWaldmann would you consider the current readme header sufficient or should there be a more complete example?

**Comment by ThomasWaldmann** [comment]
Much better already!

Maybe it should mention both special cases that need attention:
- SCM-managed but unwanted files must be excluded in MANIFEST.in
- not-SCM-managed but wanted files must be included in MANIFEST.in

Guess the latter could be auto-generated stuff at / before sdist creation time.

**Comment by webknjaz** [comment]
> * SCM-managed but unwanted files must be excluded in MANIFEST.in
> * not-SCM-managed but wanted files must be included in MANIFEST.in

@RonnyPfannschmidt I wonder if we should instead recommend customizing `git_describe_command`? Thoughts?

**Comment by RonnyPfannschmidt** [comment]
@webknjaz i don't follow how the file finder is related to the describe command

**Comment by webknjaz** [comment]
Oh, I must've confused its use seeing that it talks about the ability to have `--exclude`

**Comment by tedivm** [comment]
I've been trying to use this feature but it just doesn't work for me. I have some yaml datafiles inside of my package, and in theory using this project means they should automatically be included but they aren't. I don't have a manifest.in file (although I'm about to add one since I can't get this to work).

**Comment by RonnyPfannschmidt** [comment]
closing as solved, its mentioned in both the readme and the new mkdocs docs
