### ISSUE TITLE
Allow custom timestamp for `get_local_node_and_date()`

### ISSUE THREAD

**Issue by engnadeau** [pypa/setuptools-scm#200]
## Expected Behavior
- Ability to set custom timestamps (e.g., `%Y%m%d%H%M%S` instead of `%Y%m%d`)
- Multiple dirty builds are sometimes generated in quick succession

## Actual Behavior
- Hardcoded `%Y%m%d` timestamp: https://github.com/pypa/setuptools_scm/blob/46df188a54e3eb2b0dfb93dbae59fb23249fbcce/setuptools_scm/version.py#L140-L144

## Specs
- `Python 3.6.1`
- `setuptools-scm 1.15.6`
```

**Comment by RonnyPfannschmidt** [comment]
this scheme is registered as `node-and-date = setuptools_scm.version:get_local_node_and_date`
for a higher resolution it should be relatively simple to regster something like a `node-and-timestamp` scheme

the quickest way to get it is a own setuptools_scm plugin,
the second quickest is to make a pr with it so i can merge/release
i wont to any feature-dev this year
