### ISSUE TITLE
feature request: git ls-files --recurse-submodules

### ISSUE THREAD

**Issue by anthrotype** [pypa/setuptools-scm#206]
The default FILES_COMMAND in setuptools_scm.git module uses `git ls-files` to list the files under version control.
I have a project where I use some git submodules and would like to also include the files inside them in the source distribution of the parent project.

git ls-files has an option `--recurse-submodules` that does that.

What would be the easiest way for me to customize the git.FILES_COMMAND?

I wonder if this should be the default?

thanks

**Comment by RonnyPfannschmidt** [comment]
i just took a look at the  details -  i believe using `--cached --recurse-submodules` is acceptable, making it the default needs a major release

**Comment by anthrotype** [comment]
are there still plans to add support for including all submodules recursively in files_command?
Or  maybe allow the user to pass a files_command hook?
thanks

**Comment by anthrotype** [comment]
I wonder if this may be useful https://github.com/Kentzo/git-archive-all

**Comment by bmerry** [comment]
@RonnyPfannschmidt I can't promise I'll have the time, but would you accept a PR that adds extra config to enable this (e.g. by adding a `git_ls_command` option) without changing the default, so that the problem can be worked around without requiring a major release?

**Comment by RonnyPfannschmidt** [comment]
Works for me

**Comment by RonnyPfannschmidt** [comment]
closing this as we currently use git archives to get the details

**Comment by anthrotype** [comment]
Does git archive include files recursively?

**Comment by RonnyPfannschmidt** [comment]
As far as I am aware not
