### ISSUE TITLE
LICENSE file is not included in the 1.15.7 tarball

### ISSUE THREAD

**Issue by garbas** [pypa/setuptools-scm#211]

**Comment by igor-raits** [comment]
Also tests are not included.

**Comment by arunpersaud** [comment]
Changelog is also missing

**Comment by SnarkBoojum** [comment]
I suggest to retitle this issue "Tarball misses half of the files"...

**Comment by SnarkBoojum** [comment]
Could you just release a new version with a fixed tarball, please?

**Comment by SnarkBoojum** [comment]
Please?

**Comment by RonnyPfannschmidt** [comment]
i#ll see to it when i can - i need to reintroduce a manifest.in file as it seems atm
