### ISSUE TITLE
document/gracefully handle when users create own dev versions in tags

### ISSUE THREAD

**Issue by jab** [pypa/setuptools-scm#213]
I had already created the tag "0.15.0.dev0" of my package, before uploading that development version to PyPI. I made some further progress and wanted to release a new development version, and so I created the tag "0.15.0.dev1". It seems I've found out the hard way though (doesn't seem to be documented?) that dev versions greater than 0 are currently unsupported – I'm now hitting this AssertionError:

https://github.com/pypa/setuptools_scm/blob/46df188a54e3eb2b0dfb93dbae59fb23249fbcce/setuptools_scm/version.py#L124

(``assert tail == '0', 'own dev numbers are unsupported'``)

If I comment out that assertion, `guess_next_dev_version` works like a charm. Could you please explain why that assertion is there, whether there are any plans to add support for "own dev numbers" (seems like totally valid usage, no?), and what you recommend doing in the meantime?

Thanks 😊

**Comment by RonnyPfannschmidt** [comment]
there is no plan to support own numbers there, that number is always the **distance in commits** form the last tag

which is also the reason for the assertion

note that if you look at the surrounding code it should be glaring, that the actual number is always ignored and the distance is always used

but i do agree that there should be better tooling around tagging

**Comment by jab** [comment]
Ok, so creating ".devN" style tags is unsupported, but you find this out neither from the documentation, nor at the time that you create a tag like "X.Y.Z.dev0". Creating such a tag is a time bomb that you only find out about who knows how much later – not even once you eventually create a tag like "X.Y.Z.dev1", but only in the NEXT change, who knows how long AFTER creating the .dev1 tag, when your CI suddenly breaks with an error nowhere near any of the changes that were just made. 🤦‍♂️ It definitely seems like a footgun to allow the "X.Y.Z.dev0" in the first place, which gets right past that `assert tail == '0'`.

So, besides documenting this prominently in the README/long_description, this should be caught sooner, ideally as soon as the first ".devN" style tag is ever detected. Further, the message "own dev numbers are unsupported" should be improved with a better description of what went wrong and a hint about how to actually fix the problem, e.g. `Detected a tag like "X.Y.Z.dev*", but .dev* tags are unsupported. Do ... to fix the problem and try again.`

And on that note, *what IS the recommended fix* when someone has already gotten themselves into this mess?

I've worked around this for now by deleting my "0.15.0.dev1" tag on GitHub, which got my CI working again, but is far from ideal, as I now no longer have a git tag for the revision that corresponds to the PyPI release. And all other contributors/environments that maintain a clone of the repo need their local "0.15.0.dev1" tags deleted too, or else will continue to get the error: e.g. readthedocs.org builds will continue to fail until their checkouts can be wiped and recreated.

Too late for me, but would be happy to see this improved for future users so they don't shoot themselves in the foot like I did.

Thanks for your consideration :blush:

**Comment by RonnyPfannschmidt** [comment]
thanks for explaining your needs and your solution

as part of the solution i'll have to turn that assertion into a warning

as for publishing releases, i will document that one should never tag a dev release (setuptools_scm is responsible for `.devX` versions

for pypi/public releases i believe a viable approach is to use alpha/beta releases , for privately published development releases my own preferences is just to upload them to a devpi instance via the ci (no tag involved)
