### ISSUE TITLE
Default settings for development do not work nicely with pypi

### ISSUE THREAD

**Issue by Letme** [pypa/setuptools-scm#217]
I have a simple project and the deployment to test-pypi is done via `.travis-ci.yml` for each commit on master branch. The problem is the below error and after reading the documentation couple of times is that I do not know how to switch to SimVer.

Probably my question is more in line of how to make this pypi compatible (what to add into `setup.py`) as the default is just not working for non-tagged deployment.

Error from travis-ci:
```
HTTPError: 400 Client Error: '0.0.11.dev14+g0f7c142' is an invalid value for Version. Error: Cannot use PEP 440 local versions. see https://packaging.python.org/specifications/core-metadata for url: https://test.pypi.org/legacy/
```

**Comment by RonnyPfannschmidt** [comment]
pypi rejects local versions by design, and setuptools_scm explots that fact in a way (preventing the uploading of randomc scm versions to pypi as a stopgap in release processes)

if you want to work that in more detail you can either reconfigure setuptools_scm in setup.py to stop protecting you from that or you can alter the pypi deployment to set up a env varible in `SETUPTOOLS_SCM_PRETEND_VERSION`

**Comment by Letme** [comment]
Can you point me to how to reconfigure `setuptools_scm` in `setup.py` to stop protecting me from that?

**Comment by RonnyPfannschmidt** [comment]
for example you can use `local_scheme` of https://github.com/pypa/setuptools_scm#configuration-parameters and set it to `'dirty-tag'`

aka
```python
setup(
   ...,
   use_scm_version = {'local_scheme':'dirty-tag'},
   ...,
)```

**Comment by RonnyPfannschmidt** [comment]
note, i suggest to only set that on travis in order to prevent personal mistakes in the release process

**Comment by Letme** [comment]
If I use `SETUP_TOOLS_SCM_PRETEND_VERSION`, then I can probably use it in master only and let default stay for the tags?

Then something like `{next_version}.dev{distance}` would work correct?

**Comment by Letme** [comment]
That fits nicely with your note as well (since otherwise I have to pipe in some stuff in travis)

**Comment by RonnyPfannschmidt** [comment]
off hand no idea, i usually use the default setup, and upload dev releases to a devpi instance

**Comment by brainwane** [comment]
Is this the sort of information that should go into pypa/warehouse#3153?

**Comment by RonnyPfannschmidt** [comment]
@brainwane possibly

**Comment by RonnyPfannschmidt** [comment]
closing this one as not actionable, the defaults are intentionally not upload friendly and can be configured away with a different sceme
