### ISSUE TITLE
Tag preprocessing

### ISSUE THREAD

**Issue by SF-300** [pypa/setuptools-scm#218]
Hello,

I'm currently evaluating setuptools_scm as a solution to CI versioning needs in my organization. Due to some historical reasons tags in our repositories are not formatted according to PEP 440 but can be trivially converted to compliant ones (e.g. "Version 1.2.3" -> "1.2.3"). However it looks like currently there is no hook/callback to perform such preprocessing and parsing fails miserably. Am I missing something? Is this functionality desired? Are PRs welcome?)

Thx in advance!

**Comment by RonnyPfannschmidt** [comment]
prs are welcome, there is a rough idea to enable this via parse_scm hooks however the design work on that never was finished, and the testing neither, so its currently incomplete

**Comment by SF-300** [comment]
I need some help in grasping the architecture. What's the purpose of "meta" function? It seems to me that this function is excessive - the functionality belongs to ScmVersion constructor. And "preformatted" arg looks like a hack. However "we use ScmVersion here in order to keep legacy code working" implies that the functionality actually was in ScmVersion before. So what's the grand idea?

**Comment by SF-300** [comment]
Also I've found [this issue](https://github.com/pypa/setuptools_scm/issues/87). Looks like the main reason not to include custom hook is that it gives too much freedom. I think that this may be solved by providing some (regex?) pattern and join symbol instead of callable.

**Comment by RonnyPfannschmidt** [comment]
@SF-300 the issue has a proposed solution i'd accept, it just wasn't implemented/followed up on

**Comment by RonnyPfannschmidt** [comment]
#276 sorted this out
