### ISSUE TITLE
Regression: hg repos with setuptools_scm>=1.15 are missing dev version bumps

### ISSUE THREAD

**Issue by avirshup** [pypa/setuptools-scm#219]
`setuptools_scm` 1.15.* is reporting incorrect version numbers for my hg repositories.

Specifically, a merge commit that follows a tag commit does not seem to trigger the version bump like I would expect. In the screenshot below, for instance, I would expect the tip to be version `1.1.dev[N]+[sha]`. However, versions 1.15.* report the tip's version as `1.0`.

To reproduce:
```bash
mkdir hgmergetest && cd hgmergetest && hg init

# create initial commit and tag it
touch a && hg add a && hg commit -m "initial commit" 
hg tag 1.0

# create a branch
hg branch branch1
touch b && hg add b && hg commit -m "create branch1"

# merge the branch into default
hg update default && hg merge branch1 && hg commit -m "merge branch1 into default"
```

Expected behavior (setuptools_scm 1.13 and 1.14):
```bash
> pip install "setuptools_scm<1.15"
> python -m setuptools_scm
Guessed Version 1.1.dev3+n8dce1535e70a
```

Behavior with `1.15.*`:
```bash
> pip install setuptools_scm==1.15.7
> python -m setuptools_scm
Guessed Version 1.0
```

![image](https://user-images.githubusercontent.com/9388007/37140764-b80a0c36-2267-11e8-87f8-bd52d199140c.png)

**Comment by avirshup** [comment]
If you like, I'd be happy to submit a PR with at least a _test_ for this issue.

I'd be even happier to submit a fix if I could, of course, but I don't know much about mercurial. My best guess is that this issue has something to do with the [`revset` string in hg.py lines 11-12](https://github.com/pypa/setuptools_scm/blob/632b02b8ad1f10c79d36c03502069d74c9686c73/setuptools_scm/hg.py#L11-L12)? It would appear that the [`hg log` call on lines 14-15](https://github.com/pypa/setuptools_scm/blob/632b02b8ad1f10c79d36c03502069d74c9686c73/setuptools_scm/hg.py#L14-L15) returns an empty string.

**Comment by RonnyPfannschmidt** [comment]
personally, no idea either - i stopped using/working on mercurial a few years ago due to bitbucket's choices and the results for the community - i'm happy to have a test and would love to get a fix, but i wont work on it myself

**Comment by RonnyPfannschmidt** [comment]
its likely that the revset is incomplete, we might need to stop considering the tag commit the same version as the tag since its error prone and the edge cases keep coming

**Comment by avirshup** [comment]
Thanks for the lightning fast reply!

> its likely that the revset is incomplete

Hmmm ... after reading up (for the last few minutes, anyway) on revsets, I think I can at least take a stab at fixing this. Will open a PR soon with the test case, and hopefully the fix soon after that.
