### ISSUE TITLE
unclear documentation of Usage with Sphinx

### ISSUE THREAD

**Issue by reuvenpo** [pypa/setuptools-scm#221]
In the Usage with Sphinx section, it says: "It is discouraged to use setuptools_scm from sphinx itself".

One would assume that the intent is that `setuptools_scm` should not be used from within the `conf.py` file(`sphinx`'s configuration file), but it doesn't make sense to me to use the supplied code example anywhere else. You wouldn't put it in the `setup.py` file, as part of the `build_sphinx` command configuration, as that executes before `setuptools_scm` generates the version string.

Where then should i extract the version information, and if the answer is indeed in the `conf.py` file, then is there a way to ensure that my project is automatically installed before the documentation is built? (by either `setuptools` directly, when using `setup.py build_sphinx`, or manually in `sphinx`'s `conf.py` file)

Thank you in advance for your help! :smile:

**Comment by RonnyPfannschmidt** [comment]
the correct way to get the version is by using pkg_ressources and asking it for the version fo the installed package, i'll ensure to docment this better

the main reason for the suggestion is that there are edge-cases around documentation use

**Comment by RonnyPfannschmidt** [comment]
i just re-checked the readme its already documented to use pkg_ressources for the decalred rasons

**Comment by reuvenpo** [comment]
At the time i couldn't understand which file these lines should go in, but i've since figured out they go in `conf.py`.

My slight confusion aside, thanks for making a great tool :) i don't know how i lived without it before

**Comment by RonnyPfannschmidt** [comment]
@reuvenpo thanks for the followup, i#ll add something to that file content to make it more discoverable

**Comment by RonnyPfannschmidt** [comment]
@reuvenpo please take a look if #244 is sufficient, please drop a line of there are other places that would make things easier to understand if some comments like that where added

**Comment by reuvenpo** [comment]
Hey, yes this comment does make the example a lot clearer :)

After looking at the README again I can't think of other places where this kind of comment can add clarity, but I have to admit I didn't quite understand the last example. Is it an example of the previous section on "Version number construction", or is it a standalone example? If it's an example of the previous section it doesn't seem to me (and my unexperienced eyes) that it's related, and if it's just another usage example, it should probably go up with the other usage examples.

**Comment by RonnyPfannschmidt** [comment]
@reuvenpo thanks for that note, its indeed unclear and meant to go to setup.py

**Comment by Michael-E-Rose** [comment]
I would like to continue talking about this.

Currently, https://github.com/pypa/setuptools_scm#usage-from-sphinx suggests to use this code in `docs/conf.py`:

    from importlib.metadata import version
    release = version('myproject')
    version = '.'.join(release.split('.')[:2])

I'm using exactly like this, and the sphinx build on readthedocs fails consistently with `importlib.metadata.PackageNotFoundError: No package metadata was found for pybliometrics`.

Now I wonder whether this is a question about proper configuration of readthedocs, or about additional/different lines of code. Either way, I think this should be documented. `importlib.metadata.version()` is fairly new but intended as new default - therefore the world can benefit from more clarity.

**Comment by RonnyPfannschmidt** [comment]
@Michael-E-Rose did you do a editable/real install? before running sphinx?

**Comment by Michael-E-Rose** [comment]
If by that you mean the `make` execution in the folder where the Sphinx source files live: yes, I ran `make html` and it worked without problem.

**Comment by RonnyPfannschmidt** [comment]
No, it means doing a `pip install -e`  of the package before running sphinx

**Comment by Michael-E-Rose** [comment]
I put `-e .` in the requirements.txt for ReadTheDocs and now it works.
