### ISSUE TITLE
pkg_resources.SetuptoolsVersion is not available anymore in setuptools 39

### ISSUE THREAD

**Issue by anntzer** [pypa/setuptools-scm#223]
xref https://github.com/pypa/setuptools/commit/eeeb9b27fa48fccf2b5d52919eff1c75c4ad1718

the warning at https://github.com/pypa/setuptools_scm/blob/fc824aaaa952ded5f6ee54bcddafb0d96f4b44c4/setuptools_scm/version.py#L17 is now incorrect.

**Comment by RonnyPfannschmidt** [comment]
@jaraco - im wondering how to best resolve this, i believe i have to make a cut in supported setuptools versions

**Comment by RonnyPfannschmidt** [comment]
i checked history, the best solution forward is to parse a version, if its a tuple bail out completely, else use the strict version type obtained by parsing the version
