### ISSUE TITLE
Git and mercurial disagree on the latest tag

### ISSUE THREAD

**Issue by avirshup** [pypa/setuptools-scm#229]
Currently, [`setuptools_scm.git` only pays attention to git tags that contain a "`.`" by using](https://github.com/pypa/setuptools_scm/blob/b7182bad424848e86abf1d747fad8327d7933920/setuptools_scm/git.py#L1): 
```
git describe --dirty --tags --long --match *.*
```

OTOH, [`setuptools_scm.hg` considers _all_ tags by running](https://github.com/pypa/setuptools_scm/blob/b7182bad424848e86abf1d747fad8327d7933920/setuptools_scm/hg.py#L50):
```
hg parents --template "{latesttag} {latesttagdistance}
```

So, for instance, the tag `some-random-tag` is ignored in a git repository, but is used (and causes an error upon parsing) in a mercurial repo.

### To replicate (in an existing repository):
(I'm using `setuptools_scm 1.16.1`)

With git:
```
> git tag 1.0.0
> touch tempfile && git add tempfile && git commit tempfile -m "commit tempfile"
> git tag some-random-tag
>
> python -m setuptools_scm
Guessed Version 1.0.1.dev1+ngffe9b95
```

With hg:
```
> hg tag 1.0.0
> touch tempfile && hg add tempfile && hg commit tempfile -m "commit tempfile"
> hg tag some-random-tag
>
> python -m setuptools_scm
Traceback (most recent call last):
[...]
  File "[...]/setuptools_scm/version.py", line 86, in meta
    assert tag is not None, 'cant parse version %s' % tag
AssertionError: cant parse version None
```

(Fixes proposed below)

**Comment by avirshup** [comment]
I can submit a PR to fix this either by:

1) replicating the git behavior in `setuptools_scm.hg` (which, given common naming conventions, works for many but definitely not all use cases), OR
2) adding a function that finds correct right tag using a more generalized test (say, by trying to normalize the tag into a PEP440 version using `pkg_resources`) for both `git` _and_ `hg`

Would either of these make sense?

**Comment by RonnyPfannschmidt** [comment]
both make sense, i'm not sure which makes more sense, but i believe we should start with 1. for consistency and note 2. for a follow-up at a later point

**Comment by avirshup** [comment]
Yeah, that seems sensible - I'll submit a PR for 1) and open a new issue for 2). Thanks!

**Comment by RonnyPfannschmidt** [comment]
closing as the pr and the followup are issued
