### ISSUE TITLE
since 1.16.0 setuptools_scm can't work if only installed via setup_requires

### ISSUE THREAD

**Issue by sileht** [pypa/setuptools-scm#232]
Hi,

If setuptools_scm is in setup_requires, and the virtualenv or the operating system doesn't have setuptools_scm installed, the sdist/bdist is generated correctly.

Also we can sse this warning:

/home/tester/src/.tox/py35-postgresql-file-upgrade-from-4.2/bin/python3.5: Error while finding spec for 'setuptools_scm.git' (ImportError: No module named 'setuptools_scm')

This warning should be fatal, since the generated sdist/bdist will not work.

I'm guessing this is due to the installation done by easy_install. The console_script that run "git archive" will be not available.

**Comment by sileht** [comment]
It's due to https://github.com/pypa/setuptools_scm/blob/master/setuptools_scm/git.py#L17
using "-m". Because the package is installed with easy_install, the module will not be into the PYTHON PATH.

**Comment by RonnyPfannschmidt** [comment]
as resolution i believe i will have to make it a function

**Comment by RonnyPfannschmidt** [comment]
as part of this a failing files command should be fatal as well

**Comment by sileht** [comment]
I can provide a fix for both, is that ok for you ?

**Comment by RonnyPfannschmidt** [comment]
@sileht of course, i'm happy to release a fix once its done
from my pov its great that you fix those things right now, since i dont have the time for it this week but i can easily trigger a release in between things

**Comment by RonnyPfannschmidt** [comment]
thanks for the swift and clean work, i merged and triggered a release :+1:
