### ISSUE TITLE
documentation example for version customisation is not working

### ISSUE THREAD

**Issue by goffi-contrib** [pypa/setuptools-scm#237]
Hello and thanks for this tool.
In the README, the following code is given as an example of version customization:

```python
def myversion():
    from setuptools_scm.version import dirty_tag
    def clean_scheme(version):
        return dirty_tag(version) if version.dirty else '+clean'

    return {'local_scheme': clean_scheme}
```

but `dirty_tag` doesn't exist anymore.
Also, if we use `+` in the string like in the example above, it is removed from the final output, so it's not possible to use local version identifier as described at https://packaging.python.org/tutorials/distributing-packages/#local-version-identifiers (but without customization, the `+` is present normally).

**Comment by RonnyPfannschmidt** [comment]
thanks for the note

on point 1. indeed a mistake in the docs, the name is get_local_dirty_tag 
on point2. im not sure what you mean, can you elaborate  - it should always be there, if it gets removed then something is wrong, at least a quick skimming of the code makes it clear that the version should always be a concat of the involved strings

**Comment by goffi-contrib** [comment]
Hi, thanks for quick feedback.
for point 2, I'm using something like this:

```python
def sat_dev_version():
    """Use mercurial data to compute version"""
    def version_scheme(version):
        return VERSION

    def local_scheme(version):
        # XXX: setuptools_scm seems buggy and the '+' and the '_' are replaced by '-'
        #      breaking the local version identifier scheme
        #      cf. https://github.com/pypa/setuptools_scm/issues/237
        return "+{rev}_{distance}".format(
            rev=version.node[1:],
            distance=version.distance)

    return {'version_scheme': version_scheme,
                'local_scheme': local_scheme}

setup([…]
      setup_requires=['setuptools_scm'],
      use_scm_version=sat_dev_version)
```

But the version of the package is:

```
$ python -c "from pkg_resources import get_distribution; print get_distribution('sat').version"
0.7.0D-7e7f4e344a96-569
```
note that the `+` and `_` both became `-`

I'm using Python 2.7.12

**Comment by RonnyPfannschmidt** [comment]
your setuptools is too old - old setuptools breaks things, i believe its about time to fail harder on it

**Comment by goffi-contrib** [comment]
@RonnyPfannschmidt hum, I seem to be up-to-date with setuptools:

```
$ pip install -U setuptools
Requirement already up-to-date: setuptools in ./env/lib/python2.7/site-packages (39.0.1)
```

And still the same behaviour. Also if I don't use custom output, the `+` is there normally, that's why I tend to think it's coming from `setuptools_scm`.

**Comment by goffi-contrib** [comment]
by the way, my project is available online, you can check the full `setup.py` there: https://repos.goffi.org/sat/file/tip/setup.py

**Comment by RonnyPfannschmidt** [comment]
@goffi-contrib thanks for the note, i'll verify as i suspect a bug then

**Comment by RonnyPfannschmidt** [comment]
@goffi-contrib i cloned that repo and setuptools_scm works correctly if i disable your version schemes

with your version schemes enabled the version that gets installed has incorrect data

**Comment by RonnyPfannschmidt** [comment]
```
 python setup.py --version
/home/rpfannsc/Projects/pypa/sat/.env/lib/python2.7/site-packages/setuptools/dist.py:406: UserWarning: The version specified ('0.7.0D+18e2ca5f798e_570') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  "details." % self.metadata.version
0.7.0D+18e2ca5f798e_570
``` seems indicative enough tho - the 'D' is not a valid part of a python version string

**Comment by RonnyPfannschmidt** [comment]
for testing i replaced the 'D' with '.dev' and everything works as expected again, im inclined to close this one as user error

**Comment by goffi-contrib** [comment]
right, if I replace the "D" it's working (but I didn't got the same warning as you).
I guess setuptools is fixing invalid names in my version. Sorry for taking your time, and thanks for feedback and fix. I guess this tickets can be closed

**Comment by RonnyPfannschmidt** [comment]
@goffi-contrib then please check with your distro if they disalbe certain warnings, because it seems
