### ISSUE TITLE
git file finder: follow symlinks

### ISSUE THREAD

**Issue by sbidoul** [pypa/setuptools-scm#245]
Imagine the following directory structure where setup.py is in a subdirectory in the git repo, and contains a symlink to a parent directory.

```
package/module.py
setup/setup.py
setup/package -> ../package
```

Currently, the git file finder will ignore the symlinked directory as it does a `git ls-files <setup root>`.

Such a directory structure is useful in situations where one does not have freedom to arrange a canonical directory structure in the repo.

Would you review a PR that makes the git file finder follow symlinks (of course restricting links to files/directories that are themselves part of the same git repo).

**Comment by RonnyPfannschmidt** [comment]
in my general experience this is really easy to mess up and then opens painful security holes, so currently i strongly believe that projects with just too funky setup's should just use manifest.in or whatever works

**Comment by sbidoul** [comment]
I'm not sure it's that "funky". For instance, setuptools follows symlinks when finding packages. The SCM file finders here currently don't. It could be seen as a discrepancy.

Anyway I implemented it where I need it: https://github.com/acsone/setuptools-odoo/pull/29, you may want to have a look. I tried to make readable tests. It should be safe from a security standpoint, as it only includes files whose realpath is in the output of git ls-files. 

If you are interested I'm happy to move it as a PR here. If you find it too risky or don't want to maintain that (which I can perfectly understand), feel free to close this issue.

**Comment by RonnyPfannschmidt** [comment]
after reading the code, i believe the solution is quite reasonable and secure enough.

i'd be happy to accept it, bringing the tests you wrote to verify your code in a shape that fits setuptools_scm would be nice to have, but can be a follow-up by anyone interested

**Comment by sbidoul** [comment]
@RonnyPfannschmidt thanks for the positive feedback.

My algorithm is failing the current test with the following error:

```
    @pytest.mark.issue(228)
    def test_git_archive_subdirectory(wd):
        wd('mkdir foobar')
        wd.write('foobar/test1.txt', 'test')
        wd('git add foobar')
        wd.commit()
>       assert integration.find_files(str(wd.cwd)) == ['foobar/test1.txt']
E       AssertionError: assert ['/tmp/pytest...ar/test1.txt'] == ['foobar/test1.txt']
E         At index 0 diff: '/tmp/pytest-of-sbi-local/pytest-40/test_git_archive_subdirectory0/wd/foobar/test1.txt' != 'foobar/test1.txt'
E         Full diff:
E         - ['/tmp/pytest-of-sbi-local/pytest-40/test_git_archive_subdirectory0/wd/foobar/test1.txt']
E         + ['foobar/test1.txt']
```

So I have a question regarding the interpretation of the [file finder spec](http://setuptools.readthedocs.io/en/latest/setuptools.html#adding-support-for-revision-control-systems). It says "Your finder function MUST return relative paths, created by *appending to the passed-in directory name*". 

So I expect the passed-in directory name (wd.cwd in this case) to be present in the output, which is what my version does. 

Which one is correct? My interpretation or the current test? Or am my misinterpreting the spec?

**Comment by RonnyPfannschmidt** [comment]
as per the example the path must always be relative and based on the passed folder name, so the test is incorrect since it passes in a full path instead of switching the cwd and passing `''`
