### ISSUE TITLE
file finder is not 100% spec compliant

### ISSUE THREAD

**Issue by sbidoul** [pypa/setuptools-scm#248]
It replaces an empty path with '.', while the [setuptools file finder spec](http://setuptools.readthedocs.io/en/latest/setuptools.html#adding-support-for-revision-control-systems) explicitly warns against it.

https://github.com/pypa/setuptools_scm/blob/e4f80b9f248aea2cfea92a9fc2e2ace5d4584b9c/setuptools_scm/integration.py#L25-L27

This is a minor issue that does not seem to have any negative impact in practice.

**Comment by RonnyPfannschmidt** [comment]
good find, thanks
