### ISSUE TITLE
file finder fails when not run from the top level of the SCM clone

### ISSUE THREAD

**Issue by sbidoul** [pypa/setuptools-scm#251]
When setup.py is not at the root of the SCM directory (ie where .git or .hg reside), the file finders are disabled.

This is due to the discovery mechanism https://github.com/pypa/setuptools_scm/blob/a99467848bec1782b8dd2ea32259da21b3a94a39/setuptools_scm/discover.py#L6-L13

**Comment by RonnyPfannschmidt** [comment]
i recall roughly that the reason for this is partly that file finders dont get a distirubtion object,
so at file finding time we have no idea what the surrounding context and/or an acceptable root folder is

**Comment by sbidoul** [comment]
In #252 I assume `git rev-parse --show-toplevel` or `hg root` when run in `path` provides an acceptable root folder. This sounds a reasonable extension compared to looking for the presence of `.git` or `.hg`  in `path`.

**Comment by RonnyPfannschmidt** [comment]
:+1:
