### ISSUE TITLE
ImportError: No module named file_finder_hg (when not installed)

### ISSUE THREAD

**Issue by SnarkBoojum** [pypa/setuptools-scm#262]
There are two points where a Debian packages might get tested : at build time (it gets build then tested in-place), or as quality assurance after the package gets installed.

If I disable build-time tests, my packaging is ok and passes the quality tests.

But the build-time tests fail. In fact, all the testing_file_finder.py tests fail, because of an ImportError on the file_finder_hg module. And if I patch to remove file_finder_hg, they fail because file_finder_git isn't found. So in fact it looks like importing of files_command fails on a non-installed package.

**Comment by RonnyPfannschmidt** [comment]
the tests are intended to run against a installed/discoverable package

a workaround for build time testing might be to do an egg-info call, put them into the src folder, and add the src folder to the pythonpath

**Comment by SnarkBoojum** [comment]
The tests used to run -- and in fact, most of them run : only the new testing_file_finder.py is problematic: it's a regression.

The script runs "python setup.py egg_info" before it starts the tests.

**Comment by sbidoul** [comment]
Hi, author of the new file finder and tests here.

I don't think it's a regression. Rather increased test coverage I think. Just an hypothesis for now.

Could you try 2 independent things?
1. make extra sure you don't have any other package providing git/hg file finders installed in your system (eg setuptools-git): they might take precedence if you are not running tests in a isolated environment
2. try running `setup.py develop` before running tests

**Comment by RonnyPfannschmidt** [comment]
based on #259 its very likely this is just op still having a miss-configured system where imports happen against the wrong version of setuptools_scm

**Comment by RonnyPfannschmidt** [comment]
@SnarkBoojum based on what i have seen so far i consider it very likely that the tests just ran by accident for you and the recent change in entrypoints made it fall over

**Comment by SnarkBoojum** [comment]
Many remarks, many questions, I'll try to answer to all:

- if the autotests were passing during the build and don't anymore, that's a regression ;
- building a package happens in a container, so neither a different version nor some other package can get in the way (#259 was because I tried to investigate by hand, and did a poor job at it) ;
- running "setup.py develop" tries to install things on the system, which is not allowed during build ;
- how can the changes in entrypoints only break the file_finder code and nothing else?

I could just disable the tests during the build, but I'm not sure it's a good idea : cutting alarms doesn't solve problems. There might be something worth investigating...

**Comment by RonnyPfannschmidt** [comment]
the entrypoints just changed the instruction on where to import the file finders from

if setuptools_scm is importable but the new file finder location isn't, then its very likely there is an older version in the system somewhere

i proposed using PYTHONPATH and putting up the required egg-info instead of installing

**Comment by SnarkBoojum** [comment]
During the build, there is no version on the system, neither the older nor the current : no installation is allowed. I don't understand how all of setuptools_scm can be found but not the file_finder_* :-/

**Comment by RonnyPfannschmidt** [comment]
how do you run the tests? - can you show whats being done? - i have basically zero information on the environment that triggers the issue

**Comment by SnarkBoojum** [comment]
First `python setup.py egg_info` so the module can be found, then `python -m pytest -k "not regressions"` ; here is the log of the failure ; here is the start of the log for tests:
```
============================= test session starts ==============================
platform linux2 -- Python 2.7.15, pytest-3.3.2, py-1.5.3, pluggy-0.6.0
setuptools version 39.1.0
setuptools_scm version 2.1.0
rootdir: /<<PKGBUILDDIR>>, inifile:
collected 102 items

testing/test_basic_api.py ..........                                     [ 10%]
testing/test_file_finder.py FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF               [ 41%]
testing/test_functions.py .................                              [ 58%]
testing/test_git.py ..............                                       [ 73%]
testing/test_main.py .                                                   [ 74%]
testing/test_mercurial.py ...............                                [ 89%]
testing/test_setuptools_support.py sss                                   [ 92%]
testing/test_version.py .......                                          [100%]

=================================== FAILURES ===================================
_______________________________ test_basic[git] ________________________________

inwd = <conftest.Wd object at 0x7f97edfa2050>

    def test_basic(inwd):
>       assert set(find_files()) == _sep({
            'file1',
            'adir/filea',
            'bdir/fileb',
        })

/<<PKGBUILDDIR>>/testing/test_file_finder.py:39: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
setuptools_scm/integration.py:27: in find_files
    ???
/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py:2322: in load
    return self.resolve()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = EntryPoint.parse('.hg = setuptools_scm.file_finder_hg:hg_find_files')

    def resolve(self):
        """
            Resolve the entry point from its module and attrs.
            """
>       module = __import__(self.module_name, fromlist=['__name__'], level=0)
E       ImportError: No module named file_finder_hg

/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py:2328: ImportError
---------------------------- Captured stdout setup -----------------------------
cmd 'git init'
out 'Initialized empty Git repository in /tmp/pytest-of-jpuydt/pytest-0/test_basic_git_0/wd/.git/\n'
cmd 'git config user.email test@example.com'
cmd 'git config user.name "a test"'
cmd 'git add .'
cmd 'git commit -m test-number-0'
out '[master (root-commit) fa29063] test-number-0\n 3 files changed, 0 insertions(+), 0 deletions(-)\n create mode 100644 adir/filea\n create mode 100644 bdir/fileb\n create mode 100644 file1\n'
```

**Comment by RonnyPfannschmidt** [comment]
1. https://github.com/pypa/setuptools_scm/blob/master/setup.py#L23 facilitates that and doesn't enable it for general use (hence my mention of `PYTHONPATH`)

2. please show the output of `python -c 'import setuptools_scm; print(setuptools_scm)'` i suspect something unexpected will come up there

additionally please use `pytest` instead of `python -m pytest` as both have different effects on `sys.path`

**Comment by anthrotype** [comment]
> please use pytest instead of python -m pytest as both have different effects on sys.path

Do they? Why is that?

**Comment by RonnyPfannschmidt** [comment]
@anthrotype  https://docs.pytest.org/en/latest/usage.html#calling-pytest-through-python-m-pytest - it adds `'.'` to `sys.path`

**Comment by RonnyPfannschmidt** [comment]
@SnarkBoojum the patch of #263 should help to identify the issues

**Comment by anthrotype** [comment]
> it adds '.' to sys.path

good to know, thanks :+1:

**Comment by SnarkBoojum** [comment]
The output is `<module 'setuptools_scm' from 'setuptools_scm/__init__.pyc'>`, which doesn't look that surprising.

The reason for the use of "python -m pytest" instead of directly "pytest" is that "python3 -m pytest" would be run too if it came to that.

But indeed, I tried and that makes a difference. What I don't get is: why are just the file_finder tests failing?

I'll try the patch of #263.

**Comment by RonnyPfannschmidt** [comment]
@SnarkBoojum sorry - the python command i gave cant actually work, due to automatic addition of `'.'` to sys.path

**Comment by SnarkBoojum** [comment]
The patched test/conftest.py gives:
```
platform linux2 -- Python 2.7.15, pytest-3.3.2, py-1.5.3, pluggy-0.6.0
setuptools version 39.1.0 from '/usr/lib/python2.7/dist-packages/setuptools/__init__.pyc'
setuptools_scm version 2.1.0 from 'setuptools_scm/__init__.pyc'
```
which does look correct.

**Comment by RonnyPfannschmidt** [comment]
thanks for the verification

**Comment by SnarkBoojum** [comment]
I forced my tests to use python3, and the result is unexpected:
```
SETUPTOOLS_SCM_PRETEND_VERSION= python3 -m pytest -k "not regressions"
============================= test session starts ==============================
platform linux -- Python 3.6.5, pytest-3.3.2, py-1.5.3, pluggy-0.6.0
setuptools version 39.1.0
setuptools_scm version 2.1.0
rootdir: /<<PKGBUILDDIR>>, inifile:
collected 102 items

testing/test_basic_api.py ..........                                     [ 10%]
testing/test_file_finder.py ..............................               [ 41%]
testing/test_functions.py .................                              [ 58%]
testing/test_git.py ..............                                       [ 73%]
testing/test_main.py .                                                   [ 74%]
testing/test_mercurial.py ...............                                [ 89%]
testing/test_setuptools_support.py sss                                   [ 92%]
testing/test_version.py .......                                          [100%]

=============================== warnings summary ===============================
testing/test_git.py::test_version_from_git
  /<<PKGBUILDDIR>>/setuptools_scm/version.py:61: UserWarning: tag 'version-0.2.post210+gbe48adfpost3+g0cc25f2' will be stripped of the local component
    warnings.warn("tag %r will be stripped of the local component" % tag)

-- Docs: http://doc.pytest.org/en/latest/warnings.html
============================== 5 tests deselected ==============================
======= 94 passed, 3 skipped, 5 deselected, 1 warnings in 65.87 seconds ========
```

**Comment by sbidoul** [comment]
@SnarkBoojum could you try adding `import file_finder_git` and `import file_finder_hg` in `setuptools_scm/__init__.py`? It seems to resolve it for me.

Why it is so, and why this way of running tests fails while everything passes when run via tox, eludes me.

**Comment by RonnyPfannschmidt** [comment]
quite a surprise for me - i believe i will need a env where that happens in order to investigate the details

**Comment by sbidoul** [comment]
I could reproduce with a python 2 virtualenv with pytest installed.

**Comment by SnarkBoojum** [comment]
@sbidoul I'll be able to give your suggestion a try, but even before that : why would only import file_finder_hg work? When I removed file_finder_hg.py (and modified the rest accordingly), things broke on file_finder_git ; so it's strange importing only one of the pair does the trick.

**Comment by sbidoul** [comment]
I think I got it

**Comment by SnarkBoojum** [comment]
I had to add `from . import file_finder_git, file_finder_hg` to solve it.

**Comment by sbidoul** [comment]
@SnarkBoojum try this:

`env PYTHONPATH=$PWD:$PYTHONPATH pytest`

Your way of running tests relied on python inserting `''` in sys.path. This does not work anymore with the last version because the file finder tests change directory and the entrypoint resolver tries to `import setuptools_scm.file_finder_(hg|git)` after changing directory, at which point the `''`  in sys.path is meaningless. Putting the absolute path of the project root in PYTHONPATH resolves this and is more correct.

So not a bug nor a regression IMHO. Just new tests revealing a not entirely correct way to launch the tests.

**Comment by RonnyPfannschmidt** [comment]
@sbidoul thanks for the detailed investigation, and for demonstrating the issue generated by using `python -m pytest`

i suggest to change the invocation to `PYTHONPATH=$PWD pytest ...`

**Comment by SnarkBoojum** [comment]
It doesn't work -- contrarily to adding `from . import file_finder_git, file_finder_hg` in __init__.py

**Comment by sbidoul** [comment]
@snarkboojum We need more details then.

Pre-importing file_finder_git and file_finder_hg fixes it too, and is consistent with my explanation above (ie importing before changing directory, at a point when `''` in sys.path is the root of the project).
This solution is not optimal and not necessary: there is no reason to pre-import stuff before we need it.

I just tried again and setting PYTHONPATH to $PWD does work:

```console
$ python setup.py egg_info
$ pytest
...
INTERNALERROR> DistributionNotFound: The 'setuptools_scm' distribution was not found and is required by the application
$ env PYTHONPATH=$PWD pytest
========================================================================== test session starts ==========================================================================
platform linux2 -- Python 2.7.12, pytest-3.5.1, py-1.5.3, pluggy-0.6.0
setuptools version 39.1.0
setuptools_scm version 2.1.0
rootdir: /home/me/setuptools_scm, inifile:
collected 102 items                                                                                                                                                     

testing/test_basic_api.py ..........
testing/test_file_finder.py ..............................
testing/test_functions.py .................
testing/test_git.py ...^C
```

**Comment by SnarkBoojum** [comment]
both `PYTHONPATH=. python2.7 -m pytest -k "not regressions"` and `PYTHONPATH=/<<PKGBUILDDIR>> python2.7 -m pytest -k "not regressions"`  fail because file_finder_hg isn't found.

I see two good reasons to choose the pre-import solution:

- it's necessary so the code works correctly in more various situations ;
- it's much cleaner than playing around with PYTHONPATH.

**Comment by RonnyPfannschmidt** [comment]
`python -m will break it in any case` please use the pytest command

**Comment by sbidoul** [comment]
BTW, the difference between python 2 and python 3 is explained by this:

```console
$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/home/sbi-local/.local/lib/python2.7/site-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/python2.7/dist-packages/wx-3.0-gtk2']
>>> import setuptools_scm
>>> setuptools_scm.__path__
['setuptools_scm']
>>>
$ python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', '/usr/lib/python35.zip', '/usr/lib/python3.5', '/usr/lib/python3.5/plat-x86_64-linux-gnu', '/usr/lib/python3.5/lib-dynload', '/usr/lib/python3/dist-packages']
>>> import setuptools_scm
>>> setuptools_scm.__path__
['/home/me/setuptools_scm/setuptools_scm']
>>>
```

We see that when there is a relative path in sys.path, python 3 expands it to an absolute path, while python 2 does not. This is why python 3 survives a directory change. Interesting.

**Comment by SnarkBoojum** [comment]
What will `python -m` break? As I said, the one-liner import fixes the issue.

**Comment by RonnyPfannschmidt** [comment]
@SnarkBoojum `python -m` breaks the python path to sort this issue out once and for all i will switch the next release to the src layout, where it will no longer work that way

**Comment by RonnyPfannschmidt** [comment]
i introduced the src layout, so using `python -m pytest` will no longer create a accidental pass

**Comment by SnarkBoojum** [comment]
How does one run tests with this layout? I did a checkout, tried to setup.py egg_info and build, but neither `python -m pytest`  nor `pytest` worked.

**Comment by RonnyPfannschmidt** [comment]
by correctly setting up pythonpath as one needs to

**Comment by RonnyPfannschmidt** [comment]
`PYTHONPATH=$PWD:$PWD/src pytest`

**Comment by RonnyPfannschmidt** [comment]
closing this as 11fea5f51b7096 adds the command to do it correctly to the readme

**Comment by sbidoul** [comment]
@RonnyPfannschmidt `test_distlib_setuptools_works` fails with this method. Not sure why yet.

**Comment by sbidoul** [comment]
@RonnyPfannschmidt need to use `src` instead of `.` here?

https://github.com/pypa/setuptools_scm/blob/d9e16020b912a2c275ae749381452832afce13b8/testing/test_setuptools_support.py#L58

**Comment by RonnyPfannschmidt** [comment]
@sbidoul thanks, good find i missed that pice

**Comment by SnarkBoojum** [comment]
Ok, now setting PYTHONPATH works, but if something is needed to make pytest happy... shouldn't something be done in testing/conftest.py instead? I mean, if you need to document how to run the tests, isn't it an indication that the default settings are somehow incorrect?

**Comment by RonnyPfannschmidt** [comment]
the tests are supposed to be executed against a **installed** version

since you want to run against a **not installed** version you gotta fix stuff yourself
