### ISSUE TITLE
Support for PEP 440 release candidate tags/versions?

### ISSUE THREAD

**Issue by jonathansick** [pypa/setuptools-scm#265]
I'm trying to create a release candidate of a package that's using setuptools_scm. Following [PEP 440](https://www.python.org/dev/peps/pep-0440/#id25) (as far as I can tell), I've tagged the release candidate as `0.2.0rc1` however the version string generated by setuptools_scm is `0.2.0rc2.dev0+gc3a90a4.d20180520`.

Any suggestions on how to get setuptools_scm to generate a `X.Y.ZrcN` version string? Or is it not supported yet?

**Comment by RonnyPfannschmidt** [comment]
it is supported, the date stamp indicates a dirty working directory

**Comment by jonathansick** [comment]
Of course! Thanks @RonnyPfannschmidt. I put a `git status` in my Travis CI job and found out that my NPM `package-lock.json` was being reformatted slightly within CI (I think it's npm is doing that, undoing some formatting by Prettier...).

I solved that by adding a `git stash` at the end of my CI pipeline.

Thanks again.

**Comment by RonnyPfannschmidt** [comment]
thanks for the follow-up, this will certainly help others facing the same detail

**Comment by ri0t** [comment]
Uh, when using this with the following constellation, 1.0.0.rcX is not accepted as followup to 1.0.0
Package A has version 1.0.0.rcX
Package B requests A>=1.0.0
scm_version exports A's info as "1.0.0rcX" (note the missing last dot), whereas my git tag contains the last dot.

Is this intentional or am i doing it wrong somehow?

**Comment by RonnyPfannschmidt** [comment]
@ri0t the correction and normalization in this case is intentional see https://www.python.org/dev/peps/pep-0440/#pre-release-separators
