### ISSUE TITLE
PRETEND behaviour

### ISSUE THREAD

**Issue by jpiron** [pypa/setuptools-scm#271]
Hi,

I am not sure I understand the `SETUPTOOLS_SCM_PRETEND_VERSION` usage.
I use it in a container context where I don't wan't the scm repository to be included in the container image.
Thus I use something like:
```shell
SETUPTOOLS_SCM_PRETEND_VERSION=$(python ${PWD}/setup.py --version) 
```
prior to create the container image so that `setuptools_scm` can retrieve the version without the scm repository. 
However, I don't get the same result as with the scm repository.

With a version like `1.0.1.dev1+ge871260.d20180625` and the scm repository, the generated artifact (here a wheel) will be `my_python_project-1.0.1.dev1+ge871260.d20180625-py3-none-any.whl`, while without the scm repository and with `SETUPTOOLS_SCM_PRETEND_VERSION` set to `1.0.1.dev1+ge871260.d20180625` the generated artifact is `my_python_project-1.0.1.dev1-py3-none-any.whl`.

Looking at the `_do_parse` function code:
```python
if pretended:
        # we use meta here since the pretended version
        # must adhere to the pep to begin with
        return meta(pretended)
```
I understand this is done on purpose, but I don't get why.
I would expect the result to be the same, unless I don't get the `SETUPTOOLS_SCM_PRETEND_VERSION` usage properly.

**Comment by RonnyPfannschmidt** [comment]
pretend_version is meant to be support for packagers and tools that make the scm metadata inaccessible

the removal of the ability to pretend exact versions was removed unintentionally, since  didnt test for it

so this is a bug and should be fixed
