### ISSUE TITLE
document a get_version pattern for editable installs staying as correct as sensible

### ISSUE THREAD

**Issue by blueyed** [pypa/setuptools-scm#273]
Is the following reasonable, e.g. for output of `--version`?

I am using this to get the current version with editable installs, useful
during development:

```python
def get_version():
    try:
        from setuptools_scm import get_version
        return get_version(root='..', relative_to=__file__)
    except (ImportError, LookupError):
        from pkg_resources import get_distribution
        return get_distribution(__package__).version
```

setup.py uses the basic:

```python
    use_scm_version=True,
    setup_requires=['setuptools_scm'],
```

btw: what is a use case for `write_to`?  The file itself says that the file
should not be tracked in the SCM itself.

Ref: https://github.com/Vimjas/covimerage/pull/43

**Comment by RonnyPfannschmidt** [comment]
@blueyed ´write_to` is for when people dont want to pay the cost of `pkg_resources.get_distribution`

personally i think its perfectly valid to work with stale metadata on development, just doing semi-regular `pip install -e ...`

**Comment by blueyed** [comment]
Thanks for clarification!

**Comment by blueyed** [comment]
Closing.
README update in #274.

**Comment by majuscule** [comment]
Just want to voice my support for availability of access to updated version metadata from within an editable install. I work from within an editable install constantly, and having the version data up to date would be very helpful to avoid confusion when interacting with others who are using experimental releases of my packages. I don't feel that forcing developers to remember to repeatedly `pip install ...` is a valid solution.

Please reopen this issue.

**Comment by taldcroft** [comment]
For the `get_version()` function shown in the description, will the initial attempt to run `setuptools_scm.get_version(..)` be lightweight / fast?  In particular that it doesn't actually end up running a `git` executable if there is no git repo in the installed package directory.  I looked into the code a bit but confess to finding the code that detects the repo to be a bit inscrutable.

Running in debug mode I see for a successful detection it says:
```
found ep .git = setuptools_scm.git:parse  # found a .git directory??
cmd 'git rev-parse --show-toplevel'  # runs a git command now
...
```
While for unsuccessful:
```
root '/Users/aldcroft/git/sparkles'
looking for ep setuptools_scm.parse_scm /Users/aldcroft/git/sparkles
looking for ep setuptools_scm.parse_scm_fallback /Users/aldcroft/git/sparkles
Traceback (most recent call last):
  File "setup.py", line 21, in <module>
    cmdclass=cmdclass,
```
So it all looks good, but again just don't know what's going on under the hood.

**Comment by RonnyPfannschmidt** [comment]
without much more tooling this is hard to solve
personally i wont go and search for patterns to enable this in combination with build tools

**Comment by ashwinvis** [comment]
At fluidsim, we have a use-case which has a need for the scm version (or local version as we call it) in an editable install. Being a research code, we always use it as an editable install and the local version is useful to know which commit the code was executed with. We have [a module `fluidsim._version`](https://github.com/fluiddyn/fluidsim/blob/fc08323ffb2553e408b20cdcf575699ccef4162c/fluidsim/_version.py#L43-L59) which contains:

```python
__version__ = "0.3.0"
_loc_version = None

def get_local_version():
    """Get a long "local" version."""


    global _loc_version


    if _loc_version is None:
        from setuptools_scm import get_version


        try:
            _loc_version = get_version(root="..", relative_to=__file__)
        except (LookupError, AssertionError):
            _loc_version = __version__


    return _loc_version
```

The `if` condition and the variable `_loc_version` avoids the lag of using `get_version`, and the `try-except` is a fallback option in case no version control repository is detected.

I wonder if this is a good pattern, or can be improved upon? Any feedback is welcome.

cc:@vezeli

**Comment by RonnyPfannschmidt** [comment]
its possible to do this better using pkg_resources and/or impotzlib_metadata

by determining the distribution and its location its possible to infer the location and use static or dynamic determination of the version

the patternn with loc_version is slightly undesirable

**Comment by ashwinvis** [comment]
When you mention "by determining the distribution and its location", do you mean something like this:

```python
In [1]: from importlib import resources

In [2]: from pathlib import Path

In [3]: with resources.path("fluidsim", "__init__.py") as path:
   ...:      repo = Path(path).parent.parent
   ...:      print(repo)
   ...:
/home/avmo/src/gfdyn/fluidsim

In [4]: from setuptools_scm import get_version

In [5]: get_version(repo)
Out[5]: '0.3.2.dev19+h58ca00423a36'
```

**Comment by RonnyPfannschmidt** [comment]
@ashwinvis that would be a very rough starting point, but it needs some more sophistication to work out of the box in more general terms

**Comment by embray** [comment]
Also related are my proposals here:

https://github.com/pypa/setuptools_scm/issues/143#issuecomment-672878863

and here

https://github.com/pypa/setuptools_scm/issues/143#issuecomment-672931831

**Comment by sidekick-eimantas** [comment]
> @blueyed ´write_to`is for when people dont want to pay the cost of`pkg_resources.get_distribution`
> 
> personally i think its perfectly valid to work with stale metadata on development, just doing semi-regular `pip install -e ...`

What ballpark numbers are we lookin at when talking about the cost of `pkg_resources.get_distribution`?
I'm seeing added latency of ~0.05s
Is this a problem seen with larger packages?

**Comment by RonnyPfannschmidt** [comment]
In the early days and when pkg_resources was not in use it potentially meant additional 0.2 seconds

Which makes for a noticeable delay

**Comment by RonnyPfannschmidt** [comment]
closing this as not planned - until there is editable hooks wit scm intgration, updates are not safe

happy to pick this up once someone provides the hooks
