### ISSUE TITLE
tags with dashes still broken

### ISSUE THREAD

**Issue by punkadiddle** [pypa/setuptools-scm#275]
In #266 you tried to make setuptools_scm more compatible to accept [Semver](https://semver.org/) version tags like "v1.2.3-rc.1". The regex used to strip the prefix keeps it broken since it greedyly consumes everything including a version until the dash.

setuptools_scm should accept everything pkg_resources takes. I don't want to make this a world vs python issue but in my environment we use several languages and tagging them all differently is not acceptable.

The following works flawlessly:
```
In [2]: pkg_resources.parse_version('v1.0.1-rc.1')
Out[2]: <Version('1.0.1rc1')>
```

Line to strip prefix:
```
TAG_PREFIX = re.compile(r"^\w+-(.*)")
```

Maybe you could allow to configure a constant prefix / regexp to strip? That would make it easy to adapt to the environment.

**Comment by RonnyPfannschmidt** [comment]
I fixed a bug with actual python version numbers, semver is not supported in detail

**Comment by RonnyPfannschmidt** [comment]
I would accept a PR implementing it

**Comment by RonnyPfannschmidt** [comment]
But to be clear, this has to be a opt in, as its non python versions

**Comment by punkadiddle** [comment]
see #276
