### ISSUE TITLE
support configuration of the git describe command 

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pypa/setuptools-scm#283]
https://github.com/apache/arrow/blob/355ff0879d5fc7bd5c95aa05fd0e9daeafbaccd3/python/setup.py#L489-L500

there should be a better way to configure that

**Comment by 1ucian0** [comment]
If I understand this correctly, you would like to have `match` and `exclude` as new options in a configuration. I can definitely do this. `exclude` was added relatively recently (2017), is that a problem? Let me know!
