### ISSUE TITLE
Release 3.0.3 not in PyPI

### ISSUE THREAD

**Issue by tuukkamustonen** [pypa/setuptools-scm#291]
Repository has 3.0.3 in changelog and as git tag, but there's no build in PyPI. Seems like last master revision failed to upload: https://travis-ci.org/pypa/setuptools_scm/builds/407502770.

**Comment by RonnyPfannschmidt** [comment]
@tuukkamustonen the release has been pulled due to having been released incompletely with a broken travis config - i will try to push a 3.0.4 with a working travis config today

any suggestions for documenting pulled releases

**Comment by tuukkamustonen** [comment]
> any suggestions for documenting pulled releases

Not really - maybe just mark in `CHANGELOG.rst` that the release was pulled and doesn't exist in PyPI...

**Comment by NeonGraal** [comment]
Also update the release tag in github with same info
