### ISSUE TITLE
Release  1.5.5

### ISSUE THREAD

**Issue by mindw** [pypa/setuptools-scm#30]
1.5.3/4 are broken on Python 2.7 and Windows. 

The previous issue tracking this was deleted.

**Comment by jaraco** [comment]
I'm on it. @RonnyPfannschmidt is out temporarily.

Sorry about the lost issues; it was an unfortunate but temporary consequence of not having migrated the old issues sooner. They are recorded in #29, but only for posterity.

I'll get a 1.5.5 release out shortly. Can you review 285d7910544f to confirm that solution will also work?

**Comment by mindw** [comment]
tox -e py27 passed on Windows.
The appveyour integration only needs the project to be added and have the shields (shield.io ?) setup.

https://ci.appveyor.com/project/pypa/setuptools-scm (?)

**Comment by jaraco** [comment]
1.5.5 tagged and released.
