### ISSUE TITLE
non-matching tags are not ignored

### ISSUE THREAD

**Issue by pitrou** [pypa/setuptools-scm#303]
If I give a `tag_regex`, I would expect non-matching tags to be ignored, instead they seem to fail:
```
$ python setup.py sdist
/home/antoine/miniconda3/envs/pyarrow/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
/home/antoine/miniconda3/envs/pyarrow/lib/python3.6/site-packages/setuptools_scm/version.py:92: UserWarning: tag 'apache-arrow-js-0.9.9' no version found
  warnings.warn("tag %r no version found" % (tag,))
Traceback (most recent call last):
  File "setup.py", line 557, in <module>
    url="https://arrow.apache.org/"
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.6/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.6/site-packages/setuptools/dist.py", line 333, in __init__
    _Distribution.__init__(self, attrs)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.6/distutils/dist.py", line 281, in __init__
    self.finalize_options()
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.6/site-packages/setuptools/dist.py", line 476, in finalize_options
    ep.load()(self, ep.name, value)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.6/site-packages/setuptools_scm/integration.py", line 23, in version_keyword
    dist.metadata.version = get_version(**value)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.6/site-packages/setuptools_scm/__init__.py", line 135, in get_version
    parsed_version = _do_parse(config)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.6/site-packages/setuptools_scm/__init__.py", line 88, in _do_parse
    config, "setuptools_scm.parse_scm"
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.6/site-packages/setuptools_scm/__init__.py", line 45, in _version_from_entrypoint
    version = _call_entrypoint_fn(config, ep.load())
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.6/site-packages/setuptools_scm/__init__.py", line 33, in _call_entrypoint_fn
    return fn(config.absolute_root, config=config)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.6/site-packages/setuptools_scm/git.py", line 134, in parse
    return meta(tag, config=config, node=node, dirty=dirty, branch=branch)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.6/site-packages/setuptools_scm/version.py", line 196, in meta
    assert parsed_version is not None, "cant parse version %s" % tag
AssertionError: cant parse version apache-arrow-js-0.9.9
```

In this case my options are as follows:
```
    use_scm_version={"root": "..",
                     "relative_to": __file__,
                     "tag_regex": '^apache-arrow-([\.0-9]+)$'},
```

**Comment by RonnyPfannschmidt** [comment]
i believe this is a duplicate of #283

**Comment by pitrou** [comment]
Right, that would allow fixing the issue.

**Comment by 1ucian0** [comment]
I'm in the NYC sprint @ ga/bloomberg. I would like to jump in and try to fix this issue (well, to #283). If you are physically near by and work together on this, please find me in the library room!

**Comment by RonnyPfannschmidt** [comment]
@1ucian0 im somewhere in Europe seeing rain outside - is there a gitter/chat to collaborate

**Comment by 1ucian0** [comment]
@RonnyPfannschmidt I'll contact you on https://gitter.im/pypa/setuptools

**Comment by jaraco** [comment]
> i believe this is a duplicate of #283

I don't think it's a proper duplicate. If implemented, #283 would provide a way to work around this issue by allowing the user to filter the tags in advance, but it would leave this feature 'tag_regex' to crash if any tags do not match, which seems like a worthless feature if it crashes on a non-match. I believe it would be best to implement this request as described (non-matches should pass ignored, not raise Exceptions).

@RonnyPfannschmidt Do you see any reason why tag_regex should raise an Exception?

**Comment by RonnyPfannschmidt** [comment]
@jaraco there is a dissonance here between the regex for tags, which is to customize for project properties, and the expression to support the git describe command

as far as i understand it should be combined in some way - for now the easy solution is to have projects declare both - the tag match for describe, and the regex for parsing

**Comment by 1ucian0** [comment]
I made a test that triggers, I think, the same error:
https://github.com/1ucian0/setuptools_scm/commit/19081e5aa166f5f1733680746ae0c6032b0473b4

I'm not sure if `meta()` (`version.py:204`) is allowed to return None for non-matching tags. The function is not documented and I don't want to break invariants... What's `meta()` expected to return when `tag` is not matching `tag_regex`? Or this should never happen and unmatched tags should be filtered before?

**Comment by RonnyPfannschmidt** [comment]
meta shouldn't be passed unmatched tags ever

**Comment by jaraco** [comment]
I just realized this issue is more complicated than I originally imagined. I was imagining that `setuptools_scm` could be solely responsible for the tag filtering, but I now realize it's more complicated than that, because `setuptools_scm` is relying on (in the case of git) the `git describe` command to filter tags _because the output of git describe changes based on the tags matched_. That is, if the tag on the current commit is matched, the distance will be 0, but if the tag on the current branch is not matched, another tag will (presumably) match and the distance will be >0.

Am I right in thinking that `tag_regex` applies only to tags that were already matched? Does that mean necessarily that a client that wishes to match only some tags will necessarily need to supply a custom matcher and tag_regex?

**Comment by RonnyPfannschmidt** [comment]
@jaraco correct - the scm commands have no idea about regex usually (although modern mercurial is a fabulous tool)
