### ISSUE TITLE
ResourceWarning: unclosed file <_io.BufferedReader name=8>

### ISSUE THREAD

**Issue by SnarkBoojum** [pypa/setuptools-scm#305]
The testsuite has a small warning when run with Python 3.6.6:
```
platform linux -- Python 3.6.6, pytest-3.6.4, py-1.5.4, pluggy-0.6.0
setuptools version 39.2.0 from '/usr/lib/python3/dist-packages/setuptools/__init__.py'
setuptools_scm version 3.1.0 from '/usr/lib/python3/dist-packages/setuptools_scm/__init__.py'
rootdir: /tmp/autopkgtest.1UXGDe/build.GNi/src, inifile: tox.ini
collected 124 items / 6 deselected

testing/test_basic_api.py ..............                                 [ 11%]
testing/test_config.py .....                                             [ 16%]
testing/test_file_finder.py ..............................               [ 41%]
testing/test_functions.py ......................                         [ 60%]
testing/test_git.py ..................                                   [ 75%]
testing/test_main.py .                                                   [ 76%]
testing/test_mercurial.py ...............                                [ 88%]
testing/test_regressions.py .s                                           [ 90%]
testing/test_version.py ...........                                      [100%]
============= 117 passed, 1 skipped, 6 deselected in 30.97 seconds =============
Exception ignored in: <_io.FileIO name=8 mode='rb' closefd=True>
ResourceWarning: unclosed file <_io.BufferedReader name=8>
```

since I didn't see it in 3.0.6, I guess the change is recent...

**Comment by RonnyPfannschmidt** [comment]
in 3.1 i set up warnings to errors to iron out a set of internal mistakes

i didn't see the error you posted however - what distro is that?

**Comment by SnarkBoojum** [comment]
Debian unstable ; I'm the packager for setuptools_scm and saw it while trying to update the package.

**Comment by RonnyPfannschmidt** [comment]
@SnarkBoojum does the test env mask stuff like the $USER, i recall that masking those env vars might trigger a enquiry to the system dbus (observed that on fedora at least)

**Comment by RonnyPfannschmidt** [comment]
@SnarkBoojum on a unrelated note - its a pleasure to see that debian is one of the few distros that tests against the **installed** package

**Comment by SnarkBoojum** [comment]
If I run the tests as myself, I see that it happens during the git test:
```
testing/test_git.py ...Exception ignored in: <_io.FileIO name=8 mode='rb' closefd=True>
ResourceWarning: unclosed file <_io.BufferedReader name=8>
...............                                                             [ 71%]
```
so it's not just the autopkgtest environment having strange interactions : there is something fishy.

**Comment by SnarkBoojum** [comment]
I ran:
```
pytest-3 testing/test_git.py::test_file_finder_no_history
```
and saw the warning.

**Comment by RonnyPfannschmidt** [comment]
@SnarkBoojum thanks for the investigation, i could reproduce - pr upcoming

**Comment by RonnyPfannschmidt** [comment]
@SnarkBoojum the issue existed since longer, the the switch to failing on warnings just made it more apparent

pytest needs a tool for better tracking that as i blatantly missed the message due to green test results
