### ISSUE TITLE
How to organize a multi-library structure with one Git root?

### ISSUE THREAD

**Issue by m-burst** [pypa/setuptools-scm#307]
Hi,

I'm currently trying to do the following.
I have a repository with multiple libraries (each in its own folder) which I want to version and release separately. The library releases are tagged in the repo like `lib_name-v1.2.3`.
The problem is that I cannot run setup.py for a library if the latest tag in the repository belongs to another library (i.e. doesn't match the `tag_regex` in the setup.py of this library).

Is there a way to somehow use the latest tag matching a pattern, rather than the very latest tag in the repository?

Thanks in advance!

**Comment by RonnyPfannschmidt** [comment]
there is a mechanism to control the git describe command used, but its exposed in a bad manner right now
i want to spend some time on making consistent single config option for expected tag prefixes sane, but its hard to guess when i have it

**Comment by m-burst** [comment]
@RonnyPfannschmidt Thank you for your quick response! Could you please tell me a little more about the existing mechanism or point to me where I can read it in the docs?

**Comment by RonnyPfannschmidt** [comment]
the 2 mechanisms are

a) tag regexes https://github.com/pypa/setuptools_scm/blob/master/src/setuptools_scm/version.py#L24-L26
b) the possibility to pass describe commands to git - https://github.com/pypa/setuptools_scm/blob/master/src/setuptools_scm/git.py#L87

**Comment by m-burst** [comment]
@RonnyPfannschmidt How can I override the DESCRIBE_COMMAND using config? Do I need to replace the whole `parse` function? Is there an example somewhere?

**Comment by RonnyPfannschmidt** [comment]
@m-burst thats what i meant by bad manner, instead of a single variable that controlls it all you need both - the regex and a custom parse command
