### ISSUE TITLE
Give notice and/or workaround to developers that end users of packages produced via setuptools_scm need setuptools version >= 12

### ISSUE THREAD

**Issue by nealmcb** [pypa/setuptools-scm#312]
I was deeply surprised that it seems that adopting setuptools_scm for use in building my package places a requirement on the environment that users of my package must have. I hate to get error reports from users like that when I've changed so little in the actual code I'm delivering (or at least know I'm delivering).

They reported seeing this error
>  **`setuptools_scm.version.SetuptoolsOutdatedWarning: your setuptools is too old (<12)`**

They are on RHEL 7 (the latest version of RHEL), which apparently has something like setuptools 0.9.8, vs the current version 40.4.3(!!).

This seems related to this note in the 2.0.0 release notes: _breaking change: remove support for setuptools before parsed versions_. But I have no idea what that really means.

I've seen and experienced problems in the past with users upgrading core aspects of Python, and really don't want to have to explain to them how to set up a virtual environment starting from RHEL 7.  Are there any known issues with the latest setuptools on RHEL 7? Can it be upgraded all by itself or do other surrounding packages need to be upgraded?

What are my options:

1. Can I build my package with an older version of setuptools_scm which doesn't force end-user upgrades? Which version?
1. Is is safe for end-users to upgrade? What is the best way to do so?
1. Should I just drop use of setuptools_scm and go back to a manually updated MANIFEST?

**Comment by RonnyPfannschmidt** [comment]
versions < 2.0 work with older versions of setuptools, and if you package from a sdist, thats sufficient ( packaging with them from a scm checkout can result in problems)

its generally rather safe to update setuptools, the main reason the number has gone up so much in recent years is that really really nasty edge-cases in the apis got sorted out and each of those was a "breach" of api that is not really a problem for a vast majority of the users

for setuptools sanity questions on rhel, please poke your vendor, setuptools versions before 12 have practically no sane way to work with versions as such the versions shipped in rhel 7 are a problem

**Comment by nealmcb** [comment]
Thanks. It seems to have worked to tell the end-users to

    sudo pip install -U setuptools

which gave them 

    Successfully installed setuptools-40.4.3

I suggest noting this requirement in the README and other documentation.

I'm still puzzled at why this build change requires an install upgrade. Is there a good document that clarifies why they are intertwined?
I tried to look at something that seemed like it might be related, `"Issue #41: Dropped support for Python 2.4 and Python 2.5."` as linked from https://pypi.org/project/setuptools/2.2/ but after demanding that I log in, that sent me to an "Access denied" page: https://bitbucket.org/pypa/setuptools/issues/41
