### ISSUE TITLE
is setup_requires method deprecated?

### ISSUE THREAD

**Issue by anthrotype** [pypa/setuptools-scm#315]
Following up from https://github.com/pypa/pip/issues/5465#issuecomment-395045552

If easy_install can no longer reliably install setuptools_scm via `setup_requires`, at least of some platforms or versions of pip with old SSL, shouldn't users be officially recommended to use pyproject.toml and specify setuptools_scm in `[build-system] requires`?

The current README only mention the `setup_requires` installation method.

E.g. I noticed that tox recently removed `setuptools_scm` from its setup.py `setup_requires` list:
https://github.com/tox-dev/tox/commit/da219ee40783c0385c784fd358f6ec5f7486d784#diff-2eeaed663bd0d25b7e608891384b7298

**Comment by RonnyPfannschmidt** [comment]
@anthrotype thanks for the note - while the method is not yet deprecated, its indeed advisable to have people switch to the mechanisms outlined

tox already used pep-517 before, and just had to keep the list for a broken tool

would you like to contribute the documentation change, personally im not sure when i can get to it

**Comment by RonnyPfannschmidt** [comment]
Closed by #323

**Comment by soerenwolfers** [comment]
The problems with setup_requires disappeared with setuptools 42.0.0, which switched to using pip to resolve setup_requires (https://setuptools.readthedocs.io/en/latest/history.html#v42-0-0)
