### ISSUE TITLE
Using deprecated upload command?

### ISSUE THREAD

**Issue by pganssle** [pypa/setuptools-scm#318]
Looking at your `setup.cfg`, it seems that [`release` is an alias for `sdist bdist_wheel upload`](https://github.com/pypa/setuptools_scm/blob/3ef897a0983dfde7fdfe56a2e9f5f304acdec43e/setup.cfg#L12), but the `upload` command is *very* deprecated and probably broken in myriad ways.

The recommended way to upload packages is with `twine`. If you're already doing so, maybe time to retire the `release` alias?

**Comment by RonnyPfannschmidt** [comment]
thanks for the note - the releases typically happen by travis which uses twine, the code in question is a legacy that should be removed
