### ISSUE TITLE
v3.1.0 changelog seems wrong

### ISSUE THREAD

**Issue by airhorns** [pypa/setuptools-scm#319]
Hi folks -- I'm trying to use the new `git_describe_command` option listed in the changelog under v3.1.0 and I think it is incorrect, that feature is either unreleased or the 3.1.0 release was broken and old. https://pypi.org/project/setuptools_scm/ reports `Last released: Aug 9, 2018` and doesn't have the readme changes for `git_describe_command` so something somewhere is mistaken. On a related note, it'd be awesome to get the `git_describe_command` changes released!

**Comment by RonnyPfannschmidt** [comment]
indeed, i missed this when merging #303 - it wa after the release and should come in for `3.2`

**Comment by airhorns** [comment]
@RonnyPfannschmidt sorry to bother -- any indication on when the git_describe_command changes might get released? We have to install this package before others in order to get versioning right and it'd be great to be able to install it from pip instead of git! Let me know if I can help at all!

**Comment by RonnyPfannschmidt** [comment]
@airhorns thanks for the reminder, i'll aim at releasing within the next half hour

**Comment by RonnyPfannschmidt** [comment]
@airhorns release is published

**Comment by airhorns** [comment]
Thank you kind sir!
