### ISSUE TITLE
setuptools_scm should support custom per-project SETUPTOOLS_SCM_PRETEND_VERSION var

### ISSUE THREAD

**Issue by webknjaz** [pypa/setuptools-scm#321]
When there's two project (one is dependency of another), both use `setuptools_scm` and `SETUPTOOLS_SCM_PRETEND_VERSION` env var is set, both of them use it for their version if installed from source.

I think maybe providing some prefixing/suffixing mechanism would improve this.

**Comment by RonnyPfannschmidt** [comment]
SETUPTOOLS_SCM_PRETEND_VERSION was introduced as a absolute stopgap to enable packagers to temporarily override things for a local setup - unless there is a really good argument i'm opposed to expanding it

**Comment by webknjaz** [comment]
Good point. I faced the issue with smth heroku-like in past which did `pip install -e .` but didn't have git inside or didn't preserve `.git` (I don't remember), so I used it and I think it conflicted with some test deps (maybe `pytest`).

P.S. Anyway, I thought I'd document that this problem exists.

**Comment by RonnyPfannschmidt** [comment]
documenting it is certainly necessary

**Comment by RonnyPfannschmidt** [comment]
@webknjaz i wonder if perhaps expanding it to space separated distribution_name=version would be sensible, perhaps under the env var SETUPTOOLS_SCM_PRETEND_VERSION_FOR

**Comment by webknjaz** [comment]
Sounds good. Also in the event of PEP517 used, there could be some attr in pyproject.toml maybe?

**Comment by RonnyPfannschmidt** [comment]
That sounds wrong
