### ISSUE TITLE
README should mention that PyPI doesn't accept local version identifiers

### ISSUE THREAD

**Issue by webknjaz** [pypa/setuptools-scm#322]
And maybe suggest some workarounds for that.

Currently I came up with:
1) Setting env var with no local identifier
    ```console
    python -c 'import setuptools_scm; print(setuptools_scm.get_version(local_scheme=lambda v: ""))' | read SETUPTOOLS_SCM_PRETEND_VERSION
    ```
    which is scary because of #321
2) substituting `setuptools_scm.local_scheme` entrypoint with `lambda v: ""`

Which should probably be done only when uploading the dist because in all other cases it's still nice to have local identifier.

Ref: https://github.com/pypa/twine/issues/430
Ref: https://github.com/pypa/python-packaging-user-guide/issues/578

**Comment by RonnyPfannschmidt** [comment]
it works fine with local pypi servers, and its actually intended to be a protection - don't accidentally upload "non-releases"

for a normal release processs you'd never need the workarounds

**Comment by webknjaz** [comment]
Right. And yet this'd better be documented.
My use case is continuously uploading dists to Test PyPI to ensure that the pipeline is healthy, for example.

**Comment by RonnyPfannschmidt** [comment]
thats a interesting one, def worthwile

**Comment by chebee7i** [comment]
Thanks for this.  It would be nice if this could be configurable (not just via env variable).

I use local version identifiers in packages that are uploaded to a local devpi server.  Removing the tag is definitely undesirable, as it is used to indicate actual differences in the bdist when building extension libraries (for example, the extension may be built to statically link against different versions of a library).
