### ISSUE TITLE
setuptools_scm without runtime pkg_resources dependency?

### ISSUE THREAD

**Issue by shoyer** [pypa/setuptools-scm#328]
I would slightly prefer to use a programmatically generated `_version.py` file rather than requiring pkg_resources in `__init__.py`.  Is this supported by setuptools_scm?

This came up on Twitter:  https://twitter.com/pganssle/status/1110339405317881857

**Comment by RonnyPfannschmidt** [comment]
yes, using the `write_to` parameter to choose the target file

**Comment by shoyer** [comment]
Great, it might be nice to include a full example since this appears to come up with some regularity.

**Comment by flying-sheep** [comment]
I don’t know if the file gets dumped inside of the package or in the source tree. If it’s in the package, it would be simply:

`setup.py`:

```py
setup(
    use_scm_version=dict(write_to='mypackage/_version.py')
    ...
)
```

`mypackage/__init__.py`:

```py
from ._version import version as __version__
```

If it’s dumped into the source tree, it might have to be included in `MANIFEST.in`. Can someone clarify?

**Comment by RonnyPfannschmidt** [comment]
it shouldn't be in manifest

**Comment by flying-sheep** [comment]
`pkg_resources` is on its way out anyway, since standardized alternatives exist. See pypa/setuptools#2531:

> My hope is that `pkg_resources` can be fully deprecated in favor of `importlib.metadata` and `importlib.resources` and their backports. I'm confident, though not certain, that those projects are responsive to changes in the environment without the concept of a working set. Please consider raising that issue with that project and possibly contributing to the replacement effort.
> 
> – @jaraco

This project should migrate to those alternatives:

requirements:
```py
importlib_metadata; python_version < "3.8"
```

code:
```py
try:
    from importlib.metadata import entry_points
except ImportError:
    from importlib_metadata import entry_points
```

**Comment by RonnyPfannschmidt** [comment]
@flying-sheep https://github.com/pypa/setuptools_scm#retrieving-package-version-at-runtime already has that, closing this issue as its actually answered already

**Comment by flying-sheep** [comment]
OK, then I’ll open a new issue for migrating `iter_matching_entrypoints` to `importlib.metadata`

/edit: done! #513
