### ISSUE TITLE
Document prominently the existence of a file_finders plugin

### ISSUE THREAD

**Issue by apljungquist** [pypa/setuptools-scm#329]
I discovered this fact when troubleshooting files that should not have been included according to `MANIFEST.in` were being included.

Factoring out the feature to a separate package distribution was suggested in #190 but was rejected. Though I would have preferred a way to disable the feature, simply documenting it prominently would have saved me a lot of time.

A similar fix was attempted in #53.

The problem is somewhat aggravated by an [issue](https://github.com/pypa/setuptools/issues/436) with `setuptools`; When, in the course of figuring out why so many files where being included, I removed `setuptools_scm` the files were still being included.

**Comment by webknjaz** [comment]
Ref: https://github.com/pypa/setuptools_scm/issues/190#issuecomment-481669649
