### ISSUE TITLE
Relative `__file__` in `relative_to` error

### ISSUE THREAD

**Issue by tilgovi** [pypa/setuptools-scm#333]
Following the example in the documentation, I have a `relative_to` that contains `__file__`. In CI, recently and for reasons still unknown, this started failing. Inspecting the failure, I noticed that `__file__` was relative (`setup.py`) and that providing an absolute path fixed it.

I am not sure what to do about this other than to raise it for investigation. Perhaps something changed in setuptools that caused this to become relative now, or something changed in setuptools_scm, but I worry that others could trip over this.

**Comment by abyssary** [comment]
Can confirm that the following setup.py worked in 3.2.0 but fails in 3.3.0:
```
setup(
    use_scm_version={
        'root': '..',
        'relative_to': __file__
    }
)
```
In my particular case, the .git directory is on level above the directory containing the setup.py.
The error message we I get is 
`LookupError: setuptools-scm was unable to detect version for...`

**Comment by RonnyPfannschmidt** [comment]
my hypothesis is, that by accident the handler  for setup.py is invoked before the git one and returns none, this is a oversight on my part when merging the feature, can check later today

**Comment by pitrou** [comment]
It seems we're getting hit by this regression as well:
https://travis-ci.org/pitrou/arrow/jobs/529698203#L1193

As @abyssary above, we have an explicit `root` since the Python project is in a subdir of the git repo.

**Comment by RonnyPfannschmidt** [comment]
i cant look at this quickly i'll pull the release and sort it  out when i have the time

**Comment by pitrou** [comment]
In the meantime we're gonna pin to 3.2.0.

**Comment by tmbo** [comment]
Running into the same issue. Pinning in `setup.cfg`
```
[options]
setup_requires =
    setuptools_scm==3.2.0
```
and in `pyproject.toml`
```
[build-system]
requires = ["setuptools>=30.3.0", "wheel", "setuptools_scm==3.2.0"]
```
worked, not sure if it is actually necessary in both...

**Comment by RonnyPfannschmidt** [comment]
i did  a  quick check and my initial idea was wrong, i will need longer debugging

**Comment by RonnyPfannschmidt** [comment]
the release is pulled, i'm sorry for the inconvenience - i#ll try to debug this later on

**Comment by tmbo** [comment]
Thanks a lot for all the effort you put into this project and for the timely response 🏅 🙂 - no worries, things like this happen from time to time and I'd rather have a project that pushes updated versions than no maintenance at all :wink:

**Comment by RonnyPfannschmidt** [comment]
@tmbo your kind words are very uplifting, thank you :+1:
