### ISSUE TITLE
How to only apply versions for changes to a particular folder

### ISSUE THREAD

**Issue by sean-abbott** [pypa/setuptools-scm#341]
The folks I work with are obsessed with mono-repos, and I am left but no choice to use them.

This is problematic in trying to get automatic versioning, though, because all the clean/dirty comparisons and tags and whatnot are based on git as a whole.

I wonder if there's a way to set this up such that I can specify folders to 'watch' from root, and a specific tag prefix, and do the version calculations from there?

Thanks!

**Comment by RonnyPfannschmidt** [comment]
This would need quite a interesting addition to the git integration

**Comment by sean-abbott** [comment]
I have shell scripts that essentially do this to make a build/don't build decision, although they may not be precise enough. Ideally, you'd want the entire watch list to be relative to root.

So, assuming you're ok with only direct lineage, you can do

`git log --name-only $(git tag -l | tac | head -1)..HEAD directory1 directory2 dir3/subdir1`

And get a list of only commit messages that deal with any files in those directories.

Simliarly 

`git status -- directory1 directory2 dir3/subdir1` will give you clean and dirty on only those files, and actually report clean.

I'd probably need a pointer or bootstrap to APIs or starting points, but I could try and hack something together if you don't hate the idea.

Although last time I had an idea in this realm, it was way harder than I thought, and we ended up going with the less elegant but much easier solution. :-)

**Comment by sean-abbott** [comment]
Hypothetically, could I not write my own `parse` function to get to this? Although I would need to make an assumption about where to get the watch list.

**Comment by RonnyPfannschmidt** [comment]
Kinda, I'm currently dealing with some personal issues and do spend a very limited amount of private time on open source, so currently it's going to take a while before I can dig in deep enough to give good advise or guidance

**Comment by sean-abbott** [comment]
Fair enough. Shall I close for now?  Good luck, and hope things settle down!

**Comment by RonnyPfannschmidt** [comment]
im ussing the deffered label for things that will take a while for now

**Comment by atikhono** [comment]
You could set different tag_regex for different packages, like: `r"^{package-name}-(?P<version>[vV]?\d+(?:\.\d+){0,2}[^\+]+)(?:\+.*)?$"` (basically, the default regex without word predicate in the beginning, see https://github.com/pypa/setuptools_scm/blob/master/src/setuptools_scm/config.py#L9), and override the default git-descibe command to match {package-name}: `git describe --match {package-name}-*. `(for the default one see https://github.com/pypa/setuptools_scm/blob/master/src/setuptools_scm/git.py#L15). Hopefully, I'm getting it right, not tested.

**Comment by RonnyPfannschmidt** [comment]
closing this one,
on order to implement this properly one wold have to create a meta-scm view that considers a filtered set of tags and does elaborate log operations

that can be done as a setuptools_scm plugin
i'm happy to consider a working tested implementation for core inclusion, but i wont work on creating  it myself

**Comment by aaraney** [comment]
@RonnyPfannschmidt, can you briefly elaborate on how to write such a plugin? I am trying to do something similar by providing my own parse hook implementation as a `setuptools_scm.parse_scm` entry point script. However, as pointed out in https://github.com/pypa/setuptools_scm/issues/561, you cannot override an existing entry-point key (e.g. `.git`) without doing some hackery.

So for example, this does not work:


```toml
# pyproject.toml

[build-system]
requires = [
    "setuptools>=64",
    "setuptools_scm>=8",
    "some_plugin",
]
build-backend = "setuptools.build_meta"

[project.entry-points."setuptools_scm.parse_scm"]
".git" = "some_plugin.git:parse"

[project]
name = "some_project"
authors = [{ name = "Some Author" }]
dynamic = ["version"]
```

**Comment by RonnyPfannschmidt** [comment]
seems like there is need for a addition to manage this

**Comment by aaraney** [comment]
I may have spoken too soon. I got the following working by providing a custom `parse` function to `use_scm_version`:


```python
# setup.py
import dataclasses
import os
import shlex
import warnings
from typing import Callable, List, Optional, Union

from setuptools import setup
from setuptools_scm import Configuration
from setuptools_scm.git import GitWorkdir, get_working_directory
from setuptools_scm.git import parse as scm_parse
from setuptools_scm.git import run_git, warn_on_shallow
from setuptools_scm.version import ScmVersion


def parse(
    root: str,
    config: Configuration,
    describe_command: Optional[Union[str, List[str]]] = None,
    pre_parse: Callable[[GitWorkdir], None] = warn_on_shallow,
) -> Optional[ScmVersion]:
    """
    :param pre_parse: experimental pre_parse action, may change at any time
    """
    # dir containing pyproject.toml or setup.cfg
    pyproj_dir = os.getcwd()
    wd = get_working_directory(config, root)
    if not wd:
        return None

    scm_version = scm_parse(
        root=root, config=config, describe_command=describe_command, pre_parse=pre_parse
    )
    # give up if repo is dirty
    if scm_version is not None and scm_version.dirty:
        return scm_version
    
    # last commit to dir containing pyproject.toml or setup.cfg
    # git rev-list -n1 HEAD -- {pyproj_dir}
    cmd = ["rev-list", "-n1", "HEAD", "--", pyproj_dir]
    out = run_git(cmd, wd.path)

    hash = out.parse_success(lambda s: s.strip())
    if hash is None:
        return None

    git_describe_command = describe_command or config.git_describe_command
    if git_describe_command is None:
        git_describe_command = [
            "git",
            "describe",
            "--tags",
            "--long",
            "--match",
            "*[0-9]*",
        ]

    if isinstance(git_describe_command, str):
        git_describe_command = shlex.split(git_describe_command)

    if git_describe_command[0] != "git":
        warnings.warn(
            "custom non-git describe commands not supported. using version parsed by setuptools_scm."
        )
        return scm_version

    # git describe relative to last commit to dir containing pyproject.toml or setup.cfg
    cmd = [w for w in git_describe_command if w != "--dirty"] + [hash]
    config = dataclasses.replace(config, git_describe_command=cmd)
    return scm_parse(
        root=root, config=config, describe_command=describe_command, pre_parse=pre_parse
    )


setup(use_scm_version={"parse": parse})
```

**Comment by aaraney** [comment]
Im not sure how to package something like this up and provide it as a plugin (that doesnt require `setup.py`) without being able to override `setuptools_scm`'s `git` entry point though. @RonnyPfannschmidt, this would be possible if the `parse` option accepted an entry point string _or_ callable. I assume security and abuse concerns are the main reasons why `parse` does not accept an entry point string now? Or would you consider adding that functionality?

**Comment by aaraney** [comment]
> You could set different tag_regex for different packages, like: `r"^{package-name}-(?P<version>[vV]?\d+(?:\.\d+){0,2}[^\+]+)(?:\+.*)?$"` (basically, the default regex without word predicate in the beginning, see https://github.com/pypa/setuptools_scm/blob/master/src/setuptools_scm/config.py#L9), and override the default git-descibe command to match {package-name}: `git describe --match {package-name}-*. `(for the default one see https://github.com/pypa/setuptools_scm/blob/master/src/setuptools_scm/git.py#L15). Hopefully, I'm getting it right, not tested.

This will _mostly_ work, im doing something similar. The main issue is changes unrelated to the package (think changes to another pkg in a monorepo) you are versioning will interfere with your package's version. You need a way to grab the latest commit relative to the assets you want to version and then git describe from that point in history.
