### ISSUE TITLE
Replace plus from version number?

### ISSUE THREAD

**Issue by hugovk** [pypa/setuptools-scm#342]
I'm using `setuptools_scm` to upload non-release master builds to Test PyPI.

However, the local version part of the [default version number](https://github.com/pypa/setuptools_scm#default-versioning-scheme) (the `+xyz` bit of `0.6.1.dev4+gdf99fe2`) isn't compatible with PyPI, and gives an error:

```
HTTPError: 400 Client Error: '0.6.1.dev4+gdf99fe2' is an invalid value for Version. Error: Can't use PEP 440 local versions. See https://packaging.python.org/specifications/core-metadata for url: https://test.pypi.org/legacy/
```
https://travis-ci.org/hugovk/pypistats/builds/543062857

Is it possible to configure `setuptools_scm` so local versions are not used to allow upload to Test PyPI?

For example, maybe do something like `0.6.1.dev4.gdf99fe2` instead of `0.6.1.dev4+gdf99fe2`?

---

I tried this:

```diff
+def version_scheme(version):
+    from setuptools_scm.version import guess_next_dev_version
+
+    version = guess_next_dev_version(version)
+    return version.replace("+", ".")
+
+
 setup(
-    use_scm_version=True,
+    use_scm_version={"version_scheme": version_scheme},
```

But it made no difference; I see the local version is already stripped from this, and then later added elsewhere:

https://github.com/pypa/setuptools_scm/blob/b5f79dc9af96892d48243c45a3583c0b2ea4f480/src/setuptools_scm/version.py#L208-L215

**Comment by RonnyPfannschmidt** [comment]
you can simply use a different local version scheme to turn it off, its however not the suggested path

**Comment by hugovk** [comment]
Thanks, this gives a version like `0.6.1.dev8`, which allows uploading to Test PyPI:

```diff
+def local_scheme(version):
+    return ""


 setup(
-    use_scm_version=True,
+    use_scm_version={"local_scheme": local_scheme},
```

Is there a better suggested path? Thanks!

**Comment by RonnyPfannschmidt** [comment]
Currently not, the usage of local versions is intended to prevent accident release uploads

**Comment by hugovk** [comment]
Okay, thanks for the help!

This is just fine for me, the huge benefit is not having to edit and commit the version number at all in code, and it's also good there's a different version for Test PyPI.

Thank you for the library!

**Comment by vipulgupta2048** [comment]
Thanks! This helped. 
But, totally agree on the WHY of it. Setuptools-scm is looking out for folks to prevent blunders from happening.

**Comment by palewire** [comment]
I don't have an opinion on the proper solution to this problem, but I think it would great for the maintainers to recommend an approach for users. The [`pypi-publish`](https://github.com/marketplace/actions/pypi-publish) GitHub Action is right now recommending the use of setuptools_scm for running test releases. That sounds like a great idea and it's something I'd like to implement. But, with the bug documented here, I'm unsure of how to do it in accordance with best practices.

**Comment by RonnyPfannschmidt** [comment]
a feature for intentional overrides is planned for a feature release within the next 4-6 weeks

**Comment by palewire** [comment]
That's great. So glad to hear it, @RonnyPfannschmidt!

**Comment by palewire** [comment]
Did this get solved?

**Comment by hugovk** [comment]
For me, yes, by using https://github.com/pypa/setuptools_scm/issues/342#issuecomment-502668474

**Comment by hugovk** [comment]
@palewire I missed https://github.com/pypa/setuptools_scm/pull/405 which added `no-local-version`. So you can do:

```python
# setup.py
from setuptools import setup


setup(
    use_scm_version={"local_scheme": "no-local-version"},
)
```

Or:

```toml
# pyproject.toml
[tool.setuptools_scm]
local_scheme = "no-local-version"
```

**Comment by lgnashold** [comment]
@connortann So what is the current recommended way to do this to facilitate using testpypi releases? 

Is it 
```
setup(
    use_scm_version={"local_scheme": "no-local-version"},
)
```

Or something else?

**Comment by connortann** [comment]
I can't speak to what is recommended by the maintainers of setuptools-scm, but for me the pattern suggested in https://github.com/pypa/setuptools-scm/issues/342#issuecomment-1233118020 worked fine.
