### ISSUE TITLE
How works exactly use_scm_version

### ISSUE THREAD

**Issue by gasparmedina** [pypa/setuptools-scm#349]
Hello, I am currently working on a project that uses setuptools _scm with git.

This project uses it to compare versions. Compare  the current version of the local project, and the comparison with the latest release that is uploaded on Github.

But there is something that is not entering, and that is when the version number is generated with setuptools_scm, it generates something like this:

1.1.dev1392 + g2fba1042.d20190724

But the latest release of this projector on github is v0.100.2-rc2-1688-g2fba1042.

They are comparing these values.

But this version 1.1.dev1392 + g2fba1042.d20190724, I would like to understand how it is actually generated.

This number is generated taking what parameters?
Make a request to the repository in github to create it?

The setup of the project is

use_scm_version = True,
setup_requires = ["setuptools_scm"],

**Comment by RonnyPfannschmidt** [comment]
hi, git describe is used as a base to get the node `g2fba1042`, the distance `1392` and a tag that is likely something like `1.0` - which implies the next version would b something like 1.1,  additionally the workdir is dirty, which is indicated by `d20190724` from the current date

setuptools scm then composes `{next_guessed}.dev{distance}+{node}.d{timestamp}` to the version you see

**Comment by RonnyPfannschmidt** [comment]
also sorry for the late reply, i'm just now following up on personal things after we had to take a detour due travel issues on a ride we started Wednesday

**Comment by gasparmedina** [comment]
Hi, thank you very much for your explanation. Now it's clearer. regards
