### ISSUE TITLE
LookupError: setuptools-scm was unable to detect version for '/data/research/inplace_abn-master'.

### ISSUE THREAD

**Issue by jianlong-yuan** [pypa/setuptools-scm#350]
````
root:/data/research/inplace_abn-master# python setup.py install
Traceback (most recent call last):
  File "setup.py", line 59, in <module>
    cmdclass={"build_ext": BuildExtension}
  File "/data/config/anaconda3/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/data/config/anaconda3/lib/python3.6/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/data/config/anaconda3/lib/python3.6/site-packages/setuptools/dist.py", line 444, in __init__
    k: v for k, v in attrs.items()
  File "/data/config/anaconda3/lib/python3.6/distutils/dist.py", line 281, in __init__
    self.finalize_options()
  File "/data/config/anaconda3/lib/python3.6/site-packages/setuptools/dist.py", line 732, in finalize_options
    ep.load()(self, ep.name, value)
  File "/data/config/anaconda3/lib/python3.6/site-packages/setuptools_scm/integration.py", line 17, in version_keyword
    dist.metadata.version = get_version(**value)
  File "/data/config/anaconda3/lib/python3.6/site-packages/setuptools_scm/__init__.py", line 150, in get_version
    parsed_version = _do_parse(config)
  File "/data/config/anaconda3/lib/python3.6/site-packages/setuptools_scm/__init__.py", line 113, in _do_parse
    "use git+https://github.com/user/proj.git#egg=proj" % config.absolute_root
LookupError: setuptools-scm was unable to detect version for '/data/research/inplace_abn-master'.
```
Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
root:/data/research/inplace_abn-master#

**Comment by jianlong-yuan** [comment]
# Versioning
    use_scm_version={"root": ".", "relative_to": __file__, "write_to": "inplace_abn/_version.py"},

    # Requirements
    setup_requires=["setuptools_scm"],
    python_requires=">=3, <4",

**Comment by jianlong-yuan** [comment]
```
root:/data/research/inplace_abn-master# SETUPTOOLS_SCM_DEBUG=1 python setup.py install
root '/data/research/inplace_abn-master'
root '/data/research/inplace_abn-master'
root '/data/research/inplace_abn-master'
looking for ep setuptools_scm.parse_scm /data/research/inplace_abn-master
looking for ep setuptools_scm.parse_scm_fallback /data/research/inplace_abn-master
found ep setup.py = setuptools_scm.hacks:fallback_version
Traceback (most recent call last):
  File "setup.py", line 59, in <module>
    cmdclass={"build_ext": BuildExtension}
  File "/data/config/anaconda3/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/data/config/anaconda3/lib/python3.6/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/data/config/anaconda3/lib/python3.6/site-packages/setuptools/dist.py", line 444, in __init__
    k: v for k, v in attrs.items()
  File "/data/config/anaconda3/lib/python3.6/distutils/dist.py", line 281, in __init__
    self.finalize_options()
  File "/data/config/anaconda3/lib/python3.6/site-packages/setuptools/dist.py", line 732, in finalize_options
    ep.load()(self, ep.name, value)
  File "/data/config/anaconda3/lib/python3.6/site-packages/setuptools_scm/integration.py", line 17, in version_keyword
    dist.metadata.version = get_version(**value)
  File "/data/config/anaconda3/lib/python3.6/site-packages/setuptools_scm/__init__.py", line 150, in get_version
    parsed_version = _do_parse(config)
  File "/data/config/anaconda3/lib/python3.6/site-packages/setuptools_scm/__init__.py", line 113, in _do_parse
    "use git+https://github.com/user/proj.git#egg=proj" % config.absolute_root
LookupError: setuptools-scm was unable to detect version for '/data/research/inplace_abn-master'.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
```

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
root:/data/research/inplace_abn-master#

**Comment by RonnyPfannschmidt** [comment]
without more info on your setup i have no idea how it went wrong,

for now you can avoid the exception by setting the `SETUPTOOLS_SCM_PRETEND_VERSION` as a way ro avoid the exception

however without knowing how you made that folder, and what you expect its impossible to tell anything about it

**Comment by jianlong-yuan** [comment]
from os import path, listdir

import setuptools
from torch.utils.cpp_extension import BuildExtension, CUDAExtension


def find_sources(root_dir):
    sources = []
    for file in listdir(root_dir):
        _, ext = path.splitext(file)
        if ext in [".cpp", ".cu"]:
            sources.append(path.join(root_dir, file))

    return sources


here = path.abspath(path.dirname(__file__))

with open(path.join(here, "README.md"), encoding="utf-8") as f:
    long_description = f.read()

setuptools.setup(
    # Meta-data
    name="inplace-abn",
    author="Lorenzo Porzi",
    author_email="lorenzo@mapillary.com",
    description="In-Place Activate BatchNorm for Pytorch",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/mapillary/inplace_abn",
    classifiers=[
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.4",
        "Programming Language :: Python :: 3.5",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
    ],

    # Versioning
    use_scm_version={"root": ".", "relative_to": __file__, "write_to": "inplace_abn/_version.py"},

    # Requirements
    setup_requires=["setuptools_scm"],
    python_requires=">=3, <4",

    # Package description
    packages=["inplace_abn"],
    ext_modules=[
        CUDAExtension(
            name="inplace_abn._backend",
            sources=find_sources("src"),
            extra_compile_args={
                "cxx": ["-O3"],
                "nvcc": []
            },
            include_dirs=["include/"],
        )
    ],
    cmdclass={"build_ext": BuildExtension}
)

**Comment by RonnyPfannschmidt** [comment]
please use the GitHub source code formatting facilities and also add some more details on the directory layout/scm structure

**Comment by jianlong-yuan** [comment]
`from os import path, listdir

import setuptools
from torch.utils.cpp_extension import BuildExtension, CUDAExtension

def find_sources(root_dir):
sources = []
for file in listdir(root_dir):
_, ext = path.splitext(file)
if ext in [".cpp", ".cu"]:
sources.append(path.join(root_dir, file))

return sources
here = path.abspath(path.dirname(file))

with open(path.join(here, "README.md"), encoding="utf-8") as f:
long_description = f.read()

setuptools.setup(
# Meta-data
name="inplace-abn",
author="Lorenzo Porzi",
author_email="lorenzo@mapillary.com",
description="In-Place Activate BatchNorm for Pytorch",
long_description=long_description,
long_description_content_type="text/markdown",
url="https://github.com/mapillary/inplace_abn",
classifiers=[
"Programming Language :: Python :: 3",
"Programming Language :: Python :: 3.4",
"Programming Language :: Python :: 3.5",
"Programming Language :: Python :: 3.6",
"Programming Language :: Python :: 3.7",
],

# Versioning
use_scm_version={"root": ".", "relative_to": __file__, "write_to": "inplace_abn/_version.py"},

# Requirements
setup_requires=["setuptools_scm"],
python_requires=">=3, <4",

# Package description
packages=["inplace_abn"],
ext_modules=[
    CUDAExtension(
        name="inplace_abn._backend",
        sources=find_sources("src"),
        extra_compile_args={
            "cxx": ["-O3"],
            "nvcc": []
        },
        include_dirs=["include/"],
    )
],
cmdclass={"build_ext": BuildExtension}`

**Comment by gene1wood** [comment]
@jianlong-yuan What was the resolution of your issue?
