### ISSUE TITLE
allow arbitrary filenames/templates in write_to

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pypa/setuptools-scm#36]
superseeds #33 

there should be a way to allow the writing of arbitrary files/styles 

an idea os to have a write_to_template that acompanies write_to and
just having defaults for the supported extensions

**Comment by prologic** [comment]
:+1: I'd like to be able to (_for example_) write out a `package/version.py` with the following contents:

``` #!python
version_info = (1, 0, 3)
version = "1.0.3"
```

**Comment by RonnyPfannschmidt** [comment]
@prologic what is the version info needed for?

**Comment by prologic** [comment]
A good idea at the time; hardly used; but to programatically compute/compare version numbers at runtime much liks `sys.version_info` tuple.

**Comment by RonnyPfannschmidt** [comment]
@prologic  

my general suggestion is to always use pkg_resources.parse_version of setuptools for that

while working with version numbers im detail it beame rather apparent that all other ways break under too many circumstances

for example its not clear how to encode dev/local versions, scm commit id's or date metadata for dirty workdirs

so on one side its practically impossible to sanely encode the metadata setuptools_scm will put into theversion as a tuple, on the other hand, Versions from pkg_resources are very comparable already

also using pkg_resources to check requirmements seems much more reliable than a self-hacked scheme

**Comment by prologic** [comment]
Whilst I agree it _could_ still be useful to be able to template out `write_to` even if it's used for such purposes to avoid re-parsing the version string each time.

**Comment by RonnyPfannschmidt** [comment]
the general mechanism is implemented, for the detail i created a new issue
