### ISSUE TITLE
detected unexpected version number

### ISSUE THREAD

**Issue by VolkerBergen** [pypa/setuptools-scm#360]
Thanks for this great version tool, it is very convenient.

Yet, I get another version number than expected for my repo https://github.com/theislab/scvelo.

With
```
import scvelo as scv
from setuptools_scm import get_version
get_version(root='..', relative_to=scv.__file__)
```
I get the version number '0.1.24.dev1+gd7bb105' while '0.1.23.dev1+d7bb105' was expected. I get the same systematic differences with all other checkouts, i.e. increasing the version number by one.

I'd be extremely grateful, if you could have a look what went wrong.

git tags:
v0.0.1
v0.1
v0.1.1 - v0.1.23

Now as I am going through the readme more carefully, I see that my initial version number v0.1 might be causing this. Is that so?

**Comment by RonnyPfannschmidt** [comment]
The increment is intentional and can be changed by configuration of a version scheme that won't guess the next version

**Comment by VolkerBergen** [comment]
Thanks, I don't really get the intuition behind the auto-increment. Whatsoever, is there a straightforward way to adjust the scheme to always have the tag without the increment?

**Comment by VolkerBergen** [comment]
Alright, I now understand difference btw. dev-release and post-release. I guess, it's the latter I'm looking for, basically setting version_scheme to 'post-release'. Thanks for the clarification.
