### ISSUE TITLE
setuptools_scm creates difficulties when packaging Python modules for Debian

### ISSUE THREAD

**Issue by olebole** [pypa/setuptools-scm#361]
This is an extension of #235, but since it goes a bit deeper I made a new issue from it.

This problem with invalid tags appears now regularly when packaging a Python module for Debian: Debian uses a separate git repository which contains the upstream sources (usually taken from pypi) and the debian specific files. [Usually](https://dep-team.pages.debian.net/deps/dep14/), our repositories contain tags like `debian/1.0.2-3` or `upstream/1.0.2`.
These tags regularly confuse setuptools-scm and require us to switch off its use when we debianize a package. Switching off usually requires that we patch `setup.py`, changing the `use_scm_version=True` option. Such patches have then to be maintained over the lifetime of the package, which is quite unfortunate. Also, the package still needs to import setuptools.scm, even if it does not use it.
One example package where this happens now is gammapy/gammapy#2440.

It would be great if there was an environment variable (or something like that) that could force not using setuptools-scm and also switch off it as a requirement. Or use the version number from `debian/changelog`. Just ignoring all non-conform tags and then relying on a fallback when no suitable tag is found sounds a bit dangerous to me, since it may happen that an old tag may match the format.

**Comment by RonnyPfannschmidt** [comment]
the `SETUPTOOLS_SCM_PRETEND_VERSION` is intended for that

and that must be a valid python version number so the package has valid metadata

**Comment by olebole** [comment]
OK, thanks; this helps.
Actually, this variable is already set when using the Debian build tool `pybuild`. Funnily, I now can't reproduce anymore why I got an error here -- it just magically disappeared. So, it is safe to close the issue.

**Comment by RonnyPfannschmidt** [comment]
thanks for the followup
