### ISSUE TITLE
setuptools_scm shows version from repository in current directory instead of from application

### ISSUE THREAD

**Issue by simonvanderveldt** [pypa/setuptools-scm#366]
When using a CLI tool that uses `setuptools_scm` for the version `setuptools_scm` will return the git version from the repo one is currently in instead of the version from the CLI tool itself.

Example below:
```
$ druid --version
druid, version 0.2.0
# Now changing directory to a checkout from another repo
$ cd bowery 
$ git rev-parse --short HEAD  
ca0859e
$ druid --version
druid, version 0.1.dev18+gca0859e
```

Is this expected behavior?

**Comment by RonnyPfannschmidt** [comment]
most likely yes, its not supposed to be used in installable artifacts (as its practically impossible to get right

**Comment by simonvanderveldt** [comment]
@RonnyPfannschmidt Ah, OK, I wasn't aware of that. When/how would one use `setuptools_scm` then? Only for code that's always run/executed directly from the repo checkout directory?

In case I'd like to publish a project to PyPI what would be the suggested/correct approach? I couldn't really find anything in the docs about this.
Use `write_to` and lose the runtime reporting of dev builds seems to be the only option?

**Comment by RonnyPfannschmidt** [comment]
only in development tooling and package building,

**Comment by matthijskooijman** [comment]
Wouldn't this particular case be solved by a different interpretation of the `root` option? Rather than use the current directory, use the directory that contains `setup.py` when running from setuptools via `infer_version`?

When `get_version` is called explicitly, it would be up to the caller to figure out the correct path (e.g. relative to `__file__` or something).

**Comment by RonnyPfannschmidt** [comment]
as far as i understood this issue is about calling get_version in a package, which is neither intended not supportable, closing this issue now

**Comment by simonvanderveldt** [comment]
I guess I'm probably missing something, but what's the point of this functionality then?
I concluded it doesn't work and am back to hardcoding the version :(

**Comment by RonnyPfannschmidt** [comment]
@simonvanderveldt its simply at best fragile to figure a version fro ma in-package version, and its usually fine for end-users - for development/editable installs its best to do a regular update of the metadata with a actual editable install

**Comment by simonvanderveldt** [comment]
> for development/editable installs its best to do a regular update of the metadata with a actual editable install

@RonnyPfannschmidt Thanks for the info. What would this part look like in practice? Which metadata should be updated how?

**Comment by RonnyPfannschmidt** [comment]
Typically regular `pip install -e .` sorts it out
