### ISSUE TITLE
Untracked files are not being excluded with `./setup.py sdist`

### ISSUE THREAD

**Issue by blueyed** [pypa/setuptools-scm#376]
setuptools_scm has a special file finder to list files tracked in Git, but e.g. via https://github.com/pypa/setuptools/blob/e84f616a6507ec9115fad68b221cbf5333d9d2d9/setuptools/command/sdist.py#L124-L128 untracked files are still being included then.

The above happens when either `packages` or `py_modules` is specified.

But also when skipping this explicitly (via editing the source), untracked files get added via https://github.com/pypa/setuptools/blob/e84f616a6507ec9115fad68b221cbf5333d9d2d9/setuptools/command/install_lib.py#L12 still.

I think it would be good if setuptools_scm would exclude any untracked files after all this.

It might also be an issue with setuptools really that is iterating of package dirs etc although a file list has been provided already.

**Comment by RonnyPfannschmidt** [comment]
@jaraco i believe this may need some extra integration with setuptools, do you have any insight?

**Comment by jaraco** [comment]
I’m not sure I follow how setuptools_scm is implicated in the undesirable behavior. The API for file finders is they find all the files and then its setuptools role to determine from there which files to include or exclude. It doesn’t (and shouldn’t) have another hook for file finders to take a second crack at excluding found files.

Historically, distutils would include all sources automatically (all packages and python modules), so I would expect that behavior to continue even with file finders like setuptool_scm, which are meant to make sure non-code files are included.

Perhaps you could also give an example of a problem you’re trying to solve.

**Comment by blueyed** [comment]
@jaraco 
Thanks for the explanation.
The example is just having a project with untracked files.
The work around is to to build/upload from a clean checkout for example (or via CI).
