### ISSUE TITLE
Please add a tag for 1.7.0

### ISSUE THREAD

**Issue by felixonmars** [pypa/setuptools-scm#38]
Looks like there is a 1.6.0 version on PyPI, but not in the repository. It would be great if 1.6.0 would be tagged here as well, thanks!

**Comment by RonnyPfannschmidt** [comment]
actually it seems a lot more tags had been missing in some way - i just did a git push --tags

thanks for the note, it didn't occur to me

**Comment by felixonmars** [comment]
Looks like 1.7.0 is missing again :)

**Comment by RonnyPfannschmidt** [comment]
i have o figure how to make git push tags, sorry for the inconvenience

**Comment by untitaker** [comment]
`git push origin <tag>`

**Comment by RonnyPfannschmidt** [comment]
@untitaker my main problem is automation in a sane way, prior i used `git push --tags` but i learnd that method is no good and one has to exercise more control (also i miss the mercurial model already)

**Comment by untitaker** [comment]
I like to be explicit about what I push so this is no problem for me.

**Comment by RonnyPfannschmidt** [comment]
in future i'll push tags and let travis run on them once before uploading the releases to pypi
