### ISSUE TITLE
release 3.4

### ISSUE THREAD

**Issue by gaborbernat** [pypa/setuptools-scm#380]
Seems the master suggests using 3.4 but that was never released 🤔

**Comment by RonnyPfannschmidt** [comment]
indeed, instead of finishing details and releasing it a caught a good old cold, and im not sure if i can get to the finer details before next week

**Comment by jaraco** [comment]
Let me know if I can help.

**Comment by RonnyPfannschmidt** [comment]
thanks for the offer

I'll be back home with the computer where i have my branches/wip on Sunday
unfortunately i got also caught up in a real flu just before the holiday season.

I'm still travelling for family visits.

I apologize since i missed updating this issue when i did my twitter shoot-out wrt thing being looked up  until this year.

**Comment by jaraco** [comment]
No problem. Feel better soon.

**Comment by layday** [comment]
3.4 appears to have been released without #377 meaning the TOML example from the readme will not work - users will need to specify a `version_scheme` at a minimum.  Should the readme be updated in a bugfix release?

**Comment by RonnyPfannschmidt** [comment]
Thanks for the note, will do in a bit

**Comment by RonnyPfannschmidt** [comment]
@layday rolled this out as critical bugfix, thanks

**Comment by layday** [comment]
Great, thanks for landing pyproject support - now if I could just get rid of setup.py/cfg.

**Comment by RonnyPfannschmidt** [comment]
well, its still far out as the peps don't support editable installs

**Comment by gaborbernat** [comment]
That one needs a champion to do the work 🤔of importing a solution for editable installs

**Comment by layday** [comment]
I don't think tool table support in setuptools is predicated on editable installs - it would be no different than using pep517 with a `setup.cfg` - but that's probably a discussion for [another place](https://github.com/pypa/setuptools/issues/1688).

**Comment by RonnyPfannschmidt** [comment]
@layday the peps do not support editable install, only the legacy setuptools path does in the pip chain

**Comment by layday** [comment]
Yes but being able to define a package in pyproject.toml does not imply build isolation. That’s what I was referring to.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
