### ISSUE TITLE
Failed testing on appveyor

### ISSUE THREAD

**Issue by aodag** [pypa/setuptools-scm#385]
Using python3.4, setuptools_scm runs CI on appveyor.
But the latest release of pytest requires python 3.5 or later.

https://ci.appveyor.com/project/RonnyPfannschmidt/setuptools-scm-13mi5/builds/29536424/job/jlrlb9qho1ew11r3

```
ERROR: colorama requires Python '>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*' but the running Python is 3.4.4
```

Testing on travis uses pytest 4.6.2 that I wonder why. (because of cache?)

**Comment by RonnyPfannschmidt** [comment]
izs a old pip fallout

**Comment by RonnyPfannschmidt** [comment]
closing as the windows builds are now on gitlab ci
