### ISSUE TITLE
More explicit error in `get_version` when `git` (or `hg`) command is not available

### ISSUE THREAD

**Issue by smarie** [pypa/setuptools-scm#392]
In my [`getversion`](https://smarie.github.io/python-getversion/) library I rely on `setuptools_scm` as one of the (many) strategies to guess a module version. I rely on `setuptools_scm.get_version(<path>)` for this.

A user reported to me a case where `git` was not in his execution `PATH`. The only error I was able to get from `setuptools_scm` was the generic `LookupError`. Could we imagine to get a more strongly typed `GitNotFoundError` ?

**Comment by RonnyPfannschmidt** [comment]
#339 raises environment errors with the command as part of the error

**Comment by smarie** [comment]
Great! thanks @RonnyPfannschmidt
