### ISSUE TITLE
Convenience function for programmatic use

### ISSUE THREAD

**Issue by flying-sheep** [pypa/setuptools-scm#394]
Using setuptools_scm to provide your package’s `__version__` currently looks like this:

```py
def get_version():
    # dev dependency, not necessarily (but possibly) installed once the package is installed.
    # will fail if we’re calling it from an installed repo
    try:
        from setuptools_scm import get_version, LookupError
    except ImportError:
        pass
	else:
        try:
            return get_version(root='..', relative_to=__file__)
        except LookupError:
            pass

    # Standard way to get the version from the installed package metadata
    try:
        try:
	        from importlib.metadata import version, PackageNotFoundError
		except ImportError:  # backport
			from importlib_metadata import version, PackageNotFoundError
	except ImportError:
    	pass
	else:
	    try:
	        return version(__name__)
	    except PackageNotFoundError:
	        pass

    # Old way to get the version from the installed package metadata
    # This block can be skipped if you add a dep `importlib-metadata; python_version<'3.8'`
	try:
        from pkg_resources import get_distribution, DistributionNotFound
	except ImportError:
		pass
	else:
		try:
			return get_distribution(__name__).version
		except DistributionNotFound:
			pass

	raise ImportError('could not determine version')

__version__ = get_version()
```

Which is a bit much to replicate in every project. It would be cool to have some nice convenience function that works like `get_version`, but also takes `__name__` and retrieves the version using various means.

Of course using it like that would make it a runtime dependency …

**Comment by RonnyPfannschmidt** [comment]
@flying-sheep the suggested way  is to use either only `pkg_resources` (when unavoidable) or to use only `importlib.metadata`

invoking it at run-time is only ever possible for editable installs and always absolutely wrong and incorrect for normal installs

that of course has the  downside that the editable install metadata is sometimes lacking, there is no good solution for that atm

**Comment by flying-sheep** [comment]
I’m talking about import-time code that detects if the version of the module that is currently run is a development version or not. `importlib.metadata.version`/`pkg_resources.get_distribution` will succeed if there’s an installed version on the system, therefore I need to check if we’re in a git repository *first* and derive the version from it.

So no, invoking it at run-time is definitely not absolutely wrong and incorrect for normal installs, because I depend on that throwing an exception so I can proceed to look up the version from metadata in that case.

Or am I missing something?

**Comment by RonnyPfannschmidt** [comment]
Editable install resolves that

**Comment by flying-sheep** [comment]
They’re an unstandardized pip thing. I don’t use pip for my projects. Starting to use those would mean I’d have to adapt the testing for all the packages I maintain … I’d rather not do that.

**Comment by RonnyPfannschmidt** [comment]
i believe this functionality  should be part of a new python package that reflects  the  intent,
its perfectly fine to use setuptools_scm from such a package
its just not behaviour thats in scope for setuptools_scm itself to expose
