### ISSUE TITLE
tag_regex not working with setuptools_scm 3.4.1

### ISSUE THREAD

**Issue by pkolbus** [pypa/setuptools-scm#395]
With setuptools_scm 3.4.1, custom tag_regex expressions are not working correctly.

My setup.py contains:

    ...
    setup_args["use_scm_version"] = {
        "tag_regex": r"^(?P<prefix>.*/)?(?P<version>\d+(?:\.\d+){1,2})$"
        }
    setup_args["setup_requires"] = ['setuptools_scm']

    setuptools.setup(**setup_args)

setuptools_scm 3.4.0 works:

    $ python3 setup.py --version
    0.4.1.dev7+gc2397c5'

With 3.4.1:

    $ python3 setup.py --version
    /home/kolbus/.local/lib/python3.6/site-packages/setuptools_scm/version.py:92: UserWarning: tag 'development/0.4.0' no version found
      warnings.warn("tag {!r} no version found".format(tag))
    Traceback (most recent call last):
    ...
      File "/home/kolbus/.local/lib/python3.6/site-packages/setuptools_scm/git.py", line 135, in parse
    branch=branch,
      File "/home/kolbus/.local/lib/python3.6/site-packages/setuptools_scm/version.py", line 205, in meta
        assert parsed_version is not None, "cant parse version %s" % tag
    AssertionError: cant parse version development/0.4.0

**Comment by RonnyPfannschmidt** [comment]
please provide the full traceback

**Comment by RonnyPfannschmidt** [comment]
also could this be related to https://github.com/pypa/setuptools_scm/pull/346/files ?

**Comment by blueyed** [comment]
@RonnyPfannschmidt the issue is between 3.4.0 and 3.4.1.

**Comment by RonnyPfannschmidt** [comment]
on careful review i noted that i missed a line when sorting out the options

**Comment by pkolbus** [comment]
Verified. Thanks for the quick fix!

**Comment by RonnyPfannschmidt** [comment]
Thanks for the verification, I will release shortly
