### ISSUE TITLE
add a comparable version tuple for use in write_to_template

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pypa/setuptools-scm#41]
@prologic noted in #36 that having a version tuple for use in write_to might be helpful for a number of scenarios

personally i think just parsing versions with pkg_resources is fine is fine,
however since users declared a desire to have this im putting up this issue,

anyone can implement it, i'm happy to review and merge a reasonable solution

**Comment by prologic** [comment]
:+1: It just saves s few cpu cycles for me :)

**Comment by RonnyPfannschmidt** [comment]
closing due to lack of interest
