### ISSUE TITLE
How to add git tags to support versioning of different packages in the same repository ? 

### ISSUE THREAD

**Issue by tyagiabhishek** [pypa/setuptools-scm#413]
I have a repository which has multiple packages and want to support independent versioning of each of these projects. Does setuptools_scm support that? If so how does it do that ? Does it see the commit itself to decide if the tag is for a given package ?

**Comment by RonnyPfannschmidt** [comment]
the common solution is to have each package use a different tag prefix, and ensure the git describe command is set up for each of them differently based on 
https://github.com/pypa/setuptools_scm#configuration-parameters
at least the git describe command needs to be configured i beleive

currently i cant try this to verify

**Comment by RonnyPfannschmidt** [comment]
as there was no further feedback i consider this resolved, in case thats in error please tell me
