### ISSUE TITLE
[feature]Error is really uninformative `LookupError`. Why is Github tarball not supported?

### ISSUE THREAD

**Issue by shouldsee** [pypa/setuptools-scm#416]
```
LookupError: setuptools-scm was unable to detect version for '/tmp/pip-install-2j0del01/eutils'

    Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
    
    For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
```

Why are we dropping support for the Github tarball???? tarball is the time-proved way of version-controlling and why should a new user perfer setuptools_scm to tarball distribution?

**Comment by RonnyPfannschmidt** [comment]
unlike mercurial, git chooses since more than a decade to have tarballs that lack sensible metadata
as such setuptools_scm can not help it

it suggested to use full git clones or sdists/wheels to get correct metadata

**Comment by shouldsee** [comment]
> unlike mercurial, git chooses since more than a decade to have tarballs that lack sensible metadata
> as such setuptools_scm can not help it
> 
> it suggested to use full git clones or sdists/wheels to get correct metadata

Well is it not possible to add a DESCRIPTION file of some sort?

**Comment by RonnyPfannschmidt** [comment]
thats what the python sdist mechanism does, it itself has no way to do it correct for anything but tags, and even that is flaky

**Comment by RonnyPfannschmidt** [comment]
closing as issue imposed by git and unfixable until git gets a hintt
