### ISSUE TITLE
python-simplified-semver produces non semver distance output

### ISSUE THREAD

**Issue by ri0t** [pypa/setuptools-scm#420]
I get version numbers like this: `1.0.11.dev72+g0410623.d20200426`

Looks fine on the first glance, but alas, [the spec says the dot in front of dev72 distance part is invalid](https://semver.org/#spec-item-10) and should either be a dash or a plus if i'm not mistaken. That is also, what testing a regexp leads to: https://regexr.com/53bq4

It may be a local problem, but i wouldn't know why and the docs explicitly state the dot.

I stumbled upon this by feeding the version number to another semver-parser on a different machine which was unable to follow through.

Thanks for looking into this.

**Comment by ri0t** [comment]
Aahaha, i fixed that locally and now get:
`
python3.7/site-packages/setuptools/dist.py:474: UserWarning: Normalizing '1.0.11-dev72+g0410623.d20200426' to '1.0.11.dev72+g0410623.d20200426'
`

Guess thats a bit tougher to get around and i'll probably be easier off by just cutting after the minor..

**Comment by RonnyPfannschmidt** [comment]
setuptools_scm is for making python version numbers, the normalization is slightly different

**Comment by RonnyPfannschmidt** [comment]
closing as invalid since the python version scheme is intentionally different
