### ISSUE TITLE
Should (optionally) favor `PKG_INFO` over SCM data?

### ISSUE THREAD

**Issue by matthijskooijman** [pypa/setuptools-scm#423]
I'm the Debian maintainer of a python package. Upstream is having some problems with version detection and is considering switching to `setuptools_scm`. However, I'm afraid we'll run into the same problems still.

Consider this workflow:
 - A python package that uses `setuptools_scm` to detect its version generates a sdist tarball for a release. This properly detects the current tag in `PKG_INFO`.
 - The sdist tarball is imported into *another* git repository. This is common for Debian packages, where a git repository is used to track the packaging files, which also includes the upstream sources verbatim.
 - Then, when building using `setup.py`, `setuptools_scm` finds the Debian git repository and uses the tag/commit information from that, rather than the (IMHO more correct) `PKG_VERSION` file.

An easy way to reproduce this problem is to run `sdist`, unpack the source tarball and then create a git repo inside that unpacked directory, create a commit and a tag, and then see `./setup.py version` returning the wrong version number.

There's a few different ways to look at this:
 1. Once a build is generated (with a `PKG_VERSION` file), that version detaches from the original git repo, so git version detection is no longer appropriate and the `PKG_VERSION` should be used instead. This could be done by switching the order of the "fallback" and "parse" steps (or at least putting the `PKG_VERSION` fallback step before the "parse" step, not sure if the other fallbacks should be moved up as well).
 2. OTOH, you could say that once you import an sdist into another git repo, then you might as well be changing the original source files, so using git commit info from that repo makes more sense. This is the current behaviour.
 3. A compromise could be to require an explicit selection if both SCM and `PKG_INFO` are found. This could be done by always looking for both, and raising an error if both are found, except when the appropriate config variable (or env var maybe) is set.
 4. Another approach would be to keep the current approach (2.), but explicitly disable SCM parsing when building the Debian package. I think this can currently be somewhat done by setting `config.parse` to a dummy parse function (e.g. `lambda config: None` or something), but that does feel a bit like a hack.

Note: I'm just talking about `PKG_INFO` here, but I think that the same will hold for most if not all if the other fallback things (e.g. `.hg-archival.txt`) as well (except maybe `setup.py` version detection and certainly except the `config.fallback_version`).

Any other suggestions on how to support this case would also be welcome :-)

**Comment by RonnyPfannschmidt** [comment]
the `SETUPTOOLS_SCM_PRETEND_VERSON` env var is the intended mechanism for distro toolchains to opt out of parsing/logic

**Comment by matthijskooijman** [comment]
AFAIU, `SETUPTOOLS_SCM_PRETEND_VERSON` allows specifying a version that is used as-is, without *any* parsing. However, in the Debian package, I do not necessarily know what the (upstream) version number should be.

What I (think I) need, is something allows skipping the .git-version-parsing, but still allows `setuptools_scm` to load the version from `PKG_VERSION` and use that as the version for the setuptools build.

**Comment by RonnyPfannschmidt** [comment]
in the debian version, in particular when you apply patches from debian, you should put a debian version tag into a local version tag, aka `my.pkg.ver+debian123`

**Comment by matthijskooijman** [comment]
> in the debian version, in particular when you apply patches from debian, you should put a debian version tag into a local version tag, aka my.pkg.ver+debian123

You mean *not* use the upstream version as-is, but modify it (that is, the version that ends up in `PKG_INFO`) to explicitly indicate that this is a (possibly modified) Debian package, rather than a clean upstream install?

I guess that would indeed make sense, except:
 - It does not seem to be a common practice right now. The [Debian Python policy](https://www.debian.org/doc/packaging-manuals/python-policy/index.html) does not say anything about (modifying the) version number, and looking in existing packages, I could not find any such suffix on my Ubuntu system (running `grep '^Version:' /usr/lib/python3/dist-packages/*/PKG-INFO` shows no such suffixes, except for a few `ubuntuxx` suffixes on packages which are Debian native, so they have no upstream version, so the `ubuntu` suffix only indicates changes made from Debian to Ubuntu).
 - Other software might be checking for upstream version numbers and could be confused by suffixes (this is probably not a (big) problem in practice, though).

**Comment by RonnyPfannschmidt** [comment]
for quite a while the toolign around python version numbers was problematic (in setuptools <1.0 times it was just insane)

in the recent years packaging tooling for python has massively improved nd that is an opportuunity to make use of

for example - if more people use version checks based on the actual version parser the python standard tooling brings, they no longer get confused by correct local tags

**Comment by RonnyPfannschmidt** [comment]
closing as wont-fix - a distro should manage the version numbers in this case
