### ISSUE TITLE
root configuration parameter and PKG-INFO

### ISSUE THREAD

**Issue by bluetech** [pypa/setuptools-scm#43]
I have a git repository which contains several sub-directories, each with its own `setup.py`. To get `setuptools_scm` to work, I thus pass `root: '..'`. However, when I try to `pip install` the result of a `setup.py sdist`, it doesn't find the version. The reason (I am pretty sure) is that it tries to look for `PKG-INFO` also in `..` and doesn't find it.

Is there any way to do this while still keeping the given structure of the repository? If not, maybe it makes sense to disregard `root` when searching for `PKG-INFO`?

**Comment by RonnyPfannschmidt** [comment]
that's actually a really good find and a bug i did not anticipate at all
i'll come up with a fix
