### ISSUE TITLE
Upgrade GHA workflow to use v2 of the official actions

### ISSUE THREAD

**Issue by webknjaz** [pypa/setuptools-scm#432]
_(https://twitter.com/webKnjaZ/status/1261678107439792129 follow-up)_

So from what I saw, current workflows use actions/setup-python and actions/checkout that are v1 but both have v2 available.

It should be a low hanging fruit for somebody who wants to send an easy beginner-level PR.

**Comment by henryiii** [comment]
v2 of setup python should be trivial (it basically just allows you to pin to any Python version), but v2 of checkout is probably a bit of a challenge to do nicely - it does not include the information needed for `setuptools_scm`, even with depth=0, so you have to unshallow, which is (IMO) uglier than using "v1" for now. Here's the issue: https://github.com/actions/checkout/issues/249 .
