### ISSUE TITLE
Unable to detect version when running pytest-runner's tests

### ISSUE THREAD

**Issue by felixonmars** [pypa/setuptools-scm#44]
Hi,

I am running pytest-runner's tests with "py.test" in its hg repo root folder, and getting the following error:

```
______________________________________________________________ ERROR collecting docs/conf.py _______________________________________________________________
docs/conf.py:15: in <module>
    version = setuptools_scm.get_version(root='..')
/usr/lib/python3.4/site-packages/setuptools_scm/__init__.py:65: in get_version
    version = version_from_scm(root)
/usr/lib/python3.4/site-packages/setuptools_scm/__init__.py:34: in version_from_scm
    "instead." % root)
E   LookupError: setuptools-scm was unable to detect version for '/tmp'.
E
E   Make sure you're not using GitHub's tarballs (or similar ones), as those don't contain the necessary metadata. Use PyPI's tarballs instead.
================================================================= 1 error in 0.12 seconds ==================================================================
```

I have tried to downgrade setuptools_scm and found that it worked till 1.5.5. The repo is located at https://bitbucket.org/pytest-dev/pytest-runner

There was no error running `setup.py build`, etc, though.

Any hints?

**Comment by RonnyPfannschmidt** [comment]
Bug in the sphinx configuration of ptr, recent setuptools-scm errors out earlier

**Comment by felixonmars** [comment]
Thanks, I have opened a bug report there. For reference: https://bitbucket.org/pytest-dev/pytest-runner/issues/6

**Comment by jaraco** [comment]
At the very least, if the recommended usage is to have a try/except block for sphinx config files, then that should be advertised in the documentation. Even better would be to provide a routine or parameter such that a package can call and get the version easily. In any case, the code used in pytest-runner is also used in dozens of other packages and is part of a template I use in many packages. I don't want to refresh all of those packages with the same try/except block.

Did setuptools_scm ever add an option to traverse up to find the root?

**Comment by RonnyPfannschmidt** [comment]
early versions used traversal, but traversal easily broke in certain scanarios

a propper solution should include a relative_to option that can be filled with **file**

**Comment by RonnyPfannschmidt** [comment]
implementing #45 will provide a proper solution

**Comment by jaraco** [comment]
@RonnyPfannschmidt What is the recommended usage after the implementation of #45? What should one specify in a script, such as docs/conf.py to resolve the repo version when `os.getcwd()` could be either `.` or `docs/`?

**Comment by jaraco** [comment]
I thought this issue was resolved because it hasn't been affecting me in local development, but I realized after moving one of my projects to github ([jaraco.mongodb](https://github.com/jaraco/jaraco.mongodb)) and [running it under Travis](https://travis-ci.org/jaraco/jaraco.mongodb/jobs/88527553), that the only reason these tests weren't failing in my environment was because in my environment, the repos happen to be in a parent repo, and so when running from the root of the repo and executing `conf.py`, `get_version('..')` would reference the parent repo, which although providing an invalid version would at least not cause a failure. When run in isolation, however, the tests fail.

**Comment by jaraco** [comment]
For the time being, I've [worked around the issue](https://github.com/jaraco/jaraco.mongodb/commit/8cbfa004770b798fbb7016c8c9c44b7b15a58ece) within that project, essentially implementing the `relative_to` that Ronny alluded to earlier in this ticket. Perhaps that technique still should be considered.

**Comment by RonnyPfannschmidt** [comment]
Reopened #45 again
