### ISSUE TITLE
Version 4.0 breaks on Windows + 2.7

### ISSUE THREAD

**Issue by henryiii** [pypa/setuptools-scm#442]
The latest version seems to have lost the use of the samefile backport on Windows + 2.7, causing this error now in CI:

```
  Downloading setuptools_scm-4.0.0.tar.gz (46 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  ERROR: Command errored out with exit status 1:
   command: 'C:\hostedtoolcache\windows\Python\2.7.18\x86\python.exe' 'C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'c:\users\vssadm~1\appdata\local\temp\tmpacqthi'
       cwd: c:\users\vssadm~1\appdata\local\temp\pip-install-yxxmaf\setuptools-scm
  Complete output (22 lines):
  c:\users\vssadm~1\appdata\local\temp\pip-install-yxxmaf\setuptools-scm\src
  <pkg_resources.WorkingSet object at 0x02F22D30>
  Traceback (most recent call last):
    File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <module>
      main()
    File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "c:\users\vssadm~1\appdata\local\temp\pip-build-env-7itkho\overlay\Lib\site-packages\setuptools\build_meta.py", line 146, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "c:\users\vssadm~1\appdata\local\temp\pip-build-env-7itkho\overlay\Lib\site-packages\setuptools\build_meta.py", line 127, in _get_build_requires
      self.run_setup()
    File "c:\users\vssadm~1\appdata\local\temp\pip-build-env-7itkho\overlay\Lib\site-packages\setuptools\build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 53, in <module>
      setuptools.setup(**scm_config())
    File "setup.py", line 31, in scm_config
      from setuptools_scm.git import parse as parse_git
    File "c:\users\vssadm~1\appdata\local\temp\pip-install-yxxmaf\setuptools-scm\src\setuptools_scm\git.py", line 9, in <module>
      from os.path import samefile
  ImportError: cannot import name samefile
  ----------------------------------------
  Getting requirements to build wheel: finished with status 'error'
```

**Comment by henryiii** [comment]
I think this is because there is [no wheel provided](https://pypi.org/project/setuptools-scm/4.0.0/#files) for Python 2, so for the PEP 517 build it collects the source package, and with the source package, the backport is not installed during the install, so it fails. A py2 wheel would fix it, or using PEP 517 build, with the backport in the pyproject.toml would probably fix it too.

(Note the above is failing in the build+install of `setuptools_scm` itself during the setup phase of the PEP 517 build) (Only a Windows + 2.7 failure)

**Comment by r2dan** [comment]
It seems that wheel availability has nothing to do in this case - it fails because `os.path.samefile` is only available on Unix in Python 2.7 (https://docs.python.org/2/library/os.path.html#os.path.samefile).
Looking at the classifiers Python 2.7 is still there - https://github.com/pypa/setuptools_scm/blob/master/setup.cfg#L18. @RonnyPfannschmidt do you plan to keep the package Python 2.7 compatibility or you drop it with 4.0.0?

**Comment by AlexandreYang** [comment]
Same issue here https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=16424&view=logs&j=2c9050e0-5be6-5014-27c6-a7b39b941d76&t=b67d05b8-4057-5a69-16ef-b4379dc0abda&l=76

**Comment by henryiii** [comment]
> It seems that wheel availability has nothing to do in this case

Yes, it does. In the past, it had a backport of `os.path.samefile`. Now that has been moved to a dependency. In the changelog for 4.0:

> drop the internal copy of samefile and use a dependency on jaraco.windows on legacy systems

The problem is, since there's no wheel, Python 2 has to build `setuptools_scm`. And `setuptools_scm` uses `setupstools_scm` to build itself, and it doesn't have a PEP 517 build process, so there's no way to enforce `jaraco.windows` be preinstalled while it runs setup.py, so it fails. Adding a 2.7 compatible wheel would fix it; since then there's no build and you would not use it until it is installed, along with `jaraco.windows`. Or PEP 517 allows you to specify a setup dependency for making the wheel, so that would also fix it. (But that would require a patch release, while adding a py2 wheel could be done to the same release)

I think the issue may come from the current version of setuptools not supporting Python 2, so it makes Python 3 only wheels by default instead of universal wheels (guessing there).

Edit: I think adding --universal to the setup.py execution would fix it (could still be 4.0.0, since it could be run locally with no code changes), or (for the future 4.0.1) the universal configuration option could be added.

**Comment by RonnyPfannschmidt** [comment]
as per #440 i will undo the de-vendoring as i missed the extra dependency the library brings in anyway

additionally i will return universal wheels, the absence is a rebase mistake on my side

**Comment by r2dan** [comment]
@henryiii Thanks for explaining, now it makes sense.

**Comment by RonnyPfannschmidt** [comment]
thanks to @henryiii suggesting the universal wheel upload in #445, i quickly did that - please crosscheck if that's already a relief

**Comment by henryiii** [comment]
It can now install the wheels:

```
  Successfully installed backports.functools-lru-cache-1.6.1 configparser-4.0.2 contextlib2-0.6.0.post1 importlib-metadata-1.6.0 importlib-resources-1.5.0 jaraco.classes-2.0 jaraco.collections-2.1 jaraco.functools-2.0 jaraco.structures-2.0 jaraco.text-3.2.0 jaraco.ui-2.0.1 jaraco.windows-4.0 more-itertools-5.0.0 numpy-1.13.3 path.py-11.5.2 pathlib2-2.3.5 scandir-1.10.0 setuptools-44.1.0 setuptools-scm-4.0.0 singledispatch-3.4.0.3 six-1.15.0 toml-0.10.1 typing-3.7.4.1 wheel-0.34.2 zipp-1.2.0
  Removed build tracker: 'c:\\users\\vssadm~1\\appdata\\local\\temp\\pip-req-tracker-4_74c6'
  Installing build dependencies: finished with status 'done'
```

Hooray! However, the next step fails with a similar error:

```
    File "c:\users\vssadm~1\appdata\local\temp\pip-build-env-53auik\overlay\Lib\site-packages\setuptools_scm\git.py", line 9, in <module>
      from os.path import samefile
```

Does `jaraco.windows` not monkey patch `os.path.samefile`, perhaps? Is there a try/except that needs to be added? Is there a CPython 2.7 + Windows test?

**Comment by RonnyPfannschmidt** [comment]
the library does not monkeypatch, this is a missed try/except on my side

**Comment by henryiii** [comment]
Why is the 2.7 + Windows test turned off in the GitHub Actions? It exactly catches this error. Is there something else it was tripping over?

**Comment by henryiii** [comment]
Yes, looks like there are 8 errors after reverting the change (pulling the old copy back out, though I could also try just changing the try/except):

https://github.com/henryiii/setuptools_scm/runs/706613109?check_suite_focus=true

Wouldn't it be better to add xfails or fix these, rather than disabling the build completely? Do you know why these fail?

**Comment by RonnyPfannschmidt** [comment]
Windows short paths vs Windows long paths

**Comment by henryiii** [comment]
What's your suggestion for enabling the job?

**Comment by RonnyPfannschmidt** [comment]
A platform specific xfail

**Comment by henryiii** [comment]
4.1.0 is out, and fixed this issue for me. Thanks!
