### ISSUE TITLE
Lookup Error: Failed to install 4.1.0 

### ISSUE THREAD

**Issue by shirleylxie** [pypa/setuptools-scm#448]
Failed to install 4.1.0 on centos7.5
  ----------------------------------------
    cmd: pip install --no-binary :all: --only-binary :none: setuptools_scm
    ERROR: Exception:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 188, in _main
        status = self.run(options, args)
      File "/usr/lib/python2.7/site-packages/pip/_internal/cli/req_command.py", line 185, in wrapper
        return func(self, options, args)
      File "/usr/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 333, in run
        reqs, check_supported_wheels=not options.target_dir
      File "/usr/lib/python2.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 179, in resolve
        discovered_reqs.extend(self._resolve_one(requirement_set, req))
      File "/usr/lib/python2.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 362, in _resolve_one
        abstract_dist = self._get_abstract_dist_for(req_to_install)
      File "/usr/lib/python2.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 314, in _get_abstract_dist_for
        abstract_dist = self.preparer.prepare_linked_requirement(req)
      File "/usr/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 488, in prepare_linked_requirement
        req, self.req_tracker, self.finder, self.build_isolation,
      File "/usr/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 90, in _get_prepared_distribution
        with req_tracker.track(req):
      File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
        return self.gen.next()
      File "/usr/lib/python2.7/site-packages/pip/_internal/req/req_tracker.py", line 149, in track
        self.add(req)
      File "/usr/lib/python2.7/site-packages/pip/_internal/req/req_tracker.py", line 116, in add
        raise LookupError(message)
    LookupError: http://artifactory.**.com:8081/artifactory/api/pypi/pypi-repo/packages/50/37/645b31589ab702c212aba7fc85f9546120389175aa8e9bca5b012dd486da/setuptools_scm-4.1.0.tar.gz#sha256=e6cbfabe84b8dc84b7d543e79c28d5af917b0db9f2525264fb675fcebd6c0cf1 (from http://artifactory.**.com:8081/artifactory/api/pypi/pypi-repo/simple/setuptools-scm/) (requires-python:!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*,>=2.7) is already being built: setuptools_scm from http://artifactory.**.com:8081/artifactory/api/pypi/pypi-repo/packages/50/37/645b31589ab702c212aba7fc85f9546120389175aa8e9bca5b012dd486da/setuptools_scm-4.1.0.tar.gz#sha256=e6cbfabe84b8dc84b7d543e79c28d5af917b0db9f2525264fb675fcebd6c0cf1
ERROR: Command errored out with exit status 2: /usr/bin/python2 /usr/lib/python2.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-hhirRq/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i http://artifactory.**.com:8081/artifactory/api/pypi/pypi-repo/simple --trusted-host artifactory.**.com -- 'setuptools>=34.4' wheel 'setuptools_scm>=1.15' Check the logs for full command output. 
ERROR:Command errored out with exit status 1: /usr/bin/python2 /usr/lib/python2.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-Ioc2DG/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i http://artifactory.**.com:8081/artifactory/api/pypi/pypi-repo/simple --trusted-host artifactory.**.com -- 'setuptools>=34.4' wheel 'jaraco.windows; python_version < '"'"'3'"'"'' Check the logs for full command output.

**Comment by dyeager-recurve** [comment]
Can confirm I'm seeing the same

**Comment by dyeager-recurve** [comment]
pip download setuptools_scm --dest /tmp --exists-action i --no-binary :all:

LookupError: https://files.pythonhosted.org/packages/50/37/645b31589ab702c212aba7fc85f9546120389175aa8e9bca5b012dd486da/setuptools_scm-4.1.0.tar.gz#sha256=e6cbfabe84b8dc84b7d543e79c28d5af917b0db9f2525264fb675fcebd6c0cf1 (from https://pypi.org/simple/setuptools-scm/) (requires-python:!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*,>=2.7) is already being built: setuptools_scm from https://files.pythonhosted.org/packages/50/37/645b31589ab702c212aba7fc85f9546120389175aa8e9bca5b012dd486da/setuptools_scm-4.1.0.tar.gz#sha256=e6cbfabe84b8dc84b7d543e79c28d5af917b0db9f2525264fb675fcebd6c0cf1

**Comment by dyeager-recurve** [comment]
Confirmed I do not see this problem in a python3 environment, so that appears to be my issue.

**Comment by RonnyPfannschmidt** [comment]
this is a bug in pyproject.toml that was missed

**Comment by RonnyPfannschmidt** [comment]
the basic issue is that we build universal wheels on python3, and on python2 building wheels had a dependency lef over
