### ISSUE TITLE
Allow more tag name schemas

### ISSUE THREAD

**Issue by marc1n** [pypa/setuptools-scm#458]
In my corporation we are using Mercurial and this tag schema: `name_with_underscores_x-y-z`.
Currently, setuptools_scm (44.0.0) does not allow this schema because `setuptools_scm.hg.get_latest_normalizable_tag` looks for tags with dot only.

As a workaround we must monkey-patch `setuptools_scm.hg.get_latest_normalizable_tag`:

```python
def use_scm_version():
    def get_latest_normalizable_tag(root):
        cmd = ["hg", "log", "-r", "ancestors(.) and tag('re:\\-')", "--template", "{tags}\n"]
        outlines = do(cmd, root).split()
        if not outlines:
            return "null"
        tag = outlines[-1].split()[-1]
        return tag

    from setuptools_scm import hg
    from setuptools_scm.utils import do
    hg.get_latest_normalizable_tag = get_latest_normalizable_tag
    return {
        'tag_regex': r'\w+_(?P<version>\d+-\d+-\d+)'
    }


setup(
    use_scm_version=use_scm_version,
   # ...
)
```

This workaround works but it is producing a warning and not "dotted" version:
```console
$ python setup.py --version
/home/marcinr/venv/py37/lib/python3.7/site-packages/setuptools/dist.py:485: UserWarning: The version specified ('5-4-1.dev3+hd8efad3e67b9.d20200626') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  "details." % self.metadata.version
5-4-1.dev3+hd8efad3e67b9.d20200626
```

To silence this warning and produce "dotted" version we should monkey-patch another function:

```python
def use_scm_version():
    def get_latest_normalizable_tag(root, *args, **kwargs):
        cmd = ["hg", "log", "-r", "ancestors(.) and tag('re:\\-')", "--template", "{tags}\n"]
        outlines = do(cmd, root).split()
        if not outlines:
            return "null"
        tag = outlines[-1].split()[-1]
        return tag

    def tag_to_version(tag, *args, **kwargs):
        match = re.match(r'(\w+_)(\d+-\d+-\d+)', tag)
        if match:
            tag = match.group(1).replace('_', '-') + match.group(2).replace('-', '.')
            return orig_tag_to_version(tag, *args, **kwargs)

    from setuptools_scm import version
    from setuptools_scm import hg
    from setuptools_scm.utils import do
    import re
    orig_tag_to_version = version.tag_to_version
    hg.get_latest_normalizable_tag = get_latest_normalizable_tag
    version.tag_to_version = tag_to_version
    return {}


setup(
    use_scm_version=use_scm_version,
   # ...
)
```

This two monkey-patches make it works:
```
$ python setup.py --version
5.4.1.dev3+hd8efad3e67b9.d20200626
```

What do you think of adding to setuptools_scm a support for more tag name schemas (like ours `name_with_underscores_x-y-z`)?

I belive it will be sufficient to change some places only:
1. use `tag('re:{}'.format(config.tag_regex.pattern))` in `setuptools_scm.hg.get_latest_normalizable_tag` instead of fixed `tag('re:\\-')` and 
2. do extra `tagdict['version']` normalizing in `setuptools_scm.version.tag_to_version`: 
   ```python
   version = tagdict["version"].replace('-', '.').replace('_', '.')
   ```

**Comment by RonnyPfannschmidt** [comment]
Good call, i like the proposal, im happy to merge+release a pr on short notice

 it would be a while before I can get to implement it myself

**Comment by ziadmoubayed** [comment]
Now tag regex supports three named groups: `prefix`, `version` & `suffix`.
What about supporting more groups: `prefix`, `major`, `minor`, `patch` & `suffix`?

**Comment by RonnyPfannschmidt** [comment]
closing this for now - standard following versions are supported, fancy more tricky versions will have to wait for someone to come up with a reasonable implementation
