### ISSUE TITLE
Incorrect distance on dev versions

### ISSUE THREAD

**Issue by hannes** [pypa/setuptools-scm#459]
We use setuptools_scm in travis to upload to pip. I noticed that there seems to be some confusion with the distance computation. As an example, consider those two subsequent commits on our `master` branch:

https://github.com/cwida/duckdb/commit/f88905a2a4dec0828cbaf36f0b94e3daf158c7b2 [Travis Job](https://travis-ci.org/github/cwida/duckdb/jobs/702317173) Distance: 145
https://github.com/cwida/duckdb/commit/58afc8230dceca81ba67e5afe80b0b8f93c77293 [Travis Job](https://travis-ci.org/github/cwida/duckdb/jobs/702345961) Distance: 133

where f8 directly was before 58 in the history. One would assume now that the distance generated by setup tools is consistent. However, I get builds with a distance of 145 for the first job and 133 for the second. This seems very odd to me, when I run `setup.py install` only local clone, I get the correct dev version distance (`duckdb-0.1.10.dev70+gacd392bf8`).

Any help? Could this be related to cibuildwheel?

**Comment by hannes** [comment]
turns out it was the shallow clone which caused this. Fixed by adding 
```
git:
  depth: false
```
to travis config.

**Comment by RonnyPfannschmidt** [comment]
Thanks for the follow up
