### ISSUE TITLE
Use "release-branch-semver" with tags on release branches

### ISSUE THREAD

**Issue by pmeier** [pypa/setuptools-scm#460]
**Disclaimer** This might very well be a problem of my `git` workflow. If you think it is, feel free to close this. Still, I would appreciate comments / thoughts how to overcome this.

---

I wanted to use `setuptools_scm` together with `version_scheme=="release-branch-semver"`, but can't get it to work. Currently I use the following `git` workflow for my projects:

1. All development happens on the `master` branch
2. At a certain point I branch from `master` to `releases/<version>`
3. I perform some post-processing and commit them on this release branch
4. I create a tag `<version>` on the release branch

Afterwards I'll go back to the `master` branch and start over. 

Unfortunately, since there are post-processing commits between the branching from `master` and the tag `<version>`, no tags are found by `git describe`. 

They are however visible by `git tag`. Thus, instead of using `tag="0.0"` as the base tag, the following could be added

```python
out, _, ret = wd.do_ex("git tag")
if ret:
    tag = "0.0"
else:
    from .version import tags_to_versions
    tag = sorted(tags_to_versions(out.split("\n"), config))[-1]
```

above L110

https://github.com/pypa/setuptools_scm/blob/24c9d7579cd194d9d7982d1e2ad51c536611bf29/src/setuptools_scm/git.py#L107-L123

Using [`git merge-base`](https://git-scm.com/docs/git-merge-base) it might also be possible to determine the distance to the last common commit:

```python
cmd = f"git rev-list --count $(git merge-base HEAD $(git rev-parse {tag}))..HEAD"
out, _, ret = wd.do_ex(cmd)
distance = 0 if ret else int(out)
```

**Comment by RonnyPfannschmidt** [comment]
as far as i understood, https://github.com/pypa/setuptools_scm/blob/24c9d7579cd194d9d7982d1e2ad51c536611bf29/src/setuptools_scm/version.py#L273-L284 should implement that detail, unfortunately i am currently short on personal time and can't debug in detail

practically speaking, on the release branch `releases/$version` you should see versions as `${version}.dev${number}` and after tag you should see `$version`

if thats not the case its a bug

**Comment by pmeier** [comment]
~Huh, I never got there while debugging. I'll look into it.~

Indeed, while on a `releases/*` branch everything is working as expected. Let me try to clarify my problem. Suppose I have the following `git` tree

```
* ccb37c9 (tag: v0.2.0, releases/v0.2.0) postprocess
| * 22787ab (tag: v0.1.0, releases/v0.1.0) postprocess
| | * 8fc41cd (HEAD -> master) more work
| |/  
|/|   
* | 9aba6f0 work
|/  
* 8e4843c Initial commit
```
As you can see there is never a tag on the `master` branch. Thus, `git describe` in

https://github.com/pypa/setuptools_scm/blob/24c9d7579cd194d9d7982d1e2ad51c536611bf29/src/setuptools_scm/git.py#L107

always fails and the fallback `tag="0.0"` is used as base. 

Again, this might be problem of my `git` workflow. If you think it is, could you explain how to overcome this?

**Comment by RonnyPfannschmidt** [comment]
oh, in that case, put tags like  `v0.3.0.dev` on master to inform setuptools_scm about the new versions upcoming

**Comment by pmeier** [comment]
In retrospect that seems kinda obvious. Thanks for your time.

**Comment by RonnyPfannschmidt** [comment]
If its only oblivious in retrospective, better docs are needed

**Comment by pmeier** [comment]
Hey @RonnyPfannschmidt, I've slept over this and I'm no longer happy with the result. If I need to tag the `master` branch with the upcoming version, I'm almost back at the manual version management I was before. 

I don't see the point of having `releases/*` branches if I have to tag on the `master` branch. This might also be due to a misunderstanding of how `version_scheme=="release-branch-semver"` is intended. Could you explain the intention to me? I'm happy to send a PR to improve the documentation afterwards.

**Comment by RonnyPfannschmidt** [comment]
Setuptools_scm uses a strategy that is informed by direct history, so if release branches and tags never get merged back, there is nothing to work with

Disjointed common ancestors are really tricky to get right, in comparison all versions scheme's that merge to/ use one primary branch get most data right by git describe

**Comment by pmeier** [comment]
That indicates that I misunderstood `releases/*` branches in general. I'll do a little research and get back to you.

**Comment by pmeier** [comment]
Indeed it was a problem with my workflow. I never merged the `releases/*` branches back, but I can see now why one should do this. Thanks again for your patience.

**Comment by RonnyPfannschmidt** [comment]
Thanks for the follow up, I can understand how your work flow looks reasonable, a key issue with it is supporting tooling, not the structure itself
