### ISSUE TITLE
Getting Error as "ValueError: Zip does not support timestamps before 1980" while installing Setuptools-scm Pypi 

### ISSUE THREAD

**Issue by Rameshaaa** [pypa/setuptools-scm#464]
Describe the bug

Am working on Client machine where i don't have access for external severs. So i have to download the packages from Python websites and extract the zip-files and i have to install the packages in my machine by passing a command "python setup.py install in Command prompt. First two packages (Selenium and urllib3) working fine in my machine and setup also good.

I have try to install the Pytest Pypi but that requires setuptools-scm. So i downloaded the setuptools-scm packages and i try to to install it but Getting error as ValueError: Zip does not support timestamps before 1980.

Expected behavior

Setuptools-scm should be installed

To Reproduce

Download the setuptools-scm package from https://pypi.org/project/setuptools-scm/
Extract the zip-files and installing the setuptools-scm by passing python setup.py install
Observe that Getting error as ValueError: Zip does not support timestamps before 1980.
![Zip Error Python](https://user-images.githubusercontent.com/68278771/87520843-26ba4f80-c6a1-11ea-8e80-dfaf2e807088.png)

**Comment by RonnyPfannschmidt** [comment]
That's a user/environment error breaking setuptools

Please set up a surrounding time that zip can handle or use pre-build artifacts

**Comment by Rameshaaa** [comment]
> That's a user/environment error breaking setuptools
> 
> Please set up a surrounding time that zip can handle or use pre-build artifacts

How to setup surrounding time and where i can get the pre-build artifacts? Can please explain little briefly. I'm stuck with is package. Don't know how to resolve this

**Comment by RonnyPfannschmidt** [comment]
Sorry can't help deeper atm, I'm on mobile and have cold induced headaches + i haven't used Windows for programming in a decade, i don't see myself being in a position to help timely

I would suggest to fetch/install using a egg or a whl + finding Windows fluent python people for help on top of that

**Comment by Rameshaaa** [comment]
OK Thank you. Take Care. Meanwhile do you have the contacts for this issue?

**Comment by RonnyPfannschmidt** [comment]
Unfortunately there are none

**Comment by RonnyPfannschmidt** [comment]
closing as user error
