### ISSUE TITLE
Misleading error when git not installed

### ISSUE THREAD

**Issue by deliciouslytyped** [pypa/setuptools-scm#465]
The issue is similar to https://github.com/pypa/setuptools_scm/issues/278 , see https://github.com/pypa/setuptools_scm/issues/278#issuecomment-603160502, and also https://github.com/NixOS/nixpkgs/issues/41136#issuecomment-392332099

**Comment by RonnyPfannschmidt** [comment]
can  we conisder this one resolved by #339 ?

**Comment by deliciouslytyped** [comment]
Taking a quick peek at the patch I see things mentioning git is missing. I don't remember my original context, but at least superficially it looks like it's going in the right direction, so LGTM I guess?

**Comment by RonnyPfannschmidt** [comment]
thanks for the followup, i will consider this as resolved then

please open a new issue in case the original context comes up again and requires more action on the setuptools_scm side

**Comment by edthedev** [comment]
Had this problem today, but the issue was that `setup.py` was in a sub-folder.

Adding `use_scm_version={'root':'../..', ...}` solved our problem.

Adding this line to the error would have helped us: 

"Make sure `setup.py` is in the same folder as `.git` or use the `root` setting."

**Comment by RonnyPfannschmidt** [comment]
closing as duplicate of #279
