### ISSUE TITLE
ImportError: module 'setuptools_scm.hg' has no attribute 'FILES_COMMAND'

### ISSUE THREAD

**Issue by mofywong** [pypa/setuptools-scm#470]
Hi, I build this package(v3.1.0, v3.4.1, v4.1.2) in buildroot and has an error ImportError: module 'setuptools_scm.hg' has no attribute 'FILES_COMMAND'. I don't know what is wrong？
![image](https://user-images.githubusercontent.com/32129866/89505586-743b5f80-d7fc-11ea-8cd7-cd5935e45a7b.png)

**Comment by RonnyPfannschmidt** [comment]
@mofywong this seems to be a conflict with a existing old/outdated version that's also on `sys.path` and providing bad metadata

the entry point for the mercurial file finder changed quite a while ago and is in a specific file finder module

**Comment by mofywong** [comment]
> @mofywong this seems to be a conflict with a existing old/outdated version that's also on `sys.path` and providing bad metadata
> 
> the entry point for the mercurial file finder changed quite a while ago and is in a specific file finder module

Thanks, I clear the environment and recompile success.
