### ISSUE TITLE
support installs from GitHub release tarballs

### ISSUE THREAD

**Issue by jab** [pypa/setuptools-scm#477]
I'm using setuptools_scm in my project, and a user just opened an issue because he could not install from a GitHub release tarball: jab/bidict#115

I see in https://github.com/pypa/setuptools_scm/blob/master/CHANGELOG.rst#v400
> Add `parentdir_project_version` to support installs from GitHub release tarballs.

But according to https://github.com/pypa/setuptools_scm/search?q=parentdir_project_version, CHANGELOG.rst is the only file that contains `parentdir_project_version` in this repo. I dug a bit through git history and also found no other mention of `parentdir_project_version` nor of adding support for installing from GitHub release tarballs.

The error message given by setuptools_scm when you try to install from a GitHub release tarball indicates that this is not currently supported, but that contradicts the changelog. Please let me know if I'm missing something, and if there is in fact a way for packages using setuptools_scm to be installable from GitHub release tarballs. Thanks:)

**Comment by RonnyPfannschmidt** [comment]
closing as fixed by https://pypi.org/project/setuptools-scm-git-archive/

**Comment by RonnyPfannschmidt** [comment]
#410 implemented this in a recent release

**Comment by jab** [comment]
Thanks for updating this issue! Taking a look at this now and immediately noticed a typo in the documentation of this feature. The changelog still refers to it as  `parentdir_project_version` but the setting is actually `parentdir_prefix_version`.

**Comment by jab** [comment]
And just to make sure, if I use the `parentdir_prefix_version` feature, there is no need to use the `setuptools-scm-git-archive` plugin, right?

**Comment by RonnyPfannschmidt** [comment]
correct, i need to fix the name missmatch
