### ISSUE TITLE
Warning "setuptools_scm functionality is degraded" over stdout

### ISSUE THREAD

**Issue by HolgerPeters** [pypa/setuptools-scm#48]
The warning "setuptools_scm functionality is degraded" in setuptools_scm/setuptools_scm/version.py is printed to stdout, I rather think that it should rather be written to stderr, so that shell scripts will not break due to unexpected content in stdout.

Would `warnings.warn(....)` be suitable?

**Comment by RonnyPfannschmidt** [comment]
`distutils.log.warn` seems to be the correct tool to use
