### ISSUE TITLE
AssertionError: cant parse version XYZ

### ISSUE THREAD

**Issue by johentsch** [pypa/setuptools-scm#488]
I use `pip install -e .` to test installing my library locally. All of a sudden, this did not work anymore and apparently the error has to do with GitHub tags: The setup is failing since the development branch I'm building from contains a tag from the `docs` branch which is not a among the version tags of the library itself (taking this issue's title, the tag would be XYZ). It looks like this is causing the problem because the error output contains the warning thrown at [this line of version.py](https://github.com/pypa/setuptools_scm/blob/54e7879af5429baf1ce52b489bb3613939c95baa/src/setuptools_scm/version.py#L88). In the next step this leads to the failing assert [at line 212](https://github.com/pypa/setuptools_scm/blob/54e7879af5429baf1ce52b489bb3613939c95baa/src/setuptools_scm/version.py#L212). A quick fix for me was to comment out this assert. This leaves me with an install of my library which says to be version `'None.post0.dev5-geb8c62e'`.

Interestingly, during the process of trying different environments and versions, I needed to apply this change to three different places, apparently because I am using PyScaffold. The assert was standing in two different lines, which speaks for disparate versions. The current version installed via `pip` in the conda environment `install` is 4.1.2.

```
~/my_library/.eggs/PyScaffold-3.2.3-py3.8.egg/pyscaffold/contrib/setuptools_scm/version.py (l. 204)
~/anaconda3/envs/install/lib/python3.8/site-packages/pyscaffold/contrib/setuptools_scm/version.py (l. 204)
~/anaconda3/envs/install/lib/python3.8/site-packages/setuptools_scm/version.py (l. 208)
```

**Comment by RonnyPfannschmidt** [comment]
I suggest to configure a git describe command to sort this out temporarily

**Comment by RonnyPfannschmidt** [comment]
without more debug infos i have no idea whats up, closing this for now,
im happy to reopen of output with `SETUPTOOLS_SCM_DEBUG=1` is provided
