### ISSUE TITLE
setup.py develop and console_scripts

### ISSUE THREAD

**Issue by rouge8** [pypa/setuptools-scm#49]
When installing a package with `python setup.py develop` or `pip install -e .`, setuptools creates a script with the version hardcoded, e.g.

``` python
#!/Users/rouge8/.virtualenvs/tmp-902d747a861cbe3/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'pytest==2.7.3.dev402+ng06a70b6','console_scripts','py.test'
__requires__ = 'pytest==2.7.3.dev402+ng06a70b6'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('pytest==2.7.3.dev402+ng06a70b6', 'console_scripts', 'py.test')()
    )
```

You can make changes to files and see them reflected in the console script (e.g. add a `print` statement), but once you commit, setuptools continues running the old version. Any ideas on a workaround other than reinstalling after every commit?

**Comment by RonnyPfannschmidt** [comment]
This is a setuptools bug that should be fixed in setuptools (basically setuptools should use simplified scripts for develop installs)

It's on my extended to do, it would be nice if someone with time would step up

**Comment by untitaker** [comment]
Any reason why that script ever contains version info at all?

On 1 September 2015 07:55:07 CEST, Ronny Pfannschmidt notifications@github.com wrote:

> This is a setuptools bug that should be fixed in setuptools (basically
> setuptools should use simplified scripts for develop installs)
> 
> It's on my extended to do, it would be nice if someone with time would
> step up
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/pypa/setuptools_scm/issues/49#issuecomment-136593537

## 

Sent from my phone. Please excuse my brevity.

**Comment by RonnyPfannschmidt** [comment]
@untitaker because setuptools due to legacy assumes encapsulated egg installs without site-packages and uses very exact version information

perhaps it makes sense to teach pip install -e to use the simple pip scripts as well
