### ISSUE TITLE
Should the write_to file be included in the sdist by default?

### ISSUE THREAD

**Issue by angelo-peronio** [pypa/setuptools-scm#498]
Packaging newbie here.

Using `setuptools_scm`, I see that `my_package.egg-info/SOURCES.txt` does not include the `write_to` file unless I explicitly mention it in `MANIFEST.in`.

I guess that the `write_to` file is usually imported to provide `my_package.__version__`.

Would it be sensible for `setuptools_scm` to include the `write_to` file in the sdist by default?
Or maybe mention in the documentation the necessity of including it in `MANIFEST.in`.

**Comment by RonnyPfannschmidt** [comment]
It's not required, in the sdist the source of truth is the PKG-INFO file

**Comment by angelo-peronio** [comment]
Sorry for the late answer.

My point: if in my `__init__.py` I have something like

```python
from .version import version as __version__
```

and the `write_to` file `version.py` is not there because it was not included in `MANIFEST.in`, I have a problem.

**Comment by RonnyPfannschmidt** [comment]
That's ok, setuptools_scm works for sdists

**Comment by RonnyPfannschmidt** [comment]
to conclude, the `write_to` file does not have to be included in the sdist
