### ISSUE TITLE
Shipping mercurial remnants

### ISSUE THREAD

**Issue by SnarkBoojum** [pypa/setuptools-scm#50]
I notice that the tarballs contain .hgignore .hgtags, which is strange since the project is now on git : perhaps those file can be removed from the repository?

**Comment by RonnyPfannschmidt** [comment]
thanks for the reminds, i missed those

**Comment by SnarkBoojum** [comment]
... and I don't know how github generates tarballs, but probably .gitignore shouldn't find its way in them... :-/

**Comment by untitaker** [comment]
AFAIK you can't affect the way _GitHub_ generates its tarballs which is why you should use the ones from PyPI.

**Comment by jaraco** [comment]
.hgignore may be relevant for those of us still using Mercurial as their Git client; I'm unsure though. If you remove them and it's a problem, I'll let you know.

**Comment by RonnyPfannschmidt** [comment]
the scm artifacts are also in the sdists, thats a detail of the file finders thats problematic

**Comment by RonnyPfannschmidt** [comment]
undesired scm artifacts should be removed via MANIFEST.in
