### ISSUE TITLE
Port `iter_matching_entrypoints` to `importlib.metadata`

### ISSUE THREAD

**Issue by flying-sheep** [pypa/setuptools-scm#513]
When calling `_version_from_entrypoints` → [`iter_matching_entrypoints`](https://github.com/pypa/setuptools_scm/blob/74b17470912c83e658cfd18e66eec654be87fcd7/src/setuptools_scm/discover.py), we should use `importlib.metadata` instead of `pkg_resources`, as `pkg_resources` isn’t the standard way to do this, and is also buggy in this context (see pypa/setuptools#2531)

The changes required would be pretty minimal:

requirements:
```py
importlib_metadata; python_version < "3.8"
```

code:
```py
try:
    from importlib.metadata import entry_points
except ImportError:
    from importlib_metadata import entry_points
```

**Comment by RonnyPfannschmidt** [comment]
i consider this low prio as the issue can't affect setuptools_scm in the intended usage scsenario as of now

additionally this poses a issue as i don't really want to add the extra dependency for old pythons

so i may decide to just leave it be until the pythons that don't have importlib_metadata no longer need to be supported

**Comment by flying-sheep** [comment]
Can you please elaborate on why that isn’t the intended usage scenario? Your [readme says](https://github.com/pypa/setuptools_scm#programmatic-usage):

> In order to use `setuptools_scm` from code that is one directory deeper than the project's root, you can use:
> 
> ```py
> from setuptools_scm import get_version
> version = get_version(root='..', relative_to=__file__)
> ```

We do exactly that, and the setuptools maintainers explicitly ask you to no longer use `pkg_resources`.

If you want to keep it, in order to avoid hard-to-debug breakage, please create a new `WorkingSet` and use that instead of the global one.

> additionally this poses a issue as i don't really want to add the extra dependency for old pythons

why is that?

**Comment by RonnyPfannschmidt** [comment]
In the use case for setuptools_scm a stale workingset is typically not a issue, in particular with more modern tools around,
However additional dependencies make packaging more painful

That Being said, if a pr is submitted to use importlib on pythons that support it, im happy to merge and release

**Comment by jaraco** [comment]
Thanks Ronny. I support this initiative. Even though `pkg_resources` isn't deprecated, I am working toward deprecation and discouraging its use. I'll be happy to shepherd these changes as well. Thanks flying-sheep for the effort.

**Comment by flying-sheep** [comment]
> That Being said, if a pr is submitted to use importlib on pythons that support it, I’m happy to merge and release

Entirely possible!

Are you actually importing anything from setuptools apart from `pkg_resources.iter_entry_points`? This might actually *reduce* the amount of runtime dependencies.

**Comment by flying-sheep** [comment]
`pkg_resources` is now [officially deprecated](https://setuptools.readthedocs.io/en/latest/pkg_resources.html):

> Use of `pkg_resources` is discouraged in favor of [importlib.resources](https://docs.python.org/3/library/importlib.html#module-importlib.resources), [importlib.metadata](https://docs.python.org/3/library/importlib.metadata.html), and their backports ([resources](https://pypi.org/project/importlib_resources), [metadata](https://pypi.org/project/importlib_metadata)). Please consider using those libraries instead of pkg_resources.

@RonnyPfannschmidt what’s the plan?

**Comment by RonnyPfannschmidt** [comment]
given that setup_requires usage is now deprecated, lets add it for the next feature release

**Comment by flying-sheep** [comment]
Okay! Since #526 is merged, this should be very simple. I updated #514

**Comment by flying-sheep** [comment]
I just noticed how much this step improved import times, so this was a good move!

```console
$ PYTHONPROFILEIMPORTTIME=1 python -c 'import setuptools_scm' 2>! importprofile.log
$ tuna importprofile.log
```

before:

![before](https://user-images.githubusercontent.com/291575/136566954-764e62e7-b427-4a8c-bfa9-7efb467cf1c3.png)

after:

![after](https://user-images.githubusercontent.com/291575/136566278-a7204c9c-3d57-4889-b207-b576c2c5e611.png)
