### ISSUE TITLE
Specify version in case all strategies fail

### ISSUE THREAD

**Issue by tdegeus** [pypa/setuptools-scm#522]
I'm using 

```python
setup(
    name = 'mylib',
    packages = find_packages(),
    use_scm_version = {'write_to': 'mylib/_version.py'},
    setup_requires = ['setuptools_scm'],
)
```

which works brilliantly.

However, in distributing my code on conda-forge I came across the limitation that *setuptools_scm* fails from a GitHub archive. However, in that case I know the version, and have access to it through an environment variable. 

So the question/issue: how can I supply a version-string, while still using *setuptools_scm* to write a version file, when I know that *setuptools_scm* will simply fail.

------

I was thinking about something like this:

```python
from setuptools import setup
from setuptools import find_packages
from os import environ

def version_scheme(version):
    ret = environ.get('PKG_VERSION')
    if ret is not None:
        return ret
    from setuptools_scm.version import guess_next_dev_version
    return guess_next_dev_version(version)

version_info = {
    'write_to': 'shelephant/version.py',
    "version_scheme": version_scheme}

setup(
    name = 'mylib',
    packages = find_packages(),
    use_scm_version = version_info)
```

But:

* I wasn't sure that it would work?
* Started wondering if there is not an 'official' way, or whether there shouldn't be if there isn't?

**Comment by RonnyPfannschmidt** [comment]
In the readme we have a link to a plugin that solves a limited part of the problem

**Comment by RonnyPfannschmidt** [comment]
Also there is a fallback version configuration option

**Comment by RonnyPfannschmidt** [comment]
Sorry for the lack of links, I'm on mobile

**Comment by RonnyPfannschmidt** [comment]
@tdegeus see https://github.com/pypa/setuptools_scm#configuration-parameters - the `fallback_version` option

**Comment by tdegeus** [comment]
Thanks @RonnyPfannschmidt ! So do I understand correctly if I state that a `setuptools_scm` version cannot be overwritten as such, but it can be provided with a version if none of the strategies work? To me, this seems that the following tricky situation can occur:
1. The user shallow clones the repo, `setuptools_scm` warns, but still comes up with something.
2. The user knows that things will go wrong, happens to know the version, but cannot overwrite `setuptools_scm`'s best shot.

Is that correct?

**Comment by RonnyPfannschmidt** [comment]
There always is the pretend version env vars that always win

**Comment by tdegeus** [comment]
Great! That I did not find, and is indeed the solution!

**Comment by RonnyPfannschmidt** [comment]
closing as answered
