### ISSUE TITLE
Question: what are the possible types for the default generated versions file?

### ISSUE THREAD

**Issue by henryiii** [pypa/setuptools-scm#527]
I'm adding `version.pyi` to one of my projects so that mypy doesn't complain when this is missing. But what are the possible types for `version_tuple` produced here?  I'm using this, based on the two things I've seen so far:

```python
version: str
version_tuple: tuple[int, int, int] | tuple[int, int, int, str, str]
```
Are there any other lengths of tuple possible? (4, 6, etc)

(would have made this a Discussion if they were activated, as it doesn't require code changes, just a question).

**Comment by RonnyPfannschmidt** [comment]
i haven't speced that out actually - i believe an if typechecking can be included in the release that drops python < 3.6
i think its a thing that should trigger a code change :)

**Comment by henryiii** [comment]
This is asking about what could possibly go into `version_tuple` so a user package can add a `version.pyi` to sit alongside of a generated version.py file, not about `setuptools_scm` itself (which would be the scope of #501).

**Comment by henryiii** [comment]
For an example of a "good" Python 2 drop, see https://github.com/scikit-hep/boost-histogram/compare/v0.13.0...v1.0.0 - changed 2K lines, enabled full type support instead of halfway type checking, and still ended up with fewer lines of code. :)

(pyupgrade via pre-commit was a way to get a nice head start ;) )

**Comment by RonnyPfannschmidt** [comment]
@henryiii i was thinking of altering the template of the version file to be typed
