### ISSUE TITLE
v6 breaks on Centos7 due to older git

### ISSUE THREAD

**Issue by GertBurger** [pypa/setuptools-scm#537]
Hi,

Changes between v5 and v6 results in downstream packages failing to build/install on Centos7, e.g. black

Centos7 seems to come with git 1.8.3.1 which doesn't support the `%cI` format as used by `get_head_date()` resulting in the following error when using pre-commit+black:
```
File "/tmp/pip-build-env-y421rvu8/overlay/lib/python3.7/site-packages/setuptools_scm/git.py", line 124, in parse
        node_date = wd.get_head_date() or date.today()
      File "/tmp/pip-build-env-y421rvu8/overlay/lib/python3.7/site-packages/setuptools_scm/git.py", line 64, in get_head_date
        return datetime.strptime(date_part, r"%Y-%m-%d").date()
      File "/opt/app/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
        tt, fraction, gmtoff_fraction = _strptime(data_string, format)
      File "/opt/app/lib/python3.7/_strptime.py", line 359, in _strptime
        (data_string, format))
    ValueError: time data '%cI' does not match format '%Y-%m-%d'
```

Installing either a newer git or `setuptools_scm~=5.0` works around the issue.

**Comment by PatrikHlobil** [comment]
Hi, we have the same issue here. Unfortunately, we cannot pin the version to 5.x because we use pre-commit which automatically creates a temporary virtualenv where it installs the current version of setuptools_scm.

**Comment by alexprengere** [comment]
I confirm this issue and the proposed fix to pin to 5.x, I guess this is going to break quite a few builds 😄

**Comment by pelson** [comment]
Tracking this one too. It is awkward to pin because ``setuptools_scm`` is typically declared as a build dependency, so it effectively means re-releasing an sdist. :cry:

**Comment by RonnyPfannschmidt** [comment]
Yikes, will fix that when getting back to the computer

**Comment by pelson** [comment]
I think I've got confused. I can't reproduce when installing from sdist, only from source (as one would hope). That dramatically reduces the issue's impact, and I'm happy to report my error.

**Comment by RonnyPfannschmidt** [comment]
An sdist won't reach to git, stoneage git is a problem 👺

**Comment by petterreinholdtsen** [comment]
We are into this problem too, trying to pull in https://github.com/unioslo/pybofh/ as a dependency using pip building on RHEL 7 with git version 1.8.3.1-23.  The output from "git log -n 1 HEAD --format=%cI" is simply "%cI", which break the build.

**Comment by RonnyPfannschmidt** [comment]
bugfix is in test, release soon

**Comment by RonnyPfannschmidt** [comment]
the release pipeline for 6.0.1 has startedand includes a fix

**Comment by alexprengere** [comment]
I confirm 6.0.1 fixes the issue on CentOS 7. Thanks @RonnyPfannschmidt for the fast fix!

**Comment by PatrikHlobil** [comment]
Fix also works here. Thanks a lot for your superquick fix.
