### ISSUE TITLE
write_to creates file even if setup.py called with --help

### ISSUE THREAD

**Issue by cc-stjm** [pypa/setuptools-scm#545]
Using setuptools_scm with setup.py & the "write_to" option results in the file being written even when you call 

`python setup.py --help`

This feels like it shouldn't happen - instinctively I'd expect calling with --help to be a non-destructive action

**Comment by RonnyPfannschmidt** [comment]
I understand the sentient, unfortunately im not aware of a way to integrate it into setuptools in a more controlled manner

If there was im happy to add it
