### ISSUE TITLE
GPG Signature causes: Preparing wheel metadata: finished with status 'error'

### ISSUE THREAD

**Issue by imor-de** [pypa/setuptools-scm#548]
**By creating this issue, I want to create awareness about the following behavior:** 

I came across the following Error: pre-commit fails when setting up the black environment.

```
          ...
          File "/private/var/folders/zs/ydvqpbz95pb3_l60_2vk2k0h0000gn/T/pip-build-env-p1l6kgqx/overlay/lib/python3.9/site-packages/setuptools_scm/git.py", line 67, in get_head_date
            return datetime.strptime(date_part, r"%Y-%m-%d").date()
          File "/usr/local/opt/asdf/installs/python/3.9.2/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
            tt, fraction, gmtoff_fraction = _strptime(data_string, format)
          File "/usr/local/opt/asdf/installs/python/3.9.2/lib/python3.9/_strptime.py", line 349, in _strptime
            raise ValueError("time data %r does not match format %r" %
        ValueError: time data 'gpg: Signature made Wed Aug 26 17:50:45 2020 CES' does not match format '%Y-%m-%d'
```
(see [Black Issue 2059](https://github.com/psf/black/issues/2059))

With help from ichard26, I solved the problem by setting `log.showSignature = False` in my gitconfig.

In my optinion it is a good idea to avoid this problem in the future, by making the library independed of showSignature.

**Comment by RonnyPfannschmidt** [comment]
at first glance its not clear if there is a easy opt-out

i wont get to experiment with this soon, im happy to merge a pr that fixes this and contains a test

**Comment by ichard26** [comment]
Howdy, the triager from the original issue here. Yeah it appears that `--no-show-signature` doesn't exist which is unfortunate since it would make for a very easy fix :(

I do have this patch which does the fix the issue, but I'm not sure whether you'd like to accept it or not. There's no tests since I have zero clue. I'm planning on mocking `do_ex` or similar to return hard-coded responses that emulate output with `--show-signature` passed since setting up GPG with keys ready to test and then creating a signed commit/tag seems a ... bit too complicated. BUT that doesn't feel like a "proper" test ...

```diff
diff --git a/src/setuptools_scm/git.py b/src/setuptools_scm/git.py
index c7f301b..108811f 100644
--- a/src/setuptools_scm/git.py
+++ b/src/setuptools_scm/git.py
@@ -55,11 +55,14 @@ class GitWorkdir:
         return branch
 
     def get_head_date(self):
-        timestamp, err, ret = self.do_ex("git log -n 1 HEAD --format=%cI")
+        out, err, ret = self.do_ex("git log -n 1 HEAD --format=%cI")
         if ret:
-            trace("branch err", timestamp, err, ret)
+            trace("branch err", out, err, ret)
             return
         # TODO, when dropping python3.6 use fromiso
+        # Use the last line in output just in case there is GPG signature
+        # information for some reason.
+        timestamp = out.splitlines()[-1]
         date_part = timestamp.split("T")[0]
         if "%c" in date_part:
             trace("git too old -> timestamp is ", timestamp)
```

**Comment by pdecat** [comment]
That's how versioneer does it: https://github.com/python-versioneer/python-versioneer/pull/222/files#diff-ac576017e241195d395f0201c1d14f356c432b9cd03318fb0c4b890e978a9276R45

**Comment by jap** [comment]
Maybe this doesn't help directly, but my local version of git does support `--no-show-signature` (git 2.31.1).

**Comment by RonnyPfannschmidt** [comment]
The output has to be identified and handled in setuptools_scm

**Comment by wbolster** [comment]
the simplest fix is to avoid using any git user config, since it can have almost arbitrary effects on git output.

this can be achieved by setting `HOME=/nonexistent` when running `git` commands.

**Comment by RonnyPfannschmidt** [comment]
That's potentially required for a subset of the commands

I. May have some time by the end of the week

**Comment by flit** [comment]
Is there a schedule for the next release that will include the fix for this issue?
