### ISSUE TITLE
Running tests raises TypeError exceptions about LocalPath

### ISSUE THREAD

**Issue by SnarkBoojum** [pypa/setuptools-scm#55]
With Python 2, I get errors like this:
TypeError: coercing to Unicode: need string or buffer, LocalPath found

With Python 3, those become:
TypeError: Can't convert 'LocalPath' object to str implicitly

This is just by calling pytest from the source toplevel directory.

**Comment by SnarkBoojum** [comment]
Sigh... I have setuptools-scm 1.7.0 installed and that was what was used for the tests... sorry for the noise.

**Comment by nicolinux** [comment]
@SnarkBoojum I have the same issue - can you elaborate on the setuptools-scm problem?

**Comment by RonnyPfannschmidt** [comment]
use `python setup.py develop`?

**Comment by nicolinux** [comment]
No, not really.
My problem was that I tried to use the `tmpdir` fixture and pass it directly without converting it to a string.
