### ISSUE TITLE
weird version_tuple when hardcoding version_scheme

### ISSUE THREAD

**Issue by nschloe** [pypa/setuptools-scm#557]
I would like to use setuptools_scm to append a git sha if applicable, and in any case use a hard-coded version number as base (instead of a Git tag). To this end, I use the `"version_scheme"`:
```python
      use_scm_version={
          "version_scheme": lambda _: "4.1.0",
          "write_to": "foobar/version.py"
      }
```
The command
```
python3 setup.py --version
```
correctly produces
```
4.1.0+g4ac9d2c
```
but the `version_tuple` in `version.py` is weird:
```python
version = '4.1.0+g4ac9d2c'
version_tuple = (4, 1, '0+g4ac9d2c')
```
I would have expected
```python
version_tuple = (4, 1, 0, 'g4ac9d2c')
# or perhaps
version_tuple = (4, 1, 0, '+g4ac9d2c')
```
What's going wrong here?

**Comment by RonnyPfannschmidt** [comment]
https://github.com/pypa/setuptools_scm/blob/b366d8b3faebd9ef276305854847e9fb4d1c3576/src/setuptools_scm/__init__.py#L87-L94 is incomplete, its a bug

**Comment by RonnyPfannschmidt** [comment]
this should use packaging.version to pick things apart correctly
