### ISSUE TITLE
Can not change `.git` entrypoint for `setuptools_scm.files_command`

### ISSUE THREAD

**Issue by con-f-use** [pypa/setuptools-scm#567]
I'm trying to overwrite the file finder for git repositories in setuptools_scm, but my new entrypoint is ignored and the stock one from setuptools_scm is used. Here is a minimal example as to what I did:

```
$ cat setup.py
import setuptools

setuptools.setup(
    name="scmgit",
    version="1.0",
    entry_points="""
        [setuptools_scm.files_command]
        .git = scmgit:my_git_find_files
    """,
    install_requires=[
        "setuptools_scm",
    ],
    packages=setuptools.find_packages("src"),
    package_dir={"": "src"},
)

$ cat src/scmgit/__init__.py
import logging

def my_git_find_files(path=""):
    logging.warning("my_git_find_files path: %s", path)
    return []

$ pip install -e ./

$ python -c 'from pkg_resources import iter_entry_points as i; print(list(i("setuptools_scm.files_command")))'
[EntryPoint.parse('.git = setuptools_scm.file_finder_git:git_find_files'), EntryPoint.parse('.hg = setuptools_scm.file_finder_hg:hg_find_files'), EntryPoint.parse('.git = scmgit:my_git_find_files')]
```

Which seems the first (stock) entrypoint to still get called by setuptools_scm.

**Comment by RonnyPfannschmidt** [comment]
as far as im aware of there is no easy way to fix this for entrypoints in general

as far as i understand you want a opt-out - #561 seems like a option

im happy to review/merge/release a change for setuptools_scm to implement opt-out

**Comment by con-f-use** [comment]
In my example I want to include no file, but that just for testing if my use case is at all viable. 
In real-life, I want to filter certain files out and do some more elaborate manipulations for our company-internal version of setuptools, which would require overwriting the hook. For example, I don't want to include a few optional large files that are in some of our package repos in order to prevent an unnecessary huge download-size for the resulting package artifacts. But that is not all.

Digging deeper into the code, a workaround might be the following  in integrations.py:
```python
def find_files(path=""):
    # Note the next line!
    for ep in reversed(list(iter_entry_points("setuptools_scm.files_command"))):
        command = ep.load()
        if isinstance(command, str):
            # this technique is deprecated
            res = do(ep.load(), path or ".").splitlines()
        else:
            res = command(path)
        if res:
            return res
    return []
```
i.e. reversing the order for the file_command entrypoints. But I suspect that the order in which entrypoints are listed by `iter_entrypoints` is not that reliable.

Another similar method would be to check if there is another entrypoint of the same name (in my example we have two named `.git`) and then taking the one not part of setuptools_scm.

**Comment by RonnyPfannschmidt** [comment]
my suggestion then would be to just monkeypatch setuptools_scm in the test?

the use-case isn't clear to me, typically manifest is used to filter (as thats what setuptools uses)

**Comment by con-f-use** [comment]
Yes, but manifest requires to explicitly list files to exclude/include. I want an automatic pre-filtering of certain files so they don't have to be manually listed.

Let's say, I want to prevent the inclusion of files over 10 GB or files that have "key" or "secret" in their name or something, or I don't know, files older than 100 days or files with a number divisible by 13 in them, because I'm supersticious :rofl: . You get my drift? :wink: 

I realize that is convenience functionality and there are other ways to achieve this. Bottom line is, the way it is now, the thing being a hook at all is not useful, if you can't change the hook. Right?

**Comment by RonnyPfannschmidt** [comment]
My firs recommendation would be to hack your custom setuptools to add that

Im in the boat of just using it as is

**Comment by con-f-use** [comment]
Yeah, I fully understand. I think, I will just do an override on both:

```
    entry_points="""
        [setuptools_scm.files_command]
        .git = scmgit:my_git_find_files

        [setuptools.file_finders]
        setuptools_scm = scmgit:my_find_files
    """,
```

Fully aware that this is dangerous, because when people have my custom package `scmgit` installed and use `setuptools_scm`, it will lead to those files excluded with EVERY use of setuptools.

Just keep in mind, that from a correctness point of you, one would expect to be able to just override `setuptools_scm.files_command.git` without that being ignored. Maybe a more elegant solution will come to one of us in the future.

**Comment by aaraney** [comment]
On a related to note, I am unable to override the `.git` `setuptools_scm.parse_scm` entry point.
