### ISSUE TITLE
Question: Is there a simple way to make this work with github zip/tar where the version isn't in the tag name?

### ISSUE THREAD

**Issue by fiendish** [pypa/setuptools-scm#569]
My situation is that because github doesn't have a shortcut for always pointing at the latest release, I always create two tags for new release versions, one for the actual semver version and another one called "latest-release" that points at the same commit hash. That way I can say to e.g. "grab blahblah@latest-commit" and it will always pick up the last released tag without needing to change any scripts/code/instructions. 

Now this works _great_ using the standard `pip install git+https://github.com/org/repo.git@latest-release` which then installs using the semver tag.

But that clones the entire repo history which can be annoyingly slow for long histories, so then someone wants to instead use `https://github.com/org/repo/archive/refs/tags/latest-release.zip` which we know breaks setuptools_scm because of missing repo metadata.

But in this case using parentdir_prefix_version doesn't work because stripping the repo prefix just leaves you with "latest-release" instead of the last semver tag while the _actual_ version is that semver tag which is of course still hiding up in the repo.

Do you have any recommendation for how to handle this?

**Comment by RonnyPfannschmidt** [comment]
currently not, git is simply broken and incapable there, this hasn't been fixed in a decade  now, i don't think they ever will

there are some ideas to support fetching the data in some way, but nobody put in the time to make this work nicely (one idea could be to put annotations onto github commmits)

**Comment by RonnyPfannschmidt** [comment]
the typical suggestion is to - upload your releases to pypi or a local variant , use `pip install -U`

**Comment by RonnyPfannschmidt** [comment]
modern versions support `.git_archival` files as metadata source
