### ISSUE TITLE
Treat v-prefixed branch as release for release-branch-semver?

### ISSUE THREAD

**Issue by QuLogic** [pypa/setuptools-scm#571]
The `release-branch-semver` scheme appears to match what we do in Matplotlib pretty closely. Since we make tags like `v1,2,3`, our branches are named like `v1.2.x`. This unfortunately is not treated as a release branch because of the `v` prefix in the branch name, even though the `v` prefix is dropped from the tag.

Now, we've never made a release branch with `setuptools-scm`, so this is something we could change, but it'd require updating a bunch like docs, CI, etc.

Does this make sense to handle this prefixing in the `release-branch-semver`?

**Comment by RonnyPfannschmidt** [comment]
at first glance yes, it needs a little investigation, but it seems like something that should be added/made easy

**Comment by RonnyPfannschmidt** [comment]
@QuLogic based on https://github.com/pypa/setuptools_scm/blob/fd0559d2e2efb4a2b1c74780827fc594a7cafe7d/src/setuptools_scm/version.py#L281-L285 - this totally should be a supported new case - it needs a test-case and a normalization step

i cant add it myself swiftly, but i can give some hints for a implementation + run a release

**Comment by QuLogic** [comment]
Yes, it looks pretty straightforward, but if you have any hints, I can implement it myself.
