### ISSUE TITLE
Feature request discussion: generate AUTHORS and CHANGELOG from scm

### ISSUE THREAD

**Issue by evrardjp** [pypa/setuptools-scm#574]
Hello folks,

First, setuptools_scm is great! It's highly convenient.

One of the things I find missing is the ability to generate a CHANGELOG from git, or a AUTHORS file from git.
I feel those features could be opt-in, and match well the scope of setuptools_scm. What do you think?

**Comment by RonnyPfannschmidt** [comment]
i agree for the authors file

for changelog i want to add a towncrier integration and a Simple changelog style for git/mr based changelogs

**Comment by RonnyPfannschmidt** [comment]
as im reiterating the issue tracker, im closing this one as out of scope, should be a own setuptools plugin
