### ISSUE TITLE
The reason to avoid including git_archive plugin into this package no longer applies

### ISSUE THREAD

**Issue by eli-schwartz** [pypa/setuptools-scm#578]
cf. https://github.com/Changaco/setuptools_scm_git_archive/issues/17

I opened a discussion on the git mailing list back in January: https://public-inbox.org/git/4f65f02c-1d16-aa2c-3e7b-28d807b9ebe9@archlinux.org/T/

As a result, the git 2.32 release notes from yesterday, mention this:
 * "git log --format='...'" learned "%(describe)" placeholder.

Full documentation on the format:
https://git-scm.com/docs/git-log/2.32.0#Documentation/git-log.txt-emdescribeoptionsem

It's now possible to do this:

```
$ cat .git_archival.txt
describe-name: $Format:%(describe)$
```

As such, Git/Github now (or will as soon as Github upgrades the version of git used by the server) support "sufficient metadata for untagged/followup commits", and a consistent UX can be achieved.

**Comment by RonnyPfannschmidt** [comment]
AWESOME, THANK YOU FOR LETTING LETTING ME KNOW

I have been waiting for this for about a decade

**Comment by eli-schwartz** [comment]
Ha, well, I was sort of obligated to tell you :) considering that I independently came to the conclusion setuptools_scm_git_archive was insufficient if it could not do git describe, and having used (and had trouble with) github archives using setuptools_scm before, I selfishly wanted to be able to build them out of the box... I only realized this morning while submitting tickets that this was a documented shortcoming/wish item.

I'm delighted I was able to make your day (decade?). :D

**Comment by webknjaz** [comment]
FINALLY <3
