### ISSUE TITLE
Using `use_scm_version` `write_to` in `setup.cfg`

### ISSUE THREAD

**Issue by smarie** [pypa/setuptools-scm#582]
I love setuptools_scm, I use it in all my libs. I find the `write_to` option a great way to have the package find its own `__version__`, using the trick [described here](https://smarie.github.io/python-getversion/#package-versioning-best-practices).

I adopted last year a practice to place most of the setup information in `setup.cfg`, it seems to work very well (following this [great example](https://github.com/Kinto/kinto/blob/master/setup.cfg)) 

Until now I was always still placing `use_scm_version={"write_to": f"{name}/_version.py"}` in the `setup.py` because it was not supported in `setup.cfg`. However the `name` had to be inserted in both files, which is not convenient (For example: here in [setup.py](https://github.com/smarie/python-pyfields/blob/main/setup.py#L36) and here in [setup.cfg](https://github.com/smarie/python-pyfields/blob/main/setup.cfg#L4)).

Digging aroung in the past issues and PR I found #364 and #181 So I thought that maybe the status had evolved now ? Can I now use

```
use_scm_version = 
    write_to = foo/_version.py
```

in setup.cfg ? If this is not the recommended way, let me know !
Thanks a lot

**Comment by smarie** [comment]
There may be a workaround: in `setup.py` it seems possible to use `read_configuration` to access information from the setup.cfg. So the `setup.py` can look like

```python
from setuptools import setup
from setuptools.config import read_configuration

conf_dict = read_configuration("setup.cfg")
PKG_NAME = conf_dict['metadata']['name']

setup(
    use_scm_version={"write_to": f"{PKG_NAME}/_version.py"},
)
```

Therefore moving the `use_scm_version` statement in the other file is not really useful anymore.
I'm still wondering if there are alternatives or feedback on this approach.

**Comment by RonnyPfannschmidt** [comment]
use `pyproject.toml` setuptools will not natively support this and i won`t add a own parser in setuptools_scm

configuring `setuptools_scm` via pyproject.toml is supported since a while

**Comment by smarie** [comment]
So basically what you're saying is that I should place

```
[tool.setuptools_scm]
write_to = "pkg/_version.py"
```

in pyproject.toml.

Well this is great but that does not solve my problem :( since the pkg name has to be written twice: once here in the `write_to` contents, and once in setup.cfg (to fill the `name` metadata).

Maybe supporting a `write_to=auto` option, defaulting to `<pkg>/_version.py`, could do the trick ? Otherwise, supporting metadata variable names in `write_to` could be another, much more flexible workaround ? At least the package name is super useful.

Until such a solution is available, for those developers wishing to avoid entering the same folder name twice in two different configuration files, the workaround above seems to work. I tested it on https://github.com/smarie/python-genbadge and both in dev and release mode it works.

Thanks again @RonnyPfannschmidt !
