### ISSUE TITLE
consider switching from toml to tomli

### ISSUE THREAD

**Issue by graingert** [pypa/setuptools-scm#585]
pip is moving from toml to tomli https://github.com/pypa/pip/pull/10035 setuptools_scm should consider following suit

* pip: https://github.com/pypa/pip/pull/10035
* build: https://github.com/pypa/build/issues/308
* black: https://github.com/psf/black/pull/2301

**Comment by RonnyPfannschmidt** [comment]
Thanks for the note, will do asap
