### ISSUE TITLE
Inconsistent processing of vN.N.N tags on Mac OS X

### ISSUE THREAD

**Issue by mzabaluev** [pypa/setuptools-scm#59]
On Linux, if the latest reachable git tag has format `v{major}.{minor}.{micro}`, setuptools_scm strips out the `v` prefix.
On Mac OS X, the prefix is left intact.
Observed with setuptools_scm 1.8.0 on this project: https://github.com/gi-rust/grust-gen

**Comment by mzabaluev** [comment]
On Mac OS X, I have git from XCode Command Line Tools:

```
git version 2.4.9 (Apple Git-60)
```

**Comment by RonnyPfannschmidt** [comment]
interesting find, whats the output of git describe on apple?

**Comment by RonnyPfannschmidt** [comment]
oh, and additionally, whats the setuptools version on osx and on linux?

**Comment by RonnyPfannschmidt** [comment]
for additional details, please also show the output of setup.py --version on both platforms

**Comment by mzabaluev** [comment]
@RonnyPfannschmidt

> interesting find, whats the output of git describe on apple?

It's `v0.1.2-1-g00db58b` on an advanced branch, which `setup.py` transforms to `v0.1.3.dev1+ng00db58b`.

Sorry that I've noticed only now, setuptools_scm outputs a warning:

```
your setuptools is too old (<12)
setuptools_scm functionality is degraded
```

The version numbers of Python and setuptools on my Mac:

```
Python 2.7.10 (default, Jul 14 2015, 19:46:27) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import setuptools
>>> setuptools.__version__
'1.1.6'
```

**Comment by RonnyPfannschmidt** [comment]
can you try again witha newer versio of setuptools, just to see if there is a difference - it seems i'll have to adapt to older setuptools better

**Comment by mzabaluev** [comment]
FYI, the OS X version is 10.10.5 (Yosemite).

**Comment by RonnyPfannschmidt** [comment]
unfortunately i dont have access to any osx box myself

**Comment by mzabaluev** [comment]
With setuptools version 18.3.1 installed from Homebrew together with Python, the version is assigned as expected. I think it's fair to close this issue.

**Comment by RonnyPfannschmidt** [comment]
I created a to the point issue
