### ISSUE TITLE
Search parent directories

### ISSUE THREAD

**Issue by tdegeus** [pypa/setuptools-scm#591]
Support that you have a library directory:
```
/path/to/mylib/.git
/path/to/mylib/my/path/myscript.py
```
and support that I want to call 
```
python /path/to/mylib/my/path/myscript.py
```
and get the version string based on `/path/to/mylib/.git`. 

Currently I use
```python
from setuptools_scm import get_version
import git
root = git.Repo(os.path.dirname(__file__), search_parent_directories=True).working_tree_dir
myversion = get_version(root=root)
```

Now, it would be great to have the same `search_parent_directories` directly in *setuptools_scm*.

**Comment by RonnyPfannschmidt** [comment]
we intentionally do not search as people have sometimes interesting setups that break the expectation (like `~/.git/ `)

you can use something like `get_version(root="../../..", relativ_to=__file__)` to make it very explicit

but im not against accepting a pr that adds  the feature

**Comment by tdegeus** [comment]
Alright @RonnyPfannschmidt . Not sure that I can submit the PR before I pack up for a summer break, so maybe I'll prepare the PR after that

**Comment by RonnyPfannschmidt** [comment]
this one isnt running away unless someone takes it, i'll add a help wanted and deferred label n it and let it sit for a volunteer
