### ISSUE TITLE
Compare versions

### ISSUE THREAD

**Issue by tdegeus** [pypa/setuptools-scm#622]
I did not find (but maybe I overlooked) a way to compare versions. In particular `packaging.version` is not too good in dealing with the `dev` commits. So currently I'm using something like:
```python
import packaging.version

def greater_equal(a: str, b: str, allow_uncommited: bool=False) -> bool:

    A = packaging.version.parse(a)
    B = packaging.version.parse(b)

    if not allow_uncommited:
        if A.local is not None:
            if len(A.local.split(".")) > 1:
                msg = f"Uncommitted changes in \"{a}\""
                raise ValueError(msg)
        if B.local is not None:
            if len(B.local.split(".")) > 1:
                msg = f"Uncommitted changes in \"{b}\""
                raise ValueError(msg)

    Ab = A.base_version
    Bb = B.base_version

    if Ab > Bb:
        return True

    if Ab < Bb:
        return False

    Ad = A.dev if A.dev else 0
    Bd = B.dev if B.dev else 0

    return Ad >= Bd
```

**Comment by RonnyPfannschmidt** [comment]
It's unclear what you are asking for and why you do it here

Dev versions order below their non dev versions

**Comment by tdegeus** [comment]
I'm asking it here because `packaging.version` does not have all attributes that `setuptools_scm` has. Notably `package.version` has no attribute to identify if there are uncommitted changes. 

Furthermore, like you state, the `dev` version for `packaging.version` are ranked below the non-`dev` version. However, in `setuptools_scm` the opposite is done. In particular, for a version string that I generate with `setuptools_scm` this
```python
import packaging.version
print(packaging.version.parse("4.4") < packaging.version.parse("4.4.dev1"))
```
evaluates ``False``, whereas `setuptools_scm` conventions I think imply that it should evaluate `True`.

**Comment by RonnyPfannschmidt** [comment]
It should be false, 4.4.dev is lower than 4.4

**Comment by RonnyPfannschmidt** [comment]
note that when the last tag is sometihng like 4.4, then in a commit after it the vresion guessed is 4.5.dev...

**Comment by tdegeus** [comment]
It was indeed me that was mistaken... Sorry for the noise ;)

**Comment by RonnyPfannschmidt** [comment]
thanks for the update, version management can be a pain with the fine details :)
