### ISSUE TITLE
Add option to specify the version via PEP 517 `config_settings`

### ISSUE THREAD

**Issue by FFY00** [pypa/setuptools-scm#631]
Somewhat related to https://github.com/pypa/packaging-problems/issues/544

It would be useful to have a `config_settings` entry equivalent to `SETUPTOOLS_SCM_PRETEND_VERSION`. The use would look something like `python -m build -Cscm-pretend-version=1.0.0`.

I am not sure if setuptools exposes an interface to hook into `config_settings`, but we should figure that out.

**Comment by RonnyPfannschmidt** [comment]
Basically this is blocked until setuptools provides it

Im not going to work on it myself

**Comment by RonnyPfannschmidt** [comment]
Closing as seemingly never fixable

A alternative Version would be to create a new build backend that wraps setuptools, which is out of scope
