### ISSUE TITLE
Setup registers uncommitted changes

### ISSUE THREAD

**Issue by tdegeus** [pypa/setuptools-scm#639]
In a repository without any changes since the latest release:
```bash
$ python -c "import setuptools_scm; print(setuptools_scm.get_version())"
0.14.0
```
The setup still installs in to some develop version:
```bash
$ python -m pip install . -vv
...
Successfully installed GooseHDF5-0.14.1.dev0+g6f78d58.d20211005
....
```

Here is my `setup.py`:
```
from setuptools import find_packages
from setuptools import setup

setup(
    name="GooseHDF5",
    url="https://github.com/tdegeus/GooseHDF5",
    packages=find_packages(),
    use_scm_version={"write_to": "GooseHDF5/_version.py"},
    setup_requires=["setuptools_scm"],
)
```

I'm using `setuptools_scm` version 6.3.2

**Comment by RonnyPfannschmidt** [comment]
you unintentionally added your _version file to the scm,
please drop it and add it to gitignore

**Comment by tdegeus** [comment]
@RonnyPfannschmidt Thanks for your answer. I do want `setuptools_scm` to write `"GooseHDF5/_version.py"`. How do I do it, while still using `setup.py` ?

I guessed that adding `*_version.py` to `.gitignore` should have helped, but it did not.

**Comment by tdegeus** [comment]
Ah sorry now I get what you mean:
```
git rm GooseHDF5/_version.py
```
and adding to `.gitignore`
```
_version.py
```

**Comment by tdegeus** [comment]
However, that causes another problem: what if I want to use a dummy version for testing ?

**Comment by RonnyPfannschmidt** [comment]
after an editable install the file will be there, after a tox install the file will be there

**Comment by tdegeus** [comment]
I still feel that there is something less that optimal here.

Most recently I was build docs using `sphinx`. Normally this can be done without installing the library, however, everything fails because of the missing `_version.py` because in `__init__.py` I set:
```python
from ._version import version
```

It would be great if:
*  A dummy `_version.py` could be part of the CI without interfering with `setuptools_scm`. I can add this on my system, but on autobuild remotely the dummy will simply not be part of the clone because it is not part of the repo.
* There would be another way to include the version.

**Comment by RonnyPfannschmidt** [comment]
structurally this is a shortcoming of the python ecosystem - my general suggestion for doc building currentyl boils down to

1. use tox locally to ensure install/version update
2. use editable/real installs on rtd style setups or CI (pytest uses that for rtd for example)

**Comment by tdegeus** [comment]
Thanks. I indeed started using the 'workaround' of simply installing. 

Hopefully in some future there is a way around the Python shortcoming...
