### ISSUE TITLE
Document the relative-to keyword argument

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pypa/setuptools-scm#64]

**Comment by jaraco** [comment]
Where should the documentation go? Although it could be indicated in the Configuration Parameters section, the `relative_to` doesn't seem particularly relevant to `use_scm_version`. I would only expect it to be relevant to the `get_version` call.

**Comment by RonnyPfannschmidt** [comment]
The configuration parameters are passed 1:1 to get_version, so it should fit nicely
