### ISSUE TITLE
Support git archives

### ISSUE THREAD

**Issue by Changaco** [pypa/setuptools-scm#65]
git can inject data into archives, including tags. Here's how it could work:
1. put `use_scm_version={'git_metadata': '$Format:%D$'}` in `setup.py`
2. put `setup.py  export-subst` in `.gitattributes`
3. `setuptools_scm` extracts the version number from `git_metadata` with a regexp like `\btag: ([0-9][^,]*)\b`

**Comment by RonnyPfannschmidt** [comment]
The metadata would be incomplete and broken in many situations

Also in that case a file named .git_archival.txt should be used and registered as scm backend
I'm happy to include a Variant that demonstrably works correct with random archives from github

But I will not again spend time researching and implementing it for git

**Comment by RonnyPfannschmidt** [comment]
will be solved by #67 which should document the plugin that was kindly implemented and released by the original reporter
