### ISSUE TITLE
When I try to launch Jupyter notebook I am getting the error "__version_info__ = version.parse(docutils.__version__).release AttributeError: 'Version' object has no attribute 'release'"

### ISSUE THREAD

**Issue by Ramu588** [pypa/setuptools-scm#650]
I tried with the below options as well but, no luck. 
pip install -U setuptools

conda uninstall pyzmq (This also removes jupyter related packages!)
conda install pyzmq (to reinstall it)
conda install jupyter (to reinstall jupyter related packages)

**Comment by RonnyPfannschmidt** [comment]
With the provided details it's impossible to determine the issue

**Comment by RonnyPfannschmidt** [comment]
closing as not enough information, this is likely related to outdated packaging
