### ISSUE TITLE
Unable to install setuptools_scm even though there exists a dependency required installed

### ISSUE THREAD

**Issue by geekypy** [pypa/setuptools-scm#651]
Hello, when trying to install Paramiko that depends on Cryptography and this latter depends on the setuptools, I get these errors:
Note setuptools-59.3.0 is installed and not recognized by scm

1.-Command: python3 ./setup.py install

  **_File "/home/ocse/setuptools_scm-6.3.2/src/setuptools_scm/config.py", line 53, in _lazy_tomli_load
    from tomli import loads
ModuleNotFoundError: No module named 'tomli'_**

2.-Command: pip3 ./ install where ./ --> is where the setup.py of the 6.3.2 version is located.
It tries to downloaded from the net when the system is loaded with version 59

>>> imp.version
<module 'setuptools.version' from '/usr/local/lib/python3.9/dist-packages/setuptools-59.3.0-py3.9.egg/setuptools/version.py'>

  **_ERROR: Could not find a version that satisfies the requirement setuptools>=45 (from versions: none)
  ERROR: No matching distribution found for setuptools>=45_**

Has anyone experienced this and more importantly, anyone can assist? thank you

**Comment by RonnyPfannschmidt** [comment]
please try using `pip install .` with a reasonably modern pip
`setup.py install` is broken and strongly discouraged for usage as it cannot really support the modern packaging standards and will unvariably break for a number of use-cases

**Comment by geekypy** [comment]
Thanks! It worked!

**Comment by RonnyPfannschmidt** [comment]
Thanks for the reply, closing as solved by switching to recommended tooling.

Please ask if anything else comes up
