### ISSUE TITLE
build dependency tomli no longer supports python 3.6

### ISSUE THREAD

**Issue by jprestel-rue** [pypa/setuptools-scm#656]
heya! our pip installs are failing because a library we use has a build dependency on `setuptools_scm`, which in turn has an unpinned dependency on `tomli`, whose latest version (2.0.0) dropped support for python 3.6.

What i'm wondering is if there's a chance y'all could (temporarily?) adjust your `tomli` dependency to be `~=1.0` instead of `>=1.0`.

I know python 3.6 is end of life in about a week, but figured it didn't hurt to ask if this 🙏

**Comment by hukkin** [comment]
A modern version of pip should not install package versions incompatible with the Python interpreter. Would it solve your issue if you
```console
pip install --upgrade pip
```

**Comment by RonnyPfannschmidt** [comment]
any pip that would support a sensible env marker based tomli limit that i would accept also respects python requires metadata, please fix your build pipeline or add a own pin for control

**Comment by RonnyPfannschmidt** [comment]
closing for now, but happy to reopen in case someone finds a edge case im not aware of
