### ISSUE TITLE
Reasons for `no-guess-dev` version numbers and why it should stay.

### ISSUE THREAD

**Issue by FlorianWilhelm** [pypa/setuptools-scm#657]
[This issue extracts the discussions about `no-guess-dev`'s pros and cons from #654.] 

setuptools-scm provides the default mechanism `guess-next-dev` to guess the next version number. This version number is then used to generate development versions `devN` according to [PEP440](https://www.python.org/dev/peps/pep-0440/). Guessing the next version number is not a trivial task due to obvious ambiguities, e.g. the successor version of 1.4.1 could be 1.4.2, 1.5 or even 2.0.

For this reason I prefer `post1.devN` as it basically says that we are working on the development of the next release (post the current) whatever this release might be. To my understanding it's still PEP440 compliant and it's way less complex and error-prone than `guess-next-dev`.

**Comment by RonnyPfannschmidt** [comment]
@FlorianWilhelm the next release will have a no-guess-dev variant that will add a postrelease if it can, and intentionally error ut on a missaligned release

**Comment by RonnyPfannschmidt** [comment]
closing this issue as we recorded that for certain user groups, guessing a next version is confusing (
