### ISSUE TITLE
get_version() in 6.4.0 is backwards-incompatible

### ISSUE THREAD

**Issue by khaeru** [pypa/setuptools-scm#669]
setuptools-scm 6.4.0 introduced a change to the signature of `get_version()` in [this commit](https://github.com/pypa/setuptools_scm/commit/eaf6d6417294401fb0d404dc85e95f14b73db0d7#diff-bdefa0298003efada7c465428643cc6d9c129168afb3eb5c551b40fcc77feac1L102).

This causes downstream code to break with, e.g.:
```python
message_ix/__init__.py:10: in <module>
    from .reporting import Reporter
message_ix/reporting/__init__.py:16: in <module>
    from .pyam import collapse_message_cols
message_ix/reporting/pyam.py:4: in <module>
    from genno.compat.pyam import util
/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/site-packages/genno/compat/pyam/__init__.py:2: in <module>
    import pyam  # noqa: F401
/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/site-packages/pyam/__init__.py:30: in <module>
    __version__ = get_version(Path(__file__).parent.parent)
TypeError: get_version() takes 0 positional arguments but 1 was given
```

In the former signature, the first positional argument was understood to be `root`.

Either 6.4 should have been 7.0 to indicate the incompatible API change, or `get_version()` should warn about a deprecated signature that will, in the future, cause an error.

**Comment by RonnyPfannschmidt** [comment]
my apologies, good catch, will fix

**Comment by khaeru** [comment]
Many thanks for the quick fix and release!
