### ISSUE TITLE
6.4.1 is incompatible to Python < 3.6.5

### ISSUE THREAD

**Issue by ilotXXI** [pypa/setuptools-scm#671]
Hello.

We have to work with Python 3.6.1. Today the `setuptools-scm` 6.4.1 is released which [uses](https://github.com/pypa/setuptools_scm/blob/c585e20718c478b2639e955ee8cc56186dc1ced1/src/setuptools_scm/__init__.py#L101) `typing.NoReturn`. It [doesn't exist](https://docs.python.org/3.8/library/typing.html#typing.NoReturn) in Python < 3.6.2 (or even [3.6.5](https://docs.python.org/3.6/library/typing.html#typing.NoReturn)).

Can you please remove it?

**Comment by RonnyPfannschmidt** [comment]
i'l lremove it in a bugfix release, the next feature version of setuptools_scm will drop python 3.6 support

**Comment by ilotXXI** [comment]
Great, thank you!
