### ISSUE TITLE
document using `python -m setuptools_scm`

### ISSUE THREAD

**Issue by ziadmoubayed** [pypa/setuptools-scm#673]
I have a project that does not include `setup.py` and uses `setuptools_scm` for versioning. Package configuration is defined in `setup.cfg` and `pyproject.toml`.  Building works fine. I can build the package and artifacts look good. Also when i install the package in my venv (from source or from pip), i can read the version programatically without issues.

I am just wondering how can i get the version of the package locally without `setup.py`?

The docs only mention `python setup.py --version` for local non-programmatic use. Any other suggestions?

Thanks

**Comment by abravalheri** [comment]
Hi @ziadmoubayed, have you tried installing the latest release of `setuptools-scm` in your environment and running `python -m setuptools_scm`?
(I think it will work if your configuration for `setuptools-scm` is defined in `pyproject.toml`).

**Comment by RonnyPfannschmidt** [comment]
there is need for better docs

**Comment by ziadmoubayed** [comment]
@abravalheri that works ✅  thanks
