### ISSUE TITLE
setuptools_scm still generate .dev0

### ISSUE THREAD

**Issue by gsemet** [pypa/setuptools-scm#680]
Hi. We need to find a way to make setuptools_scm NOT generate "dirty" version during the tag build, because there are local changed files.

**Comment by RonnyPfannschmidt** [comment]
Without more details this is not actionable, its quite possible your build process is incomplete and/or broken

**Comment by gsemet** [comment]
Hi. We generate lot of intermediate files during the build, and I agree this is not clean but there is lot of history behind.... But during the time it is not clean, we do generate dev0 version in our Github pipeline. What would be the easiest way to ensure no dev0 files are not generated during the github tag pipeline?

would it be possible to have a mode "I give you the tag to use, do not try to compute anything?"

**Comment by RonnyPfannschmidt** [comment]
Set the env variable for setuptools_scm_pretend_version_for_$mypkg
