### ISSUE TITLE
setuptools_scm isn't mentioned in PyPA's User Guide

### ISSUE THREAD

**Issue by Changaco** [pypa/setuptools-scm#69]
I've been trying to fix that in https://github.com/pypa/python-packaging-user-guide/pull/190

Feel free to close this issue if you don't care.

**Comment by RonnyPfannschmidt** [comment]
It's somewhere on my own roadmap

I started working on an own release management pipeline that will include setuptools-scm but also handle grooming tasks, prerelease and postrelease steps
