### ISSUE TITLE
Consider `fetch_on_shallow` non experimental? 

### ISSUE THREAD

**Issue by cidrblock** [pypa/setuptools-scm#692]
https://github.com/pypa/setuptools_scm/blob/7950bdaa3e5d9da42434f3e7a85d05971ebeca1f/src/setuptools_scm/git.py#L110

We just put this to use to work around an RTD issue we were having.

Any possibility of removing the experimental flag knowing someone is using it. :)

Thought I would ask...

Related: https://github.com/ansible/ansible-navigator/pull/1001

**Comment by RonnyPfannschmidt** [comment]
The experimental flag will stay as its still a unstable api that's not fitting modern python packaging

**Comment by cidrblock** [comment]
TY, makes sense. :)
