### ISSUE TITLE
nb_black installation fails... 'setuptools_scm[toml]>=6.3.1' wheel Check the logs for full command output

### ISSUE THREAD

**Issue by jhassanandani** [pypa/setuptools-scm#694]
Below is the screenshot

![nb_black_error](https://user-images.githubusercontent.com/52968500/156824761-aa0804b1-12a4-4bbb-8f4c-44026b6ad93f.JPG)

**Comment by jhassanandani** [comment]
@RonnyPfannschmidt  I have added screenshot of the issue. I tried to install setuptools_scm and tomli and then tried to reinstall nb_blank. It throws same error

**Comment by RonnyPfannschmidt** [comment]
@jhassanandani you are running a isolated build with no network and no access to the current packages, please disable build isolation

Alternatively use the wheels instead of source packages

**Comment by jhassanandani** [comment]
@RonnyPfannschmidt  For nb_black there is no whl file. So I disabled build isolation. With that tomli issue is gone but still i can't install the package. Below are screenshots:

![image](https://user-images.githubusercontent.com/52968500/157077327-7541e462-960f-4ae5-ad2b-750525f99721.png)
![image (1)](https://user-images.githubusercontent.com/52968500/157077646-c024661f-c058-4873-917a-a831d7845cef.png)

**Comment by RonnyPfannschmidt** [comment]
You try to install black from source which requests setuptools_scm
Either enabled pip to install it, or preinstall it

**Comment by RonnyPfannschmidt** [comment]
closing this as self-imposed deployment issues
