### ISSUE TITLE
Docs mention missing setuptools 'file_finders' feature

### ISSUE THREAD

**Issue by zmc** [pypa/setuptools-scm#699]
Using setuptools_scm I noticed that files outside a package are ignored, even if mentioned in `MANIFEST.in`. It appeared there was an [easy solution in the docs](https://github.com/pypa/setuptools_scm/blob/8765fa750d5b013a3139eff53c89eb8c8d7a3491/README.rst?plain=1#L326-L328), but the link to setuptools' docs is broken, and I can't find a reference to the feature elsewhere in the docs.

**Comment by RonnyPfannschmidt** [comment]
thanks for the note, updated the url to [the current one](https://setuptools.pypa.io/en/latest/userguide/extension.html#adding-support-for-revision-control-systems)

**Comment by zmc** [comment]
Ah thank you! I had used the search function on the setuptools docs site, but it turns out if one doesn't use quotes the underscore trips that up quite a bit.
