### ISSUE TITLE
Option to choose most recent tag matching a pattern?

### ISSUE THREAD

**Issue by evadeflow** [pypa/setuptools-scm#70]
I've integrated `setuptools_scm` into a cookiecutter template I'm proposing my company use to bootstrap  new Python modules, and the result is _outstanding_. So first off—thanks!! This will make it _so_ much easier for people to Do The Right Thing™. The one thing that concerns me about turning this loose on my colleagues is that we (unfortunately) have 'fat' repositories containing multiple modules, and we've grown accustomed to using tags for various house-keeping and grouping purposes. Thus, tagging the repo does not always imply a release/version bump to our Python modules.

It seems that `setuptools_scm` only looks at the most recent tag(s) to infer a version number, and it expects a particular pattern. If the most recent tag were, say,  `VENDOR_ACME_20150923`, then `python setup.py --version` emits a stack trace and error message: `AssertionError: cant parse version None`. Due to the large number of tags like this that are already in our repo(s) (made for purposes I won't even pretend to understand) I'd rather not try to convince the whole team to use tags like `VENDOR_ACME_20150923-1.0.9` instead. I worry that people will either forget to tack on the semver bit, or—worse still—use the 'wrong' value and cause Jenkins to upload a bunch of incorrectly-labeled packages to our devpi server.

I'm not sure whether 'namespacing' tags like this is a particularly _good_ idea, but... for our use case, being able to use a different pattern to denote 'release-worthy' tags would be helpful, perhaps something like `VENDOR_ACME_20150923---2.1.0`. Is there a way to coax the current version of `setuptools_scm` to do this? [This section](https://pypi.python.org/pypi/setuptools_scm/1.9.0#importing-in-setup-py) in the docs implies that I can swap out most of the builtin functionality, but I'm having a little trouble figuring out how to wire all the pieces together. Any hints would be _much_ appreciated! And if this turns out to be something other people may find useful, I'd be happy to submit a pull request.

**Comment by RonnyPfannschmidt** [comment]
thanks for the detailed description 

that part is already prepared in https://github.com/pypa/setuptools_scm/blob/master/setuptools_scm/git.py#L9

as a response to #62 and #63

i just haven't added a good way to pass scm specific parameters across

a little brainstorming on a sensible way to pass such patterns trough from setup.py into setuptools_scm is needed

i was thinking of adding a `scm_config` key which may contain keyword arguments for the scm "parser"

then it can be part of the next release that i hope to finish this weekend

**Comment by RonnyPfannschmidt** [comment]
oh, an extra note - the section you reffered to is about changing the formatting of the version that setuptools_scm obtained, there currently is no support for passing a custom parsing function,

but its a nice idea to pass the parsing function as own configuration as well and i'll create a issue for that
