### ISSUE TITLE
If a git tag has a .postX suffix, setuptools_scm adds .postY suffix breaking PEP 440

### ISSUE THREAD

**Issue by Sekenre** [pypa/setuptools-scm#709]
While creating a release that only updates the build system we created a git tag "5.4.2.post1".

This has broken upstream builds as the version string becomes "5.4.2.post1.post10"

This is unexpected since I thought we would get "5.4.2.post1.dev10" instead.

Ref: https://github.com/agronholm/cbor2/pull/131#issuecomment-1106929593

**Comment by RonnyPfannschmidt** [comment]
The post release version scheme is currently unaware of nesting, i would strongly discourage using it in any serious project

Based on the use case outlined a guess next post release scheme should be added to reliably add dev tags

**Comment by Sekenre** [comment]
Hi, thanks for responding.

The use case that we have is that adding ".postN" to our tag is the recommended way to create a post release in PEP 440. We had a release where we updated the build system for wheels and added ".post1" to the tag to trigger github actions to build fresh wheels.

Unfortunately whenever someone built wheels (i.e. for tox or a local build) from a git branch it would create this broken version string. As far as we know we're doing everything right.

This won't be a problem for long since we'll do a minor release soon.

**Comment by Sekenre** [comment]
This is what we get from Git:
```
 ~/Projects/cbor2 $ git describe --tags
5.4.2.post1-8-gf0cf29c
```

**Comment by RonnyPfannschmidt** [comment]
@Sekenre if you actually want to tag post releases on occasion, then the post-release scheme is the absolutely wrong, please use the normal one

**Comment by Sekenre** [comment]
Hi @RonnyPfannschmidt as far as I can tell we're doing what PEP 440 recommends: https://peps.python.org/pep-0440/#post-releases

What is "the normal one" that you are referring to?

**Comment by RonnyPfannschmidt** [comment]
@Sekenre https://github.com/agronholm/cbor2/blob/f9b8e504e932a9f8b529282b67cf8a9309746fe4/setup.py#L68 <- this will add post release ids based on tags and distance, its incompatible with creating tags for post releases

**Comment by Sekenre** [comment]
Ok that explains it, it also makes sense that "guess-next-dev" does exactly what I expected. Thank you!
