### ISSUE TITLE
Question - How can we define root in callable in setup.py?

### ISSUE THREAD

**Issue by vikas027** [pypa/setuptools-scm#710]
As of now, my root (or git) directory is one level down w.r.t to `setup.py`. How can I use `root` (something like `use_scm_version={'root':'../..', ...}`) in the callable as shown in the [example](https://github.com/pypa/setuptools_scm#importing-in-setuppy).

```python
# content of setup.py
import setuptools

def myversion():
    from setuptools_scm.version import get_local_dirty_tag
    def clean_scheme(version):
        return get_local_dirty_tag(version) if version.dirty else '+clean'

    return {'local_scheme': clean_scheme}

setup(
    ...,
    use_scm_version=myversion,
    ...
)
```

**Comment by RonnyPfannschmidt** [comment]
Just put it into the return value of the callable

**Comment by vikas027** [comment]
Thanks @RonnyPfannschmidt
