### ISSUE TITLE
`pip 22.1` and `setuptools 62.2.0` break installation with `--upgrade --no-binary :all:` options 

### ISSUE THREAD

**Issue by DnPlas** [pypa/setuptools-scm#713]
Seems like the most recent `pip` and `setuptools` versions break the `setuptools_scm` installation when attempting an install with `--upgrade --no-binary :all:` options.
The installation process ends with an exception `pip._vendor.packaging.markers.UndefinedEnvironmentName: 'extra' does not exist in evaluation environment.` and other error messages.

### Steps to reproduce

```bash
$ python3 -m venv testenv && source testenv/bin/activate
(testenv) $ pip install --upgrade --no-binary :all: setuptools pip
...
Successfully installed pip-22.1 setuptools-62.2.0

(testenv) $ pip install --upgrade --no-binary :all: setuptools_scm
File "/tmp/pip-standalone-pip-cwfeaj42/__env_pip__.zip/pip/_vendor/packaging/markers.py", line 215, in _get_env
          raise UndefinedEnvironmentName(
      pip._vendor.packaging.markers.UndefinedEnvironmentName: 'extra' does not exist in evaluation environment.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 2
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
> NOTE: it is very important to note this only happens when installing using the mentioned options, and also installing `pip` and `setuptools` first and then `setuptools_scm` separately. The project I am working on requires those options to be present, and that way of installing.

### Expected behaviour
`setuptools_scm` is installed with no error messages.

### Workaround
Pin `pip==22.0.4` and `setuptools==62.1.0`

**Comment by lathiat** [comment]
This seems to happen during the install of the dependency pyparsing, processing

  build_reqs = ['railroad-diagrams ; extra == "diagrams"', 'jinja2 ; extra == "diagrams"']

I think this might be fixed by:
https://github.com/pypa/pip/commit/611e9253ff74ca5b8ce438c2423373ab0d44c961

I think the breaking requirement was introduced by a change to pyparsing released a few days ago in 3.0.9:
https://github.com/pyparsing/pyparsing/pull/360

**Comment by DnPlas** [comment]
As @lathiat mentioned, pypa/pip#11112 could fix this issue.
@pradyunsg can I ask if there will be a bug-fix release or if we'll have to wait ~3 months to see those changes reflected in the next release?

**Comment by RonnyPfannschmidt** [comment]
Would a negative match for the pyparsing version help as downstream workaround

**Comment by TimoRoth** [comment]
Installing pip from git master makes thing work for me again, so I'd assume this issue will be gone with the next release of pip.

**Comment by DnPlas** [comment]
> Would a negative match for the pyparsing version help as downstream workaround

That is a good point, it works for me.

**Comment by pradyunsg** [comment]
Is this still relevant? I see a mention for a merged PR.

**Comment by TimoRoth** [comment]
A new pip release happened eventually, fixing the issue.
