### ISSUE TITLE
setuptools_scm: unpinned "typing_extensions" dependency

### ISSUE THREAD

**Issue by emfloyd2** [pypa/setuptools-scm#723]
Howdy.

Shouldn't "typing_extensions" dependency be pinned to ">=4.0.0"? Since symbols such as `ParamSpec` aren't available in older versions

I just ran into issue on internal project leveraging docker - where the typing_extensions dependency of ">3.7" was already being satisfied with typing-extension v3.7.4.3.

An unpinned setuptools_scm installation (via setup_requires of another package) was getting tripped up because of this.

**Comment by RonnyPfannschmidt** [comment]
will resolve this by not requiring it at runtime in combination with #722
