### ISSUE TITLE
v7.0.3 on PyPI

### ISSUE THREAD

**Issue by frenzymadness** [pypa/setuptools-scm#737]
Hello.

I see that you have the v7.0.3 tag here but the latest version on PyPI is still 7.0.2. Is this intentional?

**Comment by RonnyPfannschmidt** [comment]
The tag triggers a automatic release, i haven't seen the pipelines for that fail, but there may be some cache issues, thanks for bringing it to attention

**Comment by RonnyPfannschmidt** [comment]
@frenzymadness indeed, it seems for unrelated reasons the *tag* process never started and thus the upload never happened, as the release pipeline does not in fact upload the artifacts, but the tag one does

i restarted the right pipeline and will close this once the upload completes

**Comment by RonnyPfannschmidt** [comment]
this time it came trough, thanks :+1:
