### ISSUE TITLE
TypeError: setuptools_scm.config.Configuration() got multiple values for keyword argument 'relative_to'

### ISSUE THREAD

**Issue by cmpilato** [pypa/setuptools-scm#738]
My project build recently stopped working, failing with:

> TypeError: setuptools_scm.config.Configuration() got multiple values for keyword argument 'relative_to'

My setup.py looks like so:

```python
import setuptools
setuptools.setup()
```

...and my pyproject.toml thusly:

```ini
[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "setuptools_scm>=6.2"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
relative_to = "__file__"
fallback_version = "0.0.0"
```

If I comment out the `relative_to` configuration line in `pyproject.toml`, the build completes.

**Comment by cmpilato** [comment]
Might something like the recent change made in https://github.com/pypa/setuptools_scm/pull/736/commits/2f24235680cb1e3a999f6185812e376bd6823849 be needed also for `relative_to`?

**Comment by RonnyPfannschmidt** [comment]
@cmpilato that was always an error, just never triggered breakage before, i will cause it to raise a better error, this setting is not to be had in pyproject.toml

**Comment by cmpilato** [comment]
Thanks, @RonnyPfannschmidt.  I suspect this codebase (which I inherited) copied a bad pattern from something else (perhaps https://pyscaffold.org/en/v4.0.2/faq.html#python-api ?).

**Comment by RonnyPfannschmidt** [comment]
@FlorianWilhelm that looks like a oversight, should I create a release with a warning so that your users can migrate

**Comment by cmpilato** [comment]
Thanks.  My "users" at the moment are all internal to my organization, so don't rush something on my account.

**Comment by RonnyPfannschmidt** [comment]
@cmpilato i mentioned one of the pyscaffold maintainers in my message, likely more users are effected and pyscaffold is used by a lot of data science folks that may not necessarily share the deeper programming and software release management backgrounds

**Comment by cmpilato** [comment]
> @cmpilato i mentioned one of the pyscaffold maintainers in my message, likely more users are effected and pyscaffold is used by a lot of data science folks that may not necessarily share the deeper programming and software release management backgrounds

That was kind of you!  (And makes way more sense than how I mis-interpreted your message.)

**Comment by FlorianWilhelm** [comment]
Hi @RonnyPfannschmidt, thanks I guess an error message with a better warning would help. 

Regarding the source of this error, we never had `relative_to = "__file__"` in `pyproject.toml` to the best of my knowledge, right @abravalheri? In our FAQ, we only say that in Monorepos it might make sense to have `relative_to = "setup.py"` in `pyproject.toml`, which should work, right? The actual problem is that `__file__` is not resolved within `pyproject.toml`.

**Comment by abravalheri** [comment]
The complete example in PyScaffold's FAQ is:

```toml
[tool.setuptools_scm]
# See configuration details in https://github.com/pypa/setuptools_scm
version_scheme = "no-guess-dev"
# ADD THE TWO LINES BELOW
root = ".."
relative_to = "setup.py"
```

We do mention `__file__` but in the context of `setup.py` (but that is a different story, right?).

Maybe it is just a misunderstanding when users try to combine the information from this section in `setuptools-scm` readme (when referring to `[tool.setuptools_scm]`):

> Additionally, include arbitrary keyword arguments in that section to be supplied to get_version().

with this entry in the `Configuration parameters` table:


relative_to: | A file from which the root can be resolved. Typically called by a script or module that is not in the root of the repository to point setuptools_scm at the root of the repository by supplying `__file__`.
-- | --

?

**Comment by RonnyPfannschmidt** [comment]
Possibly, in the pyproject.toml case relative to is always supposed to be that file

Dunder file makes no sense whatsoever

**Comment by abravalheri** [comment]
Thanks @RonnyPfannschmidt, so does it mean that we can drop the `relative_to = "setup.py"` line in our example?

**Comment by RonnyPfannschmidt** [comment]
Yes, I will release a version that takes the value out of the config and warns the user

**Comment by abravalheri** [comment]
Thank you very much @RonnyPfannschmidt!

**Comment by jamesbraza** [comment]
I follow that `__file__` doesn't work within `pyproject.toml`, and think it's good to reveal this as a flawed solution.

Sadly, this newest 7.0.3 release has unfortunately broken all of my department's CI pipelines, so I am now trying to modernize our configs.

Can I get a confirmation that the correct action is to go from:

```toml
[tool.setuptools_scm]

root = ".."
relative_to = "__file__"
```

To:

```python
from setuptools import setup

setup(
    ...,
    use_scm_version = {
        "relative_to": __file__
    },
    setup_requires=['setuptools_scm'],
    ...,
)
```

+ 

```toml
[tool.setuptools_scm]

root = ".."
```

Also, I will point out the current docs for `relative_to` don't make it clear not to use `__file__` in `pyproject.toml`.  Consider adding a line to the `README.rst` (or to the printed warning mentioned above) detailing that `__file__` doesn't resolve inside a `pyproject.toml`.

Lastly, feel free to tag me as a PR reviewer if needed.

**Comment by FlorianWilhelm** [comment]
@jamesbraza, according to @RonnyPfannschmidt, it should even work if you remove from `setup.py` the part:
```
    use_scm_version = {
        "relative_to": __file__
    },
```
Could you confirm that this also works?

**Comment by jamesbraza** [comment]
Thanks for the quick response @FlorianWilhelm !  Yes, removing the `use_scm_version = {"relative_to": __file__}` worked! 🎉 🙏 

In conclusion, the fix was simply removing `relative_to = "__file__"` from my `pyproject.toml`.
