### ISSUE TITLE
There is no way to use a custom "parse" function with `pyproject.toml`-based configuration

### ISSUE THREAD

**Issue by moshez** [pypa/setuptools-scm#743]
Since `pyproject.toml` can't import Python functions directly

```
[tool.setuptools_scm]
use_scm = { parse="some_name" }
```

tries to use the string `"some_name"` as a function, causing a traceback. If the string is defined as the name of an entrypoint of `setuptools_scm.parse`, it might make sense to use it instead. Does this make sense? Would a PR be useful?

**Comment by RonnyPfannschmidt** [comment]
Please outline your actual use case first

**Comment by moshez** [comment]
I'm not sure what you're asking here: the README mentions that the `parse` argument is "A function that will be used instead of the discovered SCM for parsing the version." The README also mentions that using `setup.cfg` and `setup.py` is deprecated. What I'm asking for is to allow to use `parse` argument *without* using a deprecated function.

I suppose alternatively, it is possible to deprecate the `parse` argument completely.

The current state documents the feature is supported, but does not allow for a way to use it that is not deprecated.

**Comment by RonnyPfannschmidt** [comment]
As there was no usecase outlined, im going to go with deprecation

**Comment by moshez** [comment]
PR #744 adds the ability to do that.

This feature has been in `setuptools_scm` for a while, and presumably is already used by people. I'm not sure why deprecation would be better.

**Comment by RonnyPfannschmidt** [comment]
after careful consideration of the build backend peps im going to reject this cappability for now

setuptools_scm will not add a own import path managment mechanism - examples for setuptools and hatch integration will be provided later

this will revisited once a common mechanism for local build backend plugins is devised

ideally something like build backend entrypoints and build backend path extensions would be provided either a standard, or a separate python package to support backends
