### ISSUE TITLE
setuptools_scm >= 7 generates wheel version 0.0

### ISSUE THREAD

**Issue by Nothing4You** [pypa/setuptools-scm#745]
Hi,

I've been looking into updating `aiomysql` to `setuptools_scm` version 7.

In `setuptools_scm` < 7 both built sdist and wheel files are generated with the correct version in the file name:
https://github.com/Nothing4You/aiomysql/runs/7272226544?check_suite_focus=true#step:10:254

Attempting to update to `setuptools_scm` >= 7.0.4 produces a wheel file name using version 0.0:
https://github.com/Nothing4You/aiomysql/commit/65e0cafe769d4fdbb78eaf756676ea3d092eb4e3
https://github.com/Nothing4You/aiomysql/runs/7272253138?check_suite_focus=true#step:10:258

For the generated sdist, the egg-info correctly includes `Version: 0.1.2.dev19+g65e0caf` and an appropriate generated scm version file.

For the generated wheel, the file is named `aiomysql-0.0-py3-none-any.whl`, egg-info contains `Version: 0.0` and the generated version file says `0.0` as well.

I haven't been able to build a minimal reproducible example, as those have been generating the correct versions in my attempts.
I can reproduce it by taking the repo checked out at the commit linked above and running e.g. `python -m build` on it:
```bash
git clone -b scmtest https://github.com/Nothing4You/aiomysql/
cd aiomysql
python -m venv --upgrade-deps venv
. venv/bin/activate
pip install build
python -m build
```
> `Successfully built aiomysql-0.1.2.dev19+g65e0caf.tar.gz and aiomysql-0.0-py3-none-any.whl`

**Comment by Nothing4You** [comment]
Individually generating only wheel or only sdist produces the correct version output.

**Comment by RonnyPfannschmidt** [comment]
@Nothing4You this seems to be a comeback of a git archival support regression,

**Comment by RonnyPfannschmidt** [comment]
the full isuse is that by going vcs -> sdist -> wheel, the issue triggers in the sdist, and a git archival is missparsed,
gonna try if i can create a quick bugfix

**Comment by Nothing4You** [comment]
thanks, appreciate the quick response.
i've been able to build a minimal reproduction example now, i forgot to actually commit relevant files before: https://github.com/Nothing4You/sscm-745

**Comment by Nothing4You** [comment]
thank you for the fix.

for my understanding, are the `UserWarning`s expected currently or is that a separate issue?

**Comment by RonnyPfannschmidt** [comment]
Warning is intended
