### ISSUE TITLE
Buggy last test in 7.0.5's `testing/test_git.py` ?

### ISSUE THREAD

**Issue by SnarkBoojum** [pypa/setuptools-scm#750]
While packaging 7.0.5 for Debian, I found the last test of `testing/test_git.py` a bit strange:
1. it's named `test_git_archhival_from_unfiltered` -- why two h ?
2. it tries to load a file which isn't currently installed by the package... and hence fails! Either that file is mandatory and it should be installed or optional and the test should handle it.

Cheers,

J.Puydt

**Comment by stanislavlevin** [comment]
This test relies on several things:
- editable installation and thereby, `.git_archival.txt` is always accessible. Most likely Debian run tests out of a git tree and that assumption is wrong.
- no expansion happened for `git_archival.txt` (see `.gitattributes`). i.e. the packaged sources are not produced by `git archive`.
