### ISSUE TITLE
The tomli package is still required with Python 3.11

### ISSUE THREAD

**Issue by gmc444-b** [pypa/setuptools-scm#753]
The [setup.cfg file](https://github.com/pypa/setuptools_scm/blob/a1bda3d984d1a40d7b00ae1d0869354d6d503001/setup.cfg#L34) specifies that `tomli` is required for Python versions less. than 3.11. However when attempting to use `setuptools_scm` to build packages like `importlib-metadata`, with the 3.11 Beta,`tomli` is still referenced.

Would it be possible to change the line above to either constrain the version to  <3.12, or drop the constraint altogether?

**Comment by RonnyPfannschmidt** [comment]
already fixed in #748
