### ISSUE TITLE
Accessing version in requirements.txt

### ISSUE THREAD

**Issue by jamesbraza** [pypa/setuptools-scm#754]
### Background

I have a repo containing 4 native namespace subpackages.

We synchronize their versioning using `from setuptools_scm import get_version` within `setup.py`.

Package 1: `setup.py`:

```python
from setuptools import find_namespace_packages, setup

setup(
    name="package1",
    ...,
    packages=find_namespace_packages(),
    setup_requires=["setuptools_scm"]
)
```
Package 1: `pyproject.toml`

```toml
[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
root = ".."
```

Package 2+: `setup.py` (and no `pyproject.toml`):

```python
from setuptools import find_namespace_packages, setup
from setuptools_scm import get_version

repo_version = get_version(root="..")
setup(
    name="package2+",
    ...,
    packages=find_namespace_packages(),
    version=repo_version,
    install_requires=[f"package1=={repo_version}"]  # How we ensure version synchronization
)
```

### Request

We now want to move to `pyproject.toml`, mainly to integrate [`pip-compile`](https://github.com/jazzband/pip-tools) with the new `requirements.txt` support in [`setuptools==62.6.0`](https://setuptools.pypa.io/en/latest/history.html#v62-6-0).  The migration works well for package 1, but doesn't go smoothly for package 2.

Package 2+: `requirements.txt`:

```txt
package1=={repo_version}  # How do we access repo version in requirements.txt?
```

And obviously this doesn't work out, because `repo_version` relies on actual Python code.

Does `setuptools_scm` have anything tools/tricks for this use case: accessing version in `requirements.txt`?

And if this is not supported, is there any alternate way we can use `requirements.txt` and `setuptools_scm` to synchronize versions across the repo's subpackages?

**Comment by RonnyPfannschmidt** [comment]
It's not supported

You could use a build plugin or just ensue you pass both paths at once to pip compile

**Comment by jamesbraza** [comment]
Firstly, thanks for responding, I appreciate it.

> ensue you pass both paths at once to pip compile

`pip-compile` works on a `requirements.in` basis (a text file like `requirements.txt`).  How would I get a `setuptools_scm` version into `pip-compile`'s `requirements.in`?  Or are you posing programmatically interfacing with `pip-compile` somehow?

**Comment by RonnyPfannschmidt** [comment]
im proposing to list the project folders in pip compile and then letting pip compile get the supposedly matching versions off the local checkouts

**Comment by jamesbraza** [comment]
> letting pip compile get the supposedly matching versions off the local checkouts

This actually works for a local install, I tried it tonight!  However, having them unpinned with respect to each other is not quite enough.

The different sub-packages are actually changed and thus versioned together.  When one goes to install the package from our internal PyPI, the versions fetched by `pip` don't have an exact version pinned, so one can have incompatible versions installed:

```bash
pip install all-packages-tests==0.1.1.dev42+g4020761  # Pre-release version
# This can (and will) fetch a different version of package1
# For example, ideally it will fail if one forgets --pre to pip install,
# instead of falling back on the last-released version
```

---

I thought about using an environment variable to synchronize versions (since `requirements.txt` supports this), but sadly `pip-compile` doesn't [support environment variables](https://github.com/jazzband/pip-tools/issues/966) yet. :/

---

Any ideas as to how to preserve this synchronization of pinning?  Otherwise, feel free to close the issue.

**Comment by RonnyPfannschmidt** [comment]
If you want to dynamically compute a dependency, you need a plugin for the builder

**Comment by jamesbraza** [comment]
Thanks for your advise/guidance! Closing this out
