### ISSUE TITLE
Environment variable for getting current version?

### ISSUE THREAD

**Issue by jamesbraza** [pypa/setuptools-scm#755]
Here is a script to make an environment variable containing the current version:

```python
import os

from setuptools_scm import get_version

os.environ["SCM_VERSION"] = get_version()
```

Does `setuptools_scm` expose an environment variable that does this already?

Looking in https://github.com/pypa/setuptools_scm#environment-variables, it seems like none of these environment variables will return the current version.

**Comment by RonnyPfannschmidt** [comment]
What's the use case for this?

**Comment by jamesbraza** [comment]
**Background**

I have a repo containing four sub-packages, where some of the sub-packages depend on the others.  Each sub-package uses a `requirements.txt` made by [`pip-compile`](https://github.com/jazzband/pip-tools).  [`setuptools==62.6`](https://setuptools.pypa.io/en/latest/history.html#v62-6-0)'s new dynamic `file` option then intakes the `requirements.txt`.  What I am trying to solve is pinning the sub-packages' versions to be in sync.

This was discussed in https://github.com/pypa/setuptools_scm/issues/754.  I was reflecting on this since then, and came up with the below possibilities.

---

**Two Use Cases**

I could use a `$SCM_VERSION` environment variable to enable two different solutions:
- Option A: pin `subpkg-dependency==${SCM_VERSION}` in the `requirements.txt`s
    - Side effect: guaranteed sub-package version matchup for local editable install and actual install from package index
    - Note: `pip-compile` doesn't [support env vars](https://github.com/jazzband/pip-tools/issues/966) yet, but I don't care as `pip-compile` will be done manually/rarely
- Option B: in CI pipeline, use something like `sed` to inject the properly pinned version into the `requirements.txt`s
    - Line in `requriments.txt` before CI: `subpkg-dependency  # NOTE: CI will pin version`
    - During CI before `sdist`: `subpkg-dependency==1.2.3.dev45+g678abc9d`
    - Side effect: guaranteed sub-package version matchup for actual install from package index
    - Note: I can already make this happen with an extra CI step (see the OP's code snippet) before the `sdist` call

Option A is nice, but requires manual creation + updating of an local env variable (too much).  However, if `setuptools_scm` already supports this, it becomes a viable route.

Option B works, and having a `$SCM_VERSION` env var would let me simplify the CI pipeline by one step.

---

What do you think?

**Comment by RonnyPfannschmidt** [comment]
my recommendation is still a setuptools plugin that expand/changes the requirements as part of the configuration step

**Comment by jamesbraza** [comment]
Okay and thank you again!

The purpose of this ticket (asking if an `SCM_VERSION`-like environment variable exists) has been resolved, so closing this out!
