### ISSUE TITLE
UnicodeDecodeError parsing setup.cfg on Windows with UTF-8

### ISSUE THREAD

**Issue by jaraco** [pypa/setuptools-scm#760]
In https://github.com/jaraco/configparser/issues/58#issuecomment-1220878403, I discovered that setuptools_scm has the same bug as distutils/pip when it tries to parse a setup.cfg file that contains non-ascii (specifically non-codepage 1252).

Probably setuptools_scm shouldn't be parsing distutils/setuptools files manually, but if it must, it should honor utf-8.

**Comment by RonnyPfannschmidt** [comment]
@jaraco unfortunately setuptools hasn't rea the setup.cfg data when it invokes the hooks, so its not yet avoidable
