### ISSUE TITLE
How do you make it increment the major or minor?

### ISSUE THREAD

**Issue by yoav-klein** [pypa/setuptools-scm#764]
Hello,

I'm trying to understand - what if I want to increment the major or minor bit in my version? How do I do it with setuptools_scm?

**Comment by RonnyPfannschmidt** [comment]
The default version scheme supports Tag ging the next desired version as `v2.3.4.dev`

**Comment by RonnyPfannschmidt** [comment]
closing as not actionable due the lack of further feedback
