### ISSUE TITLE
Document changes in how setuptools_scm deals with LFs (hex 0A character)

### ISSUE THREAD

**Issue by jpl-jengelke** [pypa/setuptools-scm#774]
We switched from a `setup.py`-based config to a PEP-517/518 compliant config. In the switch, we upgraded `setuptools_scm` and now use `python3 -m build --wheel` to release.

**Expectation** is that _if the file version matches the tag version with no uncommitted changes reported_ that `setuptools_scm` will _not_ increment. However, unexpectedly, it does. 

Here's the [pyproject.toml](https://github.com/rzellem/EXOTIC/blob/main/pyproject.toml):
```
[tool.setuptools_scm]
write_to = "exotic/version.py"
write_to_template = '__version__ = "{version}"'
```

[See the attached command log to illustrate the issue -- 20221028_error_log_setuptools_scm.txt.](https://github.com/pypa/setuptools_scm/files/9890889/20221028_error_log_setuptools_scm.txt)
**This illustrates:**
- Version file matches tag version
- No uncommitted changes
- Version written by `setuptools_scm` was updated to only set numbers and tag was recreated. The `git log` and `git describe` entries show matching tag and commit hash.
- Build execution indicates unexpected increment in version
  - Old setup did not increment when version matched tag and no changes existed post tag

**Observations:** 
- At first glance it appears nothing is incorrect here regarding the expectations for`setuptools_scm` behavior. 
- Is `setuptools_scm` looking at ignored files to determine if the repo changes?
- Are there any settings that will [make it work like the older setup](https://github.com/rzellem/EXOTIC/tree/1.10.2)?

Because it appears that we are execution our build/release cycle correctly, I am reporting this as a bug.

**Comment by jpl-jengelke** [comment]
I think this verifies that the mere act of executing `setutools_scm` can change the file, even when versions stay the same. However, what changed? Control characters or something? 

Anyway, it looks like there is something wrong, or at least something difficult to see. ... 

```
workstation:EXOTIC jpl-jengelke$ cat exotic/version.py 
__version__ = "2.0.0"
workstation:EXOTIC jpl-jengelke$ git log -1
commit e08cb1710b13f31d9242dba606bcc84dd650158d (HEAD -> main, tag: 2.0.0)
Author: jpl-jengelke <email_obfuscated>
Date:   Fri Oct 28 11:06:02 2022 -0700

    Issue #988: Updating version to test setuptools_scm release versioning. ...
workstation:EXOTIC jpl-jengelke$ git diff
workstation:EXOTIC jpl-jengelke$ git status
On branch main
Your branch is ahead of 'origin/main' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
workstation:EXOTIC jpl-jengelke$ git describe
2.0.0
workstation:EXOTIC jpl-jengelke$ git describe --long
2.0.0-0-ge08cb17
workstation:EXOTIC jpl-jengelke$ python3 -m setuptools_scm
2.0.0
workstation:EXOTIC jpl-jengelke$ git diff
diff --git a/exotic/version.py b/exotic/version.py
index 8c0d5d5..849a10d 100644
--- a/exotic/version.py
+++ b/exotic/version.py
@@ -1 +1 @@
-__version__ = "2.0.0"
+__version__ = "2.0.1.dev0+ge08cb17.d20221028"
\ No newline at end of file
workstation:EXOTIC jpl-jengelke$ python3 -m setuptools_scm
2.0.1.dev0+ge08cb17.d20221028
workstation:EXOTIC jpl-jengelke$ python3 -m setuptools_scm
2.0.1.dev0+ge08cb17.d20221028
workstation:EXOTIC jpl-jengelke$ python3 -m setuptools_scm
2.0.1.dev0+ge08cb17.d20221028
workstation:EXOTIC jpl-jengelke$ git checkout exotic/version.py 
Updated 1 path from the index
workstation:EXOTIC jpl-jengelke$ python3 -m setuptools_scm
2.0.0
workstation:EXOTIC jpl-jengelke$ git diff
diff --git a/exotic/version.py b/exotic/version.py
index 8c0d5d5..5a6bc65 100644
--- a/exotic/version.py
+++ b/exotic/version.py
@@ -1 +1 @@
-__version__ = "2.0.0"
+__version__ = "2.0.0"
\ No newline at end of file
workstation:EXOTIC jpl-jengelke$ 
```

**Comment by jpl-jengelke** [comment]
OK, the problem is that setuptools_scm is not adding a linestop character (hex 0A) when it rewrites the version file: (Note that the dot in the below hexdump may represent an invisible control character.)
```
workstation:EXOTIC jpl-jengelke$ 
workstation:EXOTIC jpl-jengelke$ cat exotic/version.py | hexdump -C
00000000  5f 5f 76 65 72 73 69 6f  6e 5f 5f 20 3d 20 22 32  |__version__ = "2|
00000010  2e 30 2e 31 22 0a                                 |.0.1".|
00000016
workstation:EXOTIC jpl-jengelke$ python3 -m setuptools_scm
2.0.1
workstation:EXOTIC jpl-jengelke$ git diff
diff --git a/exotic/version.py b/exotic/version.py
index 159d48b..5719d15 100644
--- a/exotic/version.py
+++ b/exotic/version.py
@@ -1 +1 @@
-__version__ = "2.0.1"
+__version__ = "2.0.1"
\ No newline at end of file
workstation:EXOTIC jpl-jengelke$ cat exotic/version.py | hexdump -C
00000000  5f 5f 76 65 72 73 69 6f  6e 5f 5f 20 3d 20 22 32  |__version__ = "2|
00000010  2e 30 2e 31 22                                    |.0.1"|
00000015
workstation:EXOTIC jpl-jengelke$ 
```
I'm not sure if this is because of what it is getting from `pyproject.toml` or something else in the code. However, it's important to note that I cannot myself update the version number in the file, neither from `vi` nor the GitHub interface without the `0A` character being present.

**Comment by jpl-jengelke** [comment]
OK, it looks like there was behavior change in how things work, and it's OK. I just think it should be documented. 

So the LF character (`0A`) has to be explicitly specified in the TOML in `pyproject.toml` at the end of the version template. (TOML allows CTRL characters, unicode and escape sequences.)

`pyproject.toml` (good):
```
[build-system]
requires = [
    "cython~=0.29.32;platform_system!='Windows'",
    "oldest-supported-numpy",
    "setuptools>=62.6",
    "setuptools_scm[toml]>=6.4.2",
    "wheel>=0.37.1",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = 'exotic/version.py'
write_to_template = "__version__ = '{version}'\n"
```
Then the file (in this case `exotic/version.py`) can be edited with vi (or something) and contain:
```
__version__ = '2.0.2'
```
After that it worked. 

So this ticket is now just a request to document that the requirement that CTRL-characters must be explicitly specified in the TOML whereas using older implementations of setuptools and setuptools_scm works without that.

**Comment by RonnyPfannschmidt** [comment]
Version files should not be git tracked

**Comment by jpl-jengelke** [comment]
I see that version files are unsupported here (but [in some scenarios they are indeed tracked as a matter of course](https://packaging.python.org/en/latest/guides/single-sourcing-package-version/)). Personally I think tracking version files in certain use cases maximizes flexibility. That would allow a case where someone downloads a source ZIP and just runs code. 

Also, it is valuable to understand that hex 0A (LF) stopped being automatically written to the end of the `write_to_template` value.

**Comment by RonnyPfannschmidt** [comment]
Tracking files that always auto update by tooling is always going to bite, and im not going to accommodate that kinda usage as it introduces quite some maintenance /support burden


The intent of setuptools_scm is to get manually managed version files out of the scm, so it's totally OK if anyone that insist on keeping them in the scm suffers the consequences

**Comment by RonnyPfannschmidt** [comment]
As for downloading archives, git export Metadata may be used as reasonable approximate
