### ISSUE TITLE
Allow custom parsing for the version_tuple

### ISSUE THREAD

**Issue by onerandomusername** [pypa/setuptools-scm#775]
I'd like to be able to supply a custom parser for the tuple and parse the class provided by packaging.version.Version in a specific manner. 

I'm currently trying to fit setuptools_scm into a workflow where there is a VersionInfo tuple previously defined in the library itself.

(current code)
```py
class VersionInfo(NamedTuple):
    major: int
    minor: int
    micro: int
    releaselevel: Literal["alpha", "beta", "candidate", "final"]
    serial: int


version_info: VersionInfo = VersionInfo(major=2, minor=7, micro=0, releaselevel="alpha", serial=0)
```

Ideally, I would like to get a `packaging.version.Version` object and be able to return the tuple from that, which would be passed into the template unchanged.

(example, not entirely sure of the name)
```toml
[tool.setuptools_scm]
get_tuple = '''
def parse_tuple(version):
  fields = (version.major, version.minor, version.patch)
  fields += ('alpha' if version.pre else 'final',)
  fields += (version.dev or None,)
  return fields
'''
```

Paired with the above code as a template, this would allow me to move to setuptools_scm without causing a breaking change to the library's version indicators, or a runtime slowdown to compute this at runtime. 
This tuple can be set at build time, and that's where I'd like to do it if its possible.

**Comment by RonnyPfannschmidt** [comment]
The proposed solution is overreaching and won't be accepted

I can however accept a pr that adds the parsed version of the version string to the write_ti template

**Comment by onerandomusername** [comment]
> I can however accept a pr that adds the parsed version of the version string to the write_ti template

I'm sorry, I don't fully understand what you mean by "parsed version".

**Comment by RonnyPfannschmidt** [comment]
Currently only the tuple setuptools_scm provides is added to the template, I'm open to enable passing the SvmVersion object as well

**Comment by RonnyPfannschmidt** [comment]
current versions pass the scm_version object as scm_version
