### ISSUE TITLE
`tox` run results in `ModuleNotFoundError: No module named 'typing_extensions'`

### ISSUE THREAD

**Issue by zacharyburnett** [pypa/setuptools-scm#777]
when running tests with `tox` on a package using `setuptools_scm`, I get the following error:
```
_ ERROR collecting .eggs/setuptools_scm-7.0.5-py3.10.egg/setuptools_scm/_types.py _
.eggs/setuptools_scm-7.0.5-py3.10.egg/setuptools_scm/_types.py:15: in <module>
    from typing_extensions import ParamSpec, TypeAlias, Protocol
E   ModuleNotFoundError: No module named 'typing_extensions'
```
This issue did not occur yesterday and started today, as far as I can see.

These can been seen on Github Actions here: https://github.com/spacetelescope/jwst/actions/runs/3371837511/jobs/5607433908#step:9:158

**Comment by RonnyPfannschmidt** [comment]
its unclear why pytest picks up python files in a .eggs folder 
its also unclear why those exist, its possibly related to a setuptools update

please either preinstall setuptools_scm and/or use a more modern python packaging mechanism so that eggs wont end up in your worktree

**Comment by RonnyPfannschmidt** [comment]
Closing as seemingly resolved,
