### ISSUE TITLE
setuptools_scm example project code fails on Apple Silicon (ARM)

### ISSUE THREAD

**Issue by TimPansino** [pypa/setuptools-scm#778]
# Description

We've received multiple bug reports over at [New Relic](https://github.com/newrelic/newrelic-python-agent) about an inability to install on Apple Silicon (ARM). Pip seems unable to determine the version from an sdist, and it seems newer versions of pip will then discard the install and fail. One such public issue is [here](https://github.com/newrelic/newrelic-python-agent/issues/621). 

Our project uses pip, setuptools, and setuptools_scm. From what we can tell the bug is coming from here, but we've been unable to conclusively prove that the bug isn't related to pip or setuptools due to a lack of insight into the temporary environment. We've attempted to trace the 0.0.0 being returned up and down through editable installs of all 3 packages and ended up here, with the current conclusion that setuptools-scm fails to either write or read the metadata properly, doesn't seem to have any working fallbacks, and is causing issues with pip.

# Reproduction

I've constructed a fairly simplistic example project following the example code included for Setuptools SCM. After publishing to test.pypi.org I've been able to reproduce the failure. This should help avoid all the legacy installation complexity included in our repo.

[Example Project Repo](https://github.com/TimPansino/python-packaging-test)

The following command attempts to install the published version that definitely fails.

```bash
pip install -i https://test.pypi.org/simple --extra-index-url https://pypi.org/simple packaging-test-482c583e907c==0.1.6
```

# Error Messages

An example from the NewRelic package:

```
Collecting newrelic
  Using cached newrelic-8.0.0.179.tar.gz (881 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Discarding https://files.pythonhosted.org/packages/07/b9/44f9ab7751365d20fd81238455e9bc0964f65e425521fb021bbe300e5701/newrelic-8.0.0.179.tar.gz (from https://pypi.org/simple/newrelic/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*,!=3.5.*,!=3.6.*): Requested newrelic from https://files.pythonhosted.org/packages/07/b9/44f9ab7751365d20fd81238455e9bc0964f65e425521fb021bbe300e5701/newrelic-8.0.0.179.tar.gz has inconsistent version: filename has '8.0.0.179', but metadata has '0.0.0'
```

An example from the simple test package:

```
  WARNING: Requested packaging-test-482c583e907c==0.1.6 from https://test-files.pythonhosted.org/packages/3f/78/cdef55b6743f195ba41808320b273e4b5cf8c60a924d7781f9951cf83813/packaging-test-482c583e907c-0.1.6.tar.gz, but installing version 0.0.0
Discarding https://test-files.pythonhosted.org/packages/3f/78/cdef55b6743f195ba41808320b273e4b5cf8c60a924d7781f9951cf83813/packaging-test-482c583e907c-0.1.6.tar.gz (from https://test.pypi.org/simple/packaging-test-482c583e907c/) (requires-python:>=3.7): Requested packaging-test-482c583e907c==0.1.6 from https://test-files.pythonhosted.org/packages/3f/78/cdef55b6743f195ba41808320b273e4b5cf8c60a924d7781f9951cf83813/packaging-test-482c583e907c-0.1.6.tar.gz has inconsistent version: expected '0.1.6', but metadata has '0.0.0'
ERROR: Could not find a version that satisfies the requirement packaging-test-482c583e907c==0.1.6 (from versions: 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6)
ERROR: No matching distribution found for packaging-test-482c583e907c==0.1.6
```

# What We Know

The bug seems to not be present when:

* Our `pyproject.toml` file is deleted.
* We run inside a virtual environment in any way.
* We pre-install setuptools-scm into the local environment before installing the bugged package.
* The package is installed on any other architecture besides ARM based Macs. Tested and working as intended on:
  * ARM based Debian and Ubuntu.
  * x86 based Debian and Ubuntu
  * x86 based MacOS
* When installing from a wheel and not an sdist.

# Potentially Related

When attempting to build universal wheels for this project, none of the SCM tracked files were actually included in the wheel. This is completely unrelated to M1 Macs since it was building on a completely standard Ubuntu GitHub Actions runner. There are some older versions in the package on test.pypi like [this one](https://test.pypi.org/project/packaging-test-482c583e907c/0.1.2/#files) which included a wheel that installs but doesn't contain any actual python files. This seems coincidental but also broken and potentially another symptom.

# Links

* [Example Repo](https://github.com/TimPansino/python-packaging-test)
* [Example PyPi Package](https://test.pypi.org/project/packaging-test-482c583e907c/)
* [NewRelic Project](https://github.com/newrelic/newrelic-python-agent)

**Comment by RonnyPfannschmidt** [comment]
At first glance there are multiple packaging mistakes (starting at the incomplete pyproject.toml)

I'll have to do dig a little more later

It's strongly recommended to stop using setup_requires and start using pep517

If that is not feasible it is critical to preinstall setuptools_scm

More details later today

**Comment by TimPansino** [comment]
Any other details on this? What packaging mistakes do you see in the example project? This doesn't look particularly different from the examples.

```
[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "packaging-test-482c583e907c/_version.py"
```

**Comment by RonnyPfannschmidt** [comment]
I haven't been able to get back to this

The output with SETUPTOOLS_SCM_DEBUG would be a good help

**Comment by fruch** [comment]
> I haven't been able to get back to this
> 
> The output with SETUPTOOLS_SCM_DEBUG would be a good help

I'm guessing the issue is:
https://github.com/pypa/pip/issues/11539

and upgrade to latest pip might solve it

**Comment by RonnyPfannschmidt** [comment]
im closing this issue as no more details to debug where provided and the new information seems to indicate a upstream issue

if new information come up that point to setuptools_scm please provide them in a new issue, thanks

**Comment by fruch** [comment]
> > I haven't been able to get back to this
> > 
> > The output with SETUPTOOLS_SCM_DEBUG would be a good help
> 
> I'm guessing the issue is:
> https://github.com/pypa/pip/issues/11539
> 
> and upgrade to latest pip might solve it
> 

Upgrade to latest pip (2022.3.1) won't be enough installing pip from main branch do help, the fix didn't got to any release of pip yet.
