### ISSUE TITLE
Using a custom version_scheme outside setup.py

### ISSUE THREAD

**Issue by kasium** [pypa/setuptools-scm#781]
setuptools_scm allows to use a custom version_scheme function. When not using `setup.py` this needs to be an entry-point name. However, this doesn't work logically. When the project is installed (e.g. `pip install -e .`), setuptools asks setuptools_scm for the version tp install the project. But the project is not installed at that point and therefore the entry point is not accessible. Then, the install will fail due to `assert main_version is not None`.
Can you please check how to solve this chicken-egg issue?

One idea - Support qualified names: Instead of an entry-point give the qualified name to a function and setuptools_scm will execute it

**Comment by kasium** [comment]
@RonnyPfannschmidt  had you some time to look into this? Is there anything I can support with?

**Comment by RonnyPfannschmidt** [comment]
Haven't been able to look at it, I'm currently unable to give much time to setuptools_scm
