### ISSUE TITLE
Add CLI without calling the module via `python -m setuptools_scm`

### ISSUE THREAD

**Issue by ketozhang** [pypa/setuptools-scm#786]
Furthermore it allows me to install this tool with pipx, currently not possible.

**Comment by webknjaz** [comment]
Alternatively, use https://github.com/mtkennerly/dunamai, maybe?

**Comment by RonnyPfannschmidt** [comment]
`pipx run --spec setuptools_scm python -m setuptools_scm` works, wouldn't mind a 3rd party contrib for it tho
