### ISSUE TITLE
[feature] provide more information

### ISSUE THREAD

**Issue by Freed-Wu** [pypa/setuptools-scm#791]
Now this package only provide `__version__` for program's `--version`.
Can this package provide more information, for example, the first git commit is
in 2020, and the latest git commit is 2022, can it generate `__copyright__ =
"2020-2022"` for program use, like

```console
$ foo --version
foo 0.0.1
Copyright (C) 2020-2022
Written by USERNAME.
```

And can it provide USERNAME from `pyproject.toml`?
Such as

```toml
[project]
authors = [{ name = "foo", email = "bar@gmail.com" }]
```

will

```console
$ foo --version
foo 0.0.1
Copyright (C) 2020-2022
Written by foo <bar@gmail.com>.
```

by provide `__author__`?

This version info is a standard form of [GNU help2man](https://www.gnu.org/software/help2man).

Thanks!

**Comment by RonnyPfannschmidt** [comment]
This would be vastly more complicated, currently i don't see a compelling reason to create something like that

**Comment by Freed-Wu** [comment]
> This version info is a standard form of [GNU help2man](https://www.gnu.org/software/help2man).

This may be a reason.

**Comment by RonnyPfannschmidt** [comment]
I never had any contract with that toolset, I'm not aware of python workflows surrounding those either

I don't have the bandwidth to create and maintain support for very uncommon toolsets

In particular if they expand scope in a potentially error prone manner

**Comment by Freed-Wu** [comment]
ok, I see.
