### ISSUE TITLE
Hidden files no longer required for git archive?

### ISSUE THREAD

**Issue by kwinkunks** [pypa/setuptools-scm#793]
In [the docs](https://pypi.org/project/setuptools-scm/) under *Git archives*, it states that in order for the version number to be retrieved from tags, some special content is required in 2 files: `.git_archival.txt` and `.gitattributes`.

However, after comparing notes with a colleague, it seems like the two files might not actually be required. I tried removing them and I _think_ everything is working properly. Am I missing something, or can these files be dispensed with now?

The project I'm building: https://github.com/kwinkunks/unmap (except without those 2 files)

The content of `unmap/_version.py` (which is not in the archive) is being updated, e.g.:

```
# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.3rc2.dev1+g77e7a8a.d20221205'
__version_tuple__ = version_tuple = (0, 1, 3, 'dev1', 'g77e7a8a.d20221205')
```

The versioning code [is in `unmap/__init__.py`](https://github.com/kwinkunks/unmap/blob/main/unmap/__init__.py#L6-L17).

**Comment by RonnyPfannschmidt** [comment]
more context is needed, classically git does not include the metadata needed to do this, so please show how you actually build things in a way i can repeat directly

**Comment by kwinkunks** [comment]
I'm sorry, I was not paying attention and missed this question.

I'm building the project with `python -m build`.

**Comment by RonnyPfannschmidt** [comment]
@kwinkunks basically these files are needed for when someone pulls a git tag download
the artifacts build with `python -m build` do already include the metadata
but downloads from github tag archives dont

**Comment by kwinkunks** [comment]
Okay, I think I understand. Thank you for explaining that.

So since the artifacts include the metadata (I now see the version in PKG-INFO and in the wheel metadata), why do I need setuptools_scm to write to the `_version.py` file? Can I also skip that part? Or does this file cover some other scenario?

**Comment by RonnyPfannschmidt** [comment]
the _version.py file is commonly used as importing a module sometimes is orders of magnitude faster than loading the package metadata

in the old pkg_resources times loading the metadata could be as expensive as 0.2 seconds or even more

which is absolute horrendous when you want very quick cli commands 

even with importlib.metadata the delay can be noticeable

**Comment by kwinkunks** [comment]
Wonderful, thank you for the clarification :raised_hands: I will close this issue if there's no objection.
