### ISSUE TITLE
Version with just commit hash

### ISSUE THREAD

**Issue by jinlow** [pypa/setuptools-scm#809]
First of all, thanks for a very slick and easy to use package!
Is it possible to use this package to make the package version, only be the commit hash?
It's not super clear to me how to customize the behavior of `setuptools_scm`, without docs or many usage examples.
I see the options listed in the README [here](https://github.com/pypa/setuptools_scm#configuration-parameters), are there examples of using the options outside of the examples showing them in `setup.py` which has been deprecated?
Thanks!

**Comment by RonnyPfannschmidt** [comment]
its not clear what you are asking for - a commit hash ist NOT a valid version on its own

while its possible to get there in a hackish way, under no circumstances its suitable for something you release

**Comment by jinlow** [comment]
Hi @RonnyPfannschmidt - I understand it's not a valid version per se. 
This would be for a package, not released to pypi, but rather only being used in an internal workflow. We don't really care about a standard "version", but really only care about being able to identify which git commit the package was built with. Which is why I was wondering about using this package to accomplish this.

Would you have any hints, to point me towards how to do this, even in an hackish way :)

**Comment by RonnyPfannschmidt** [comment]
then i would recommend to just use a version scheme that always includes the git commit as local tag

something like calver by date for the normal version, and the default node versioning forthe local part

if you never tag, it will allways dutifully add the node at the end - if you tag it will skip it

in case you use hatch there are extra options to let hatchformat the commit id into links of the metadata

**Comment by jinlow** [comment]
Thanks @RonnyPfannschmidt, I’m still unclear how to specify these settings? This would just be something I would put in my `pyproject.toml`?
Sorry if this is a silly question, maybe I am missing some examples in the docs or something, that would show how to do these kinds of customizations.

**Comment by RonnyPfannschmidt** [comment]
Yes, one we use version scheme and local scheme

**Comment by Narutoworld** [comment]
Hi @jinlow
I want to use this package in a similar way as you described, did you have it running ?
Could you share more details ?

**Comment by RonnyPfannschmidt** [comment]
Closing as seemingly solved

Examples will be expanded in the next version
