### ISSUE TITLE
Suddenly using wrong version after installing previous version from pypi

### ISSUE THREAD

**Issue by antazoey** [pypa/setuptools-scm#817]
1. I started out with a python package installed in editable mode.
2. I installed previous release from a few versions ago from PYPI to test something.
3. Then, I tried to re-install the package back into editable mode, but now it is using 1 version higher than the older version I had installed rather than the latest tag.

I can't seem to get it back on the latest tag! I ran `git clean -xfd`. I have all the right tags. I don't know why it is stuck thinking the old version is latest

**Comment by antazoey** [comment]
I re-cloned the repo and it is using the expected version again, but am curious if there is an easier resolution for next time.

**Comment by RonnyPfannschmidt** [comment]
It's not quite clear what had happened

This should not happen

**Comment by RonnyPfannschmidt** [comment]
closing as i cant reproduce and extra details are missing
