### ISSUE TITLE
Debian packaging issues

### ISSUE THREAD

**Issue by brianmay** [pypa/setuptools-scm#83]
It is common practise to take the PyPI source of a package and put it into another git with packaging for Debian.

However this confused setuptools_scm, it appears to look at the Debian git packaging instead of the correct upstream version stored in the *.egg-info/PKG-INFO file. Somehow it gets confused when it sees a list of tags like:

```
debian/1.3.2-1
debian/1.4.1-1
patched/1.3.2-1
patched/1.4.1-1
upstream/1.3.2
upstream/1.4.1
```

and thinks the next version should be something like `2.dev12+ngfbfb690`

Is it possible to somehow force setuptools_scm to use the version from the egg-info file? Preferably without needing to patch the source tree?

Or maybe setuptools_scm can't find a sane version tag, it should revert to looking at egg-info anyway?

**Comment by RonnyPfannschmidt** [comment]
starting with version `1.10.0` set the environment variable `SETUPTOOLS_SCM_PRETEND_VERSION`

**Comment by brianmay** [comment]
Ok, that is a cleaner work around then the one I had. Thanks.

However just setting it to a predefined version number means I have the version hard coded and need to remember to update it. 

Hmm... Something like the following might work, what do you think?

```
export SETUPTOOLS_SCM_PRETEND_VERSION="$(cat django_guardian.egg-info/PKG-INFO | sed -n 's/^Version: //p')"
```

**Comment by brianmay** [comment]
In Makefile syntax that should be:

```
export SETUPTOOLS_SCM_PRETEND_VERSION=$(shell cat django_guardian.egg-info/PKG-INFO | sed -n 's/^Version: //p')
```

**Comment by RonnyPfannschmidt** [comment]
off hand no idea, i'm not a make/shell magician - should be fine if it works

**Comment by RonnyPfannschmidt** [comment]
@brianmay any opinion on having way to declare a cleanup function for the tags?

that way you could generate versions that spell +Debian as local versions that indicate patches

**Comment by brianmay** [comment]
pybuild, the modern tool for building Debian packages, now automatically sets `SETUPTOOLS_SCM_PRETEND_VERSION` based on the latest entry in debian/changelog.

Possibly a change like this could help some people; for my work flows however I think I just make sure the appropriate version is in the latest debian/changelog entry.

**Comment by RonnyPfannschmidt** [comment]
@brianmay i see, can this one be closed then?

**Comment by brianmay** [comment]
Ronny Pfannschmidt notifications@github.com writes:

> @brianmay i see, can this one be closed then?

## Probably - I don't see why not.

Brian May brian@linuxpenguins.xyz
https://linuxpenguins.xyz/brian/

**Comment by RonnyPfannschmidt** [comment]
thanks
