### ISSUE TITLE
Cannot use my own version_scheme function (obtain version from changelog)

### ISSUE THREAD

**Issue by vanheck** [pypa/setuptools-scm#832]
I'd like to use `setuptools_scm` for funcionality of call my own function to obtain version from `Changelog.md` and add  `local_scheme`.
I tought it should be done by changing the `version_scheme` to set to my function.

My version scheme in `pkg/version.py`:
```py
def my_version_scheme(version):
    v = parse_version_from_changelog()
    return f"{v}"
```

And `pyproject.toml`:
```toml
[project]
dynamic = ["version"]

[tool.setuptools_scm]
version_scheme = "pkg.version:my_version_scheme"
```

But I'm getting the output:
```sh
# python -m setuptools_scm
Traceback (most recent call last):
  File "/opt/conda/envs/python39/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/python39/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/envs/python39/lib/python3.9/site-packages/setuptools_scm/__main__.py", line 6, in <module>
    main()
  File "/opt/conda/envs/python39/lib/python3.9/site-packages/setuptools_scm/_cli.py", line 35, in main
    version = _get_version(config)
  File "/opt/conda/envs/python39/lib/python3.9/site-packages/setuptools_scm/__init__.py", line 156, in _get_version
    version_string = format_version(
  File "/opt/conda/envs/python39/lib/python3.9/site-packages/setuptools_scm/version.py", line 558, in format_version
    assert main_version is not None
AssertionError
```

versions:
```sh
# conda list | grep setuptools
setuptools                67.6.1                   pypi_0    pypi
setuptools-scm            7.1.0                    pypi_0    pypi
types-setuptools          67.6.0.6                 pypi_0    pypi
```

Probably the problem is in [filter of Entrypoints](https://github.com/pypa/setuptools_scm/blob/main/src/setuptools_scm/_entrypoints.py#L79) and not functionality of adding my function to them?

Or what I'm doing wrong?

**Comment by RonnyPfannschmidt** [comment]
With most build backends random local code cannot be imported

I plan to add support fit that in 8.x

**Comment by RonnyPfannschmidt** [comment]
as i was just re-reading this feature request, i have to close it as wrong/invalid

files with user-written version strings are not a canonical source of truth and are rejected as valid version source
they may be used as input for determining a version/semver bump (i intend to add towncrier and scriv based bumps)

there wil lbe helper to specify custom parse/annotate steps for obtaining the ScmVersion
