### ISSUE TITLE
Customizing Version Scheme with pyproject.toml is broken

### ISSUE THREAD

**Issue by ZhiyuanChen** [pypa/setuptools-scm#835]
I set `pyproject.toml` as the document,

```
[tool.setuptools_scm]
version_scheme = "versioning:get_version"
write_to = "package/_version.py"
```

And create a new `versioning.py` which contains

```python
from setuptools_scm import ScmVersion


def get_version(version: ScmVersion):
    from setuptools_scm.version import guess_next_version

    return version.format_next_version(guess_next_version, "{guessed}b{distance}")
```

However, the following error is arised:

```
Traceback (most recent call last):
  File "/mnt/shared/mamba/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/mnt/shared/mamba/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/mnt/shared/mamba/lib/python3.10/site-packages/setuptools/__init__.py", line 108, in setup
    return distutils.core.setup(**attrs)
  File "/mnt/shared/mamba/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 147, in setup
    _setup_distribution = dist = klass(attrs)
  File "/mnt/shared/mamba/lib/python3.10/site-packages/setuptools/dist.py", line 488, in __init__
    _Distribution.__init__(
  File "/mnt/shared/mamba/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
    self.finalize_options()
  File "/mnt/shared/mamba/lib/python3.10/site-packages/setuptools/dist.py", line 912, in finalize_options
    ep(self)
  File "/mnt/shared/mamba/lib/python3.10/site-packages/setuptools_scm/integration.py", line 127, in infer_version
    _assign_version(dist, config)
  File "/mnt/shared/mamba/lib/python3.10/site-packages/setuptools_scm/integration.py", line 60, in _assign_version
    maybe_version = _get_version(config)
  File "/mnt/shared/mamba/lib/python3.10/site-packages/setuptools_scm/__init__.py", line 156, in _get_version
    version_string = format_version(
  File "/mnt/shared/mamba/lib/python3.10/site-packages/setuptools_scm/version.py", line 558, in format_version
    assert main_version is not None
AssertionError
```

**Comment by RonnyPfannschmidt** [comment]
This is currently expected, setuptools_scm does no pythonpath manipulation yet

**Comment by bhazelton** [comment]
But isn't this just following the example in the readme?

**Comment by RonnyPfannschmidt** [comment]
@bhazelton not at all

None of the examples try to get local code from pyproject.toml

**Comment by bhazelton** [comment]
Ok, then I am misunderstanding this section of the readme: https://github.com/pypa/setuptools_scm#customizing-version-scheme-with-pyprojecttoml

It _seems_ like that is pointing at a local function `myversion_func`

**Comment by CamilleMo** [comment]
> Ok, then I am misunderstanding this section of the readme: https://github.com/pypa/setuptools_scm#customizing-version-scheme-with-pyprojecttoml
> 
> It _seems_ like that is pointing at a local function `myversion_func`

Hello, so we are two to misunderstand the readme. Is there a way to define a custom implementation for local/version_scheme by writing some code ? When I try to reproduce the example in the readme I get the same error as  @ZhiyuanChen : `assert main_version is not None`

**Comment by RonnyPfannschmidt** [comment]
Now that I am re-reading, it seems like when the feature was added, i missed a import detail that should get more explicit documentation

The next release will include a working version, but needs a resolution of a project management hick up, and I'm currently very thin stretched when it comes to doing opensource work

**Comment by CamilleMo** [comment]
Ok thanks for your swift reply. Great ! This is good news. Thanks a lot for your work

**Comment by ZhiyuanChen** [comment]
Thanks to everyone! 

I looked into it a bit, it seems like https://github.com/pypa/setuptools_scm/blob/main/src/setuptools_scm/_entrypoints.py#L106-L111 currently returns `None`.

```python
    if isinstance(scheme_value, str):
        scheme_value = cast(
            "_t.VERSION_SCHEMES",
            _get_ep(entrypoint, scheme_value)
            or _get_from_object_reference_str(scheme_value),
        )
```

I guess, `_get_from_object_reference_str(scheme_value)` should have returned function defined in `versioning:get_version`, but got None. 
@RonnyPfannschmidt if I'm right, would you mind if I submit a patch?

**Comment by RonnyPfannschmidt** [comment]
There may be a need to reevaluate the exact spelling depending on whether path manipulation is necessary

**Comment by ZhiyuanChen** [comment]
> There may be a need to reevaluate the exact spelling depending on whether path manipulation is necessary

I have tried my best (it's 4 a.m. beijing time) but I couldn't find another way around manipulating sys.path ...

I assume we don't want to use some hacky ways (i.e. `os.getcwd()`), so to get the source root, we must use `config.absolute_root`. 
The only place where `config.absolute_root` is available is `_get_version`.
So, here is #836 

I believe we could also pass `config.absolute_root` to `format_version`, and all the way to `_get_from_object_reference_str` and import it with `importlib.util.spec_from_file_location` and `importlib.util.module_from_spec` there, see more in #837

Sorry I'm not familiar with importlib, please let me know if there is a better way.

**Comment by RonnyPfannschmidt** [comment]
What I meant was that we needs a way to be explicit about sys.path manipulation

**Comment by OliverKleinBST** [comment]
I put some debug into _entrypoints.py:iter_entry_points
and it seems there is some problem with the argument "name" when we scan through the entrypoints:

**search for the following "group"**
**setuptools_scm.version_scheme**
leads to
(EntryPoint(name='calver-by-date', value='setuptools_scm.version:calver_by_date', group='setuptools_scm.version_scheme'), EntryPoint(name='guess-next-dev', value='setuptools_scm.version:guess_next_dev_version', group='setuptools_scm.version_scheme'), EntryPoint(name='no-guess-dev', value='setuptools_scm.version:no_guess_dev_version', group='setuptools_scm.version_scheme'), EntryPoint(name='post-release', value='setuptools_scm.version:postrelease_version', group='setuptools_scm.version_scheme'), EntryPoint(name='python-simplified-semver', value='setuptools_scm.version:simplified_semver_version', group='setuptools_scm.version_scheme'), EntryPoint(name='release-branch-semver', value='setuptools_scm.version:release_branch_semver_version', group='setuptools_scm.version_scheme'))
but now we search for the following "name"
**setuptools_scm.version:no_guess_dev_version**
in the following list
calver-by-date
guess-next-dev
no-guess-dev
post-release
python-simplified-semver
release-branch-semver

so eventually we should not compare to the name field but to the value field:
instead of 
return (ep for ep in eps if ep.name == name)
fo
return (ep for ep in eps if **ep.value** == name)

In that case my example config actually seems to work:
version_scheme = "setuptools_scm.version:no_guess_dev_version"

**Comment by oz123** [comment]
This is very misleading. I also read the description and thought that I can use a custom function to format my own version.

What works is adding a custom function in setup.py. As described. However, if you use setup.py, you are forced to use:
```
python setup.py sdist # this reads setup.py
```
As `build` does not work, 
```
python -m build -s # does not read setup.py
```

**Comment by RonnyPfannschmidt** [comment]
i reached a different conclusion - for setuptools a setup.py will be needed to pass in code - setuptools_scm will not add a import path manipulation mechanism

**Comment by ZhiyuanChen** [comment]
> i reached a different conclusion - for setuptools a setup.py will be needed to pass in code - setuptools_scm will not add a import path manipulation mechanism

Could you please add document on how to use setup.py to pass the func?

**Comment by RonnyPfannschmidt** [comment]
the basi  gist is something along the lines of

```python
# setup.py
from setuptools import setup
from setuptools_scm import ScmVersion

def version_for_project(version: ScmVersion) -> str:
   return "1.2.3"
   
setup(use_scm_version={'version_scheme':version_for_project})
```

i started working on a mkdocs based documentation tree with more details

**Comment by ZhiyuanChen** [comment]
> i started working on a mkdocs based documentation tree with more details

I'm actually quite familiar with MkDocs and mkdocstring, see [my website](https://zyc.ai) and some of my project: [CHANfiG](https://chanfig.danling.org) and [DanLing](https://danling.org). Is there anything I can do?
