### ISSUE TITLE
accessing more template variables in write_to_template, eg node

### ISSUE THREAD

**Issue by graingert** [pypa/setuptools-scm#839]
I'd like to be able to set:

```
write_to_template = '__version__ = "{version}"\n__git_revision__ = "{node}"'
```

however only the `{version}` and `{version_tuple}` template variables are available to the template

**Comment by RonnyPfannschmidt** [comment]
the scm_version variable is now avaliable on main, im currently avoiding writing a custom formatter

**Comment by ofek** [comment]
Sorry, how would that be used?

**Comment by graingert** [comment]
@RonnyPfannschmidt which PR was this closed by?

**Comment by RonnyPfannschmidt** [comment]
#854
