### ISSUE TITLE
Tagged version only created correctly when not running on the main branch

### ISSUE THREAD

**Issue by aranvir** [pypa/setuptools-scm#844]
I have a gitlab pipeline to build my wheels. I wanted the following result:
- On tag: build wheel with version from tag. No dev, dirty, clean whatever, just: 1.0.0
- Push to main: guess-next-dev, ergo 1.1.0.dev10 or something
- Push to any other branch: guess-next-dev plus commit, ergo 1.1.0.dev10+g005dfe

This works fine except for tagging, but in a confusing way:
- When I tag the main branch with 1.0.0, I get: 1.0.0+g5w8e6a
- When I tag any other branch with 1.0.0, I get: 1.0.0

I had no tags on the repository, but even after adding tags, the behavior stays the same (tagging the main branch gives the wrong version, tagging any other branch gives the correct version).

I'm using `setuptools-67.7.2` and `setuptools-scm-7.1.0`.

My custom version is defined in `setup.py` as. All other stuff is in a `pyproject.toml`.
```python
import setuptools
from setuptools_scm.version import ScmVersion


def custom_version():
    def custom_local_scheme(version: ScmVersion):
        if version.branch == "main":
            return version.format_choice("", "")
        else:
            return version.format_choice("+{node}", "+{node}")

    return {
        'version_scheme': 'guess-next-dev',
        'local_scheme': custom_local_scheme
    }


setuptools.setup(use_scm_version=custom_version)
```

**Comment by aranvir** [comment]
Nevermind, I'm stupid. Other branch had some stuff deleted for debugging... realized I need to check for version.exact on my `custom_version()` callback.

```python
import setuptools
from setuptools_scm.version import ScmVersion


def custom_version():
    def custom_local_scheme(version: ScmVersion):
        if version.branch == "main" or version.exact is True::
            return version.format_choice("", "")
        else:
            return version.format_choice("+{node}", "+{node}")

    return {
        'version_scheme': 'guess-next-dev',
        'local_scheme': custom_local_scheme
    }


setuptools.setup(use_scm_version=custom_version)
```

**Comment by RonnyPfannschmidt** [comment]
Thanks for the follow
That type of thing can sometimes steal days 😊
