### ISSUE TITLE
support the parsing of custom tag styles

### ISSUE THREAD

**Issue by wcooley** [pypa/setuptools-scm#87]
We tag our releases with "**tag/x.y.z**" (don't ask), which causes an _AssertionError_ in `setuptools_scm/version.py/meta()` because `pkg_resources.parse_version` returns _None_ in `tag_to_version`.

All I need is to filter my tag to trim those 4 characters from the beginning: `lambda tag: tag[4:]`,
which makes re-implementing `parse` a bit overkill.

As an experiment, I've monkey-decorated `meta` in my `setup.py`, but it's too ugly for me to be happy schelpping about to all my projects:

``` python
import setuptools_scm.version
meta = setuptools_scm.version.meta
setuptools_scm.version.meta = lambda tag, *args, **kwargs: \
    meta(tag[4:], *args, **kwargs)
```

It would be much nicer to have a `cleanup_tag` callable for `use_scm_version`:

``` python
setup( ...
    use_scm_version={'cleanup_tag': lambda tag: tag[4:]}
    ...
)
```

I can imagine that there are plenty of other potential users in a similar situation, given the variety of release tag naming that I've seen in various repos.

**Comment by RonnyPfannschmidt** [comment]
please show the exception

**Comment by wcooley** [comment]
Are you suggesting that it should be able to handle a tag like "tag/1.0.0"?

My description was a _bit_ wrong; `pkg_resources.parse_version` returns an instance of `SetuptoolsLegacyVersion` instead of `SetuptoolsVersion`:

``` python
>>> import pkg_resources
>>> type(pkg_resources.parse_version('1.0.0'))
<class 'pkg_resources.SetuptoolsVersion'>
>>> type(pkg_resources.parse_version('tag/1.0.0'))
<class 'pkg_resources.SetuptoolsLegacyVersion'>
```

So the `if isinstance(version, SetuptoolsVersion):` in `tag_to_version` fails and falls off the end and `tag_to_version` returns `None`. Here's the backtrace:

```
$ python setup.py --version
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    use_scm_version=True,
  File "/usr/lib64/python3.4/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "myvenv/lib/python3.4/site-packages/setuptools/dist.py", line 272, in __init__
    _Distribution.__init__(self,attrs)
  File "/usr/lib64/python3.4/distutils/dist.py", line 280, in __init__
    self.finalize_options()
  File "myvenv/lib/python3.4/site-packages/setuptools/dist.py", line 327, in finalize_options
    ep.load()(self, ep.name, value)
  File "testdist/.eggs/setuptools_scm-1.11.0-py3.4.egg/setuptools_scm/integration.py", line 19, in version_keyword
  File "testdist/.eggs/setuptools_scm-1.11.0-py3.4.egg/setuptools_scm/__init__.py", line 104, in get_version
  File "testdist/.eggs/setuptools_scm-1.11.0-py3.4.egg/setuptools_scm/__init__.py", line 69, in _do_parse
  File "testdist/.eggs/setuptools_scm-1.11.0-py3.4.egg/setuptools_scm/__init__.py", line 30, in version_from_scm
  File "testdist/.eggs/setuptools_scm-1.11.0-py3.4.egg/setuptools_scm/__init__.py", line 36, in _version_from_entrypoint
  File "testdist/.eggs/setuptools_scm-1.11.0-py3.4.egg/setuptools_scm/git.py", line 39, in parse
  File "testdist/.eggs/setuptools_scm-1.11.0-py3.4.egg/setuptools_scm/version.py", line 86, in meta
AssertionError: cant parse version None
```

(You might also want to store the original value of `tag` in `meta()` and include that in the `assert` message.)

I made a minimal project `setup.py`:

``` python
import setuptools; setuptools.setup(name='testdist',
        setup_requires=['setuptools_scm'],
        #version='1.0.0',
        use_scm_version=True,
)
```

I toggled comments on `version` and `use_scm_version` to confirm that without `use_scm_version` enabled `python setup.py --version` worked. Then I toggled back, `git` `init`'d, `add`'d, `commit`'d & `tag -a`'d "**tag/1.0.0**", then ran `python setup.py --version` and got the above traceback.

I suppose you could add `SetuptoolsLegacyVersion` to the `tag_to_version` conditional, but I'd still rather not have the "**tag/**" in the version string.

| Package | Version |
| --- | --- |
| Python | 2.7.11, 3.3.6, 3.4.3, 3.5.1 |
| setuptools | 21.0.0, 21.1.0 |
| setuptools_scm | 1.11.0 |

**Comment by RonnyPfannschmidt** [comment]
ok, i understood the actual issue

with the current parsers in setuptools, only version tags using direct versions and versions using the `v` prefix are supported

i'm reluctant to add this kind of cleanup myself, since one of the key ideas behind this too is to standardize on something everyone can use without modifications,
now if everybody comes along and puts in another hook to support yet another special scheme,
the whole point of having a tool that makes a standard becomes moot

**Comment by jaraco** [comment]
I recognize the necessity to encourage best practices, but I'd be in favor of an opt-in hook that provides arbitrary logic, such that for a project (or team) that doesn't follow these practices, there's a straightforward workaround. There's still incentive for them to move to best practices to eliminate the use of this hook. I imagine something like:

``` python
parse_tag = lambda tag: re.match('tag/(.*)', tag).group(0)
setup(
    use_scm_version={'parse_tag': parse_tag}
)
```

Setuptools_scm would discard any tags that raise an exception by parse_tag.

I haven't looked too deeply into this and I sort-of expected it was already supported because hgtools had something like this. I would like to see the OP's use case supported.

**Comment by RonnyPfannschmidt** [comment]
@jaraco with your proposed naming i see less of a problem with the addition

**Comment by RonnyPfannschmidt** [comment]
i'm closing this one due to lack of own followup, i'm happy to accept a implementation, but not a open issue

**Comment by wcooley** [comment]
That's fine; I changed my naming scheme to remove the prefix. I think I made a first cut back then but it was too messy and after thinking through a better design I decided it would require deeper changes than I would be able to muster.

**Comment by hardkrash** [comment]
Just wanted to switch to this tool and discovered that I cannot use the tool as we keep our release tags in a separate namespace  `releases/M.m.p` so build tools to only build and release the explicitly tagged releases.

The simplest fix would to look at the `basename` of the tag and use it.
An alternative fix would be to use a `re` that provides an extraction.
e.g. `'^v?(?P<version>\d+\.\d+\.\d+)$'`

And as a user I could override this `re` with `'^releases/v?(?P<version>\d+\.\d+\.\d+)$'`

**Comment by jaraco** [comment]
@hardkrash, that sounds like a slightly refined description of what I've proposed above, which if an acceptable implementation existed, we would merge. Would you consider devising an impl.?

**Comment by wcooley** [comment]
@hardkrash The hack I'd employed was the following in my `setup.py`:

```python
try:
    # Monkey-decorate `meta` to strip 'tag/' off release tags
    import setuptools_scm.version
    meta = setuptools_scm.version.meta
    setuptools_scm.version.meta = lambda tag, *args, **kwargs: \
        meta(tag[4:], *args, **kwargs)
except ImportError:
    # At the beginning of a tox build in a clean virtualenv, `setuptools_scm`
    # is not yet installed when it runs `pip install setuptools_scm .[TEST] ...`
    # so the above import fails. But the version doesn't matter, because it's
    # just querying for dependencies.
    use_scm_version = False
else:
    use_scm_version = True
```

Replace the `tag[4:]` with `tag[9:]` for your case or replace the whole lambda with something more powerful.
