### ISSUE TITLE
Automatic search of an SCM root? (should not rely on relative paths) 

### ISSUE THREAD

**Issue by dantrag** [pypa/setuptools-scm#871]
I have a large project where Python modules are located somewhat deep:
```
root
├─ .git
├─ other stuff
└─ python
   └─ modules
      └─ mymodule
         ├─ src
         │  └─ mymodule
         │     └─ __init__.py
         └─ pyproject.toml
 ```

 It feels quite wrong to write `root="../../.."`, because a Python module should be as self-contained as possible, and it is not its responsibility to know where it is located in a bigger project. What is worse, to be able to write a version file, I have to write `write_to="python/modules/mymodule/src/mymodule/version.py"` instead of `write_to="src/mymodule/version.py`. Python module should not be responsible for knowing the `python/modules/` path.

#### Suggestion 1
Is it problematic to go up in the tree from the `pyproject.toml` and look for a `.git` folder or until we are able to extract a version? Maybe do this as the first fallback if version extraction failed with `root="."`. Even if this is enabled with something like `root="auto"` it would be great and make life easier for a lot of people.

#### Suggestion 2
Make `write_to` relative to `"."` and not `"root"`. The latter is only responsible for looking for an SCM root, writing a version file is a different area of responsibility. (+how often does one have to write a version.py file outside the current module?) Otherwise `write_relative_to` option defaulting to `"."` would be convenient as well.

_If there is an existing way of doing what I want, I would be grateful for a hint._

**Comment by RonnyPfannschmidt** [comment]
Root must be declared relative to the project configuration thanks to numerous project's Messing around with SCM folders in surprising locations

There's the search parents option to set up unsafe search of the scm root

write-to will be replaced with a correct relative path,

The initial mistake combined with external adoption means fixing it with the same name would constitute a surprise breaking change

**Comment by dantrag** [comment]
Thanks! It seems like a little hidden feature, I couldn't find it in any documentation :) But it was exactly what I would like to see:
```
[tool.setuptools_scm]
write_to = "src/mymodule/version.py"
search_parent_directories = "true"
```
Now I can safely move the module around and re-use it.

**Comment by RonnyPfannschmidt** [comment]
There was a short while where this behavior was the default, however numerous bug reports came in as results, unfortunately it's not safe in general

**Comment by dantrag** [comment]
Interesting, I imagine being able to specify arbitrary paths is also not safe 😛 Either way, thanks for the great work you are doing, cannot be appreciated enough!

**Comment by RonnyPfannschmidt** [comment]
Being able to define project specific bases is at least safer than nothing

That being said, since you brought it to my attention, it is most likely safer to specify the expected sub directory
