### ISSUE TITLE
path to write_to relative to what?

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [pypa/setuptools-scm#875]
I have a "non standard" setup (long legacy) where my package is not at the root of the git repo.

So I have to do:

```
[tool.setuptools_scm]
root = ".."
```
which works for getting the version, and for the file-finding, which is great.

However, when I try to set it up to write the version to a file, I need to specify the path relative to the root, rather than relative to pyproject.toml.

```
[tool.setuptools_scm]
root = ".."
write_to = "py_gnome/gnome/_version.py"
```
(gnome is the package dir)

However, this then finds and writes the file properly when building the sdist. but when build tries to build the sdit, it is again looking for `../py_gnome/gnome/_version.py`

```
  File "/Users/chris.barker/miniconda3/envs/gnome_build/lib/python3.10/site-packages/setuptools_scm/__init__.py", line 77, in dump_version
    with open(target, "w") as fp:
FileNotFoundError: [Errno 2] No such file or directory: '../py_gnome/gnome/_version.py'
```

Which does not exist in the sdist, of course. :-(

Possible Solutions:

1) The write_to path should be relative to where the pyproject.toml file is, rather than the SCM root.

2) When building an sdist (outside of SCM), maybe this code should not be running at all? I *thought* the idea was that the _version.py file would get added to the sdist, to setuptools_scm wouldn't need to try to figure it out again. What does it do? it can't use the SCM from an sdist, so ???

**Comment by RonnyPfannschmidt** [comment]
write_to is relative to the determined root - a workaround is using search_parents
a fix will come from #870
