### ISSUE TITLE
Documenting Use of `[tool.setuptools.dynamic]` for Custom Version Schemes?

### ISSUE THREAD

**Issue by RobertRosca** [pypa/setuptools-scm#877]
I wanted to customise the version numbers a bit more than is allowed for by the configuration exposed by setuptools_scm in `pyproject.toml` and had a bit of trouble figuring out how to do this in a decent way. Eventually I found an approach that seems to work pretty well.

In `pyproject.toml`:

```toml
[build-system]
requires = ["setuptools", "wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
version = { attr ="{module}.{attribute}" }
```

Have `setuptools_scm` as a build time requirement, but instead of using `[tool.setuptools_scm]` to configure the version, set `[tool.setuptools.dynamic.version]` to some `attribute` in  `module`.

At build time the CWD is `src` (for `src` style projects at least), so this gives you two options:

1. Set this to some module within your package, e.g. `my_package._version.version` for `src/my_package/_version.py` with an attribute `version`.
2. Set this to a 'module' in the `src` directory, e.g. `get_version.version` for `src/get_version.py` with an attribute `version`.

Option 2 has the advantage of not including the file which defines how to build the version string inside the package.

Either way, inside this file you need to define how the version number is built, and how/where to save this to a file. A basic example is something like:

<details>
  <summary><code class="notranslate">src/get_version.py</code></summary>
  
```python
from pathlibimport Path

from setuptools_scm import Configuration, ScmVersion, _do_parse, dump_version


def _custom_version(v: ScmVersion):
    version = str(v.tag)

    if v.exact:
        return version

    if v.distance:
        version += f".dev{v.distance}"

    if v.node:
        # Drop off the "g" prefix
        short_hash = v.node[1:]
        version += f"+{short_hash}"

    return version


config = Configuration(root=".")

v = _do_parse(config)

if v is None:
    raise RuntimeError("No version was found")


version = _custom_version(v)


dump_version(
    root=config.root,
    version=version,
    write_to=Path(__file__).parent / "extra" / "__version__.py",
    template=config.write_to_template,
)
```
</details>

With this setup you can customise the number arbitrarily.

Is this something worth adding to the documentation, or is it not really desired? I've seen a few comments/issues/suggestions about making it easier to customise the version scheme but none seem to mention this approach. If documenting this sounds okay I'd be happy to make PR.

**Comment by RonnyPfannschmidt** [comment]
I'm working on allowing version schemes imported from pyproject.toml

The mechanism needs some extra exploration

My current impression is that the most reliable Code pass over needs a setup.py

**Comment by RonnyPfannschmidt** [comment]
i reached the conclusion that for setuptools a setup.py has to be used, dealing with import paths is the job of the build backend, setuptools_scm only arguments those

for setuptools the canonical way is a setup.py
for hatch i will have to coordinate with hatch-vcs
