### ISSUE TITLE
`hatch-vcs` picks up an old version

### ISSUE THREAD

**Issue by Saransh-cpp** [pypa/setuptools-scm#881]
I ran into an issue with `hatch-vcs` (https://github.com/ofek/hatch-vcs/issues/47), but since `hatch-vcs` uses `setuptools_scm` under the hood, I am reporting it here.

We accidentally created a [liionpack](https://github.com/pybamm-team/liionpack) release with the tag [v.0.3.4](https://github.com/pybamm-team/liionpack/tags) (not compatible with `hatch-vcs` or `setuptools_scm`). The tag was recently renamed to `v0.3.4`, creating some confusion for git (see how [releases](https://github.com/pybamm-team/liionpack/releases) and [tags](https://github.com/pybamm-team/liionpack/tags) are not in sequence, but still, GitHub recognizes that the latest tag is `v0.3.7`).

https://github.com/pybamm-team/liionpack/pull/270 aims to implement VCS versioning in `liionpack` using `hatch-vcs`, but for some reason, `hatch-vcs` keeps on picking up the version `v0.3.4` while installing `liionpack`, whereas, the latest version is `v0.3.7`.

Could you please let us know where we are going wrong? Thanks!

**Comment by RonnyPfannschmidt** [comment]
As starting point it may be necessary to run with SETUPTOOLS_SCM_DEBUG=1

Git describe May be able to help as well

**Comment by Saransh-cpp** [comment]
That pushed me in the right direction, thanks! This was a git issue and not a `setuptools_scm` or `hatch_vcs` issue. Closing this.

**Comment by RonnyPfannschmidt** [comment]
@Saransh-cpp just in case can you showcase the git issue for others running into it

**Comment by Saransh-cpp** [comment]
Definitely.

### How we ended up in this situation

We manually edited the Git tag on the GitHub release and "renamed" it to `v0.3.4` (from `v.0.3.4`), but GitHub decided to remove the old tag and create a new one on the latest commit with the name `v0.3.4`. All the old releases were intact, the `v0.3.4` release moved up to be the latest release, and everything went haywire from there. Tip: don't use GitHub GUI to rename tags.

At this point, everything was picking `v0.3.4` to be the latest tag (including `git describe`).

### Fix

I moved the tag back to the commit it was originally associated with (using my memory, as there was no information about the tag's history on GitHub or in Git) -
```
git tag -f v0.3.4 commit_hash
```

**Comment by RonnyPfannschmidt** [comment]
thanks for the update, that reads like a horrifying blindside in the github ux

**Comment by lwasser** [comment]
hey @Saransh-cpp so i just ran into the same thing!! so grateful for this issue as i was super confused as to what was happening. 

can you explain how you used git describe to figure out where the tag / commit hash inconsistencies were? if i create a new tag locally everything works as expected with setuptools_scm but i'm not sure how to "see" that tags were modified. i'm helping someone so i don't know the actual tag history / whether they did rename at some point, etc. many thanks!!

**Comment by Saransh-cpp** [comment]
Hi @lwasser! Unfortunately, most of the debugging was possible because of my familiarity with that repository 😬

If `git describe` or `git tag` shows you an older tag as the latest one, the problem is with the git tags and not with `setuptools_scm`. The older tag that is being picked up as the latest would be the one that was modified (existed before, but was recently renamed, say `v.0.0.1` to `v0.0.1`). I hope this helps! I could also take a look at the repo if it is open-source.

**Comment by lwasser** [comment]
hey there @Saransh-cpp thank you for the kind offer!! Finally i was able to figure it out. it did take what you were saying - a bit of digging and also a colleague showed me a really neat git viz tool - gitup that helped me "See" the timeline of the commits across branches. 

you've been super helpful here - thank you again!! 💟
