### ISSUE TITLE
keeping the local_scheme as supplied in the tag

### ISSUE THREAD

**Issue by jvailius** [pypa/setuptools-scm#882]
If I tag e.g. `v1.0.0+test` is there a simple way (i.e. ideally without implementing a custom function for the complete version format) to keep the `+test`?

Thank you
Jan

**Comment by RonnyPfannschmidt** [comment]
Currently passtrough of such local tags isn't directly supported at all

**Comment by jvailius** [comment]
Thank you for the quick answer.
