### ISSUE TITLE
Multiple(submodule) versioning

### ISSUE THREAD

**Issue by dofuuz** [pypa/setuptools-scm#885]
Is there any way to get multiple version strings using setuptools_scm?

There is a submodule in git repo, and I want something like
```
__version__ = '0.3.7'
```
```
__libsoxr_version__ = '0.1.3-7-gacc0dac'
```
in separate files. 

I tried to use setup.py to get version of submodule, but it does not cover all use-cases.
https://github.com/dofuuz/python-soxr/blob/04b04300e49d42edc20f21eb2e7a6a514165e78e/setup.py#L41
(Github Action Wheel package's versioning is broken now.)

**Comment by RonnyPfannschmidt** [comment]
th use case here is not clear,

if you want to pull in git subrepos and put version infos about them somewhere, then its not a immediate use-case of setuptools_scm, but rather something where you create a build step that generates a extra output

this is not something setuptools_scm will directly support

**Comment by dofuuz** [comment]
@RonnyPfannschmidt Your understanding is correct. I want to generate version strings of main and submodules at once.
Is there some appropriate place to put the extra build step?
My [setup.py](https://github.com/dofuuz/python-soxr/blob/fix-build-ver/setup.py) kinda works, but it breaks in dirty state.

**Comment by RonnyPfannschmidt** [comment]
thats best answered by setutools documentation

currently setuptools_scm does it in a bad way due to a wide range of behaviours in setuptools

the plan is to eventually supplement a extension to the sdist/wheel building commands in order to etablish a pattern

once thats avaliable  it wil lbe exposed and documented

**Comment by RonnyPfannschmidt** [comment]
closing as not planned based on the initial scope
