### ISSUE TITLE
Docker build stuck on install phase

### ISSUE THREAD

**Issue by chenww** [pypa/setuptools-scm#888]
Have a pyproject.toml project to build Docker image and the build stuck forever at the last step. Any insight is greatly appreciated!
thanks

 
#10 [6/9] RUN        SETUPTOOLS_SCM_DEBUG=true SETUPTOOLS_SCM_PRETEND_VERSION="0.1.0rc1" pip install -e .[test] -vvv
#10 0.758 Using pip 23.2.1 from /usr/local/lib/python3.11/site-packages/pip (python 3.11)
#10 0.759 Non-user install because site-packages writeable
#10 0.799 Created temporary directory: /tmp/pip-build-tracker-owy30i6_
#10 0.800 Initialized build tracking at /tmp/pip-build-tracker-owy30i6_
#10 0.800 Created build tracker: /tmp/pip-build-tracker-owy30i6_
#10 0.800 Entered build tracker: /tmp/pip-build-tracker-owy30i6_
#10 0.801 Created temporary directory: /tmp/pip-install-ugebpw6r
#10 0.803 Created temporary directory: /tmp/pip-ephem-wheel-cache-s7hv6x5o
#10 0.831 Obtaining file:///
#10 0.832   Added file:/// to build tracker '/tmp/pip-build-tracker-owy30i6_'
#10 0.835   Created temporary directory: /tmp/pip-build-env-bnaut7j3
#10 0.837   Installing build dependencies: started
#10 0.837   Running command pip subprocess to install build dependencies
#10 1.315   Using pip 23.2.1 from /usr/local/lib/python3.11/site-packages/pip (python 3.11)
#10 1.872   Collecting setuptools>=68.1.2
#10 1.875     Obtaining dependency information for setuptools>=68.1.2 from https://files.pythonhosted.org/packages/4f/ab/0bcfebdfc3bfa8554b2b2c97a555569c4c1ebc74ea288741ea8326c51906/setuptools-68.1.2-py3-none-any.whl.metadata
#10 1.994     Downloading setuptools-68.1.2-py3-none-any.whl.metadata (6.2 kB)
#10 2.108   Collecting setuptools_scm[toml]>=7.1.0
#10 2.126     Downloading setuptools_scm-7.1.0-py3-none-any.whl (43 kB)
#10 2.153        ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.8/43.8 kB 1.6 MB/s eta 0:00:00
#10 2.289   Collecting packaging>=20.0 (from setuptools_scm[toml]>=7.1.0)
#10 2.308     Downloading packaging-23.1-py3-none-any.whl (48 kB)
#10 2.319        ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.9/48.9 kB 4.9 MB/s eta 0:00:00
#10 2.385   Collecting typing-extensions (from setuptools_scm[toml]>=7.1.0)
#10 2.385     Obtaining dependency information for typing-extensions from https://files.pythonhosted.org/packages/ec/6b/63cc3df74987c36fe26157ee12e09e8f9db4de771e0f3404263117e75b95/typing_extensions-4.7.1-py3-none-any.whl.metadata
#10 2.404     Downloading typing_extensions-4.7.1-py3-none-any.whl.metadata (3.1 kB)
#10 2.494   Downloading setuptools-68.1.2-py3-none-any.whl (805 kB)
#10 2.555      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 805.1/805.1 kB 13.9 MB/s eta 0:00:00
#10 2.573   Downloading typing_extensions-4.7.1-py3-none-any.whl (33 kB)
#10 2.732   Installing collected packages: typing-extensions, setuptools, packaging, setuptools_scm
#10 4.046   Successfully installed packaging-23.1 setuptools-68.1.2 setuptools_scm-7.1.0 typing-extensions-4.7.1
#10 4.047   WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#10 4.368   Installing build dependencies: finished with status 'done'
#10 4.369   Checking if build backend supports build_editable: started
#10 4.369   Running command Checking if build backend supports build_editable
#10 4.610   Checking if build backend supports build_editable: finished with status 'done'
#10 4.612   Getting requirements to build editable: started
#10 4.612   Running command Getting requirements to build editable
#10 4.809   finalize hook {'name': None, 'version': None, 'author': None, 'author_email': None, 'maintainer': None, 'maintainer_email': None, 'url': None, 'license': None, 'description': None, 'long_description': None, 'keywords': None, 'platforms': None, 'classifiers': None, 'download_url': None, 'provides': None, 'requires': None, 'obsoletes': None}
#10 4.826   abs root {'root': '.', 'relative_to': 'pyproject.toml'}
#10 4.827   file pyproject.toml
#10 4.827   root '/'
#10 4.827   relative_to 'pyproject.toml'
#10 4.827   dist name: firmware_orchestrator
#10 4.828   version 0.1.0rc1 -> 0.1.0rc1
#10 4.828   scm version <ScmVersion 0.1.0rc1 dist=None node=None dirty=False branch=None>
#10 4.828   config {'version_scheme': 'post-release', 'local_scheme': 'node-and-date'}
`

**Comment by RonnyPfannschmidt** [comment]
This looks like a bug,is that project open source?

**Comment by chenww** [comment]
not opensource one. however, if you need any info, I can provide @RonnyPfannschmidt

**Comment by eduardowitter** [comment]
Minimal scenario to reproduce the issue:

Dockerfile:
```docker
FROM        artifactory.charterlab.com/docker-public/python:3.11.3-slim-bullseye
ENV         SETUPTOOLS_SCM_PRETEND_VERSION="1.0.0"

COPY        ./dummy-proj /dummy-proj
COPY        ./pyproject.toml /pyproject.toml

# install app requirements
RUN         pip3.11 install --no-cache-dir --upgrade pip==23.1.2
SHELL       ["/bin/bash", "-o", "pipefail", "-c"]
RUN         pip install --no-input --no-cache-dir -v .
```
pyproject.toml:
```toml
[build-system]
requires = [
  "setuptools >= 40.9.0",
  "setuptools_scm[toml]>=6.2"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_scheme = "post-release"

[tool.setuptools.packages.find]
include = ["dummy-proj"]

[project]
name = "dummy-proj"
dynamic = ["version"]
authors = [
  { name="John Doe", email="john@doe.com" },
]
description = "Demo project"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    'psutil ~= 5.9.5',
    'bencodepy ~= 0.9.5',
    'aiormq ~= 6.7.7',
    'requests ~= 2.31.0'
]
```
Project structure (empty `__init__.py`):
```bash
dummy-proj$ tree -a
.
├── Dockerfile
├── dummy-proj
│   └── __init__.py
└── pyproject.toml

1 directory, 3 files
```
Steps:
- `docker build --no-cache --progress=plain --network=host -t dummy-proj:1.0.0 .`

Result:
```bash
#9 [5/5] RUN         pip install --no-input --no-cache-dir -v .
#9 0.269 Using pip 23.1.2 from /usr/local/lib/python3.11/site-packages/pip (python 3.11)
#9 0.287 Processing /
#9 0.288   Installing build dependencies: started
#9 0.288   Running command pip subprocess to install build dependencies
#9 1.408   Collecting setuptools>=40.9.0
#9 2.263     Downloading setuptools-68.1.2-py3-none-any.whl (805 kB)
#9 3.498        ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 805.1/805.1 kB 653.6 kB/s eta 0:00:00
#9 3.711   Collecting setuptools_scm[toml]>=6.2
#9 3.998     Downloading setuptools_scm-7.1.0-py3-none-any.whl (43 kB)
#9 4.011        ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.8/43.8 kB 3.9 MB/s eta 0:00:00
#9 4.224   Collecting packaging>=20.0 (from setuptools_scm[toml]>=6.2)
#9 4.509     Downloading packaging-23.1-py3-none-any.whl (48 kB)
#9 4.524        ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.9/48.9 kB 3.7 MB/s eta 0:00:00
#9 4.708   Collecting typing-extensions (from setuptools_scm[toml]>=6.2)
#9 4.991     Downloading typing_extensions-4.7.1-py3-none-any.whl (33 kB)
#9 5.078   Installing collected packages: typing-extensions, setuptools, packaging, setuptools_scm
#9 5.340   Successfully installed packaging-23.1 setuptools-68.1.2 setuptools_scm-7.1.0 typing-extensions-4.7.1
#9 5.340   WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#9 10.94 
#9 10.94   [notice] A new release of pip is available: 23.1.2 -> 23.2.1
#9 10.94   [notice] To update, run: pip install --upgrade pip
#9 10.98   Installing build dependencies: finished with status 'done'
#9 10.98   Getting requirements to build wheel: started
#9 10.98   Running command Getting requirements to build wheel
```
It stays forever in `Running command Getting requirements to build wheel`

Pip: 23.1.2
Python: 3.11.0rc1
Docker: 24.0.5, build ced0996
OS: Ubuntu 22.04.3 LTS

@chenww  uses MacOS, same behavior.

**Comment by RonnyPfannschmidt** [comment]
Running the build with the tool build and SETUPTOOLS_SCM_DEBUG may provide more insights

**Comment by eduardowitter** [comment]
Good point @RonnyPfannschmidt  . I removed everything related to SCM and still got the same result:
```diff
diff --git a/Dockerfile b/Dockerfile
index 3bb3400..c157426 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,5 +1,4 @@
 FROM        artifactory.charterlab.com/docker-public/python:3.11.3-slim-bullseye
-ENV         SETUPTOOLS_SCM_PRETEND_VERSION="1.0.0"
 
 COPY        ./dummy-proj /dummy-proj
 COPY        ./pyproject.toml /pyproject.toml
diff --git a/pyproject.toml b/pyproject.toml
index 2c50a8b..1a4f1f3 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -1,19 +1,14 @@
 [build-system]
 requires = [
-  "setuptools >= 40.9.0",
-  "setuptools_scm[toml]>=6.2"
-]
+  "setuptools >= 40.9.0"]
 build-backend = "setuptools.build_meta"
 
-[tool.setuptools_scm]
-version_scheme = "post-release"
-
 [tool.setuptools.packages.find]
 include = ["dummy-proj"]
 
 [project]
 name = "dummy-proj"
-dynamic = ["version"]
+version = "1.0.0"
 authors = [
   { name="John Doe", email="john@doe.com" },
 ]
```

**Comment by RonnyPfannschmidt** [comment]
as there is no further details, i'll close this as initially mis-identified docker issue
in case the reason is known by now i'd appreciate a follow-up
