### ISSUE TITLE
pip build wheel spurious console warning "listing git files failed..."

### ISSUE THREAD

**Issue by sarnold** [pypa/setuptools-scm#890]
This happens because there is no .git directory in pip's isolated build environment temp dir.  It doesn't cause a failure, as it should be expected in this case.  This only issue is that it does get emitted as a warning (instead of just info) so Tox notices this and colors it red in the middle of otherwise green/white console output and my eyes are conditioned to scan the console for that.  Can that output be changed to info only for isolated wheel builds?  Thanks!

**Comment by RonnyPfannschmidt** [comment]
Setuptools doesn't provide sufficient API for this

**Comment by RonnyPfannschmidt** [comment]
closing a not actionable
