### ISSUE TITLE
Documentation on project page (`README.rst`) is in conflict with latest release 7.1.0

### ISSUE THREAD

**Issue by tscheburaschka** [pypa/setuptools-scm#891]
The title says it all. In particular the "version_file" argument (that should replace the deprecated "write_to" argument) does not work with the 7.1.0 installation of setuptools_scm. This took a considerable while for me to find out and it is surprising and disappointing at the same time.
Would it help to run development in a separate "develop"-branch, such that the README from "main" shown on the git homepage reflects the latest release?

**Comment by RonnyPfannschmidt** [comment]
Next generation docs Will Link out properly

The branch model won't change

**Comment by tscheburaschka** [comment]
Is there any ETA for "next generation docs" (or just for a new release, for that matter) available?

**Comment by RonnyPfannschmidt** [comment]
there currently is no eta for personal reasons - i hope to land both docs and the 8.0 release within the next 2 weeks tho
