### ISSUE TITLE
Use tag from any branch when guessing next version

### ISSUE THREAD

**Issue by kevalmorabia97** [pypa/setuptools-scm#893]
I have a main branch and a release branch where some extra files are removed from the release and new changes are added. When I create a tag from the release branch (e.g. `0.2.0`), it gives the correct version for the release `0.2.0` but if I switch to main branch, it would still use the `old_version.devN` format since the main branch technically does not have the new tag linked to it.

Can I somehow overwrite the setuptools_scm tag search logic so it searches for the most recent tag regardless of the branch it was created on and then take the distance from `git log 0.2.0..main`?

**Comment by RonnyPfannschmidt** [comment]
It's not quite clear what you are asking for,if you never merge back,then it's incorrect to presume

Can you show a example mermaid grap of the history?

**Comment by kevalmorabia97** [comment]
Yes I have not merged back the release branch onto the main branch and it needs to stay different. Can I somehow still have setuptools_scm use the most recent tag regardless of where it was created?

**Comment by RonnyPfannschmidt** [comment]
Intentionally not, unless you merge then tagged commit back, you are not on a descendant of it

Getting completely broken tagging schemes right is not a project goal as it's too fragile

A good solution is too put a .dev tag onto a commit that's not a descendant of the release to Start the next iteration

**Comment by kevalmorabia97** [comment]
Thanks for the suggestion, thats precisely what I was looking for!
