### ISSUE TITLE
Readme refers to non existent version 8

### ISSUE THREAD

**Issue by matthewhegarty** [pypa/setuptools-scm#902]
Readme refers to non existent version 8, but latest release is 7.1.0

```
[build-system]
requires = [
    "setuptools>=60",
    "setuptools-scm>=8.0"]
```

[source](https://github.com/pypa/setuptools_scm/blame/5b1c77b71ebf66413f3ecfea2222b5b3e0a26bcd/README.md#L30)

Presumably this refers to a forthcoming release, but it caught me out.

**Comment by matthewhegarty** [comment]
Closing - this must be due to recent changes in README

**Comment by RonnyPfannschmidt** [comment]
Release was planned yesterday
