### ISSUE TITLE
generated _version.py breaks on python <3.8

### ISSUE THREAD

**Issue by marcelm** [pypa/setuptools-scm#905]
I have this in my `pyproject.toml`:
```
[tool.setuptools_scm]
write_to = "src/toolname/_version.py"
```
setuptools_scm 8.0.0 seems to incorrectly generate the `_version.py` file (it contains syntax errors):
```
# file generated by setuptools_scm
# don't change, don't track in version control
from __future__ import annotations
__version__ : str = version : str = '4.5.dev38+g44c9a18'
__version_tuple__ : 'tuple[int | str, ...]' = \
  version_tuple : 'tuple[int | str, ...]' = (4, 5, 'dev38', 'g44c9a18')
```

[Logs for a failed GitHub Actions run](https://github.com/marcelm/cutadapt/actions/runs/6247483075/job/16960159583).

**Comment by RonnyPfannschmidt** [comment]
this is a unfortunate oversight, with the drop of python3.7 in the support matrix

as your build env uses a higher python version that new setuptools_scm version is pulled in
i'll release a bugfix that allows the old syntax to keep that working

**Comment by marcelm** [comment]
Thanks! I’m not sure I understand. I get the SyntaxError even on Python 3.10:
```
$ python3
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from __future__ import annotations
>>> a : str = b : str = "hello"
  File "<stdin>", line 1
    a : str = b : str = "hello"
                ^
SyntaxError: invalid syntax
```

(Thanks BTW, due to your comment, I noticed that apparently my build matrix is configured incorrectly and uses Python 3.10 for all builds, independent of the specified version number.)

**Comment by RonnyPfannschmidt** [comment]
i have a local bugfix + a regression test that switches to type comments, release incoming in a few

**Comment by marcelm** [comment]
Thanks for this quick fix! With that, I can drop my `_version.pyi` file that I kept for this purpose.

I wanted to clarify my comment from above. The Python version is not the problem as Python 3.7 understands this style of annotation:
```
a : str = "hello"
```
The problem is attempting to use two annotations in a row like this:
```
a : str = b : str = "hello"
```
That is a SyntaxError up until at least Python 3.11.

**Comment by ssbarnea** [comment]
This affects lots of project and breaks also with newer versions of python, I would recommend yanking 8.0 release until we have a fix to limit the ecosystem impact.

**Comment by leouieda** [comment]
Just wanted to say a big thank you for finding and fixing this so quickly! I love this package and use in every single project I develop. Much love from the community ❤️

**Comment by abhinavsingh** [comment]
> This affects lots of project and breaks also with newer versions of python, I would recommend yanking 8.0 release until we have a fix to limit the ecosystem impact.

Totally, v8 must be yanked imho, so that we can remove the pin.
See https://github.com/pypa/setuptools_scm/issues/908

**Comment by RonnyPfannschmidt** [comment]
@abhinavsingh just yanked it

**Comment by RonnyPfannschmidt** [comment]
bug-fix release triggered
