### ISSUE TITLE
add a semver based version scheme and a way to decide the emcrement

### ISSUE THREAD

**Issue by anthrotype** [pypa/setuptools-scm#92]
Hello,

The README.md says that:

> it's necessary to always include a patch version (the 3 in 1.2.3), or else the automatic guessing will increment the wrong part of the semver...
> Future versions of setuptools_scm will switch to SemVer by default hiding the the old behavior as an configurable option

Are you planning to implement this SemVer-compatible behavior any time soon?
I would like to omit an extra '0' patch number when tagging a minor release, e.g. '2.6' instead of '2.6.0', but still have setuptools_scm increment the last digit, '2.6.1.dev...'

I guess one could already do this by passing a custom entry point or callable as `version_scheme`, though I'll have to figure it out how to do it.

**Comment by RonnyPfannschmidt** [comment]
there are no immediate plans due to personal time constraints and the tool working fine for me

**Comment by RonnyPfannschmidt** [comment]
ref #240

**Comment by RonnyPfannschmidt** [comment]
fixed by #240
