### ISSUE TITLE
Mypy error on python 3.8 on version generation

### ISSUE THREAD

**Issue by ralequi** [pypa/setuptools-scm#926]
The current setuptools_scm generates an (mypy) invalid version.py for python 3.8.

The current version generates something like:
```
# file generated by setuptools_scm
# don't change, don't track in version control
from __future__ import annotations

__version__ = version = '2.0.2.dev217'  # type: str
__version_tuple__ = version_tuple = (2, 0, 2, 'dev217')  # type: tuple[int | str, ...]
```

While previous version did something like:
```
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '2.0.2.dev70'
__version_tuple__ = version_tuple = (2, 0, 2, 'dev70')
```

The new added typing is invalid in python 3.8's mypy:

```
$ mypy -p ${PYTHON_PACKAGE_NAME} --ignore-missing-imports
x/version.py:4: error: Unexpected "..."  [misc]
x/version.py:4: error: "tuple" is not subscriptable, use "typing.Tuple" instead  [misc]
x/version.py:4: error: Incompatible types in assignment (expression has type "Tuple[int, int, int, str]", variable has type "Tuple[Union[int, str], Any]")  [assignment]
```

The commit defc575f31d843f134a71999bc4d092e473541a8 introduced the bug (Jul 12 2023) by @RonnyPfannschmidt 
 and references issue #527 

This is breaking many of my pipelines, and probably soon many other people's.
Please, consider a more flex typing while python 3.8 hasn't reached it's EOL.

Thank you, this package is great and helps a lot on my python's packages!

**Comment by ralequi** [comment]
Just a note: I've tested this on pythons **3.8**, **3.10**, **3.11** and **3.12-rc**. Only failing on 3.8
The python **exact** version i'm using is the one provided in docker hub

**Comment by RonnyPfannschmidt** [comment]
seems like i made a mistake when testing the change, whats he mypy version
im under the impession i need to ad quotes even tho its already a comment

**Comment by ralequi** [comment]
Thanks for your quick reply @RonnyPfannschmidt 
Our failing setup versions are:

```bash
# mypy --version
mypy 1.5.1 (compiled: yes)

# python3 --version
Python 3.8.18

# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
[...]
```

**Comment by RonnyPfannschmidt** [comment]
it seems like this happens only on mypy on python 3.8 itself, im going to replace it with a typing.Tuple for now

**Comment by ralequi** [comment]
Thank you!

Going to test ASAP

**Comment by ralequi** [comment]
Forgot to confirm, but the fix worked for me!
Thank you!

**Comment by RonnyPfannschmidt** [comment]
@ralequi thanks for getting back :+1:
