### ISSUE TITLE
Travis clones shallow repo, breaks git describe

### ISSUE THREAD

**Issue by anthrotype** [pypa/setuptools-scm#93]
Hi,
Maybe this is obvious for many of you. However, I spent more than one hour trying to figure out why setuptools_scm was not working on Travis, but it was working locally.
It turned out that Travis clones the repo with --depth=50, so if you have more than 50 commits since the last tag the `git describe` command fails, and setuptools_scm will use the fallback `0.0` version.

The workaround was simply to  do `git fetch --unshallow`.

I know this is not strictly setuptools_scm's problem, but rather a Travis or a git problem.
But maybe it could help other users if this was mentioned in the README?

Thanks.

**Comment by RonnyPfannschmidt** [comment]
@anthrotype  its now possible to use the specification of a parse function to import and use the strategies from #93, i'd appreciate feedback on its use/utility (its completely experimental)

**Comment by anthrotype** [comment]
This works well for me, thank you.
I wonder, why not making `fetch_on_shallow` as the default, rather than `warn_on_shallow`?

**Comment by RonnyPfannschmidt** [comment]
@anthrotype its not the default, because it incurs uncontrolled network traffic potentially at build time

as such its a behavior where i'd rather go for an error than go for a implicit git pull

**Comment by anthrotype** [comment]
I see. I guess you could close this issue then.
Thank you.

**Comment by ulope** [comment]
@RonnyPfannschmidt How does one enable `fetch_on_shallow` from setup.py?

**Comment by georgek** [comment]
Was this actually fixed? An alternative solution would be for a CI system to expose the output of git describe in an environment variable which setuptools_scm could then use instead of calling `git describe` itself. Would such a thing be possible? There are open issues in Gitlab for exposing such an environment variable.

**Comment by RonnyPfannschmidt** [comment]
currently thre is a opt-in dable using a setup.py parameter, there was no investigation of env vars that help,

in case gitlab/gthub do create such env vars, i'm more than happy to add/use support for them

**Comment by georgek** [comment]
OK. I'll keep you updated on the Gitlab env vars!

**Comment by RonnyPfannschmidt** [comment]
Lovely, thanks
