### ISSUE TITLE
Is it neccessary to pull in rich as build-backend depndency?

### ISSUE THREAD

**Issue by hroncok** [pypa/setuptools-scm#941]
Hello,
I've noticed version 8 now declares a build-backend dependency on rich:

https://github.com/pypa/setuptools_scm/blob/6ab652e2beef00947d9a14cd2834a037ed4795db/pyproject.toml#L3-L6

However, the build works without rich. I assume that's because the import is try-expected:

https://github.com/pypa/setuptools_scm/blob/6ab652e2beef00947d9a14cd2834a037ed4795db/src/setuptools_scm/_log.py#L32-L42

In Fedora Linux, I plan to patch this out to simplify the bootstrap of our Python packages for the next Python version. However, I was wondering if this should actually be a build dependency. Why is it?

**Comment by RonnyPfannschmidt** [comment]
Debugging mistake, happy to take it out again

**Comment by hroncok** [comment]
Will send a PR.
