### ISSUE TITLE
pyproject.toml does not contain a tool.setuptools_scm section

### ISSUE THREAD

**Issue by mtelka** [pypa/setuptools-scm#953]
I'm packaging various Python projects for OpenIndiana.  The packaging (and especially testing) is done in real environment with possibly many unrelated packages installed to make sure the packaged project works properly once it is installed.

When I try to work with a project that does not use `setuptools_scm` and `setuptools_scm` is installed then I see this warning:
```
[10/08/23 10:00:26] WARNING  pyproject.toml does not contain a tool.setuptools_scm section                                  setuptools.py:119
```
The warning is seen in many logs, including testing log.  This causes a problem to us because it raises errors when we compare test logs between test runs.  Yes, we could add a special rule to our testing logic to filter out this warning, but since this is a regression from `setuptools_scm==7.1.0` then I'd prefer to see it fixed/changed at the `setuptools_scm` side.

Possible solution would be to change `log.warning(e)` to `log.debug(e)` in the [setuptools.py file](https://github.com/pypa/setuptools_scm/blob/v8.0.4/src/setuptools_scm/_integration/setuptools.py#L119).  If that's not possible or desirable then what about to implement some way how to silence the warning using an environment variable?

Thank you.

**Comment by mtelka** [comment]
Related issue: #938

**Comment by RonnyPfannschmidt** [comment]
Would a log level of info be sufficient?
If its debug it might get lost in the noise

**Comment by mtelka** [comment]
I just tested and yes, `log.info` is enough.

**Comment by fabcor-maxiv** [comment]
What is the reason why this log entry is written (warning level or not)? Does it check if `setuptools-scm` is listed in `build-system.requires`?

**Comment by mcepl** [comment]
Sorry, but https://github.com/pypa/setuptools-scm/commit/517ed805638f5166b1055c68d7a1e6a53cf4d6ae is still wrong: when my project doesn’t use `setuptools_scm` at all, why it is even activated, and why is my logging (in whatever level) spammed at all? This is just wrong from the beginning.

**Comment by RonnyPfannschmidt** [comment]
Setuptools has no safe way to control the file finder entry point

**Comment by mcepl** [comment]
I am sorry, but could you elaborate a bit, I really don’t understand what do you mean and how it is relevant to my complaint?

**Comment by RonnyPfannschmidt** [comment]
Setuptools always considers all plugins, there's no way to opt out easily 

You shouldn't be seeing the indo log in most cases 

If you do please elaborate on environment and context in a new issue
