### ISSUE TITLE
Time-based patch version scheme

### ISSUE THREAD

**Issue by con-f-use** [pypa/setuptools-scm#956]
A time-based patch version scheme (e.g. `v2.13.231010161353`) has proven quiet useful for our company-internal, private python package index. We are using a pretty trivial (maybe naive) implementation:

```python
def timebased_patch_version(version):
    if version.exact:
        return version.format_with("{tag}.0")
    return version.format_with("{tag}.{time:%y%m%d%H%M%S}")
```

as a plugin (entrypoint):
```toml
# pyproject.toml (of "internalsetuptools" package)

[project.entry-points."setuptools_scm.version_scheme"]
timebased-patch-version = "internalsetuptools:timebased_patch_version"
```

My question is, would an upstream of this to `setuptools_scm` be considered?

----- 

### Rationale

Normally, one would use a local version, but not all package index implementation support that, some even require a format exactly matching `\d+\.\d+\.\d+` outright. When using such index implementation that version scheme is useful because:
 - Uploaded dirty versions can still be distinguished from properly committed versions by virtue there not being a commit at the corresponding build time of the dirty upload
 - Clean versions can still be mapped to a commit in most cases, because it is unlikely that the commit times matches to the exact second. 
 - Humans can still tag and easily recognize "release" and "staging" versions, because they would be exactly on a tag, and have "0" as the patch version instead of a timestamp. E.g. `2.0.0` for a "release" (major) and `2.1.0` for a "staging" (minor) version.
 - It still reads and sorts like a regular SemVer but conveys useful extra information for humans.
 
I do realize it is a compromise of a version scheme for quite specific circumstances. However, it is also quite few lines of code. If you give the go-ahead, I'd prepare a PR.

**Comment by RonnyPfannschmidt** [comment]
I have to reject - its a footgun

a) it enable pypi upload of non-released versions
b) versions no longer match tags

 if you need it multiple times, make a own plugin with a ample warning about its problem
the strong recommendation is to use indexes that support local version uploads for non-released versions

**Comment by con-f-use** [comment]
Almost expected this. Thank you for your time.

Another idea, and I seem to remember something similar may be (or have been) already part of `setuptools_scm`, would be to have a `scheme_format` config keyword, used like so:

```toml
# pyproject.toml 
[tool.setuptools_scm]
scheme_format = "{tag}.{time:%y%m%d%H%M%S}"
```

Where of course the formatting would have to be done safely, so no code-injection can be done, as the pep-517 style packaging explicitly disallows arbitrary code execution as was possible with `setup.py`.
Alternatively, one could forgo the introduction of a new keyword and have the `version_scheme` config option accept a format string in addition to accepting only the name of a preexisting version scheme or a callable.

An idea to make it save, would be to pass an `ScmVersion` instance to `string.format` after converting it to a dict:
```python
if "{" in version_scheme:    # stand-in for better format string detection
    version_scheme = version_scheme.format(**version.to_dict())
```

**Comment by RonnyPfannschmidt** [comment]
The same reason i rejected this feature is also the reason I rejected more powerful formatting
