### ISSUE TITLE
fallback_version option not used when other ways of determining the version fail.

### ISSUE THREAD

**Issue by dbc-bogdan** [pypa/setuptools-scm#963]
Hi,
fallback-version does not seem to be used when all other ways to extract the version fail.

pyproject.toml setuptools_scm configuration:
```
[tool.setuptools_scm]
root="."
version_scheme = "guess-next-dev"
local_scheme = "node-and-timestamp"
fallback_version = "0.0.0"
```

Steps to reproduce:

```bash
$ git init
$ git commit -m "first commit"
$ git tag 0.0.1
$ python -m build # results in a python wheel with version 0.0.1 => as expected

$ git commit -m "second commit"
$ git tag weird_tag
$ python -m build # results in a python wheel with version 0.0.2.dev1... => ignores latest tag, uses the previous one

$ git commit -m "third commit"
$ git tag weird_tag2
$ python -m build # UserWarning: tag 'weird_tag2' no version found ... AssertionError: assert version is not None. I would have expected 'fallback_version' to be used.
```

Cheers, Bogdan

**Comment by RonnyPfannschmidt** [comment]
The behavior is correct and intentional

The weird tag without Numbers is ignored by the Tag match

The weird tag with a number is wrong metadata and should error

The fallback is for when nothing is found, the case shown is wrong metadata which should not be hidden

**Comment by topherbuckley** [comment]
Sorry to necro this, but I found it to be the most relevant example of my existing question. What determines "wrong" metadata? Where can I find the rules for this? What if I need tags that do not represent versions, e.g. a named release called trainedModel1080p, how can I have these and not throw this error? Would I always just need another versioned tag after this named release?

**Comment by RonnyPfannschmidt** [comment]
Tag patterns and custom describ commands solve that

**Comment by topherbuckley** [comment]
@RonnyPfannschmidt I don't follow. 

>The weird tag with a number is wrong metadata and should error

Why is it considered "wrong"? Is any tag with a number that does not fit the `v.*.*.*` format considered wrong? Is it considered wrong by setuptools_scm, or something upstream?

**Comment by RonnyPfannschmidt** [comment]
setuptools scm is supposed to provide standard compliant versions for python projects - using the python standard for versions

random other stuff is "wrong" by that logic 
please outline your use-case in more detail if you want me to understand why you consider it valid and if it is sensible/possible to support that
