### ISSUE TITLE
Fails to detect version on hg-git checkout

### ISSUE THREAD

**Issue by jaraco** [pypa/setuptools-scm#97]
As the world moves to git and I'm still straggling behind using Mercurial, I often check out a git repo with hg-git. However, if I'm trying to build a package with setuptools_scm on a repo where tags were added in Git, it will fail to detect the tags, even though hg-git reports them:

```
$ hg id -i -t
f77ac09b3dbc 4.7.1 tip
$ python -m rwt setuptools_scm==1.11.1
Loading requirements using setuptools_scm==1.11.1
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 26 2016, 10:47:25) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import setuptools_scm as ss
>>> ss.version_from_scm('.')
<ScmVersion 0.0 d=112 n=f77ac09b3dbc d=False x={}>
>>> ss.utils.do('hg id -i -t')
'f77ac09b3dbc tip'
```

The issue, I believe, is that setuptools_scm [disables hg-git when bypassing hgrc](https://github.com/pypa/setuptools_scm/blob/v1.11.1/setuptools_scm/utils.py#L54).

I've been using hg-git for some time against git repos without encountering this issue, and here's why: Where tags already existed in the repo (or were added by git users), I never bothered building the application. And where I was adding tags, I was adding them with Mercurial, so they showed up in the Mercurial-native metadata. It was only lately when I've wanted to avoid creating those Mercurial tag commits that I've encountered the issue. Here's what I've done:

```
# create the tag using mercurial
$ hg tag 4.7.2
# push the tagged commit (with the tag), but not the tagging commit.
$ hg push -r 4.7.2
# strip the tagging commit
$ hg strip -r .
# pull to get the tag from git in hg-git metadata
$ hg pull
```

That has the effect of creating the tag in Git in the same manner as it would have been created by a git client.

This issue leads me to wonder why hgrc is bypassed. I'm sure there is a good reason - it's just no apparent from the code. What options are there?

**Comment by RonnyPfannschmidt** [comment]
Unfortunately i did not document why the `do_ex` Funktion limits the hgrcpath to the current repo

After recovery from illness I can take a look at doing a major release changing that default

**Comment by jaraco** [comment]
Thanks. Feel better, and no rush.

**Comment by RonnyPfannschmidt** [comment]
@jaraco please verify this was enough - i might need to add some extra output handling for hg errors

**Comment by jaraco** [comment]
Confirmed - at least for the use case provided, this change works like a charm.
