### ISSUE TITLE
How to get scm-version to match current tag

### ISSUE THREAD

**Issue by Adamtaranto** [pypa/setuptools-scm#970]
Hit there, 

I'm having trouble generating a build for pypi with a version number that matches the latest release tag exactly. 

After committing latest edits I've added and pushed the tag v0.0.4

When I then run `python3 -m pip install --upgrade build && python3 -m build` I get a package named `mytool-0.0.5.dev0+g0ff1795.d20231105` and I can see that `src/mytool/_version.py` has been updated with the same version number.

If I try to build the release before updating the tag (current tag still v0.0.3 but with new commits on top) I get `0.0.4.dev8+g2e4e874.d20231105`. 

How do I prevent setuptools-scm from thinking its own changes to _version.py are a new dev version of the package?

Here is the relevant section of my pyproject.toml:
```
dynamic = ["version", "dependencies"]

[tool.setuptools_scm]
write_to = "src/mytool/_version.py"
```

**Comment by RonnyPfannschmidt** [comment]
The version file must never be committed, please delete it from the scm

**Comment by Adamtaranto** [comment]
I've tried deleting the latest tag, adding `src/mytool/_version.py` to the `.gitignore` and then re-creating the tag like so:

```
git tag -a v0.0.4      
git describe               
# returns: v0.0.4
python setup.py --version  
# Creates: 0.0.5.dev0+g8932514.d20231105
git describe               
# returns: v0.0.4
```
The version assigned by setuptool-scm does not match the tag in git describe.

**Comment by RonnyPfannschmidt** [comment]
Git ignore will not remove already committed content, please explicitly delete it from the SCM

**Comment by RonnyPfannschmidt** [comment]
closing as user error based on initial input and lack of further responses
