### ISSUE TITLE
Documentation for Sphinx usage a bit unclear

### ISSUE THREAD

**Issue by matt-graham** [pypa/setuptools-scm#972]
The docs suggest including the following snippet in a Sphinx `conf.py` file

https://github.com/pypa/setuptools_scm/blob/c39489f9cfced1b584b054564a6579c821db494f/docs/usage.md?plain=1#L123-L128

to set the Sphinx documentation version from the installed package metadata. While in retrospect this probably should have been obvious, I originally copied this snippet verbatim without changing the argument of `get_version` to the relevant package name instead of `'setuptools_scm'`, causing the built documentation to instead display the installed version of `setuptools_scm`. Perhaps to make it more obvious the argument needs to be adjusted to the relevant package name this should match the previous example

https://github.com/pypa/setuptools_scm/blob/c39489f9cfced1b584b054564a6579c821db494f/docs/usage.md?plain=1#L113

and use `"package-name"` as the argument to `get_version`?

**Comment by RonnyPfannschmidt** [comment]
Absolutely, great suggestion,I completely missed that footgun
