### ISSUE TITLE
github project url is not configured

### ISSUE THREAD

**Issue by ssbarnea** [pypa/setuptools-scm#974]
setuptools-scm project should point to https://setuptools-scm.readthedocs.io/en/latest/ and not the current readme on github (that is what it does when the URL is not configured).

Please go to https://github.com/pypa/setuptools_scm and address this on the righthand sidebar. Thanks. Sadly that is no doable via a PR.

**Comment by RonnyPfannschmidt** [comment]
done, thanks for the note
