### ISSUE TITLE
Docs request: `SETUPTOOLS_SCM_PRETEND_VERSION` recommendation

### ISSUE THREAD

**Issue by jamesbraza** [pypa/setuptools-scm#978]
From https://setuptools-scm.readthedocs.io/en/latest/config/#environment-variables as of `setuptools_scm==8.0.4`:

> `SETUPTOOLS_SCM_PRETEND_VERSION`
> 
> used as the primary source for the version number in which case it will be an unparsed string
> 
> it is strongly recommended to use use distribution name specific pretend versions

Can we add more details to this recommendation?  Why is it strong recommended to use distribution-specific pretend versions?

To me, adding distribution-specifics adds both more work and complexity, so it seems like a downside

**Comment by RonnyPfannschmidt** [comment]
any from source build you trigger while having the general one set will configure those with the wrong version as well

**Comment by jamesbraza** [comment]
When you say "from source build", what do you mean by that? You mean like `pip install -e .`?

What is the intended use case of distribution-specific versions?

I will add the takeaways to the docs, but for now just trying to understand the story

**Comment by RonnyPfannschmidt** [comment]
if you install other python packages from a sdist and they use setuptools_scm, they also get the wrong version

**Comment by jamesbraza** [comment]
Oh I get it.  I interpreted `DIST_NAME` to be the OS (e.g Linux, macOS, Windows).

I see now it's really the package name.  I will open a PR for that shortly, thanks!
