### ISSUE TITLE
Failing to point to project's root

### ISSUE THREAD

**Issue by doronz88** [pypa/setuptools-scm#985]
When trying to build my project I'm getting: `LookupError: setuptools-scm was unable to detect version for ...`.
After googline I arrived at the following issue: #278 seeing I'm encountering the same problem - when my `pyproject.toml` resides in a subdirectory:

```
PROJECT ROOT
└── src
    ├── rpcclient <- this is where I'm trying to build
    │   ├── pyproject.toml 
```

I tried adding `root = "../../"` at `tool.setuptools_scm`, but then encountered another error:

```
ValueError: invalid pyproject.toml config: data.project.version.
configuration error:
```

I guess the solution to `pyproject.toml` projects is somewhat different

**Comment by joelkim** [comment]
+1 same here. anybody has solution?

**Comment by joelkim** [comment]
I found the cause. I forgot to remove the version specification line before applying dynamic versioning.
