### ISSUE TITLE
on windows, path comparison should be case-insensitive

### ISSUE THREAD

**Issue by ThomasWaldmann** [pypa/setuptools-scm#993]
Just seen that on github CI (windows / msys2 based part), using the latest setuptools_scm:
```
WARNING setuptools_scm._file_finders.git toplevel mismatch computed d:/a/borg/borg vs resolved D:/a/borg/borg 
```

**Comment by RonnyPfannschmidt** [comment]
@ThomasWaldmann seems like we are hitting https://github.com/python/cpython/issues/84548

i'll investigate a workaround
