### ISSUE TITLE
LookupError: setuptools-scm was unable to detect version for /app when project is used as a git submodule.

### ISSUE THREAD

**Issue by lumalav** [pypa/setuptools-scm#999]
I forked [OCRmyPDF](https://github.com/lumalav/OCRmyPDF) project and made a couple of changes to it. This project uses setuptools_scm and its configuration can be seen in the following [pyproject.toml](https://github.com/lumalav/OCRmyPDF/blob/main/pyproject.toml) file.

To build this project, I just use `docker build -t myImage .` and works fine.

However, I have a second private project which has the forked repository as a submodule and a docker compose file that orchestrates the build of other projects in the repository + the submodule. However, when using git submodules, the forked repository "loses" its original .git folder and now the parent repo is the one tracking everything. This is when I see the error happen since this setup would not work to build the forked repo.

So, I understand I can avoid this by not having the forked repository as a submodule and just cloning it independently to the desired location and still building it with the docker compose file. However, shouldn't this still be possible? What could I do to make the git submodule setup work?

**Comment by RonnyPfannschmidt** [comment]
I would recommend using the SETUPTOOLS_SCM_PRETENT_VERSION_FOR_mydist envvar to pass over the configuration

Git submodules are currently no supported and it's unclear how to support them in general

**Comment by lumalav** [comment]
OK. Thanks for the quick response.
